### ISSUE TITLE
Creating Neural Network Graphs

### ISSUE THREAD

**Issue by kadir-gunel** [JuliaGraphs/LightGraphs.jl#1028]
Hello, 

I am trying to draw a simple RNN image. Is it possible to draw reflexive edges by using LightGraphs ?

B.R.

**Comment by sbromberger** [comment]
If you mean graphs with self loops, in general, yes - those are representable in LG but not all analytics will work. 

There is an open issue in GraphPlot, the visualization package, dealing with self loops. You might check over there for the latest status.

**Comment by sbromberger** [comment]
Hey @kadir-gunel , I'm cleaning up open issues today and will close this out. If you have any other questions, please don't hesitate to continue here or on Discourse. Good luck!

Seth.
