### ISSUE TITLE
multilayer network

### ISSUE THREAD

**Issue by adamglos92** [JuliaGraphs/LightGraphs.jl#1029]
Hello,
Is there any implementation multilayer networks (or multiplex, hypergraph, etc.)? I would really appreciate such.

**Comment by sbromberger** [comment]
Unfortunately not natively. You might be able to cobble something together using metagraphs though.

**Comment by sbromberger** [comment]
Closing this out, but feel free to continue discussion here, or on Discourse.

**Comment by adamglos92** [comment]
It should be sufficient for multiplexes, as in each node I can have a additional graph defined over the layers. As right know it is more than enough for me, I am satisfied with that. Thanks!

Just in case, if the code would be good enough, will You be interested in including it into JuliaGraphs?

**Comment by sbromberger** [comment]
> Just in case, if the code would be good enough, will You be interested in including it into JuliaGraphs?

We are always open to new functionality. This sounds like a good addition. You should start thinking now about whether you will be able to maintain the code / repo in the long term. If so, it makes this a much easier decision. (We need to make sure all JuliaGraphs code is maintained / maintainable.)
