### ISSUE TITLE
Adding new graph generators

### ISSUE THREAD

**Issue by mcognetta** [JuliaGraphs/LightGraphs.jl#1030]
As (very briefly) discussed on Slack, there are several graph generators present in [NetworkX](https://networkx.github.io/documentation/networkx-2.0/reference/generators.html) and [SageMath](http://doc.sagemath.org/html/en/reference/graphs/sage/graphs/graph_generators.html) that are not in LightGraphs.

This issue is to facilitate progress towards adding new graph generators to LightGraphs (note that this list is not exhaustive):

- [x] [Barbell Graph](http://mathworld.wolfram.com/BarbellGraph.html) (this is used in transitivity tests) 
- [x] [Complete Multipartite Graph](https://en.wikipedia.org/wiki/Multipartite_graph) 
- [x] [Circular Ladder Graph](https://en.wikipedia.org/wiki/Ladder_graph#Circular_ladder_graph)
- [x] [Dorogovtsev-Goltsev-Mendes](http://graphstream-project.org/doc/Generators/Dorogovtsev-Mendes-generator/) (this would be in randgraphs.jl) 
- [x] [Ladder Graph](https://en.wikipedia.org/wiki/Ladder_graph)
- [x] [Lollipop Graph](http://mathworld.wolfram.com/LollipopGraph.html)
- [x] [Turan Graph](https://en.wikipedia.org/wiki/Tur%C3%A1n_graph)

**Comment by simonschoelly** [comment]
Some of these suggestions are quite easy to implement with what we already have in LightGraphs, but maybe not as efficient as possible, so you could improve that:

```
function barbell_graph(n1, n2)
    g = blockdiag(CompleteGraph(n1), CompleteGraph(n2))
   add_edge!(g, 1, n1 + 1);
   return g
end

ladder_graph(n) = cartesian_product(PathGraph(n), PathGraph(2))
or 
ladder_graph(n) = Grid([n, 2])

circular_ladder_graph(n) = cartesian_product(CyclicGraph(n), PathGraph(2))

function lollipop_graph(m, n)
    g = blockdiag(CompleteGraph(m), PathGraph(n))
    add_edge!(g, m, m+1)
    return g
end
```
The `Dorgovtsev-Goltsev-Mendes` graph sounds quite interesting, in case we will add some planarity algorithms one day.

**Comment by mcognetta** [comment]
It seems there are two definitions of the `Dorogovtsev-Goltsev-Mendes` graph, one random and one deterministic.

- Random: https://arxiv.org/pdf/cond-mat/0106144.pdf - page 24 (this one should probably only be called `Dorogovtsev-Mendes`)
- Deterministic: https://arxiv.org/pdf/cond-mat/0112143.pdf - page 1 (this one may be called `Dorogovtsev-Goltsev-Mendes` or `pseudofractal`)

**Comment by jpfairbanks** [comment]
I think all of these are great additions.

Also, @mcognetta, go jackets 🐝

**Comment by mcognetta** [comment]
(So this doesn't get closed) I will add the last two on this list in the next day or so.

**Comment by sbromberger** [comment]
Closed since all graphs have been implemented.
