### ISSUE TITLE
Function edit_distance should consider edge costs.

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGraphs/LightGraphs.jl#1036]
Right now, `edit_distance`, does not consider edge costs. This makes this function useless, as the outcome does not in any way depend on on what edges the two graphs have.

**Comment by juliohm** [comment]
Indeed, it would be nice to have this in addition to the vertex costs :+1:

Please let me know if you have any questions about the current implementation, and I can try take a look at it again. It is been a while.

**Comment by sbromberger** [comment]
@juliohm I was confused by the result of 

```
g = PathGraph(5)
h = CycleGraph(5)
edit_distance(g, h)
```

**Comment by juliohm** [comment]
@sbromberger you mean that it should give 0 distance? I will review the algorithm in the book, it may be a corner case that we are missing.

**Comment by sbromberger** [comment]
I’m not sure what it should return. The graphs are identical except for an edge between 1 and 5.

**Comment by juliohm** [comment]
The second output of the algorithm is a sequence of vertex operations to convert the first graph into the second. Let's do a few examples to illustrate this.

```julia
g = PathGraph(5)
h = PathGraph(6)

edit_distance(g, g) # edit path: [(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
edit_distance(g, h) # edit path: [(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (0, 6)]
```
Imagine that graph `g` is made of blue vertices, and graph `h` is made of red vertices. The edit path to convert `g` into `g` is trivial. We just need to replace each vertex by itself, one by one. Now, the edit path to convert `g` into `h` starts replacing each blue vertex by a red vertex, one by one. At the end, however, the graph `h` still has one additional red vertex that is not present in `g`. This is the last operation in the path `(0,6)` that adds a new vertex to graph `g` at position 6.

Now with your example:

```julia
g = PathGraph(5)
h = CycleGraph(5)

edit_distance(g, h) # edit path: [(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
```

We get the same sequence of vertex operations as expected. Imagine that we are just replacing blue by red again. So the edit path is the minimum-cost sequence of vertex operations to convert one graph into another.

Now let's understand the cost. By default we have `subst_cost = (u,v) -> 0.5`. This means that every time we replace a vertex by another we spend 0.5 units regardless of the vertices `(u,v)` we are looking at. If we look at the edit path above `[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]` we are making 5 substitutions and therefore 5*0.5 = 2.5 total cost. We could change this substitution cost function to `subst_cost = (u,v) -> u != v ? 0.5 : 0.0` to make sure that trivial substitutions like above `(1,1) , (2,2) , ...` are costless. In this case, the edit path is the same but the total cost is zero:

```julia
g = PathGraph(5)
edit_distance(g, g, subst_cost=(u,v) -> u != v ? 0.5 : 0.0)
# edit cost, edit path: (0.0, Tuple[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])
```

**Comment by sbromberger** [comment]
I’m a bit confused then. Since LG vertices are a `1:n` range, can’t edit distance (at least as currently implemented) simply be derived from the difference in the ranges’ upper bounds? That is, if edges aren’t taken into account, then it’s just up to the vertex set. 

What am I missing?

**Comment by juliohm** [comment]
@sbromberger the edit path is a function of the cost functions we specify. The sequence of edit operations with minimum cost is not only about counting the number of vertices, the cost functions can be more complex than the default constant cost functions. For example, we can say that it is much more expensive to replace 1 by 10 than it is to replace 1 by 2.

Adding the edge costs like proposed in this issue makes the algorithm even more powerful. We cannot infer the edit distance with just counting, there must be a search. Imagine two arbitrary complex graphs instead of `PathGraph` and `CycleGraph`.

**Comment by jpfairbanks** [comment]
Can we define a useful an edge cost function to add as an option?

Also this discussion would make a good notebook documentations.

**Comment by jpfairbanks** [comment]
@juliohm, how are things in Rio? Stalebot bumped this today.

**Comment by juliohm** [comment]
Life is good James! Thanks for asking. :) Working on some new features for
GeoStats.jl but can try find time to extend the edit distance next week. If
anyone wants to work on it please go ahead.

Cheers,

**Comment by juliohm** [comment]
A solution is being discussed in #1087
