### ISSUE TITLE
define `convert`er for graph types?

### ISSUE THREAD

**Issue by oxinabox** [JuliaGraphs/LightGraphs.jl#1037]
I was trying to workout how to convert a `SimpleWeightedGraph` into a `SimpleGraph`.

I expected 
`convert(SimpleGraph, myweightedgraph)` to work

but no such method exists.

What I ended up doing was `SimpleGraph(adjacency_matrix(myweightedgraph))`

Which seems like it should generally work.

```
convert{::Type{SimpleGraph}, graph::AbstractGraph} = SimpleGraph(adjacency_matrix(graph))
```

Or something like that?

And then the reverse could be defined too in SimpleWeightedGraphs.jl

**Comment by sbromberger** [comment]
```
julia> g1 = PathGraph(10)
{10, 9} undirected simple Int64 graph

julia> s1 = SimpleWeightedGraph(g1)
{10, 9} undirected simple Int64 graph with Float64 weights

julia> g2 = SimpleGraph(weights(s1))
{10, 9} undirected simple Int64 graph

julia> g2 == g1
true
```

**Comment by oxinabox** [comment]
Yes, so adding that as a `convert` overload

**Comment by sbromberger** [comment]
There's a bit of a gotcha there with explicit zeros in SWGs though: they'll be counted as edges. I'm not sure I'm in favor of a `convert` or a constructor at this point.

**Comment by oxinabox** [comment]
`convert`   falls back onto constructers, right?

Thing feels more like a conversion than a construction.
Idk if this is a reasonable rule of thumb but saying

"I am converting this weighted graph into an unweighted graph"

Than

"I sm contructing a new unweighted graph, based on this weighted graph"
I feel more natu

**Comment by sbromberger** [comment]
Convert is not standard within LightGraphs. We typically construct new graphs from different graph types. Conversion implies no loss; there is definitely a loss here as we're removing metadata.

If we add this – and I'm still not yet in favor – then it belongs in SimpleWeightedGraphs in any case.

**Comment by jpfairbanks** [comment]
I'm generally not clear on when to use a constructor and when to overload convert. What is the pro/con for that one decision?

We should definitely provide a constructor for SimpleGraph from every other AbstractGraph type.

I think the better fallback would be 
```julia
function SimpleGraph(g::AbstractGraph)
   g = Graph(nv(g))
   for e in edges(g)
       add_edge!(g)
    end
    return g
end
```

And graph types that are matrixlike, for example SimpleWeightedGraph could use your `SimpleGraph(adjacency_matrix(g))` approach.

**Comment by sbromberger** [comment]
> I'm generally not clear on when to use a constructor and when to overload convert. What is the pro/con for that one decision?

My opinion is that `convert(typeof(b), convert(typeof(a), b)) == b` is axiomatic. That doesn't work here.

> We should definitely provide a constructor for SimpleGraph from every other AbstractGraph type.

I do not agree at this point.

**Comment by sbromberger** [comment]
> But there should be a way to get the SimpleGraph underlying every AbstractGraph by removing metadata.

Why? The idea is that every algorithm in LightGraphs should work with any graph `<: AbstractGraph`. I can't think of any use case where it's desirable to create a `SimpleGraph` once you have another type. (Perhaps if you don't care about the metadata any more?)

That said: If there's an easy way to do this universally, then I'd be open to reviewing a PR. But my opinion is that there are way too many constructors (especially with all the type parameterization – just take a look at [SimpleWeightedGraphs](https://github.com/JuliaGraphs/SimpleWeightedGraphs.jl/blob/master/src/simpleweightedgraph.jl) for an example of the flexibility we need to provide – to make it worth adding another constructor with questionable benefit.
