### ISSUE TITLE
define `weight(::AbstractEdge)` here?

### ISSUE THREAD

**Issue by oxinabox** [JuliaGraphs/LightGraphs.jl#1041]
It seems that `weight` is only defined for `AbstractWeightedEdge`,
But `weights` is defined for `AbstractGraph`.

It seems like `weight` should be defined to be consistent with `weights`.

**Comment by sbromberger** [comment]
I'm not sure what you're looking for. `weights` defaults to `DefaultDistance` for graphs that do not support weighted edges, or you can pass in a "matrix-like" to any algorithm (e.g., Dijkstra) that can use weights.

**Comment by oxinabox** [comment]
The fact that `weights(g::SimpleGraph)` is basically  `fill(1, (nv(g), nv(g)))`  (without bounds checking)
is also pretty surprising.

I really expected 
`weights(g::SimpleGraph) == adjacency_matrix(g)` 

It is really weird to me that in the matrix form for edges that **don't exist** in a `SimpleGraph`, have weight `1`.
But in a in a `SimpleWeightedGraph` they have weight `0`.

I thought using `weights(g)` I would be able to write code based on working with the weight matrix,
I would end up with code that was agnostic to the type of graph.

**Comment by jpfairbanks** [comment]
I see why you would think that the weights of an AbstractGraph should be the adjacency matrix. The idea is that you wouldn't iterate over weights(g), but would iterate over the graph with `edges(g)` or `neighbors(g,v)` and then index into weights(g) to get the appropriate weight.

For your code that wants to use `weight(e::AbstractEdge) = 1` can you define your method locally?

**Comment by sbromberger** [comment]
Another idea is to simply do `adjacency_matrix(g) .* weights(g)`.

**Comment by sbromberger** [comment]
We can certainly put something like

> Weights on nonexistent edges are undefined and should not be referenced.

**Comment by sbromberger** [comment]
ref #1048

**Comment by sbromberger** [comment]
Closing via #1048.
