### ISSUE TITLE
Function to delete a bunch of vextexs at once

### ISSUE THREAD

**Issue by oxinabox** [JuliaGraphs/LightGraphs.jl#1043]
`rem_vertex!` can remove 1 vertex.
Which is fine.

But if you want to remove more than one vertex then it is really annoying to do so.
Since the ids will all change every time you remove one.

**Comment by oxinabox** [comment]
I am currently using code like

```
@show inds = findall(isolated_vertexes(sog))
@show offset_inds = inds .- (0:(length(inds)-1))
sog_clean = deepcopy(sog)
for to_del in offset_inds
    rem_vertex!(sog_clean, to_del)
end
```

Output:
```
inds = findall(isolated_vertexes(sog)) = [5, 6, 8, 10, 12, 13, 14, 15, 16, 17, 18, 20, 22]
offset_inds = inds .- (0:length(inds) - 1) = [5, 5, 6, 7, 8, 8, 8, 8, 8, 8, 8, 9, 10]
```

**Comment by simonschoelly** [comment]
Probably not the solution you are looking for, but you could just build the subgraph of non-isolated vertices. Something like 
```
keep = setdiff(vertices(sog), inds)
sog_clean = sog[keep]
```
A `rem_vertices!` function might still be nice - we also have an `add_vertices!` function

**Comment by oxinabox** [comment]
Nice, I didn't know indexing did that.

**Comment by sbromberger** [comment]
The proper way to get rid of a bunch of vertices at once is to use induced subgraphs, as @simonschoelly shows.

**Comment by simonschoelly** [comment]
The problem with the induced subgraphs that we have right now, is that they copy the graph which for large graphs uses a lot of memory. I see a legit use case for a function `rem_vertices!`: A user loads or creates a large graph and then removes all the vertices that they don't need, such as isolated vertices or vertices that do not belong to the largest component.

We even could have a flag `rem_vertices!( ..., preserve_order=true)` , which preserves the order. This operation is very costly if we would do it for every vertex that we want to remove, but if we do it for the whole batch of vertices that should be removed, then it might be worth it.

**Comment by sbromberger** [comment]
PRs welcome.
