### ISSUE TITLE
Cache-Efficient Parallel BFS

### ISSUE THREAD

**Issue by SohamTamba** [JuliaGraphs/LightGraphs.jl#1046]
Serial BFS is optimised using a `bitArray` instead of a `Vector{Bool}` to represent the `visited` array and hence, reduce the number of cache-lines to store the array.

This is not possible for parallel implementations as modifying a `bitArray` is not thread-safe. I thought I found a work around for it but there doesn't seem to be much performance improvement for the parallel implementation. The improvement in the sequential implementation also isn't as much as I expected.

A review would be appreciated
```
nthreads() = 10
|V| = 10000000  |E| = 1010000000  |s| = 1

--------------------Bool Parallel GDistances------------------------------
  10.220 s (76 allocations: 192.65 MiB)
--------------------Bit Parallel GDistances------------------------------
  9.226 s (81 allocations: 209.10 MiB)
--------------------Bool Serial GDistances------------------------------
  24.540 s (6 allocations: 162.12 MiB)
--------------------Bit Serial GDistances------------------------------
  21.684 s (7 allocations: 153.78 MiB)
```

Code:
[Serial Bool BFS](https://github.com/SohamTamba/LightGraphs.jl/blob/bit_BFS/src/traversals/gdistances.jl)
[Serial Bit BFS](https://github.com/SohamTamba/LightGraphs.jl/blob/bit_BFS/src/traversals/bit_gdistances.jl)
[Parallel Bool BFS](https://github.com/SohamTamba/LightGraphs.jl/blob/bit_BFS/src/Parallel/traversals/gdistances.jl)
[Parallel Bit BFS](https://github.com/SohamTamba/LightGraphs.jl/blob/bit_BFS/src/Parallel/traversals/bit_gdistances.jl)

The main idea behind `Parallel Bit BFS` is to first check the `bitArray` and then check the `Vector{Bool}`.
Most edges should be filtered using `bitArray`

cc: @sbromberger

**Comment by sbromberger** [comment]
That’s a 15% improvement in serial, and it will likely improve with larger graphs. If you can post the benchmark code I can run it locally on large graphs and will report back.

**Comment by SohamTamba** [comment]
Thanks

Here's the [code](https://gist.github.com/SohamTamba/c3a4578bbd07dc2d9034992117422347).

It creates a graph `static_scale_free(10000000, 1000000000, 3)`.

While benchmarking, I created the graph only once and stored it on the disk.
You might want to do the same. 
There's a `load(TT)` function in the script but you could probably use `GraphIO` instead.

Make sure to set the value of `nthreads`.
In my benchmarks, I set it to 10.
