### ISSUE TITLE
erdos_renyi(n, p) method runs forever when p = 1.0

### ISSUE THREAD

**Issue by Stachu270** [JuliaGraphs/LightGraphs.jl#1070]
It would be great to have an ability to perform erdos_renyi function with p=1.0.

**Comment by simonschoelly** [comment]
Well that's just a complete graph. But I have to agree, that this should not happen. I have some improved (faster!) Erdos-Reniy functions for LightGraphs, but they ready for a pr yet. If it is important to you, I can work on them.

**Comment by Stachu270** [comment]
It is not really important to me. Just fount it while doing some assignment and thought that there is no reasonable explanation why it should not work.

**Comment by jpfairbanks** [comment]
The problem is almost certainly a corner case for this loop. https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/SimpleGraphs/generators/randgraphs.jl#L97

We didn't think to test `er(n,1)` because it is `CompleteGraph(n)`

**Comment by jpfairbanks** [comment]
```julia
if p == 1
   return CompleteGraph(n)
end
```

makes sense to me, I would also be fine with 

```julia
if p >= 1
   return CompleteGraph(n)
end
```

because p>1 could only mean CompleteGraph or error, and I would rather not error when the right answer is unambiguous. I guess that is the WWW philosophy of robustness https://en.wikipedia.org/wiki/Robustness_principle. 

> Be conservative in what you send, be liberal in what you accept

**Comment by sbromberger** [comment]
Yeah, I agree with not erroring on > 1.0. Let me propose a PR today.
