### ISSUE TITLE
New Feature: Line graphs

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGraphs/LightGraphs.jl#1083]
Here is a proposal for people looking for issues to work on.
It would be great, if LightGraphs had support for [line graphs](https://en.wikipedia.org/wiki/Line_graph).

##### Things to do: 
In a first step, one should implement a function `linegraph` that creates a line graph from undirected and directed graphs. There should also be an option for getting the mapping from the new vertices to the old edges.
**Difficulty:** easy

##### Additional features: 
It would also be great to have a function that tests if a graph is a line graph of another graph and if it is, then get the original graph back.
**Difficulty:** medium

**Comment by jpfairbanks** [comment]
I agree this would be a good idea. This is a perfect opportunity for an "implicit graph" implementation. By that I mean, you can construct a type that represents the linegraph, but only uses storage for the original graph.

**Comment by abhinavmehndiratta** [comment]
I implemented a function linegraph but under what directory should it go

```julia
function is_comn_endpt(e1,e2)
    return src(e1) == src(e2) || src(e1) == dst(e2) || dst(e1) == src(e2) || dst(e1) == dst(e2)
end

function linegraph(g::AbstractGraph)
    nedg = ne(g)
    lg = is_directed(g) ? SimpleDiGraph(nedg) : SimpleGraph(nedg)
    edg_node = Dict(edges(g) .=> 1:nedg)
    edg_arr = [e for e in edges(g)]

    for i in 1:(nedg-1)
        for j in i+1:nedg
            e1 = edg_arr[i]
            e2 = edg_arr[j]
            if is_directed(lg)
                if dst(e1) == src(e2)
                    add_edge!(lg,edg_node[e1],edg_node[e2])
                end
                if dst(e2) == src(e1)
                    add_edge!(lg,edg_node[e2],edg_node[e1])
                end
            else
                if is_comn_endpt(e1,e2)
                    add_edge!(lg,edg_node[e1],edg_node[e2])
                end
            end
        end
    end
    
    return lg
end
```

**Comment by simonschoelly** [comment]
Maybe `src/operators.jl`? Also consider if it would not be better to implement James suggestion instead.

**Comment by jpfairbanks** [comment]
if instead of calling `add_edge!` and creating a new graph, that for loop was an implementation of `edges(g::LineGraph{G}) where G<:AbstractGraph`, then you would have most of the implementation of 

```julia
struct LineGraph{G}
   g::G
end
```

**Comment by sbromberger** [comment]
As brilliant as I think that suggestion is, I’m not sure what advantage it brings to add another struct to the mix. If we implement the function instead, I would like to see the `code_warntype` output to make sure it’s type stable. 

I love James’ creativity but am I sure whether a new struct type would be understood and used. 

We could also make a lazy variant of the function that provides an edge iterator instead of a fully-formed graph, I guess.

**Comment by jpfairbanks** [comment]
The linegraph of a graph is bigger than the underlying graph, right? 

If Linegraph(G) = (Vl, El) don't we have  |Vl| = |E| and |El| = |sum_i (degree_i choose 2)| or something?

I think the memory savings are worth it. Since all of the information is captured in the original graph.

**Comment by sbromberger** [comment]
The linegraph is indeed larger than the underlying graph (assuming a not-unresonably-sparse graph).

I guess my issue with the "lazy struct" (how perjorative!) is this: if you're creating a linegraph, presumably you want to *do* something with it, and you likely want to do more than one thing with it. Returning a larger graph via function is essentially "memoizing" the result; you can reuse the result with no additional computation time for its generation. With the linegraph as a structure, you're recomputing the linegraph every time you want to do something with it.

**Comment by abhinavmehndiratta** [comment]
> As brilliant as I think that suggestion is, I’m not sure what advantage it brings to add another struct to the mix. If we implement the function instead, I would like to see the `code_warntype` output to make sure it’s type stable.
> 
> I love James’ creativity but am I sure whether a new struct type would be understood and used.
> 
> We could also make a lazy variant of the function that provides an edge iterator instead of a fully-formed graph, I guess.

I am new to julia.But does this mean writing seperate functions for directed and undirected graphs as the return type (i.e linegraph) will be different for both of them and so the function will not be type stable ?

**Comment by sbromberger** [comment]
> But does this mean writing seperate functions for directed and undirected graphs as the return type (i.e linegraph) will be different for both of them and so the function will not be type stable ?

Yes. Sometimes the compiler can infer the return type correctly, but many times it can't. The best way to do this is to create a "master function" that takes the graph/digraph `g` and an empty AbstractGraph `h`, makes sure the `g` and `h` are the same types, and then fills and returns `h` appropriately. Then you have two functions that take `g::::IsDirected` and `g::::(!IsDirected)` and use those as the front-facing functions, creating `h` appropriately and calling the "master function" with `g` and `h`.

**Comment by abhinavmehndiratta** [comment]
Is this a right way to implement a lazy version of linegraph ?
```julia
using LightGraphs
import LightGraphs: SimpleEdge

function lineg_edges(g::AbstractGraph,ch::Channel)
        nodemap = Dict(edges(g) .=> 1:ne(g))
        earr = collect(edges(g))
        @async begin
            for i in 1:(ne(g)-1)
                for j in i+1:ne(g)
                    e1 = earr[i]
                    e2 = earr[j]
                    if is_directed(g)
                        if dst(e1) == src(e2)
                            put!(ch,SimpleEdge(nodemap[e1],nodemap[e2]))
                        end
                        if dst(e2) == src(e1)
                            put!(ch,SimpleEdge(lg,nodemap[e2],nodemap[e1]))
                        end
                    else
                        if (src(e1) == src(e2) || src(e1) == dst(e2)
                                || dst(e1) == src(e2) || dst(e1) == dst(e2))
                            put!(ch,SimpleEdge(nodemap[e1],nodemap[e2]))
                        end
                    end
                end
            end
            close(ch)
        end
end

function lazy_linegraph(g::AbstractGraph)
    ch = Channel{edgetype(g)}(1)
    lineg_edges(g,ch)
    return ch
end
```
