### ISSUE TITLE
Connectedness of directed graphs

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGraphs/LightGraphs.jl#1088]
Currently `is_connected(g)` is equivalent to `is_weakly_connected(g)` if `g` is a digraph. The English Wikipedia on the other hand says, that for a digraph, `g` is connected if for every pair of vertices `(u, v)` there is either a path from `u`to `v` or one from `v` to `u`.
To make stuff more complicated, I can't find that definition anywhere else in the literature. But apparanently this concept is called *semi-connected* in a lot of places (for example also in Networkx).
I would therefore propose to add a deprecation warning to `is_connected` for digraphs and also to implement a function `is_semi_connected` for digraphs.

Related issue: #368

**Comment by sbromberger** [comment]
There was a lot of discussion around this after #368. Paging @jpfairbanks.

**Comment by simonschoelly** [comment]
Can we revive this?

**Comment by sbromberger** [comment]
Sure. But I think this does what you want: `is_weakly_connected` is exactly
> `g` is connected if for every pair of vertices `(u, v)` there is either a path from `u` to `v` or one from `v` to `u`.

So having `is_connected(g::::DiGraph)` equal `is_weakly_connected(g)` adheres to the Wikipedia definition. What am I misunderstanding?

**Comment by simonschoelly** [comment]
In the digraph  
```
u <-- v --> w
```
there is no path from u to w or from w to u, but the graph is still weakly connected.
