### ISSUE TITLE
Articulation for directed graphs

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGraphs/LightGraphs.jl#1089]
Right now, the function `articulation(g)` allows `g` do be a digraph. That is probably an error, as in PR #529 , `SimpleGraph` was replaced by `AbstractGraph` in a lot of places.

If we keep `articulation` for directed graphs, we should at least document what this exactly calculates. We could probably introduce functions for articulation points with respected to the different concepts of connectivity in digraphs, e.g. `strong_articulation`

**Comment by simonschoelly** [comment]
@sbromberger  Do you have an opinion here?

**Comment by sbromberger** [comment]
Given that this function is probably not used for directed graphs right now, I'd suggest `@traitfn`ing it to undirected graphs only.

**Comment by simonschoelly** [comment]
This will eventually be implemented by #1111, so there is no point in making a PR for this only, so I am closing this.
