### ISSUE TITLE
Why can't we add label to the vertex and edges?

### ISSUE THREAD

**Issue by orhanabar** [JuliaGraphs/LightGraphs.jl#1091]
It would be good if we can give vertex a label.
Also, add_vertex does not get any argument for vertex name(id) it creates it starting from one. Why can't we choose vertex id?

**Comment by sbromberger** [comment]
This is the way SimpleGraphs work. You might want to take a look at [MetaGraphs](https://github.com/JuliaGraphs/MetaGraphs.jl) if you need labels.
