### ISSUE TITLE
Documentation rem_edge!

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGraphs/LightGraphs.jl#1103]
The documentation for `rem_edge! ` states the following:
```
### Implementation Notes
If `rem_edge!` returns `false`, the graph may be in an indeterminate state, as
there are multiple points where the function can exit with `false`.
```
In my opinion this is not true for `LightGraphs.SimpleGraphs`. Should we still keep that note in case some other package might error when a nonexisting edge gets removed?

**Comment by jpfairbanks** [comment]
Yeah. It might make sense to clarify that "the graph may be in an indeterminate state" is referring to the fact that the `AbstractGraph` API specification does not require ACID removals. It doesn't require Atomic, Consistent, Isolated, or Durable. SimpleGraph when used in serial programs is probably ACI but not D.

**Comment by simonschoelly** [comment]
I'm still not sure about this, but it might be better to close this now and maybe revisit it in the future.
