### ISSUE TITLE
inneighbors and similar methods provide direct access to the node adjacency vectors

### ISSUE THREAD

**Issue by ndinsmore** [JuliaGraphs/LightGraphs.jl#1107]
Because methods like inneighbors provides effectively a reference to the node adjacency vectors, any operations on the graph can have strange side effects.

Imagine that want to remove all the inflowing edges of a given node... you would expect the following to work:
```julia
for n in inneighbors(g,1)
   rem_edge!(g,n,1)
end
```
But strangely that ends up only removing every other edge.  With a little instrumentation, you can see why....  The for loop is trying to iterate while looking directly at ```g.fadjlist[1]```
```
julia> g=DiGraph(WheelGraph(10))
{10, 36} directed simple Int64 graph

julia> @show inneighbors(g,1);
inneighbors(g, 1) = [2, 3, 4, 5, 6, 7, 8, 9, 10]

julia> for n in inneighbors(g,1)
          @show n,inneighbors(g,1)
          rem_edge!(g,n,1)
       end
(n, inneighbors(g, 1)) = (2, [2, 3, 4, 5, 6, 7, 8, 9, 10])
(n, inneighbors(g, 1)) = (4, [3, 4, 5, 6, 7, 8, 9, 10])
(n, inneighbors(g, 1)) = (6, [3, 5, 6, 7, 8, 9, 10])
(n, inneighbors(g, 1)) = (8, [3, 5, 7, 8, 9, 10])
(n, inneighbors(g, 1)) = (10, [3, 5, 7, 9, 10])

julia> @show inneighbors(g,1);
inneighbors(g, 1) = [3, 5, 7, 9]
```
If this is documented please forgive me.

**Comment by sbromberger** [comment]
This is documented in the docstrings:

> ### Implementation Notes
> Returns a reference, not a copy. Do not modify result.

**Comment by ndinsmore** [comment]
Fair enough, but I would read that as don't modify the array , not don't modify the graph.

**Comment by sbromberger** [comment]
If you’d like to propose a change to clarify the docs, I’d be grateful.

**Comment by sbromberger** [comment]
Closing due to lack of interest/adoption. Feel free to continue discussion or submit a PR if you'd like to propose alternate wording.
