### ISSUE TITLE
transitiveclosure for simple graphs

### ISSUE THREAD

**Issue by AsileBcd** [JuliaGraphs/LightGraphs.jl#1114]
Some time ago I added  `transitiveclosure` and `transitiveclosure!` to the library. These two functions are built for DiGraphs. 

The equivalent for undirected graphs is missing, and as far as I can tell, looks like this.

```julia
"""
    ```transitiveclosure!(g::SimpleGraph, selflooped=false)```
Compute the transitive closure of an undirected graph.
If `selflooped` is true, add self loops to the graph.

### Implementation Notes
This version of the function modifies the original graph.
"""
function transitiveclosure!(g::Graph, selflooped=false)
    cc = connected_components(g)
    x = selflooped ? 0 : 1
    for comp in cc
        for i in 1:(length(comp) - x)
            for j in (i+x):length(comp)
                add_edge!(g, comp[i], comp[j])
            end
        end
    end
    return g
end 

"""
    ```transitiveclosure(g::SimpleGraph, selflooped=false)```
Compute the transitive closure of an undirected graph.
If `selflooped` is true, add self loops to the graph.
"""
function transitiveclosure(g::Graph; selflooped = false)
    copyg = copy(g)
    return transitiveclosure!(copyg, selflooped)
end
```
It is simplified compared to the DiGraph version, as there is no need to look outside connected components. Otherwise it is almost a copy past of `transitiveclosure` for DiGraphs. Would it be interested to add it to the library?

**Comment by sbromberger** [comment]
@AsileBcd do you want to work on this?

**Comment by AsileBcd** [comment]
Yes, sure! I will do that next weekend hopefully.

**Comment by sbromberger** [comment]
@AsileBcd are you still interested in working on this? If so, I'll keep it open. Thanks.

**Comment by AsileBcd** [comment]
Yes, I am, sorry for the delay. I will take care of this ASAP.
