### ISSUE TITLE
neighborhood and egonet functions broken.

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#1116]
The issue in a nutshell:
```
julia> g = CycleGraph(4)
{4, 4} undirected simple Int64 graph

julia> egonet(g, 1, 3)
ERROR: ArgumentError: Vertices in subgraph list must be unique
```

This is because
```
julia> neighborhood(g, 1, 3)
5-element Array{Int64,1}:
 1
 2
 4
 3
 3
```

because
```
julia> neighborhood_dists(g, 1, 3)
5-element Array{Tuple{Int64,Int64},1}:
 (1, 0)
 (2, 1)
 (4, 1)
 (3, 2)
 (3, 2)
```

There's another  problem with `neighborhood_dists`:

```
g = SimpleDiGraph([0 1 1 0; 0 0 0 1; 0 0 0 1; 0 0 0 0])
add_edge!(g, 1, 4)
```
![iterm2 orxhuc](https://user-images.githubusercontent.com/941359/51572989-5564ba80-1e5c-11e9-8b3c-622be178047c.png)

```
julia> neighborhood_dists(g, 1, 4)
6-element Array{Tuple{Int64,Int64},1}:
 (1, 0)
 (2, 1)
 (3, 1)
 (4, 2)
 (4, 2)
 (4, 2) # this is wrong - at least one of these should be distance `1`
```

In any case, `neighborhood_dists` should only be unique vertices, and they should hold the minimum distance. This will result in `neighborhood` being a unique vector, and will thus fix `egonet`.

Hat tip: @danberge.

**Comment by jpfairbanks** [comment]
Yes this is a problem. We have two questions for the solution.

Q1: What is the right answer mathematically?
A: `neighborhood(g, v, 3)` should be the set of vertices with dist <= 3 from v. 

Q2: What is the right data structure to use for the return value of the function? 
A: I think any iterable collection that contains every vertex in the set exactly once is a good candidate. This means that `sort(collect(neighborhood(g,v,3)))==sort(unique(collect(neighborhood(g,v,3))))`. I don't think the API contract should be any more specific than that. I think that `Set` and `Vector{Int}` are equally valid return values and want to leave open the possibility that `neighborhood(g::SetGraph,v,3)::Set{Int}` for a hypothetical `SetGraph <: AbstractGraph` which stores the neighborhoods as sets.

**Comment by Dom-Skinner** [comment]
Hi all, 

I think I'm still having the same issue as above with neighborhood not giving what I was expecting.

If I define a graph:

```
g = SimpleGraph(4)
add_edge!(g, 1,  2)
add_edge!(g, 1,  3)
add_edge!(g, 2,  3)
add_edge!(g, 3  ,4)
```

Then neighborhood(g,1,1) is as expected
```
julia> println(neighborhood(g,1,1))
[1, 2, 3]
```

but neighborhood(g,1,2) I would expect to be [1,2,3,4] as all vertices are at most 2 edges away from vertex 1. Instead I get
```
julia> println(neighborhood(g,1,2))
[1, 2, 3, 3]
```

I tried deleting the package and reinstalling. Package version I'm using:

```
 julia> Pkg.status("LightGraphs")
     Status `~/.julia/environments/v1.1/Project.toml`
   [093fc24a] LightGraphs v1.3.0
```

**Comment by sbromberger** [comment]
Apparently fails on triangle with tail.

**Comment by Dom-Skinner** [comment]
> Apparently fails on triangle with tail.

Sorry! I realized the updated LightGraphs version fixed this bug. I removed and reinstalled LightGraphs, but that didn't change anything until I restarted my IDE and only then was the updated package used. It's working now.

**Comment by sbromberger** [comment]
Good to hear. Thanks for the update!
