### ISSUE TITLE
New Feature: Counting the total number of triangles in a graph

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGraphs/LightGraphs.jl#1121]
Right now, `LightGraphs` only has the ability to count the number of triangles in a neighborhood of a vertex `v`. with the function `triangles(g, vertices)`. Obviously we could then just calculate `triangles(g, vertices(g)) ÷ 3` but there should be a faster way to do that.
This problem is sometimes used in benchmarks such as the [GAP Benchmark Suite](http://gap.cs.berkeley.edu/benchmark.html). There is also a lot of interest in this problem in the context of parallel graph algorithms.

A first implementation does not have to be the fastest, but could serve as a reference for further improvements.

Difficulty: Easy/Medium

**Comment by abhinavmehndiratta** [comment]
> I have learned a novel way of doing this quickly that I am happy to describe to whomever decides to take this on.

For undirected graphs we could just calculate trace(A^3) / 6 where A is the adjacency matrix but that would use V^2 space is there a better solution ?

**Comment by sbromberger** [comment]
triangle counting is a hard problem on large graphs - that's why it's part of the [MIT Graph Challenge](https://graphchallenge.mit.edu/champions). Note that I work with Roger and Geoff; they're the ones that came up with the technique I referred to earlier.

**Comment by abhinavmehndiratta** [comment]
Oh I just looked at  _"Fast Triangle Counting Using Cilk"_  but I have limited knowledge regarding parallelism will have to read up on it

**Comment by simonschoelly** [comment]
It is usually best to avoid creating solutions that use V^2 space, as these will not work with large sparse graphs. Also, a first implementation does not have to be parallel, it would actually be good to have a sequential algorithm, so we can check if the parallel version is really faster.

**Comment by alimamdouh212** [comment]
@sbromberger  @simonschoelly  what is the statue of that issue now, i would like to work on it.

**Comment by sbromberger** [comment]
I'd prefer if we merge/close out some of your other PRs first.
