### ISSUE TITLE
New Feature: Randomly orient edges of graphs.

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGraphs/LightGraphs.jl#1122]
For benchmarking and testing graph algorithms we often need directed graphs, sometimes also ones without cycles.
While a directed Erdös-Renyi-graph could work in such a case, it has poor locality and has cycles. `LightGraphs` has some generators for graphs with certain properties, but these graphs are often undirected. It would therefore be nice, if we had some functions that would take a graph, and return a random edge orientation.

Things that could be considered:
* What fraction of the edges should only be oriented in one directed and what fraction in both directions?
* We should have a function that avoids producing cycles and might have the probability of choosing a starting vertex.
* I haven't done much research into that, but it would be nice, if we had a a function that produces a random orientation where the number of weakly connected components significantly differs from the number of strongly connected components.

Difficulty: Easy/Medium

**Comment by jpfairbanks** [comment]
These are interesting questions. Is there an existing literature on these problems. @sbromberger works with some people who have done serious thinking about counting directed cycles and their applications.

**Comment by sbromberger** [comment]
Since we've merged #1148, can we close this or do we need to keep it open for more types of random graphs?

**Comment by simonschoelly** [comment]
I would leave it open, it still would nice if we had a function that takes an undirected graph and returns a directed graph with every edge oriented randomly and a fraction of the edges directed in both directions.

**Comment by sbromberger** [comment]
that one sounds deceptively simple :)
