### ISSUE TITLE
New Feature: Adjanceny-matrix reordering algorithms.

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGraphs/LightGraphs.jl#1123]
Wikipedia can explain the bandwidth of a graph better than I: [https://en.wikipedia.org/wiki/Graph_bandwidth](https://en.wikipedia.org/wiki/Graph_bandwidth)
Reducing the bandwidth of a graph could possibly increase the speed of some algorithms because of better cache locality; but I cannot guarantee that it actually will, that is something that we have to try.

There are various algorithms for doing that. For exampe BGL has some of them in the subsection "Sparse Matrix Ordering Algorithms": [https://www.boost.org/doc/libs/1_69_0/libs/graph/doc/table_of_contents.html](https://www.boost.org/doc/libs/1_69_0/libs/graph/doc/table_of_contents.html)

Difficulty: Easy

**Comment by jpfairbanks** [comment]
I think should be a more general "Matrix reordering algorithms" issue. Reducing bandwidth is good for some algorithms and some sparsity patterns, but is not the most effective way to improve performance for sparse matrix algorithms.

**Comment by simonschoelly** [comment]
Alright, I changed the name. Hopefully the intent is still clear. If you know some better algorithms for reordering, you could maybe add them here - I'm mainly creating these issues so people interested in contributing to `LightGraphs` have something to do.

**Comment by abhinavmehndiratta** [comment]
I tried to implement the rcm algorithm , here -
https://github.com/abhinavmehndiratta/jupyter/blob/master/RCM.ipynb

**Comment by simonschoelly** [comment]
At one point you can create a PR with this code, that would make it easier to comment on your code. Here are some ideas:
- Maybe it would be sufficient if your algorithms outputs a permutation of the vertices as a vector. Then you can use `g[your_permutation]` to get the permutated graph.
- You could do some benchmarks now, to check if some algorithms are now faster with the permutated graph, for example the isomorphism algorithms might benefit.
- If you benchmark, you should ensure, that you use the smallest `eltype` that is necessary for storing your graph. By default we have `eltype(g) == Int`, but for example a graph with only 200 vertices would benefit from having `eltype(g) == UInt8`. This also means, that the output of your algorithm should have the same eltype as the input.
- If you are developing with a terminal, the package `UnicodePlots`  has a method `spy` that can also visualize sparse matrices.

**Comment by sbromberger** [comment]
Sorry to jump in so late, but why are these algorithms unique to graphs and adjacency matrices? That is, RCM is a general matrix operation. It might have benefits to us in LightGraphs (?) but I would argue that it probably belongs in a different package altogether (like LinearAlgebra or SparseMatrices or ...)

I am open to persuasion. :)

**Comment by simonschoelly** [comment]
The advantage is, that RCM (and other matrix reordering algorithms) can improve performance of graph algorithms as it improves locality, so caching performs better. I commented on some experiments on this #1128.

The inspiration for this issue actually came from the (Boost Graph Library)[https://www.boost.org/doc/libs/1_69_0/libs/graph/doc/table_of_contents.html] where they have several of these reordering algorithms.

**Comment by simonschoelly** [comment]
Here is a benchmark, that shows how speed can improve by reordering the vertices:
```
julia> using LightGraphs, BenchmarkTools, Random

julia> g = dorogovtsev_mendes(10^5)
{100000, 199997} undirected simple Int64 graph

julia> g_rand = g[randperm(nv(g))];

julia> g_ord = g[reverse_cuthill_mckee(g)];

julia> @btime connected_components(g);
  25.120 ms (42 allocations: 4.77 MiB)

julia> @btime connected_components(g_rand);
  25.641 ms (42 allocations: 4.77 MiB)

julia> @btime connected_components(g_ord);
  9.681 ms (42 allocations: 4.77 MiB)
```
