### ISSUE TITLE
Proposal: Return NamedTuple instead of Tuple from functions

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGraphs/LightGraphs.jl#1127]
In some functions, such as `label_propagation` we return two arguments in form of a `Tuple`. I would propose that we change that so that the return a `NamedTuple`. Then a user could write
```
label_propagation(g).label
```
or 
```
label_propagation(g)[:label]
```
instead of 
```
label_propagation(g)[1]
```
where one would actually have to check the documentation of `label_propagation` to know, what actually happens.

The disadvantage of this is, that it might break some existing code.

Here are some functions that return tuples, there might be more:
* `label_propagation`
* `mincut`
* `euclidean_graph`
* `non_backtracking_matrix`
* `karp_minimum_cycle_mean`
* `local_clustering`
* `induced_subgraph`

**Comment by sbromberger** [comment]
I really like this idea.
