### ISSUE TITLE
Interface / feature request: destructuring of edges

### ISSUE THREAD

**Issue by chethega** [JuliaGraphs/LightGraphs.jl#1132]
It would be really convenient to write `src_vertex, dst_vertex = edge`, and likewise `for (u,v) in edges(g)`.

In order for this to work, we would need to add 
```
function Base.indexed_iterate(e::LightGraphs.AbstractEdge, i::Int, state=1)
i == 1 && return (src(e), 2)
i == 2 && return (dst(e), 3)
throw(BoundsError(e, i))
end
```
and declare that the interface requires that edges destructure as source, destination, and then optional metadata. Weighted graphs people could just extend the method and use `i==3` and following for their own argument destructuring.

Example:
```
julia> function Base.indexed_iterate(e::LightGraphs.AbstractEdge, i::Int, state=1)
       i == 1 && return (src(e), 2)
       i == 2 && return (dst(e), 3)
       throw(BoundsError(e, i))
       end

julia> g=SimpleGraph(5); add_edge!(g, 3, 4);

julia> for (u,v) in edges(g)
       @show u,v
       end
(u, v) = (3, 4)

julia> for (u,v,z) in edges(g)
       @show u,v
       end
ERROR: BoundsError: attempt to access Edge 3 => 4
```

**Comment by sbromberger** [comment]
We had this before but ran into a few issues: specifically, what do we do with metadata and/or weights? Does this work only for `AbstractSimpleEdge`?

**Comment by simonschoelly** [comment]
We could either only do it for concrete types, then it is no problem at all and up to the developers of each packae. 
Or we could get use `fieldnames` to get the names of the fileds.  Then we could write a generated function that does this.

**Comment by chethega** [comment]
We can write this for `AbstractEdge`, and it will work for all `<: AbstractEdge` that don't specialize destructuring already. No need to go `@generated` or look at `fieldnames`.

Metadata / weight people can override for more destructured elements, as long as the first and second destructuring values are `src` and `dst` (which is pretty canonical, right?).

Specifying what comes in third or fourth position would be the job of `AbstractWeightedEdge` or `AbstractMetaEdge`, I'd guess.

**Comment by simonschoelly** [comment]
You are right, we don't need to use `@generated`, we can use `getfield`, then we have
`indexed_iterate(e::AbstractEdge, i::Int, state=1) = (getfield(e, i), i + 1)`
Not sure yet, what `state` does.

**Comment by chethega** [comment]
No, we don't need `getfield`, we need exactly what I wrote: The first `indexed_iterate` gives the `src(e)`, the second `dst(e)`. 

We do not want to know the memory layout of `AbstractEdge`; for all we know, some crazy person uses 14 bit `src`, 14 bit `dst` and 4 bits of flags, all packed into an `UInt32`, and implemented exactly our interface by extracting some bits and converting them to an integer. The only thing we know about `<:AbstractEdge` is that we can call `dst` and `src`, and that is enough to implement a generic fallback that works.
