### ISSUE TITLE
Shortest path for unweighted graphs

### ISSUE THREAD

**Issue by abhinavmehndiratta** [JuliaGraphs/LightGraphs.jl#1136]
If i use BFS instead of Dijkstra it is much faster.It could be an addition for SimpleGraphs.
```julia
julia> g = SimpleGraph(200000,1600000)

julia> function shortest_path_bfs(g::SimpleGraph{T},src::T) where T
           visited = falses(nv(g))
           dist = [typemax(T) for _ in 1:nv(g)]
           q = Vector{T}()
           
           visited[src] = true
           dist[src] = zero(T)
           push!(q, src)
           
           while !isempty(q)
               u = popfirst!(q)
               for v in outneighbors(g, u)
                   visited[v] && continue
                   visited[v] = true
                   dist[v] = dist[u] + 1
                   push!(q, v)
               end
           end
           
           return dist
       end
shortest_path_bfs (generic function with 1 method)

julia> shortest_path_bfs(g, 1) == dijkstra_shortest_paths(g, 1).dists
true

julia> @btime dijkstra_shortest_paths(g, 1).dists
  256.262 ms (71 allocations: 18.49 MiB)

julia> @btime shortest_path_bfs(g, 1)
  80.051 ms (23 allocations: 4.55 MiB)
```

**Comment by sbromberger** [comment]
ref: #1077. It might be better instead to make this a version of Dijkstra's that works on unweighted graphs.

**Comment by abhinavmehndiratta** [comment]
Sorry my bad, I didn't realize that gdistances did that already. Should I close this then ?

**Comment by sbromberger** [comment]
No, but let's make a variant of `dijkstra_shortest_paths` that uses this when no weights are needed. Have it return a `DijkstraState` and have all the options (except for `distmx`).

**Comment by abhinavmehndiratta** [comment]
> No, but let's make a variant of `dijkstra_shortest_paths` that uses this when no weights are needed. Have it return a `DijkstraState` and have all the options (except for `distmx`).

But wouldn't this be confusing as the name suggests that dijkstra algorithm would be used but instead we are using gdistances ?
