### ISSUE TITLE
Wilson's algorithm for Uniform Spanning Trees

### ISSUE THREAD

**Issue by dahtah** [JuliaGraphs/LightGraphs.jl#1151]
I have an implementation of Wilson's classic algorithm for Uniform Spanning Trees that I can contribute, is there any interest in that?

**Comment by simonschoelly** [comment]
This algorithm will sample u.a.r a spanning tree from all spanning trees of a graph? Sounds interesting to me.

**Comment by dahtah** [comment]
Yes, it's from this classic paper: Wilson, D. B. (1996). Generating random spanning trees more quickly than the cover time. In STOC (Vol. 96, pp. 296-303). 
I'll prepare a pull request

**Comment by sbromberger** [comment]
ref: #1162
