### ISSUE TITLE
Documentation for Custom GraphTypes....

### ISSUE THREAD

**Issue by FHell** [JuliaGraphs/LightGraphs.jl#1165]
We are working on a small package to work with embedded graphs, and ran into some trouble along the way. It appears that the developer documentation is a bit out of date or some functions are overly specific in what they accept. Esepcially when it comes to weights.

Repo is here: https://github.com/FHell/EmbeddedGraphs.jl

For weights the developer documentation states that the output of weights only needs to be indexable. It actually is required to be 
`<: AbtractMatrix{Real}`
as far as we have discovered.

For the interface the following functions are needed but not in the Developer Documentation:

```
zero(g::CustomGraph) = EmbeddedGraph(SimpleGraph(0), [], distance)
edgetype(::CustomGraph{T,U}) where T <: Integer where U = LightGraphs.SimpleEdge{T}
```

For the functions on the types, edgetype and is_directed the interface.jl error message and the documentation suggest that it would be sufficient to define
```
is_directed(::Type{CustomGraph}) = false
edgetype(::CustomGraph) = LightGraphs.SimpleEdge{Any}
```

These don't seem to work if the CustomGraph has the normal parameter, when it should be

```
is_directed(::Type{CustomGraph{T, U}}) where T <: Integer where U = false
edgetype(::CustomGraph{T, U}) = LightGraphs.SimpleEdge{T}
```

Especially the first threw us for a massive loop as the error occurs in some corner of SimpleTraits.

**Comment by simonschoelly** [comment]
Actually I think it might be easier to define
```
is_directed(::Type{<:CustomGraph}) = ...
```
and
```
edgetype(g::CustomGraph) = LightGraphs.SimpleEdge{eltype(g)})
```
but I agree with you, that if it is not mentioned in the documentation, then it should be.

What do you use the `zero` function for? As far as I know, that is usually not specified as part of the interface.

**Comment by sbromberger** [comment]
I think we should clarify `weights` as follows:

```
Note that the output does not necessarily have to be a dense matrix, but it must be a subtype of `AbstractMatrix{<:Real}` and indexable via [u, v].
```

Thoughts?

**Comment by sbromberger** [comment]
actually, `zero()` made it into the interface. I'll add the docs.

**Comment by simonschoelly** [comment]
I don't think we should require that the matrix that is returned by `weights` has eltype `Real` - that requirement should be left to the algorithms working with `weights`. Otherwise we might restrict ourself too much - for example `Unitful.jl` types are not subtypes of `Real`.

**Comment by sbromberger** [comment]
I don't know what breaks if we don't, though. I assume `Unitful` takes care of ordering, but...

**Comment by sbromberger** [comment]
Ah, I think we can `<: Number`.

**Comment by FHell** [comment]
Thanks! Looks great and I learned something here! :)
