### ISSUE TITLE
RFC: Parameterized Graphs {T<:Integer}

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#117]
I've got a use case where I need the ability to reference nodes that have a range of 2^128. That is, I could represent the graph without external mapping if I were able to use 128-bit ints instead of what we currently have, which is Int (which defaults to 64 or 32 depending on system).

Conversely, if I know I have a small graph, it might make sense to specify an integer size < 64 or 32 bits. This would result in memory savings, and perhaps some speed.

Finally, allowing parameterization can eliminate the inconsistency of relying on system default Int sizes.

Drawbacks (will add more as I think of them):
- Increased complexity
- need to decide what happens when add_vertices!(n) produces nv(g) > chosen typemax
- how we handle defaultdistance / edge weights may have to change as well

Anyway - thoughts on this idea?

**Comment by jpfairbanks** [comment]
What is the source of 2^128 nodes? you don't actually have more than 2^64 nodes right? Another solution to this problem I have seen before is to map names (arbitrarily large strings) to int64 and then use the int64 to index the graph. A Dict{T, Int} is appropriate for this. Then you can have graphs indexed by strings as well as by int128 or int32.

**Comment by sbromberger** [comment]
IPv6 addresses are 128 bits long. It would be convenient to be able to do graph analysis of v6 network traffic without having a translation dict.

Also, for IPv4, I only need 32 bits. It might be more performant to be able to create a graph with smaller-sized ints.

**Comment by jpfairbanks** [comment]
```julia
type Graph
    vertices::UnitRange{Int}
    edges::Set{Edge}
    fadjlist::Vector{Vector{Int}} # [src]: (dst, dst, dst)
    badjlist::Vector{Vector{Int}} # [dst]: (src, src, src)
end
```

`fadjlist` and `badjlist` need to be sparse representations indexed by T if you want to do that. It is a good idea because then when one goes to distribute these graphs across memory spaces that is easier. The biggest graph processing systems use such techniques. Translation from the big space to a small space will be happening somewhere, either before the data gets into the graph or inside the graph.

**Comment by sbromberger** [comment]
mmm. Yup. I forgot about fadjlist and badjlist appending. The problem is that performance is really bad with sparse matrices right now, so this will likely have to wait until the situation improves a bit.

Closing out due to inviability but can continue discussion for future implementation if you'd like. Thanks for the input!
