### ISSUE TITLE
Add CUDA support

### ISSUE THREAD

**Issue by yuehhua** [JuliaGraphs/LightGraphs.jl#1192]
I hope to add CUDA suuport for graph data structure, thus, graph could be calculated by GPU.

I checked the data structure of graph, for example, `SimpleGraph`:

```julia
mutable struct SimpleGraph{T <: Integer} <: AbstractSimpleGraph{T}
    ne::Int
    fadjlist::Vector{Vector{T}} # [src]: (dst, dst, dst)
end
```

The adjacency list  of a graph is `Vector{Vector{T}}`, while CUDA use `CuVector`.

A straight way to deal with this problem is change `Vector{Vector{T}}` to `AbstractVector{AbstractVector{T}}` for all graphs.

I have no idea whether the solutions above may cause any performance issue.

The other way is to design a specialized graph data structure with `CuVector`.

Any suggestions?

**Comment by sbromberger** [comment]
In general, data structures should use concrete types for best performance. The way I'd recommend you approach this is to create a new graph type called `CudaGraph` or something, and implement the interface functions. Details can be found in [the developer documentation](http://juliagraphs.github.io/LightGraphs.jl/latest/developing.html).

**Comment by yuehhua** [comment]
Thank you for suggestion. I check my project again, and figure out I just have to make values of `PropDict` in `MetaGraphs` for CUDA support.

**Comment by sbromberger** [comment]
I'm not sure how that would work. MetaGraphs uses SimpleGraphs as the backend.

**Comment by yuehhua** [comment]
I need vertex, edge, graph properties for  CUDA calculation.
