### ISSUE TITLE
savegraph() does not save graph properties of metagraphs.

### ISSUE THREAD

**Issue by mikeKAH** [JuliaGraphs/LightGraphs.jl#1203]
Dear folks,
I want to save a metagraph to file using 
`savegraph("mygraph.txt", mg, GMLFormat() )`

The node/edge properties are correctly stored in mg, however, they to not appear in `mygraph.txt`.
I also opened a thread and provide a minimal example [here](https://discourse.julialang.org/t/metagraphs-graphio-how-to-save-graph-properties-to-file/23553).
Best regards, mike

**Comment by sbromberger** [comment]
MetaGraphs persistence is currently limited to `MGFormat()` and `DOTFormat()`.
