### ISSUE TITLE
Maximum cost path problem

### ISSUE THREAD

**Issue by Tarlan0001** [JuliaGraphs/LightGraphs.jl#1207]
Is it possible to solve the following problem using LightGraphs.jl?

I have a graph with 10 levels, on each level, there are 100 vertices. The tree is directed: from a vertex from level 1 it's possible only to go to any vertex of level 2.
 
I can begin from any vertex of level 1. Each pair of vertices `i` and `j` have `d()`-distance, and `c()`- cost. The distance should be less than some fixed value F to connect those vertices.

I need to build a path from level 1 to level 10 with the maximum cost. The path may go through each vertex only once.

I suppose BFS is suitable. I will appreciate for the demo of the usage for this purpose!

**Comment by sbromberger** [comment]
Others may have a better approach, but I'd probably look at this in three steps:

1) remove all edges that do not satisfy "distance < F". This may result in a disconnected graph.
2) reweight the edges based on cost, but map it so that the new distances are the inverses of the costs.
3) use dijkstra with a source set that includes level 1 vertices to find the shortest path from level 1 to each vertex in level 10, and pick the one with the shortest distance.

Again, there may be a more clever way of doing this, and I'm not sure of the remapping of `c()` to make this a shortest-paths problem (vs a max-cost problem), but it should get you started.

**Comment by Tarlan0001** [comment]
@sbromberger Thanks!
I can't remove edges that do not satisfy "distance < F", because, there are always two edges `n_i` and `n_j`, that can be connected.
Also, the initial edge is not fixed and there are 100 possibilities...

**Comment by sbromberger** [comment]
> I can't remove any edge that does not satisfy "distance < F", because, there are always two edges `n_i` and `n_j`, that can be connected.

I'm not sure I understand what you mean by "there are always two edges." A given node at level `n` has edges only to nodes at level `n+1`, right? The constraint is that each edge must be at a distance less than `F`. What do you mean by connected edges?

**Comment by Tarlan0001** [comment]
I mean, that for any edge on level 1 there is an edge exists on level 2,that the distance is less than F.
So, I can't remove any edge from the graph as you said.

**Comment by sbromberger** [comment]
Oh, so you've already filtered the graph (step 1). OK. Then you can just start w/ Step 2.

**Comment by sbromberger** [comment]
This would also be a great discussion for our Slack channel. :)

**Comment by Tarlan0001** [comment]
No, I can't build the path on the basis of inversed costs ans ignore the distances. If the distance is more than F, the path can't go through that edge.

**Comment by Tarlan0001** [comment]
Would you be so kind to forward this on the Slack?

**Comment by sbromberger** [comment]
There's no way to forward threads from github to slack. Join the Julia Slack (https://julialang.slack.com/; go to https://slackinvite.julialang.org/ if you need an invite) and then join the `#graphs` channel.

**Comment by sbromberger** [comment]
Also: I think this process described above will work. At the end of Step 2, before you "pick the one with the shortest distance", you have an (ordered) list of paths that meet the "maximum cost" requirement for each vertex in level 1 to each vertex in level 10. Then all you need to do is filter that list to remove all paths in the list that exceed `F`, and pick the first one.

**Comment by sbromberger** [comment]
I'm still a bit confused by `F`. Does `F` represent the maximum allowed distance for a path from level 1 to level 10, or does it represent the max distance allowed between levels `n` and `n+1`?

**Comment by Tarlan0001** [comment]
It's maximum distance between 2 edges from levels `n` and `n+1`

**Comment by sbromberger** [comment]
Then you should filter the graph as I described in step 1. That will prune all edges that do not meet this requirement.

**Comment by Tarlan0001** [comment]
> Edit: but what do you mean by "distance between two edges"? Usually distance is measured between two _vertices_.
Sorry, I meant vertices. Edited.

**Comment by sbromberger** [comment]
Again, you'll probably get better help in Slack, but if there's a case that two vertices are connected by an edge that has a distance greater than `F`, then you need to prune those before you start (that's step 1 in the above process). From there you can then proceed to step 2.

**Comment by Tarlan0001** [comment]
I have written in slack. But still no help :)
