### ISSUE TITLE
Assumption on vertices ordering

### ISSUE THREAD

**Issue by matbesancon** [JuliaGraphs/LightGraphs.jl#1209]
As discussed in this blog [post](http://matbesancon.github.io/post/2019-05-30-vertex-safe-removal/), there are stronger assumptions in the interface than in the documentation on `vertices(g)`.

It is indeed used as an ordering in many algorithms that don't expect a specific graph type. The problem with the current state is that:

`vertices(g)` is completely redundant with `1:nv(g)`
Any graph for which this doesn't hold breaks for algorithms (at least the first two I picked, kruskal and pagerank)

**Comment by sbromberger** [comment]
I think this is a good discussion to have but I don't know what can be done to remove the ordering requirement without rewriting significant parts of LightGraphs. Certainly specific graph types such as SimpleGraphs, StaticGraphs, MetaGraphs, and SimpleWeightedGraphs require ordered vertices, and I don't know a way around that short of rewriting the code which will make it less performant.

For new graph types, I see the dilemma. We could perhaps start extending our use of traits via SimpleTraits, and tag functions that assume ordered vertices, but when do we stop? There are probably other priorities out there (having adjacency lists, for example, or "matrix-friendly" backing stores...)

**Comment by sbromberger** [comment]
> The first fix is to make vertices return 1:nv(g) for VSafeGraph, but if you think about it, it means it needs to do such with any graph type, which means the vertices function is redundant with other functions of the interface and should not be mandatory. The other option is to fix breaking code to really use the interface signalled and documented and not the leaked implementation.

The issue, I think, is that people are using `vertices` when they really mean `1:nv(g)`, and `1:nv(g)` when they really mean `vertices`. That is, `vertices` should really just promise an iterator over vertices, and `1:nv(g)` should produce a (self-explanatory) range.

**Comment by matbesancon** [comment]
Code like coloring, pagerank or Kruskal are using `vertices`, and then using its elements for indices in vectors that have size `nv(g)`.

We can use `VSafeGraphs` (or any other test graph) to test that code should not use vertices for `1:nv(g)`.

Agreed that this would start being a bit heavy to use another trait for that. The first thing we could do is for all those algorithms, see whether the vertex ordering assumption is really that bad to remove.

**Comment by simonschoelly** [comment]
Two comments on this:
1. In your blog post you are talking about the difference between vertex indices and vertex values. I think there might be a third kind, namely vertex label. The difference between a value and a label is, that you can use the label to refer to a certain vertex, And the difference between a label and an index is, that we have some restrictions on indices (consecutive integers for example), that allow us to write fast algorithms.

2. Instead of relying on `SimpleTraits.jl`, we could also implement the traits without macros. That would make analysis a bit more transparent and allows us to avoid certain restrictions that SimpleTraits as.

**Comment by matbesancon** [comment]
> The difference between a value and a label is, that you can use the label to refer to a certain vertex

Ok interesting, so you are thinking value in terms of what MetaGraph would give right? I was using `vertex_value` as you are using `vertex_label`. But I would tend to agree that label is a more meaningful term here.

**Comment by matbesancon** [comment]
> Instead of relying on SimpleTraits.jl, we could also implement the traits without macros. That would make analysis a bit more transparent and allows us to avoid certain restrictions that SimpleTraits as.

+1 for that, it's fairly easy to write this trait here.
