### ISSUE TITLE
[breaking] snake_case for the construction of new simple graphs

### ISSUE THREAD

**Issue by matbesancon** [JuliaGraphs/LightGraphs.jl#1221]
`LightGraphs.CompleteGraph` and such can lead to confusion, because of the syntax one might think they are constructing something of type CompleteGraph. We should deprecate these constructors in favour of:
- `LightGraphs.complete_graph`
- `LightGraphs.path_graph`
- `LightGraphs.binary_tree`

**Comment by sbromberger** [comment]
Yes. This has been a disappointment of mine for a while. My suggestion is to create the snake case and alias the camel case with deprecation now, and then remove the deprecation in 2.0. PRs gratefully accepted.

**Comment by matbesancon** [comment]
fixed in #1233
