### ISSUE TITLE
Proposal: github issue template

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#1224]
Given that having consistent bug reports is a good thing, I propose creating an issue template with (at least) the following information:

1) Julia version
2) LightGraphs version
3) Issue type (bug / enhancement / performance)
4) Description of issue (what happened)
5) Description of expected behavior (what did you expect to happen)
6) minimal working example demonstrating issue (optional but encouraged)
7) Suspected cause (optional but encouraged)
8) link to PR (optional)

Am I missing anything here? Is this too complex?

I'd like to implement this as quickly as possible (by, say, 28 June).

**Comment by simonschoelly** [comment]
Roughly how the bug template looks for me at work, has maybe a fever items:
- Summary (Not sure if that is needed, most of the times people seem to copy the title here)
- How to reproduce (can also contain a MWE)
- Excepted behavior
- Actual behavior
- Additional stuff (so suspected cause, link to PR can all be here) 

For point 1. and 2.  you could add the information that they should run
```
versioninfo()
] status LightGraphs
```
in the REPL.

Will this issue template just be for bugs? Or also for suggestions/usability questions?

**Comment by sbromberger** [comment]
> Will this issue template just be for bugs? Or also for suggestions/usability questions?

I don't think we can limit it to specific types of reports, so I tried to capture the type in question 3. Is there a better way?

**Comment by simonschoelly** [comment]
Not sure, I am not that familiar with issue templates here. But it looks as if users can adjust the text anyway if it does not fit their purpose, so it is not that big of a problem.
Just saw that the Julia repository contains a link to discourse for questions, might be worth doing here.

**Comment by sbromberger** [comment]
I'd rather have questions here, actually. I haven't logged into discourse in a while and it's nice to have a central place for all things LG.

In any case, let me try to get this template set up taking your comments into account. Thanks for the feedback.

**Comment by sbromberger** [comment]
I've added a bug report template. Comments please.

**Comment by simonschoelly** [comment]
I created a (nonsense ?) test issue:
https://github.com/JuliaGraphs/LightGraphs.jl/issues/1225

`]stats LightGraphs` does not not work, should be `st` or `status`.

Looks like it would be good to have a bit more empty lines between the items, otherwise the markdown layout gets easily messed up.

**Comment by abhinavmehndiratta** [comment]
> I created a (nonsense ?) test issue:
> #1225
> 
> `]stats LightGraphs` does not not work, should be `st` or `status`.
> 
> Looks like it would be good to have a bit more empty lines between the items, otherwise the markdown layout gets easily messed up.

Maybe doing
```julia
julia> using Pkg; Pkg.installed()["LightGraphs"]
v"1.2.0"
```
is better since `status` doesn't work in Julia 1.0
