### ISSUE TITLE
[BUG] issymmetric incorrect for directed graphs.

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGraphs/LightGraphs.jl#1228]
**Description of bug**
The function `issymetric` only uses the type of a graph and not what edges there actually are. Therefore a directed graph is always considered as not symmetric, even if all edges are there in both directions. This is not intuitive, especially as it is not the case for the adjacency matrix of such a graph.

**How to reproduce**
```julia
julia> g = CompleteDiGraph(4)
julia> issymetric(g)
false
julia> issymmetric(adjacency_matrix(g))
true
```

**Expected behavior**
`issymmetric` should return true, when for every edge in a graph also the reverse edge is there.

**Actual behavior**
`issymmetric` only considers the type of the graph.

**Version information**
```julia
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = gvim

(v1.1) pkg> status LightGraphs
    Status `~/.julia/environments/v1.1/Project.toml`
  [ec485272] ArnoldiMethod v0.0.4
  [864edb3b] DataStructures v0.15.0
  [093fc24a] LightGraphs v1.2.0 [`~/.julia/dev/LightGraphs`]
  [699a6c99] SimpleTraits v0.8.0
```

**Comment by sbromberger** [comment]
Is there a way to test symmetry for digraphs that's not O(E) in lookups?

**Comment by simonschoelly** [comment]
I don't think there is.

**Comment by mcognetta** [comment]
`issymmetric` isn't exported but it should be right? I have a PR for this for generic graphs but it could potentially be optimized a bit more.

**Comment by sbromberger** [comment]
I don't think we need this functionality at all. Worst-case, it devolves into `issymmetric(adjacency_matrix(g))` but perhaps without the extra allocation to create the matrix.

O(E) makes it prohibitive for all but small graphs in any case, so it's not something that's going to be generally useful, and for small graphs it's not too onerous to create the adjacency matrix.

**Comment by sbromberger** [comment]
Thoughts on removing this function entirely?

**Comment by sbromberger** [comment]
Reopen
