### ISSUE TITLE
[PkgEval] LightGraphs may have a testing issue on Julia 0.3 (2015-08-12)

### ISSUE THREAD

**Issue by IainNZ** [JuliaGraphs/LightGraphs.jl#123]
[PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) is a script that runs nightly. It attempts to load all Julia packages and run their tests (if available) on both the stable version of Julia (0.3) and the nightly build of the unstable version (0.4). The results of this script are used to generate a [package listing](http://pkg.julialang.org/) enhanced with testing results.

#### On Julia 0.3
* On **2015-08-03** the testing status was `Tests pass.`
* On **2015-08-12** the testing status changed to `Tests fail.`

*This issue was filed because your testing status became worse. No additional issues will be filed if your package remains in this state, and no issue will be filed if it improves. If you'd like to opt-out of these status-change messages, reply to this message saying you'd like to and @IainNZ will add an exception. If you'd like to discuss [PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) please file an issue at the repository. For example, your package may be untestable on the test machine due to a dependency - an exception can be added.*

*Test log*:
```
>>> 'Pkg.add("LightGraphs")' log
INFO: Installing AutoHashEquals v0.0.5
INFO: Installing LightGraphs v0.3.0
INFO: Installing LightXML v0.2.0
INFO: Installing ParserCombinator v1.6.3
INFO: Building LightXML
INFO: Package database updated

>>> 'Pkg.test("LightGraphs")' log
Julia Version 0.3.11
Commit 483dbf5* (2015-07-27 06:18 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
INFO: Testing LightGraphs
ERROR: BoundsError()
 in indexed_next at tuple.jl:20
 in readgraph at /home/vagrant/.julia/v0.3/LightGraphs/src/persistence.jl:44
 in readgraph at /home/vagrant/.julia/v0.3/LightGraphs/src/persistence.jl:39
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /home/vagrant/.julia/v0.3/LightGraphs/test/runtests.jl, in expression starting on line 32
=============================[ ERROR: LightGraphs ]=============================

failed process: Process(`/home/vagrant/julia/bin/julia /home/vagrant/.julia/v0.3/LightGraphs/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
INFO: No packages to install, update or remove
ERROR: LightGraphs had test errors
 in error at error.jl:21
 in test at pkg/entry.jl:718
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in cd at pkg/dir.jl:28
 in test at pkg.jl:67
 in process_options at ./client.jl:213
 in _start at ./client.jl:354

>>> End of log
```

**Comment by jpfairbanks** [comment]
I came across this test failure and I think I "fixed" it in commit 5a3d871225a697478b40b5496804d46e4fdf71c6. The problem was calling split on a blank line does not return the four fields you want to unpack into 4 variables. I just put in an 
```
if line != ""
```
to avoid the Error, but that might not be the way you want to fix it.

**Comment by sbromberger** [comment]
Which is weird, because it passed Travis. Hm.

**Comment by sbromberger** [comment]
See #124

**Comment by sbromberger** [comment]
@jpfairbanks - could you retest with latest master? I can't reproduce the failures on either of my systems (across 3 different versions of Julia). Thanks.

**Comment by sbromberger** [comment]
Pretty sure this has been resolved.
