### ISSUE TITLE
Can't find greedy things

### ISSUE THREAD

**Issue by cormullion** [JuliaGraphs/LightGraphs.jl#1235]
The documentation (Latest version as of July 13th) refuses to tell me about anything with the word `greedy`. There is apparently some support for greedy colouring algorithms... ?

This might be a problem with Documenter's search... (?) But I think that Documenter lets you make an [index of all functions](https://juliadocs.github.io/Documenter.jl/dev/man/syntax/#@index-block-1), which might be a last resort.

**Comment by sbromberger** [comment]
Nope, all exported functions should have docs. This is probably an omission.

**Comment by cormullion** [comment]
👍 (We used SimpleGraphs.jl for a while, until I searched the LightGraphs source. :))

**Comment by sbromberger** [comment]
a general request: if you see missing docs, please file an issue (just like this). LG functionality has grown by leaps and bounds and the docs unfortunately have not kept up. We're trying to fix this.
