### ISSUE TITLE
Figure out approach to use of randomness

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#1237]
Following on to #1236 - the way we currently handle randomness is not quite consistent: some functions/processes use seeds to the RNG returned via `getRNG()`, an unexported function, and some use instances of an RNG directly (SBM). 

I'm not quite sure what the best approach is, so opening to discussion. Assigning to @simonschoelly and @matbesancon since they were both involved in discussions around this issue. Thanks.

**Comment by sbromberger** [comment]
ping on this - would be nice to see some discussion and a decision here :)

**Comment by matbesancon** [comment]
This PR: https://github.com/JuliaGraphs/LightGraphs.jl/pull/1212 makes it consistent but the result is breaking. Overall, it's way more flexible to allow users to pass a RNG in keyword, defaulting to `Random.GLOBAL_RNG`. They can change the default one for a faster, a thread safe RNG, etc depending on their needs

**Comment by matbesancon** [comment]
Regarding the first from https://github.com/JuliaGraphs/LightGraphs.jl/pull/1236, maybe we could pull out the RNG from the struct and requiring it on random operations. This would allow removing the `mutable`

**Comment by matbesancon** [comment]
I think with the current PRs we have a good approach to randomness:
- Don't store RNG in types
- Optionnally pass a `rng::Random.AbstractRNG` element to any function requiring it
