### ISSUE TITLE
Inserting vertices at a particular position in the vertex order

### ISSUE THREAD

**Issue by epatters** [JuliaGraphs/LightGraphs.jl#1246]
In LightGraphs, the vertices of a graph are labelled by consecutive integers starting at 1, which gives them a definite order (see #1209). Sometimes I want to perform graph mutations that respect this order.

For example, given a graph on n vertices, I'd like to replace vertex i with another graph on k vertices and then reconfigure the edges in some way. Ideally, the new vertices would be labeled i, i+1, ..., i+k-1, and the vertices previously labeled i+1, ..., n would be re-labeled i+k, ..., n+k-1.

I know of two ways to do this:

1. Don't mutate the original graph at all, but create an entirely new graph.
2. Make a copy of the induced subgraph on i, ... , n; remove all the vertices i, ..., n; and add then add back vertices i, ..., n+k-1 and corresponding edges.

Neither seems very efficient. What do you recommend in this situation? Should LightGraphs have an efficient function that allocates a block of new vertices at a particular position in a graph, shifting all subsequent vertices/edges as appropriate?

**Comment by simonschoelly** [comment]
Maybe would also help, if we had a function that would do inplace permutation/subgraph ?

**Comment by epatters** [comment]
Right, if LightGraphs had an efficient in-place permutation operation, we could do the insertion I describe by adding the vertices at the end, as usual, and then permuting them into the right place.

**Comment by sbromberger** [comment]
> Should LightGraphs have an efficient function that allocates a block of new vertices at a particular position in a graph, shifting all subsequent vertices/edges as appropriate?

I don't think there's an efficient way to do this. As far as inplace subgraph, I'm not sure what that means. If I understand it, it means that we violate the requirement that vertices can be represented by a consecutive 1-indexed range.

**Comment by sbromberger** [comment]
This isn't hard and fast, but I am leaning more and more towards the idea that once you've got your data in a graph structure, it should be more or less immutable.

**Comment by simonschoelly** [comment]
`induced_subgraph!` would just do, what `induced_subgraph` currently does, but just inplace, so no unnecessary allocation happens. 

As for mutable graphs, I think they are important. Several reasons for having them:
1. Would allow one to build the graph stepwise.
2.There are a lot of graph algorithms that depend on mutating a graph. See for example that maximum independent set algorithm that was recently posted on the #graph slack.
3. Mutable graphs can represent the current state of some system. When that system changes, then also the graph has to change.

**Comment by epatters** [comment]
Agreed @simonschoelly, re: mutation. While I like functional code and try to write it when it can, many graph algorithms are most easily expressed in imperative style, with lots of small mutations performed in sequence.

**Comment by sbromberger** [comment]
> Should LightGraphs have an efficient function that allocates a block of new vertices at a particular position in a graph, shifting all subsequent vertices/edges as appropriate?

`LightGraphs` shouldn't, since this will require specialized implementations for all graph types. For what graph type are you needing this?

**Comment by epatters** [comment]
Thanks for the followup. I was hoping to have this feature for `Simple(Di)Graph` and eventually also `Meta(Di)Graph`.

**Comment by sbromberger** [comment]
I think the best way of handling this right now is to use the built-in operators:
```
julia> g = wheel_graph(5)
{5, 8} undirected simple Int64 graph

julia> add_vertices!(g, 3)
3

julia> h = blockdiag(g, wheel_graph(5))
{13, 16} undirected simple Int64 graph

julia> collect(edges(h))
16-element Array{LightGraphs.SimpleGraphs.SimpleEdge{Int64},1}:
 Edge 1 => 2  
 Edge 1 => 3  
 Edge 1 => 4  
 Edge 1 => 5  
 Edge 2 => 3  
 Edge 2 => 5  
 Edge 3 => 4  
 Edge 4 => 5  
 Edge 9 => 10 
 Edge 9 => 11 
 Edge 9 => 12 
 Edge 9 => 13 
 Edge 10 => 11
 Edge 10 => 13
 Edge 11 => 12
 Edge 12 => 13
```

**Comment by epatters** [comment]
I see. Thanks for the guidance.

**Comment by sbromberger** [comment]
I'll go ahead and close this, but if you would like to continue discussing it, let me know.
