### ISSUE TITLE
add_edge! potentially slow

### ISSUE THREAD

**Issue by mwien** [JuliaGraphs/LightGraphs.jl#1248]
**Description of the bug**
The complexity of adding the edge (u, v) to a graph G with the function add_edge!(G, u, v) is O(d(u)) where d(u) is the degree of node u in G. This is due to the fact that v might have to be inserted in the middle of the vector which stores the neighbors of u (this has cost O(n) compared to inserting at the beginning or end which has cost O(1)). This might be a conscious design decision, but imho this is unnecessarily slow and could be easily resolved.

**How to reproduce**
```julia
sz = 6000000;  
G = SimpleDiGraph(sz);  
for i in 1:(sz÷3)  
  add_edge!(g, 1, i)  
end  
for i in (2*sz÷3 + 1):sz
  add_edge!(g, 1, i)
end
for i in (sz÷3+1):(2*sz÷3)
  add_edge!(g, 1, i)
end
```
While the first two for-loops are fast because vertices are inserted at the end of the adjacency list, the third one will take a very long time because vertices are added in the middle. While this example is constructed to highlight this and there might be friendlier cases, even adding the edges in a random order should produce a similar effect.

**Possible solution**
In my opinion the easiest solution is to store the adjacencies in a Set. Then insert, remove and lookup are possible in O(1). Currently these operations are O(n), O(n) and O(logn). The only potential drawback I see is that the adjacent vertices would not be ordered anymore. But this should not be necessary in most cases anyway.

**Comment by simonschoelly** [comment]
This should not be a bug.

While it is indeed true, that the datastructure used for `SimpleGraph` is not ideal for random insertion, you should consider it as a compromise between various demands.

First, there is a big parallel between sparse matrices and graphs - for sparse matrices one often also uses formats like CSR or CSO, which behave quite similar as the adjancency lists used here do.

It is true, that hash maps and sets offer theoretical lookup and modifications in constant time, although even here, one has to consider that a hashtable can be eventually full and has to be resized then.

But there are some other factors, that are quite important for graph algorithms: Many graph algorithms work by iterating over all outgoing/incoming edges of a vertex. In such a case, adjacency lists are nearly optimal, not only does one then pay only constant time for each accessed vertex, but also the data lies adjacent in memory, which has a huge benefit for caching.

If one needs to modify a graph often, there might indeed be some better alternatives: using sets, full matrices, red/black trees, b-trees or using an additional graph builder datastructure for construction.

If you are interested in these kind of things, it might be interesting to create a new graph datastructure that implements the LightGraphs interface and then do some benchmarks.

Also interesting would, to figure out, what kind of datastructures are ideal for parallel graph processing.

Feel free to join us in the #graphs channel on slack, if these kind of things interest you.

**Comment by mwien** [comment]
Thanks for your extensive reply!

First of all, I'm sorry that the issue is labeled as a Bug, that was unintentional and for some reason I wasn't able to remove the label afterwards. 

I understand that you prioritize neighbor iteration over modifying existing graphs and I agree that the latter is of much less importance. Also, I don't have much experience with these practical aspects of writing high-efficiency programs, so I failed to take the importance of the cache into account and just didn't understand why you chose this data structure. Now I do, so sorry for that.

I have also seen that the function, which constructs a graph from an edge list, is quite efficient and avoids the pitfall above. Maybe it would be a good idea to mention in the docs that e.g. construction from an edge list is in some cases better than insertion by hand (so to speak) for larger graphs. 

What might be interesting would be an implementation for dense graphs which stores an adjacency list as well as an adjacency matrix. Then iteration would still be over a vector and insertion, deletion and lookup are all in true O(1) not even amortized. 

Cheers!
