### ISSUE TITLE
Base.eltype link leads to 404

### ISSUE THREAD

**Issue by mroavi** [JuliaGraphs/LightGraphs.jl#1250]
Clicking on `Base.eltype` here:

![image](https://user-images.githubusercontent.com/19517248/65714267-0d590000-e09b-11e9-98f7-0b0ea900160b.png)

leads to:

![image](https://user-images.githubusercontent.com/19517248/65714311-22ce2a00-e09b-11e9-91c7-bf0e8c38ecdf.png)

**Comment by sbromberger** [comment]
Closed via #1255. Thanks for the report!
