### ISSUE TITLE
[BUG] incidence_matrix can produce invalid instances of SparseMatrixCSC

### ISSUE THREAD

**Issue by rafreeman** [JuliaGraphs/LightGraphs.jl#1251]
**Description of bug**
The function `incidence_matrix` can produce matrices that do not conform to the SparseMatrixCSC type assumption that the entries in the `rowval` field of a sparse matrix are sorted by column.  As a result, arithmetic operations involving outputs of `incidence_matrix` can be incorrect.  The assumptions on the sparse type are listed at the top of

> `julia/stdlib/SparseArrays/src/sparsematrix.jl`

and the relevant assumption is
```julia

# Assumes that row values in rowval for each column are sorted
#      issorted(rowval[colptr[i]:(colptr[i+1]-1)]) == true

```
This assumption appears in all Julia versions from 1.0 on, including `master`.

**How to reproduce**
```julia

julia> using LightGraphs

julia> A = incidence_matrix(path_digraph(3))
3×2 SparseArrays.SparseMatrixCSC{Int64,Int64} with 4 stored entries:
  [1, 1]  =  -1
  [2, 1]  =  1
  [2, 2]  =  -1
  [3, 2]  =  1

julia> B = incidence_matrix(reverse(path_digraph(3)))
3×2 SparseArrays.SparseMatrixCSC{Int64,Int64} with 4 stored entries:
  [2, 1]  =  -1
  [1, 1]  =  1
  [3, 2]  =  -1
  [2, 2]  =  1

julia> A + B
3×2 SparseArrays.SparseMatrixCSC{Int64,Int64} with 4 stored entries:
  [1, 1]  =  -1
  [1, 1]  =  1
  [2, 2]  =  -1
  [2, 2]  =  1

julia> Matrix(A + B)
3×2 Array{Int64,2}:
 1  0
 0  1
 0  0

julia> Matrix(A)
3×2 Array{Int64,2}:
 -1   0
  1  -1
  0   1

julia> Matrix(B)
3×2 Array{Int64,2}:
  1   0
 -1   1
  0  -1

julia> Matrix(A) + Matrix(B)
3×2 Array{Int64,2}:
 0  0
 0  0
 0  0

```

**Expected behavior**
Because `reverse` does not change the order of the vertices or edges, the incidence matrices `A` and `B` should be the same except for the sign, that is, `A+B` should be the zero matrix regardless of whether they are added as sparse matrices or first converted to dense matrices and then added.

**Actual behavior**
`B` is not a valid SparseMatrixCSC instance because it lists its nonzero entries in the wrong order.  Thus `A+B` does not produce a sparse zero matrix but rather an invalid sparse matrix with duplicate values that add up to zero.  Hence converting this sparse sum to dense via `Matrix(A+B)` does not yield the expected zero matrix.  In contrast, `Matrix(A)` and `Matrix(B)` produce the correct dense versions of the incidence matrices, and the sum of these dense versions is zero as expected.

**Version information**
 ```julia

julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 5 2600 Six-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, znver1)

(v1.2) pkg> status LightGraphs
    Status `~/.julia/environments/v1.2/Project.toml`
  [093fc24a] LightGraphs v1.3.0

```

**Comment by sbromberger** [comment]
ping @jpfairbanks

**Comment by sbromberger** [comment]
```
julia> g = path_digraph(3)
{3, 2} directed simple Int64 graph

julia> r = reverse(g)
{3, 2} directed simple Int64 graph

julia> i = incidence_matrix(g)
3×2 SparseArrays.SparseMatrixCSC{Int64,Int64} with 4 stored entries:
  [1, 1]  =  -1
  [2, 1]  =  1
  [2, 2]  =  -1
  [3, 2]  =  1

julia> z = incidence_matrix(r)
3×2 SparseArrays.SparseMatrixCSC{Int64,Int64} with 4 stored entries:
  [2, 1]  =  -1
  [1, 1]  =  1
  [3, 2]  =  -1
  [2, 2]  =  1

julia> i.rowval
4-element Array{Int64,1}:
 1
 2
 2
 3

julia> z.rowval
4-element Array{Int64,1}:
 2
 1
 3
 2
```

**Comment by jpfairbanks** [comment]
Yeah that is bad, our `incidence_matrix` implementation definitely precedes v1.0 so I'm curious when this assumption was added. I guess the easiest fix is to just sort the incidence matrix after we make it. The most efficient way would be to create in such a way that it would be sorted. Let me take a look at the code now.
