### ISSUE TITLE
`unique` on graphs doesn't work (possibly a hash issue)

### ISSUE THREAD

**Issue by tomerarnon** [JuliaGraphs/LightGraphs.jl#1256]
Given an array of graphs (`Graph` or `DiGraph`) with duplicate values, `unique` does not remove the duplicates.

```julia
julia> unique([DiGraph(), DiGraph()])
2-element Array{SimpleDiGraph{Int64},1}:
 {0, 0} directed simple Int64 graph
 {0, 0} directed simple Int64 graph
```
Whereas I would expect to see behavior like:
```julia
julia> unique([DiGraph(), DiGraph()])
1-element Array{SimpleDiGraph{Int64},1}:
 {0, 0} directed simple Int64 graph
```

Tested on Julia v1.2 and v1.0, LightGraphs v1.3.0

No idea why this is happening, but from playing around at the REPL, maybe it has something to do with how either `hash` or `==` are implemented on graphs?
```julia
julia> v = rand(3);

julia> hash(v) == hash(deepcopy(v))
true

julia> g = DiGraph();

julia> hash(g) == hash(deepcopy(g))
false

julia> g == deepcopy(g)
true
```

**Comment by tomerarnon** [comment]
Not to say that this is necessarily a great fix, but implementing a custom hash like
```julia
import LightGraphs.SimpleGraphs.AbstractSimpleGraph
Base.hash(G::AbstractSimpleGraph, h::UInt) = hash(G.fadjlist, hash(typeof(G), h))
```
does seem to solve the problem.

```julia
julia> unique([DiGraph(), DiGraph()])
1-element Array{SimpleDiGraph{Int64},1}:
 {0, 0} directed simple Int64 graph
```

That said, maybe there is another approach that doesn't involve defining `hash` for each type...

**Comment by sbromberger** [comment]
Is there a reason you need `unique` on graphs? Equality of graphs is a bit tricky. (Are isomorphic graphs equal?)

If you can describe your use case, then maybe we can offer alternatives. Hashing `fadj` will only work for undirected graphs; we'd need to override `Base.hash` for each graph type.

**Comment by tomerarnon** [comment]
Turns out I actually don't need it at all, but ran into it in the early stages of something and figured it could be good to report. I was doing `if g in G...` with some newly generated graph and a running set of prior graphs. Afterwards I was generating many graphs and running `unique` at the end to see if that was better, etc. I'm not doing any of this any more, so it's a moot point by now 😅 

As for equality and hashing, oof, yeah that is complicated. In any case the reason I hashed only `fadj` was that I figured `badj` stood for "backwards adjacency" and could therefore be implicitly dependent on `fadj` (maybe not?) so if you hash it along with the type you should be safe. That was just a guess, so maybe not sound at all.

**Comment by sbromberger** [comment]
yeah, sorry, you were right about `fadj` (you can tell how often I use it.)

We have equality defined for simplegraphs[1], but I don't think we've got them for others. I think it's better if we allow the users define their own equality for their graphs, as some might need structure, some might need structure + metadata, ...

Glad to hear you were able to work around this.

[1]
```
==(g::SimpleGraph, h::SimpleGraph) =                                                                                                     
    vertices(g) == vertices(h) &&
    ne(g) == ne(h) &&
    fadj(g) == fadj(h)
```

**Comment by tomerarnon** [comment]
True, but since `DiGraph() == DiGraph()`, which is covered by the defined `==` you have there, I was expecting `unique` to return only one of the two `DiGraphs`, not both (since they're equal). But looks like unique uses `hash` rather than `==` directly, hence the mismatch. Anyway, I'm not using this at all anymore so it's fair enough to close it, but a hash function equivalent to that `==` should do the same job 😄

**Comment by sbromberger** [comment]
OK, but are these two graphs equal? Why / why not?
```
g = path_graph(3)
h = Graph(3); add_edge!(h, 1, 2); add_edge(h, 1, 3)
```

or what about these?
```
s = SimpleWeightedGraph(g, 1)
t = SimpleWeightedGraph(g, 2)
u = SimpleWeightedGraph(g, 1.0)
```

This is why I think equality should be in the eye of the user :)

**Comment by tomerarnon** [comment]
I would say they're unequal by default, since they're not even the same type. Though I agree that this is just one interpretation 😜
Adding an `==` that is as robust as it is for numeric types is surely impossible, so you'll get not argument from me there!
