### ISSUE TITLE
Documentation needs an update

### ISSUE THREAD

**Issue by cormullion** [JuliaGraphs/LightGraphs.jl#1257]
Just working through the 'latest' version of the documentation, I noticed, while trying each of the graph types:

<strike> `EuclideanGraph` -> deprecated, now `euclidean_graph` </strike>
`WheelDiGraph`  -> deprecated, now `wheel_graph`
`PathGraph` -> is deprecated, now `path_graph` 
`BarbellGraph` -> is deprecated, now `barbell_graph`
`CircularLadderGraph` is not defined, use `circular_ladder_graph`
`CliqueGraph` -> is deprecated, now `clique_graph`
`Grid` -> is deprecated, now `grid`

**Comment by sbromberger** [comment]
I don't understand the bug report: [`euclidean_graph`](https://juliagraphs.github.io/LightGraphs.jl/latest/generators.html#LightGraphs.SimpleGraphs.euclidean_graph) is now the correct function name. The docs are consistent with this.

**Comment by cormullion** [comment]
Oops, I think you're right about EuclideanGraph - I must have made a mistake in my notes.... :( 

<img width="939" alt="Screenshot 2019-11-11 at 08 41 12" src="https://user-images.githubusercontent.com/52289/68573210-2bb66780-045f-11ea-9fee-859067e2c2e7.png">

<img width="918" alt="Screenshot 2019-11-11 at 08 39 53" src="https://user-images.githubusercontent.com/52289/68573224-37a22980-045f-11ea-87f0-ff24c3d1d60e.png">

<img width="923" alt="Screenshot 2019-11-11 at 08 47 28" src="https://user-images.githubusercontent.com/52289/68573595-f1999580-045f-11ea-8ce4-0b713ee2c8fb.png">

...

**Comment by sbromberger** [comment]
yup, I see it now.

**Comment by sbromberger** [comment]
Fixed via #1263. Thanks - it gave me an excuse to update a bunch of scripts :)
