### ISSUE TITLE
New feature: Characteristic Length

### ISSUE THREAD

**Issue by oskarddfa** [JuliaGraphs/LightGraphs.jl#1259]
I would like to implement a function that returns the characteristic length (aka average shortest path) of a graph.

This is how I wrote it:
``` """ Calculate the characteristic length (average shortest path) of a graph."""
function characteristic_length(graph::AbstractGraph; cutoff::Real=Inf, silent=false)
    (!silent && !is_connected(graph)) && (@warn "Graph is not connected.")
    L = 0
    for i in 1:nv(graph)
        L += sum(clamp.(dijkstra_shortest_paths(graph, i).dists, 0, cutoff))
    end
    return L / (nv(graph) * (nv(graph) - 1))
end
```
I am not using the floyd_warshall_shortest_paths function since for me iterating multiple time the dijkstra algorithm was faster, but I didn't do a real benchmarking. However, it is trivial to implement the several functions to calculate the characteristic length.

What do you think, does it make sense to add it to LightGraphs?

**Comment by sbromberger** [comment]
just a few thoughts in no particular order:
1) this is going to be REALLY expensive – it's essentially doing what a full-bore betweenness centrality is doing. I would look at F-W instead. Try it with dense graphs with large numbers of vertices - say, 1M - and see what happens.

What's the real purpose of cutoff/clamp?

Also, think about removing `silent` - either this works for disconnected graphs or it doesn't. We generally don't warn inside library code.

**Comment by oskarddfa** [comment]
Sorry for the late answer, I didn't get any notification and didn't look at it again. 

1. Indeed it depends a lot how big and dense the graph is. I did not try it for big graphs. However the implementation is quite the same.

2. The cutoff/clamp is something I specifically used, it is indeed not too useful. However the distance does not really make sense if the graph is disconnected, because it becomes infinite. The problem is that the F-W state gives back just the biggest possible value for the unconnected vertices (i.e. 9223372036854775807 for Integer64). The cutoff gives the possibility to have a kind of sensible answer for the distance. 

3. If 2 is not there, then it does not make sense to accept disconnected graphs. So the warning would become an `@assert  is_connected(graph) "Unconnected graph do not have sensible characteristic length" `. Or otherwise one could `return  Inf` .

Then it would look like this:
```
function characteristic_length(graph::AbstractGraph;silent=false)
    !is_connected(graph) && return Inf
    sum(floyd_warshall_shortest_paths(graph).dists) / (nv(graph) * (nv(graph) - 1))
end
```

**Comment by oskarddfa** [comment]
Moreover, for a possible implementation the name should be decided between `characteristic_length`, `characteristic_path_length`, `average_path_length` or `average_shortest_path`. Literature is not really consistent in it.

**Comment by sbromberger** [comment]
Looping back to this: given that it's essentially a one-liner, and there is an inconsistency in the name, I don't know that this is needed in LightGraphs at this point. It might be a good thing to put in a "recipes" section of the documentation, though. I've been thinking lately about adding such a section.

**Comment by sbromberger** [comment]
I'm going to close this out but if we ever start a LG recipes section of the documentation, this should be considered. Thanks!
