### ISSUE TITLE
Support for mixed graphical models.

### ISSUE THREAD

**Issue by dietercastel** [JuliaGraphs/LightGraphs.jl#1269]
Hi all,

Is there a plan to add mixed graphs (having both directed and undirected edges) to LightGraphs? I'd like to visualize some of them with GraphPlot.jl but currently I don't see a way to even create a mixed graph.

I'm not confident enough in Julia to write an efficient implementation just yet, maybe I'll give a prototype a go in the coming weeks/months. I've got some idea how that would be possible:  Either a graph within a graph approach or a new type of edge that switches between SimpleGraph and SimpleDiGraph. 

But thought of sharing the idea already. Maybe someone else could help/co-create? Or maybe there's already a solution I'm not seeing yet (quite new to this library still).

Let me know what you think. :-)

**Comment by sbromberger** [comment]
I don't know what the general utility of such a graph would be - currently we don't specialize on the edges (that is, edges vs arcs - we don't make a distinction at the edge level, just at the graph level).

In the meantime, one of the ways we can represent a "mixed graph" is to create a directed graph and ensure the edges that represent undirected edges have a reverse edge created.

**Comment by dietercastel** [comment]
Good point, thanks @sbromberger. Glad I asked! That is indeed a more trivial way of creating such a mixed graph. 

The general utility would be in using it for e.g. [Chain Graphs](https://en.wikipedia.org/wiki/Mixed_graph#Bayesian_inference). That's why I asked. I don't know any other applications of it yet. But I wouldn't be surprised there are more (graph theory is a vast field).

I'll give your suggestion a shot and will try to contribute upstream. You can assign me for this and if I'm stuck somehow I'll report back here.

**Comment by jpfairbanks** [comment]
Yeah definitely just have edges with both directions. What application do you have in mind for mixed graphical models? Describing Bayesian models where some relations are causal and some are noncausal (but correlational)? I've recently started thinking about this in my own research.

**Comment by sbromberger** [comment]
@dietercastel I'll assume this works for you; if not, let me know and I'll reopen this issue. Thanks.

**Comment by dietercastel** [comment]
> Yeah definitely just have edges with both directions. What application do you have in mind for mixed graphical models? Describing Bayesian models where some relations are causal and some are noncausal (but correlational)? I've recently started thinking about this in my own research.

I'm doing a course on Uncertainty using graphical models and working on a Julia library [found here](https://github.com/KULeuven-MAI/UAI.jl) to accompany my studying.

> @dietercastel I'll assume this works for you; if not, let me know and I'll reopen this issue. Thanks.
Thanks for the response! I've finally taken this up again and indeed that seems to work (so far). I created the following function to get the "chain components" for such a graph. 

```
"""
Gets the chain components of a graph with the given nodeNames.
"""
function getChainComponents(graph::SimpleDiGraph)
	newG = SimpleDiGraph(nv(graph))
	graphEdges = collect(edges(graph))
	for e in edges(graph)
		if reverse(e) in graphEdges 
			add_edge!(newG,src(e),dst(e))		
		end		
	end
	result = connected_components(newG)
	return result
end
```

Small example:
```
julia> using UAI
julia> (g,n) = parseGraph("e<a-b-c-d>e")
SubString{String}["e", "a-b-c-d"]
SubString{String}["a", "b", "c", "d", "e"]
({5, 8} directed simple Int64 graph, SubString{String}["a", "b", "c", "d", "e"])

julia> getChainComponents(g)
2-element Array{Array{Int64,1},1}:
 [1, 2, 3, 4]
 [5]
```
