### ISSUE TITLE
k-clique count?

### ISSUE THREAD

**Issue by Chakerbh** [JuliaGraphs/LightGraphs.jl#1270]
Is there a plan to implement k-clique count? I'm comparing LightGraph to other systems and it would be wonderful if there's a builtin function that can count the number of cliques of size k that an node is a part of. 

I currently have a naive implementation to count 4-clique 
```
function clique4(g::AbstractGraph)
    # Idea from https://discourse.julialang.org/t/find-k-cliques-in-a-graph/24022/7
    result = 0
    for e in edges(g)
        intrs = intersect(neighbors(g, e.src), neighbors(g, e.dst))
        for z in intrs
            result += length(intersect(neighbors(g, z), intrs))
        end
    end
    result
end
```
As you can probably notice, the performance is terrible. But it doesn't even return the correct result for some datasets 😅 (I'm exclusively using SNAP datasets).

**Comment by simonschoelly** [comment]
There isn't such functionality in LightGraphs yet. Actually there is not much functionality for any kind of  #P and #NP hard problems, apart from some approximation algorithms. In the meantime, you could use the VF2 subgraph algorithm in the `LightGraphs.Experimental` submodule for counting k-cliques.

**Comment by Chakerbh** [comment]
@simonschoelly Sorry, but is there any example of that? I couldn't find a way to use the function in the VFS module to implement clique count.

**Comment by simonschoelly** [comment]
Something like this should work:
```julia
using LightGraphs, LightGraphs.Experimental

count_k_cliques(g::SimpleGraph{T}, k) where {T} =
    count_subgraphisomorph(g, complete_graph(T(k))) ÷ factorial(k)
```
Of course its not very efficient, especially as we overcount all the permutations and thus have to divide by `k!` afterwards.

For this case, one should also be able to use `count_induced_subgraphisomorph` instead, as it should give the same result. Maybe one of them is slightly faster than the other one.

**Comment by Chakerbh** [comment]
Thanks @simonschoelly, that works indeed. Unfortunately as you mentioned, the performance is bad for this one. 
```
julia> @time sum(LightGraphs.triangles(g)) ÷ 3
  0.784286 seconds (453.75 k allocations: 18.156 MiB, 1.28% gc time)
13082506

julia> @time count_induced_subgraphisomorph(g, complete_graph(3)) ÷ 6
1110.907944 seconds (78.49 M allocations: 1.171 GiB, 0.01% gc time)
13082506
```

**Comment by simonschoelly** [comment]
Triangle counting is a special case anyway. If you just need that, I think there was also a PR for some algorithm for triangle counting, that was never merged to LightGraphs for some reason.

**Comment by sbromberger** [comment]
I wrote a naive triangle counting function using Roger Pearce's and Geoff Sanders's degree-sorted  algorithm but it was never optimized. I suppose I could go back and figure out how to make it fast but I'm swamped for the foreseeable future.

**Comment by sbromberger** [comment]
I'm going to close this out since we have an equivalent and since nobody seems to be stepping up to make a PR. :) Feel free to do so, though! It might be better off in Experimental or in its own repo.

**Comment by Chakerbh** [comment]
Thanks @sbromberger
