### ISSUE TITLE
Add `target` parameter for shortest path

### ISSUE THREAD

**Issue by alainchau** [JuliaGraphs/LightGraphs.jl#1273]
Currently, `dijkstra_shortest_paths(g, srcs, distmx=weights(g))` computes all the paths between a vertex (or vertices) and the rest of the vertices. Can we add a method or adjust the function signature to accommodate a `target` parameter? I think the source code change should be minor; the algorithm terminates as soon as it reaches the target.

I was curious to see how Python's NetworkX handles this case and apparently they just do full Dijkstra and return the desired quantity. Seems inefficient but perhaps the gains are not worth implementing an early stopping condition?
https://networkx.github.io/documentation/networkx-1.10/_modules/networkx/algorithms/shortest_paths/weighted.html#dijkstra_path_length

**Comment by sbromberger** [comment]
If you have source and target, it's probably better to just use A*.

**Comment by sbromberger** [comment]
@alainchau let me know if A* won't work for you, and I'll go ahead and re-open for discussion. Thanks.

**Comment by b2jia** [comment]
I second Alain's comment. I think for the uninitiated (who are unaware that A-star without a heuristic provided is equivalent to Dijkstra) it would be helpful to provide this parameter 'target'.

I'm finding it difficult to find the shortest path in a non-verbose way without this parameter. For instance,

```
source = 1
target = 2402
g = SimpleWeightedGraphs.SimpleWeightedDiGraph(adj_mat)
path = LightGraphs.enumerate_paths(LightGraphs.dijkstra_shortest_paths(g, source), target)
```

feels very cumbersome. I am currently unable to use ```LightGraphs.a_star()``` on a ```SimpleWeightedDiGraph``` - this does not work:

```
source = 1
target = 2402
g = SimpleWeightedGraphs.SimpleWeightedDiGraph(adj_mat)
path = LightGraphs.a_star(g, source, target)

>>> RuntimeError: <Pycall.jlwrap (in a Julia function called from Python)
JULIA: MethodError: no method matching SimpleWeightedGraphs.SimpleWeightedEdge{Int64, Float64}(::Int64, ::Int64)
```
