### ISSUE TITLE
New Feature: Dominator Tree

### ISSUE THREAD

**Issue by ajoanni** [JuliaGraphs/LightGraphs.jl#1279]
It would be nice to have an implementation of the Lengauer-Tarjan algorithm for creating the dominator tree from a given directed graph. [Dominator](https://en.wikipedia.org/wiki/Dominator_(graph_theory))

Is this planned for the near future?

**Comment by sbromberger** [comment]
> Is this planned for the near future?

Only if someone steps up to implement it... :)

**Comment by sbromberger** [comment]
https://dl.acm.org/doi/10.1145/357062.357071
