### ISSUE TITLE
Discussion: return type of `{in|out}degree` 

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#1282]
Right now, `degree` functions return whatever type is returned from `length` (currently int64). It seems to me that `degree` should return `eltype(g)`, especially since we don't support multigraphs (this could change via an override for any graph type in which a vertex's degree could  exceed the number of vertices in the graph). This has implications for, e.g., degeneracy where the core number of a vertex is seeded with its degree.

Comments? If no objections, I'll put together a PR.

This is likely not a breaking change (but I'll let @jpfairbanks weigh in as the SemVer expert).

**Comment by matbesancon** [comment]
IMO it's fine for some algorithms to return Int and not the integer type we use for storage, and then let users do the conversion when needed

**Comment by sbromberger** [comment]
A problem with the current setup is that if we have degrees > 2^63 (unlikely, but still), things will fail.

**Comment by simonschoelly** [comment]
If we have degrees > 2^63, then we also have more than 2^63 edges, so we also have an issue with `ne`.

**Comment by sbromberger** [comment]
yup. We force `eltype(ne)` to be `widen(nv(g))` in some places. I think we need to consider whether or not it makes sense to complete the abstraction work to include the possibility that we go beyond `Int64`.
