### ISSUE TITLE
2.0.0 notes / discussion

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#1284]
Here's the list of things I'd like to do in order to release LG 1.3.1:

- [x] merge #1278 

For 1.4.0:
- [x] move `Experimental/ShortestPaths` and `Experimental/Traversals` into `src/`
- [ ] create necessary deprecations
- [ ] finish modularization of centrality measures (not into `Experimental`) and create deprecations
- [ ] remove all uses of `seed` in favor of an RNG

This will allow us to remove those deprecations for 2.0, which I think we should schedule after GSoC.

**Comment by sbromberger** [comment]
cc @matbesancon @jpfairbanks @simonschoelly @somil55

**Comment by matbesancon** [comment]
Looks like a good plan to me

**Comment by sbromberger** [comment]
1.3.1 released tonight. [Discourse announcement](https://discourse.julialang.org/t/ann-lightgraphs-1-3-1-and-the-upcoming-roadmap/35063).

**Comment by sbromberger** [comment]
OK, so we're a bit stuck. Here's the dilemma:

We can deprecate the various shortest path algorithms (SPAs) to use `shortest_paths`, no problem. However, the return types have also changed. Instead of getting a `AStarState`, you get an `AStarResult`. There is no way to make this nonbreaking – if we provide an `AStarState` constructor that takes an `AStarResult`, we're still not encouraging the use of the new structs.

So - my proposal is that we release 2.0 without ANY deprecations (and with tons of documentation and notice). This will allow us to move cleanly to the new `shortest_paths` methods and reduces a bit of complexity in the library itself.

Thoughts?

**Comment by matbesancon** [comment]
I think we should create a 2.0 branch and merge all the breaking stuff on
it. This allows us to make a last 1.x release with either deprecations
(when possible) or warnings when not avoidable

**Comment by sbromberger** [comment]
OK. I'm making `sbromberger/2.0.0` right now (we can change the name).

**Comment by sbromberger** [comment]
Another thing that I want to try: moving complex functionality into submodules. Examples are:
- [ ] centrality
- [ ] cycles
- [ ] shortest paths
- [ ] traversals
- [ ] community
- [ ] biconnectivity
- [ ] dominating set
- [ ] independent set
- [ ] vertex cover

Basically, anything where we have a directory of related functions is fair game. (Things that are in a single file off of `src` MAY be eligible, but aren't a priority.)

This way, we can reduce `LightGraphs` core to just the stuff exported by LightGraphs, and people can `using LightGraphs.Centrality` if they need the functionality or leave it out if they don't. I think I like the modular approach while keeping the functions inside of LightGraphs (as opposed to in separate repos).

Thoughts?

**Comment by juliohm** [comment]
Hi @sbromberger , sorry for not being so active recently with LG development. Have been really busy with the GeoStats.jl stack, it is consuming all my research time :)

Regarding the submodule question, I wonder if you considered the usual approach to large projects in Julia in which LightGraphs.jl becomes an umbrella package reexporting the submodules, and a package like LightGraphsBase.jl is created with the minimum amount of graph definitions. In this approach followed by projects like Makie.jl, DiffEq.jl, Makie.jl, etc., we facilitate the lives of users/devs that are only interested in depending on a sub-part of the project:

```
LGBase.jl
LGCentrality.jl
LGTraversals.jl
...
LightGraphs.jl (umbrella)
```

I understand that splitting modules into multiple repos can be painful, but the new Project.toml and Pkg manager are really handy nowadays to solve the versions of the parts. Anyways, just passing to say hi, miss you guys!

Best,

**Comment by sbromberger** [comment]
@juliohm - great to hear from you!!!!

Yes, I did consider this but I'm not quite sure I want to do that. The reason is that it's too hard to keep so many moving parts in sync and working well together. At least it was - maybe the new Pkg system will make things easier, but I remember doing this a couple years ago and having to pull a bunch of stuff back in.

I think for now I'd like to move slowly. If we decide to make submodules then it should be relatively easy to move them out later into separate repos.

I'm probably being way too conservative here but there are lots of changes happening for 2.0 and I'd like to minimize the moving parts unless there's a really compelling reason to do this, and I'm not sure there is right now.

We have a few months to consider it though, and I could be persuaded to change my position. It's been known to happen from time to time. :)

**Comment by sbromberger** [comment]
Ref: #1318

**Comment by sbromberger** [comment]
Ref: #1323

**Comment by sbromberger** [comment]
OK, here's the current status:

branch `1.4.0-dev` has been created. This branch will hold all the new (non-breaking) functionality and will provide deprecations. As of now `Traversals` (#1330) and `ShortestPaths` (#1331) are in queue for review and merge.

branch `2.0.0-dev` has also been created. This branch will hold breaking changes only. I'm not quite sure how we keep it current with 1.4.0-dev, but I imagine it will involve a lot of rebases.

@matbesancon's breaking RNG fix (#1324, #1328) is already merged into 2.0.0-dev.

**Comment by sbromberger** [comment]
More info on the strategy here: https://gist.github.com/sbromberger/bc119e33e894582df0eddc35be4d20bd

**Comment by sbromberger** [comment]
bump

**Comment by matbesancon** [comment]
go away bot

**Comment by o314** [comment]
Hello,

Is there any current doc / roadmap about the evolution toward v2.0 ?  
Actually, best of my knowledge, there is a lot of branch : 2.0.dev, the 1.3, the master and they all differ a lot.  
It's not that easy to know what to uses, what to properly install, even expect

I was in particular trying to use tarjan scc (config julia 1.3)

Thanks

**Comment by sbromberger** [comment]
The official version can be obtained by `]add LightGraphs`. Any other version is not supported at this time.

**Comment by o314** [comment]
Thanks for the quick feedback.
That's what i have done. v2 looks much clearer and very promising !

I have read #1506 meanwhile.   
Hoping this will not delay too much the release.  
If some help is needed, and one can contribute, do not hesitate to ask.
