### ISSUE TITLE
Question: API randbn() and usage in stochastic_block_model()

### ISSUE THREAD

**Issue by zierenberg** [JuliaGraphs/LightGraphs.jl#1289]
Let me start by saying thank you for an awesome (light-weight) package for generating graphs. I am new to julia, but the first thing that entered my regular workflow is to use LightGraphs both for implementing neural networks as well as problems in statistical physics. Currently, I am starting to develop a ComplexNetworks module which builds on LightGraphs. So I looked at the graph generators and wanted to construct my networks similar - both to learn from the community and just in case they might at some point be of interest to be included in LightGraphs :). However, I fell over the following problem:

I wanted to hijack the LightGraphs.SimpleGraphs.randbn() function to generate a modular network of small communities with large fraction of internal weights coupled to other communities with different fraction of weights. I imagined that this is similar to stochastic_block_model(), which requires multiple calls of randbn(m,p,seed). Here is the problem:

If I always initialize randbn(m,p.seed) with the same seed, then I essentially draw the same random numbers over and over again. This should introduce unnecessary correlations (even though m and p might change ...). I could imagine a simple change in API that could resolve this:

`
function randbn(n::Integer, p::Real, rng::AbstractRNG)
`

with the ordinary implementation, plus 

`function randbn(n::Integer, p::Real, seed::Integer=-1)`
`    rng = getRNG(seed)`
`     randbn(n,p,rng)`
`end`

for convenience and to not break things. 

I am a rookie with both julia and proper code development on github, but I could try to make a PR if this is desired. If there is a good reason for why things are the way they are - I will not interfere.

Thanks, johannes

**Comment by sbromberger** [comment]
I think we haven't yet "fixed" this (see #1237 and #1247). cc @matbesancon @simonschoelly for comments since they were involved in the original discussion.

Bottom line: I think we should eliminate the use of seeds as parameters to functions like this. Open to feedback here.

**Comment by jpfairbanks** [comment]
I just reviewed this code: https://github.com/JuliaGraphs/LightGraphs.jl/blob/351a0bdd04e0262f8ae4073baaf7d5381e3d9d5b/src/SimpleGraphs/generators/randgraphs.jl#L1046

It looks like the current interface for generating an SBM graph is to call 
```julia
sbm = StochasticBlockModel(parameters...)
nvg = 100
nve = 1000

SimpleGraph(nvg, neg, sbm)
```
This approach uses the default global RNG. I guess you would want to use something like this:

 ```julia
rng = getRNG(seed)
sbm = StochasticBlockModel(parameters...)
nvg = 100
nve = 1000

SimpleGraph(nvg, neg, make_edgestream(sbm, rng=RNG))
```

The reason for this design is that I was working on dynamic algorithms for analyzing SBMs when I implemented this and so I need to draw graphs from an SBM one edge at a time to simulate a dynamic graph formation process. If you want to add additional dynamic graph generation models, this would be a good approach. You have one function that creates a channel of edges and then you pass that channel to the SimpleGraph Constructor to take a prefix of that edge stream into a finite graph.

**Comment by zierenberg** [comment]
Thank you for the explanation - I did not get to the edge_stream concept before but it looks really nice. For my current implementation, I was fine with standard iteration over the to-be-made adjacency matrix, but that might not always work.

As for the discussion on the API, I would agree that internal function should not receive seeds but the rng. This would be consistent with `make_edgestream` and also with the default seed=-1 that in fact passes the global RNG. 

However, if I understood the referenced discussion correctly, I would still see a lot of value in passing seeds to the generators (e.g. `erdos_renyi()`) from outside. That way, the user can reproduce other peoples work if they generate with a specific seed (given that the internal structure did not change).
