### ISSUE TITLE
OpenStreetMapX's A* algorithm is much faster than ours

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#1290]
https://github.com/pszufe/OpenStreetMapX.jl/blob/master/src/a_star.jl#L35

It's true.
```
julia> g = Graph(1_000_000, 5_000_000)
{1000000, 5000000} undirected simple Int64 graph
julia> @benchmark OpenStreetMapX.a_star_algorithm(g, 1, 999_999)
BenchmarkTools.Trial: 
  memory estimate:  101.00 MiB
  allocs estimate:  87
  --------------
  minimum time:     1.528 s (0.08% GC)
  median time:      1.540 s (0.08% GC)
  mean time:        1.537 s (0.06% GC)
  maximum time:     1.542 s (0.08% GC)
  --------------
  samples:          4
  evals/sample:     1
julia> @benchmark LightGraphs.a_star(g, 1, 999_999)
BenchmarkTools.Trial: 
  memory estimate:  627.33 MiB
  allocs estimate:  34860625
  --------------
  minimum time:     3.747 s (11.70% GC)
  median time:      3.801 s (13.20% GC)
  mean time:        3.801 s (13.20% GC)
  maximum time:     3.855 s (14.66% GC)
  --------------
  samples:          2
  evals/sample:     1
```

We should incorporate those changes.

cc @bartoszpankratz @pszufe

**Comment by pszufe** [comment]
This has been implemented by @bartoszpankratz. We can help porting it to LightGraphs. Our implementation might be though not so well tested as yours so and the user's base of LightGraphs is much bigger. Hence I propose starting with excessive randomized testing.

**Comment by sbromberger** [comment]
Sounds great, @pszufe - I can rig up a test harness for it.

If there's anything else you find that can be faster, please feel free to open up PRs or issues here. We'd love to have LG meet your needs without having to resort to overriding our algorithms.
