### ISSUE TITLE
Modify Johnson's simple cycles to use our visitor-based DFS

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#1307]
This would eliminate the need for the recursive function and would get us more consistent.

**Comment by alimamdouh212** [comment]
The current DFS algorithm prevent the node that have been visited before to be visited again, but 
 in Johnson's the same node can be visited multiple times, 
i can imagine calling the algorithm again in visitfn!, but that is just mutual recursion, which mean that we didn’t solve the problem, but still the algorithm can be made iterative, and i think it will be good PR.

**Comment by sbromberger** [comment]
Wouldn't that require us to expose `visited` and other internal state to the new function?

**Comment by sbromberger** [comment]
(Also - does our new dfs solve this problem?)

**Comment by alimamdouh212** [comment]
@sbromberger if `visted` was was exposed we can solve that, but we can’t solve it now .

**Comment by sbromberger** [comment]
copying @estelle0500 here - she's been working on this.

**Comment by estelle0500** [comment]
Yes, I’m planning to expose `visited` to the visitor functions.
