### ISSUE TITLE
[BUG] using experimental dfs might prevent some optimization for he code

### ISSUE THREAD

**Issue by alimamdouh212** [JuliaGraphs/LightGraphs.jl#1317]
sometimes we need to label the node in this  forum 

`label[v] = somefunc( [ labe[i] for for i in children[v] ]) `

a good example of that is if we wanted to know how many nodes some node v can reach, then

`reachs[v] = sum(1+reachs[i]... for i in children[v] `

then we need just to keep track of the the node that we started processing them, but not yet completed, aka dfs stack nodes.
then it is a good idea to save the node name besides its current label in the stack, because every time we declare that we finished processing  node and ready to till the parent , we would have just used the the dfs stack to know this node’s name, so keep the name of the node and its value nearby the in the same stack, will be good for the cashes.
the thing is that is not an option if we use the  experimental dfs.
 
i did this experiment

`
function count(g::AbstractGraph{T},source) where {T}
    s = Vector{ Tuple{T,T,T} }([])
    ptr = one(T)
    visited = falses(nv(g))
    visited[source] = true
    push!(s,(source,0,1))
    while !isempty(s)
        v, _, _ = s[end]

        vneighbors=outneighbors(g,v)
        while ptr <= length(vneighbors)
            u = vneighbors[ptr]
            if visited[u] == false
        
                push!(s,(u,ptr+1,1))
        
                visited[u] = true
        
        
                break
            end
            ptr+=1
        end
        if ptr > length(vneighbors)
            _, pt, size = pop!(s)
            if !isempty(s)
                old = s[end]
                s[end]=(old[1], old[2], old[3]+size)
            end
        else
            ptr = 1
        end
    end
end

` 

`mutable struct Count{T<:Integer} <: AbstractTraversalState
    stack::Vector{T}
end

@inline function newvisitfn!(s::Count, u, v) where T 
    push!(s.stack,1)
    return true
end

@inline function postlevelfn!(s::AbstractTraversalState)
    if length(s.stack) > 1
        lastsize = pop!(s.stack)
        s.stack[end]=s.stack[end]+lastsize
        
    
    end
    return true
end`

`
 s = Vector{Int32}([1])
    state = Count(s)
    
    g=CycleGraph(1000_000)
    
    @benchmark traverse_graph!(g, 1, DFS(), state)
    @benchmark count(g, 1)

`

and this was the result

for the experimental dfs

`memory estimate:  23.37 MiB
  allocs estimate:  1999001
  --------------
  minimum time:     323.184 ms (0.00% GC)
  median time:      344.239 ms (0.00% GC)
  mean time:        348.843 ms (1.84% GC)
  maximum time:     397.919 ms (7.98% GC)
  --------------
  samples:          15
  evals/sample:     1`

for the function i write without using it 
`

  memory estimate:  12.12 MiB
  allocs estimate:  24
  --------------
  minimum time:     102.863 ms (0.00% GC)
  median time:      107.142 ms (0.00% GC)
  mean time:        108.668 ms (0.59% GC)
  maximum time:     125.031 ms (0.00% GC)
  --------------
  samples:          46
  evals/sample:     1
`

**Comment by sbromberger** [comment]
We're in the middle of a fix for DFS given #1312 . Let's not make multiple issues.

**Comment by alimamdouh212** [comment]
@sbromberger  the problem with the star graph is different from the problem with the cycle graph,
so i wanted to point it.

**Comment by sbromberger** [comment]
Understood. We're getting ready to do a pretty comprehensive rewrite of DFS, so let's hold off on opening any other issues until we can evaluate the new function's correctness. If you see problems after the merge, please open up issues then.
