### ISSUE TITLE
Bikeshedding submodule name consisting of algorithms for Dominating Sets and Independent Sets 

### ISSUE THREAD

**Issue by SyxP** [JuliaGraphs/LightGraphs.jl#1333]
@sbromberger wants to group these algorithms under a common submodule. The key issue here is to think of where a user would think these algorithms will go under.

Ideas include:
 
1. NPComplete, but this might end up being a huge space of algorithms and functions.
2. Clique, as the algorithms here are Clique related.
3. Perhaps these algorithms are distinct enough and each warrant their own submodule.

**Comment by sbromberger** [comment]
I think we might use `Clique` and move the other clique functions in as well. But I'd really like some more discussion first, and soon.

cc @jpfairbanks @simonschoelly @matbesancon @SohamTamba

**Comment by sbromberger** [comment]
Closing. We’ve chosen `VertexSubsets`.
