### ISSUE TITLE
Implement a circulant graph generator.

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGraphs/LightGraphs.jl#1342]
It would maybe be nice to have a circulant graph generator in LightGraphs. I think we can have  two versions, with the signatures
```julia
circulant_graph(n, connection_set)
circulant_digraph(n, connection_set)
 ```
The first function creates a `SimpleGraph` with `n` vertices where there is an edge between vertex i and j, whenever `j - i ∈ connection_set  (mod n)` or  `i - j ∈ connection_set (mod n)`
and the second function creates `SimpleDiGraph` with `n` vertices where there is an edge between vertex i and i, whenever `j - i ∈ connection_set  (mod n)`.

References: 
[1] https://en.wikipedia.org/wiki/Circulant_graph
[2] Christ Godsil, Gordon Royle - Algebraic Graph Theory, page 8

**Comment by srv-twry** [comment]
@simonschoelly @sbromberger Hi, I am looking to participate in GSoC with this project and want to work on this issue in order to get started. Can I?

**Comment by sbromberger** [comment]
Be my guest! Please make sure you’re using the latest master and yell if you need help.
