### ISSUE TITLE
Consistent Style Standards

### ISSUE THREAD

**Issue by birm** [JuliaGraphs/LightGraphs.jl#1352]
re #1351

It'd be nice to have an agreed-upon set of rules that could be used to automatically or semi-automatically applied on LightGraphs.

In 1351, I ended up using JuliaFormatter with the following rules:
indent = 4, margin = 100, always_for_in = true, whitespace_typedefs = true, whitespace_ops_in_indices = false, remove_extra_newlines = true

However, some other changes needed to be made after the fact; namely, re-adding the semicolon in the last line of src/shortestpaths13/bellman-ford.jl, fixing each of the trait functions which were more than one statement (see JuliaGraphs/LightGraphs.jl@cc0b755), and making the inline functions one line (see JuliaGraphs/LightGraphs.jl@2e66207).

**Comment by sbromberger** [comment]
Not really a bug :)

This is an overdue conversation, so thanks for starting it. Could I ask you to put together some concrete style rules we can use as the basis for discussion? I tried to give some feedback in the now-closed PR.

This will be a gigantic task, but the first step is agreeing on some style conventions, and publishing them.

**Comment by birm** [comment]
Ah, I didn't notice that it created a bug by default; maybe we want to add a feature request option to the .github issue templates?

I think that the suggestions on the base [JuliaLang/julia](https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#general-formatting-guidelines-for-julia-code-contributions) repo is at least a good start, if a bit vague.

I think that one of the decisions that isn't even mentioned there is what to do when a divisible line is longer than the limit. Should we break it down so each comma separated item (in an import/export or function call) is on a new line, or group them so each line is within the line limit?

The other half of this having a CI check. That would, I think, be pretty useful for ensuring that the standards are kept.

**Comment by sbromberger** [comment]
- my preference is to break it down so each item gets its own line.
- agreed, but that's a pretty big undertaking. (I'm so used to `gofmt` that this seems really primitive.)

**Comment by sbromberger** [comment]
bump

**Comment by birm** [comment]
I do plan on getting to this, it just will likely require skills that I don't yet have. It should be a good excuse to learn about programming languages at a lower level, if nothing else.
In case anyone is curious about [the existing julia formatter](https://github.com/domluna/JuliaFormatter.jl) I've run it on centrality, and you can see it's suggestions `[here](https://github.com/JuliaGraphs/LightGraphs.jl/compare/master...birm:format?expand=1)`.

**Comment by birm** [comment]
(of course, if someone else gets to it first, I won't be upset)
