### ISSUE TITLE
[Feature] Add a way to detect a Tree & Implement faster diameter algorithm

### ISSUE THREAD

**Issue by dr0pdb** [JuliaGraphs/LightGraphs.jl#1359]
It would be great if there was a way to detect if a passed in undirected graph is a Tree.

A tree has the following properties:
1. `n` vertices
2. `n-1` edges
3. connected i.e. for every pair of vertices, there is a unique path between them.

## Usefulness

There are several instances where a problem has an extremely easier solution for a tree in comparison to a general graph.

For instance: `diameter/maximum eccentricity` of a graph. In `src/distance.jl` right now in order to compute the diameter of a graph, we first compute the eccentricity of every vertex and then take the maximum out of that.

In the case of a tree, there are much simpler and faster `O(n)` algorithms to compute the diameter.

Once we detect that a graph is in fact a tree we can use the faster algorithms. In other cases, the general algorithm will be used

#### Edit

oops, It's not a bug. Shouldn't have used the `bug` issue template. I don't have access to remove the label. Requesting someone with access to remove the label please :)

**Comment by srv-twry** [comment]
@sbromberger @simonschoelly If it seems a reasonable thing, I can implement this.

**Comment by sbromberger** [comment]
Is there a way to do this that's not |V|^2? Otherwise couldn't we just implement
```
is_tree(g::AbstractGraph) = nv(g) == ne(g)-1 && is_connected(g)
```
?

**Comment by srv-twry** [comment]
Yes, we could and should implement what you're suggesting. I just wrote the conditions for a tree. A simple connectivity check using a dfs from any vertex should be fine as you've suggested.
