### ISSUE TITLE
Isomorphism for trees

### ISSUE THREAD

**Issue by alimamdouh212** [JuliaGraphs/LightGraphs.jl#1360]
#1359 reminded me that there is there is `o(nlgn)`  tree isomorphism algorithm, so i am asking if that is ok as a PR.

**Comment by sbromberger** [comment]
You've currently got 4 open PRs, each in a different state of readiness. As I mentioned before, I'd prefer you work on concluding those before starting any more, especially in the `Experimental` tree.
