### ISSUE TITLE
[BUG] merge_vertices() doesn't work as expected

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#1369]
**Description of bug**
merge_vertices doesn't work properly.

**How to reproduce**
```
g = path_graph(5)
h = merge_vertices(g, [2, 3])
collect(edges(h))
```

**Expected behavior**
Describe what you expected to happen.
```
Edge 1 => 2
Edge 2 => 3
Edge 3 => 4
```

**Actual behavior**
```
Edge 1 => 2
Edge 2 => 4
```

`merge_vertices!` exhibits correct behavior.

**Comment by birm** [comment]
So, maybe this isn't an issue, but #1368 turns out not to work with duplicated entries in `vs`
```julia
julia> a = path_digraph(5)
{5, 4} directed simple Int64 graph

julia> merge_vertices!(a, [2,3]) 
2

julia> collect(edges(a))
3-element Array{LightGraphs.SimpleGraphs.SimpleEdge{Int64},1}:
 Edge 1 => 2
 Edge 2 => 4
 Edge 4 => 3

julia> a = path_digraph(5)
{5, 4} directed simple Int64 graph

julia> merge_vertices!(a, [2,2,3])
2

julia> collect(edges(a))
1-element Array{LightGraphs.SimpleGraphs.SimpleEdge{Int64},1}:
 Edge 2 => 3

```

**Comment by sbromberger** [comment]
nothing that a simple `unique` can't fix, right? I'll try a quick PR.

**Comment by birm** [comment]
I'm at it anyway, so unless you've already done it, I will.

**Comment by sbromberger** [comment]
I've done it. There were a couple of other minor things to check also :)

**Comment by sbromberger** [comment]
ref: #1370. Doesn't close this issue, but does fix the unique vertices issue.

**Comment by sbromberger** [comment]
@birm - please consider joining us on the Julia slack - we hang out in the #graphs channel.
