### ISSUE TITLE
[2.0.0] revamp documentation

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#1376]
cc @kshyatt - we'll want to create docstrings for all new modules and ensure that all public functions have correct docs (preferably with examples).

Might also take the opportunity to standardize on a format.

**Comment by CameronBieganek** [comment]
One note on documentation:

Currently the [Core Functions](https://juliagraphs.org/LightGraphs.jl/stable/core/) page of the documents is only accessible if you happen to search for one of the functions, like `degree`. There's no menu link to Core Functions page.
