### ISSUE TITLE
Adding functions to work with planarity graphs

### ISSUE THREAD

**Issue by Lucasslimam** [JuliaGraphs/LightGraphs.jl#1383]
I would like to add a function to test if something called "combinatory description" (I don't know if the term is exactly the same in English) and to do that we can work with adjacency lists but the order of the vertices in the adjacency lists is important to do that. Unfortunately I noticed that the vertices are always stored in ascending order so I would like to know what is the best, work with my own structure or modifying the function add_edge!().

**Comment by sbromberger** [comment]
For `SimpleGraphs`, the output from `fadj` and `badj` adjacency list accessors will always be in sorted order. Can you use those?

**Comment by Lucasslimam** [comment]
I would need an unsorted order, for exemple, if someone does add_edge!(g,1,3) and later add_edge!(g,1,2) I would like to have g.fadjlist[1] = [3,2]

**Comment by Lucasslimam** [comment]
> For `SimpleGraphs`, the output from `fadj` and `badj` adjacency list accessors will always be in sorted order. Can you use those?

I would need an unsorted order, for exemple, if someone does add_edge!(g,1,3) and later add_edge!(g,1,2) I would like to have g.fadjlist[1] = [3,2]

**Comment by sbromberger** [comment]
Oh. nope. That won't work then. We keep the adjacency lists sorted internally.

**Comment by Lucasslimam** [comment]
> Oh. nope. That won't work then. We keep the adjacency lists sorted internally.

What would you recommend ? If I am going to do my function with my own structure I would probably use something like this: function name(desc::Vector{Vector{Int}}, num_edges::Int) do you think that would be a problem ? I would like to use structures Like AbstractGraph and its functions so the function would be more resembling to the rest of the functions in LightGraphs

**Comment by sbromberger** [comment]
What I'd recommend just off the top of my head is something like what we do in MetaGraphs:
```
mutable struct PlanarityGraph{T} <: AbstractGraph{T}
    g::SimpleGraph{T}
    orderedadjacency::Vector{Vector{T}}
end
```

and then just implement the interface and core functions, and you should be all set.

**Comment by Lucasslimam** [comment]
> What I'd recommend just off the top of my head is something like what we do in MetaGraphs:
> 
> ```
> mutable struct PlanarityGraph{T} <: AbstractGraph{T}
>     g::SimpleGraph{T}
>     orderedadjacency::Vector{Vector{T}}
> end
> ```
> 
> and then just implement the interface and core functions, and you should be all set.

Hmmm ok, thanks!! As soon as I check the feasibility of this idea to my project I will continue the discussion!

**Comment by sbromberger** [comment]
Sounds good. I'll close this out for now.
