### ISSUE TITLE
doc issue with bulleted lists?

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#141]
@hayd - could use your help here. In http://lightgraphsjl.readthedocs.org/en/latest/pathing/, under Graph Traversal, the source shows:

```
## Graph Traversal

*Graph traversal* refers to a process that traverses vertices of a graph following certain order (starting from user-input sources). This package implements three traversal schemes:
* `BreadthFirst`,
* `DepthFirst`, and
* `MaximumAdjacency`.
```

This results in the following markdown:

## Graph Traversal

*Graph traversal* refers to a process that traverses vertices of a graph following certain order (starting from user-input sources). This package implements three traversal schemes:
* `BreadthFirst`,
* `DepthFirst`, and
* `MaximumAdjacency`.

But what's being rendered in rtd isn't right.

Totally not urgent, but I'd appreciate any advice.

**Comment by hayd** [comment]
try a newline before the list

```
*Graph traversal* refers to a process that traverses vertices of a graph following certain order (starting from user-input sources). This package implements three traversal schemes:

* `BreadthFirst`,
* `DepthFirst`, and
* `MaximumAdjacency`.
```

I think this is a different flavors of markdown issue.

Commonmark requires the newline, github is more forgiving. Not sure what rtd is using, redcarpet?.

In fact, you can see this: http://johnmacfarlane.net/babelmark2/?text=*Graph+traversal*+refers+to+a+process+that+traverses+vertices+of+a+graph+following+certain+order+(starting+from+user-input+sources).+This+package+implements+three+traversal+schemes%3A%0A*+%60BreadthFirst%60%2C%0A*+%60DepthFirst%60%2C+and%0A*+%60MaximumAdjacency%60.

**Comment by sbromberger** [comment]
Brilliant - that worked. Thank you!
