### ISSUE TITLE
WIP: Final bits of coverage to get to 100%!

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#142]
- [x] https://coveralls.io/builds/3335340/source?filename=src%2Fspectral.jl line 82 (cc @hayd since I'll bet you have a really good solution for this)

- [x] https://coveralls.io/builds/3335340/source?filename=src%2Fpersistence.jl - need a bad graph to test.

**Comment by hayd** [comment]
For the former you can have a build matrix, one install with and one install without. E.g. see https://github.com/hhatto/autopep8/blob/master/.travis.yml

**Comment by sbromberger** [comment]
We aware now at 100% coverage :)
