### ISSUE TITLE
Katz centrality for weighted graphs

### ISSUE THREAD

**Issue by bkamins** [JuliaGraphs/LightGraphs.jl#1423]
Why in https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/Centrality/katz.jl#L46 there is the restriction to `Bool` type. I think that allowing `Float64` should be enough and it would allow for weighted graphs.

**Comment by bkamins** [comment]
(it is not a bug but feature request - the "bug" label was added automatically and I do not know how to remove it)

**Comment by sbromberger** [comment]
If you'd like to make a PR, please do (to the code in master branch). But do you have a reference for Katz on weighted graphs? I've not seen this before.

**Comment by bkamins** [comment]
igraph supports weights https://igraph.org/r/doc/alpha_centrality.html

Also from a linear algebra perspective there is no problem with the definition.

Of course one has to be careful to make weights meaningful (as e.g. negative weights clearly do not make sense). But since SimpleWeightedGraphs defines `pagerank` for weighted graphs then in the same way Katz centrality can be accepted.

**Comment by bkamins** [comment]
Also `eigenvector_centrality` now just works for weighted graphs

**Comment by sbromberger** [comment]
I would suggest we make this a different centrality type, say, `Bonacich`. It's one of many in the class of eigenvector centrality measures. I think the most common use for `Katz` is without weights.

**Comment by bkamins** [comment]
I leave it up to you to decide (as I have a minimal understanding of the LightGraphs.jl design). But the only change required in the code is to change `Bool` to `Float64`, all else is the same (it can be called `Bonacich` if you prefer this).

**Comment by sbromberger** [comment]
OK. Let me make a quick PR and you can review it? I have a special way I'd like to do it.

**Comment by sbromberger** [comment]
After talking with one of our Katz experts here, I think your original proposal (add a method to Katz for weights) is the right one. Let me put up a PR for review.

**Comment by sbromberger** [comment]
I think I've done it. @bkamins - Would you mind providing an example of a proper result with a very small graph and weight matrix? I'll include that in our tests.

**Comment by bkamins** [comment]
Here is what igraph produces. Is 5x5 small enough? Tested for 4 values of alpha centrality. I have also hand-checked that the results follow the theory
```
> library(igraph)
> adjm <- matrix(1:25, nc=5) / 25
> diag(adjm) <- 0
> print(adjm)
     [,1] [,2] [,3] [,4] [,5]
[1,] 0.00 0.24 0.44 0.64 0.84
[2,] 0.08 0.00 0.48 0.68 0.88
[3,] 0.12 0.32 0.00 0.72 0.92
[4,] 0.16 0.36 0.56 0.00 0.96
[5,] 0.20 0.40 0.60 0.80 0.00
> g <- graph_from_adjacency_matrix(adjm, weighted=TRUE)
> print(g)
IGRAPH e1deea0 D-W- 5 20 -- 
+ attr: weight (e/n)
+ edges from e1deea0:
 [1] 1->2 1->3 1->4 1->5 2->1 2->3 2->4 2->5 3->1 3->2 3->4 3->5 4->1 4->2 4->3 4->5 5->1 5->2 5->3 5->4
> for (a in c(0.1, 0.2, 0.3, 0.4)) {
+     print(a)
+     print(alpha_centrality(g, alpha=a))
+ }
[1] 0.1
[1] 1.075051 1.172686 1.265867 1.354891 1.440030
[1] 0.2
[1] 1.213834 1.481742 1.726354 1.950582 2.156872
[1] 0.3
[1] 1.517035 2.143117 2.691209 3.175030 3.605258
[1] 0.4
[1] 2.552494 4.374501 5.906917 7.213701 8.341269
```
to test `isapprox` is probably needed.

I am not sure if you allow SimpleWeightedGraphs.jl as a dependency in tests, because I guess within LightGraphs.jl it is not possible to test it, unless your implementation allows for passing weights as a separate argument (I am not sure what API for passing weights you envision in 2.0 release).
