### ISSUE TITLE
2.0 discussion: revamp LinAlg

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#1429]
cc @bkamins @haampie @jpfairbanks @simonschoelly @matbesancon 

Hi all,

I wanted to get the Linear Algebra experts I know together to discuss how to better structure the linear algebra stuff in LightGraphs (now in the `linalg13` directory) for LG 2.0.

I think there have been some significant changes to linear algebra functions since we originally wrote this code, so there are undoubtedly some optimizations we can make for, _e.g._, pagerank.

Could I ask you to go through the `linalg13` codebase and make some performance/correctness suggestions? Specifically, what I'd like to see changed is our awkward handling of `adjacency_matrix(...; dir=:out)`. I want to get rid of directionality in the AM if we can do it in a performant way: that is, the adjacency matrix should always be [i, j] indexed and if someone needs something different then `transpose()` might do the trick. We originally included directionality because it was much quicker and more memory-efficient than doing the transpose post-creation. Maybe that's still the case. If it is, we'll do something else because I don't really like the kwarg-with-symbol option.

Anyway, thanks in advance for any suggestions you'd care to make.

**Comment by simonschoelly** [comment]
One approach would be to not create a new matrix out of a graph. but instead have a wrapper class that that implements the matrix interface.

Some experiments that I did with this can be found here: https://github.com/simonschoelly/SimpleValueGraphs.jl/blob/3a010f1ecf09d0cf50064b0a125bf05680cd1277/src/matrices.jl#L5

Advantages:
- The user can choose themselves if they want to convert that matrix to a `Matrix`, a `SparseMatrixCSC` or some other matrix format, such as as a gpu implementation.
- Less memory usage

Disadvantages:
- This is a breaking change
- It might be unintuitive that the matrix changes whenever the underlying graph changes
- Unless the user converts the matrix to another format, the matrix is probably not writeable and some operations might not be very fast as they would use the general matrix interface and not some specialized implementation (unless we add that)

**Comment by bkamins** [comment]
This was similar what I was thinking. I.e. maybe we can allow users to choose a linear operator or a materialized matrix. Maybe accessible via a different function.

The point is that e.g. `(I - alpha*transpose(A)) \ v` where `A` is an adjacency matrix (this is solved to find Katz centrality) could possibly be made more efficient if we did not materialize `A` as sparse matrix (and additionally you can e.g. leverage the fact that for graphs `A` is symmetric). Of course this would require implementing a lot of functionality internally e.g. defining some transformations on linear operators, but this could be relevant for very large graphs.

**Comment by matbesancon** [comment]
I also agree with what's been proposed. A desirable feature would be to have type-generic linalg algorithms (working with symbolic maths, autodiff).

Regarding the risk of mutating the graph, we can call it a matrix view or equivalent, which clearly indicates that this may be moving under your feet

**Comment by bkamins** [comment]
Actually the fact that it would be a view would be a benefit IMO. You can always `copy` if you want to fix the state at some moment.
