### ISSUE TITLE
Fast PageRank computation via a Sparse Linear System

### ISSUE THREAD

**Issue by karjudev** [JuliaGraphs/LightGraphs.jl#1430]
For a university project I recently came across the alternative implementation of the PageRank algorithm presented in [1] that seems to converge in less iterations that the traditional power method.

The algorithm performs a quite simple algebraic manipulation of the original PageRank formulation to solve the problem as a sparse linear system. The resulting matrix is an M-matrix so it notes that the Gauss - Seidel iterative method performs better on it.

I have a toy implementation that served for the academic project but I'd like to adapt it and maybe add it to LigthGraphs as an alternative implementation of the algorithm in the library.

Let me know if it could be a good contribution for the project.

**References**:
[1] [Del Corso, Gianna M., Antonio Gulli, and Francesco Romani. "Fast PageRank computation via a sparse linear system." Internet Mathematics 2.3 (2005): 251-273.](https://projecteuclid.org/download/pdf_1/euclid.im/1150474883)

**Comment by sbromberger** [comment]
@karjudev we'd welcome new code! Best thing to do is to create a PR, and then do some benchmarking (using the `BenchmarkTools` package) on graphs of different sizes, densities, etc. Specifically, show where it works better and worse than the existing algorithm.

**Comment by karjudev** [comment]
For sure I'll make a PR when the work will be finished. Just an "aesthetic" question: what's the canonical way of adding an alternative implementation along with the existing one? Do I have to extend `CentralityMeasure` with another struct i.e. `SparseLinearPageRank`?
