### ISSUE TITLE
Feature Request - DiGraph ancestors/descendants

### ISSUE THREAD

**Issue by chris-b1** [JuliaGraphs/LightGraphs.jl#1436]
I'm not tied to the names, this just happens to be what networkx calls them - doc links  [`anscestors`](https://networkx.github.io/documentation/networkx-1.9/reference/generated/networkx.algorithms.dag.ancestors.html#ancestors) [`descendents`](https://networkx.github.io/documentation/networkx-1.9/reference/generated/networkx.algorithms.dag.descendants.html#networkx.algorithms.dag.descendants)

I've been using this StackOverflow recipe from @sbromberger - would be happy to submit as a PR if it fits in the API

```julia
# https://stackoverflow.com/a/55243475/3657742
function ancestors(g::SimpleDiGraph{T}, src) where T <: Integer
    reverse!(g)
    a = Vector{T}()
    for (v, d) in enumerate(gdistances(g, src))
        if d < typemax(T)
            push!(a, v)
        end
    end
    reverse!(g)
    return a
end
```

**Comment by sbromberger** [comment]
There's a much easier way to get the descendants now (in master). This assumes you want all the descendants up to a given cutoff distance (if you want ALL of them, just remove the `SP.BFS(maxdist=cutoff)` bit and let the default sp alg work for you.

```
using LightGraphs, LightGraphs.ShortestPaths
const SP = LightGraphs.ShortestPaths

findall(SP.parents(SP.shortest_paths(g, src, SP.BFS(maxdist=cutoff)) .!= 0)
```

To get the ancestors, just reverse the graph first.

**Comment by abhinavmehndiratta** [comment]
```
julia> using LightGraphs.Traversals

julia> LT =  LightGraphs.Traversals
LightGraphs.Traversals

julia> LT.visited_vertices(g, source, LT.BreadthFirst(neighborfn = inneighbors))
```
I think this should work

**Comment by sbromberger** [comment]
Oh, jeez. Of course. I forgot we added `neighborfn` to `BreadthFirst`. Awesome.
