### ISSUE TITLE
Outdated plotting documentation

### ISSUE THREAD

**Issue by MaximeBouton** [JuliaGraphs/LightGraphs.jl#1439]
The documentation on how to plot graphs indicates [GraphLayout.jl](https://github.com/IainNZ/GraphLayout.jl) first, which seems to be abandoned. 

It should be removed or probably be at the bottom of the list.

**Comment by leios** [comment]
I also noticed this. Happy to put forward a PR that removes the stale information (unless there is a reason you have kept it in).
