### ISSUE TITLE
Feature Request - Network Percolation

### ISSUE THREAD

**Issue by vgauthier** [JuliaGraphs/LightGraphs.jl#1441]
Hi!

I implemented both a bond and site percolation algorithm based on the Newman-Ziff's algorithm. I would be happy to submit as a PR if it fits in the API ?

Please find the code with examples at the following link:
https://github.com/ComplexNetTSP/Percolation

Best,

**Comment by sbromberger** [comment]
Hi @vgauthier - sorry for the delay. (Work's been busy.)

Just to let you know I haven't forgotten about this.
