### ISSUE TITLE
Use of memory

### ISSUE THREAD

**Issue by erlebach** [JuliaGraphs/LightGraphs.jl#1451]
Consider the following code, which simply defines a graph, captures its edges into arrays `xe,ye,ze`. I am trying to understand memory usage. From what I can see, the only memory use is that taken by the graph, and the node and edges arrays `xn,xe` and the associated `y` and `z` arrays. Using `@btime` indicates total usage of about 5kbytes. However, I only count about 1kbytes. That is a pretty large discrepency. I change `n` from 10 to 100 to 1000 and confirmed that the memory usage is proportional to `n`, which is expected. But I still do not understand the 5kbytes of storage when `n=10`.  The main memory is taken by the adjacency matrix, more specifically, `fadj` and `badj`. At the end of the day, I simply must have miscounted. 
```
using LightGraphs, BenchmarkTools

function testGraph()
    n = 10
    graph = SimpleGraph(n, 3*n)
    nes = ne(graph)
    xn = rand(n)
    yn = rand(n)
    zn = rand(n)
    xe = zeros(Float32, 3*nes)
    ye = zeros(Float32, 3*nes)
    ze = zeros(Float32, 3*nes)
    for (i,e) in enumerate(edges(graph))
        xe[3*i-2] = xn[src(e)]
        xe[3*i-1] = xn[dst(e)]
        xe[3*i] = NaN
        ye[3*i-2] = yn[src(e)]
        ye[3*i-1] = yn[dst(e)]
        ye[3*i] = NaN
        ze[3*i-2] = zn[src(e)]
        ze[3*i-1] = zn[dst(e)]
        ze[3*i] = NaN
    end
    println("size: ", sizeof(xe))
   println("size: ", sizeof(zn))
    println("size(graph): ", sizeof(graph))
end
```

**Comment by sbromberger** [comment]
ok, so just to clear something up: `fadj` is not an adjacency matrix: it's an adjacency LIST. That is, it's not a VxV matrix; it's a vector of V vectors (sometimes called a "ragged matrix"). The length of each inner vector with outer vertex `u` corresponds to the number of neighbors for `u`.

For undirected graphs, `fadj` and `badj` point to the same adjacency list since inbound neighbors == outbound neighbors for all neighbors. For directed graphs, we have to track `fadj` and `badj` separately, which is why directed graphs take twice the memory as their undirected counterparts.

Now, on to your questions:

You are allocating 1016 bytes for `graph`. You are also allocating 120 bytes (80 plus vector overhead) each for `xn`, `yn`, and `zn`, and 160 bytes each for `xe`, `ye`, and `ze`.

So, in total, you should be allocating 1016 + 360 + 480 = 1856 bytes just for the data structures. You can confirm the data sizes by using `varinfo()`. Anything else would likely be function overhead plus temporary allocations inside the loop (`println` isn't free).

**Comment by sbromberger** [comment]
Also, I'm getting 11Kbytes allocation:
```
BenchmarkTools.Trial: 
  memory estimate:  11.83 KiB
  allocs estimate:  360
  --------------
  minimum time:     0.001 ns (0.00% GC)
  median time:      57.571 μs (0.00% GC)
  mean time:        72.442 μs (1.40% GC)
  maximum time:     5.397 ms (95.58% GC)
  --------------
  samples:          10000
  evals/sample:     1
```

**Comment by sbromberger** [comment]
And just to confirm: without the `println`s,

```
julia> @benchmark testGraph()
BenchmarkTools.Trial: 
  memory estimate:  3.86 KiB
  allocs estimate:  36
  --------------
  minimum time:     0.001 ns (0.00% GC)
  median time:      5.223 μs (0.00% GC)
  mean time:        5.636 μs (4.29% GC)
  maximum time:     504.884 μs (98.51% GC)
  --------------
  samples:          10000
  evals/sample:     7
```

**Comment by sbromberger** [comment]
Also: as I just remembered, `varinfo()` underestimates in some cases. Therefore, I think showing 3.86KB on something that was calculated as "1872 + loop variables" is pretty close.

**Comment by erlebach** [comment]
Thank you. I did not know about `varinfo()`. I love digging deeper. I notice that it is found in `InteractiveUtils.jl` as well as in the `Main` module. They give the same results when invoked as `varinfo(LightGraphs)`. `varinfo()` provides information about all the structures and functions in a Module, so running it tells me that `SimpleGraph` itself uses 40 bytes. 

How did you come up with the 1016 bytes allocated for `graph`? I do not have the impression that `varinfo` provides that information. I also tried `dump`. Obviously, I prefer such tools to manual counting :-)

I am appreciating Julia more and more. But the learning curve is steeper than it should be for most people in my opinion.

**Comment by sbromberger** [comment]
> How did you come up with the 1016 bytes allocated for `graph`?

```
julia> using LightGraphs, LightGraphs.SimpleGraphs

julia> g = Graph(10,30)
v{10, 30} undirected simple Int64 graph

julia> varinfo()
  name                    size summary           
  –––––––––––––––– ––––––––––– ––––––––––––––––––
  Base                         Module            
  Core                         Module            
  InteractiveUtils 182.987 KiB Module            
  Main                         Module            
  ans               1016 bytes SimpleGraph{Int64}
  g                 1016 bytes SimpleGraph{Int64}
 ```

But note that `varinfo()` isn't 100% accurate in all cases:
> The memory consumption estimate is an approximate lower bound on the size of the internal structure of the object.

In the case of the graph, it'd be (I think) 8 bytes for `ne` + 40 bytes per vertex + 8 bytes per edge. So for a (10, 30) graph it's more like 648 bytes. Manual counting is going to be more accurate, but it's not something we generally do in LG. Our data structures are already pretty much theoretically optimal so there's no point.

> I am appreciating Julia more and more. But the learning curve is steeper than it should be for most people in my opinion.

How would you do this in any other language? (That is, get the runtime memory usage of some mutable structure?)

**Comment by erlebach** [comment]
"How would you do this in any other language? (That is, get the runtime memory usage of some mutable structure?)"

I was not referring to this task in particular. I was referring to the language as a whole. I have had more difficulty with Julia than most other languages. Perhaps that is the price one pays for efficiency and power.

**Comment by sbromberger** [comment]
Is there a specific set of things you're having trouble with? There's definitely a learning curve coming from C/C++, but the generics are similar, and overloading is analogous to multiple dispatch in many ways.

**Comment by erlebach** [comment]
I am not having trouble at this time, Seth. I am debugging. 
Actually, I have never successfully included Revise.jl into my workflow and would like to. After failing twice, I decided to leave it for another day.
