### ISSUE TITLE
How to get all shortest paths between a  source node to a target node? 

### ISSUE THREAD

**Issue by fanyuan-lab** [JuliaGraphs/LightGraphs.jl#1456]
Hope for your reply.

**Comment by birm** [comment]
You may find [this documentation](https://juliagraphs.org/LightGraphs.jl/v1.3/pathing/#Shortest-Path-Algorithms-1) helpful in finding the shortest paths using lightgraphs. If that doesn't help you, please let us know what issues or confusion you're having.

**Comment by fanyuan-lab** [comment]
Thanks for your reply. For example, a cycle with 4 nodes, label 1,2,3,4. In this case, there are two different shortest paths between node 2 and node 4, namely Edge 2=>1, 1=>4 or Edge 2=>3, 3=>4. My goal is to find all shortest paths between source node and target node. So I am wondering if there is any algorithms or functions in LightGraphs can solve the problem.
