### ISSUE TITLE
Adding and removing edges, benchmarks

### ISSUE THREAD

**Issue by erlebach** [JuliaGraphs/LightGraphs.jl#1457]
Hi @sbromberger ! This is not an issue with `LightGraphs` per say, so if there is a better place to post this, I can do so. I have written a benchmark to add/remove edges. I hope that I do not violate any major benchmark principles, except calling @benchmark from within a function. I use variable interpolation, so do not see how this could be a problem. Could you please take a look? the idea is that given a `SimpleGraph`, with a specified number of nodes and edges, I wish to remove an arbitrary edge, and add an arbitrary edge. This is done in the function `runGraph`,  which is benchmarked. All needed variables are passed in the argument list. I have found that adding an edge is quite a bit more expensive than removing a random edge. The needed random indices are precomputed in the global space. I run the add/remove process `n` times, compute the average time per add/remove. I cannot simply do this once with `@btime` for example, because I suspected that the timing might depend on the number of edges added and removed. What is weird is that I  find that the time is quite high per add/remove pair for `n=10`, and the time goes down for higher `n`. I suspect, but do not know, that I might be benchmarking optimized code. I store the results in a `DataFrame`. The code below only runs a single graph, but create a list of different graphs at the top of the page, and benchmark 9 graphs for each of 5 value of `n` In any case, I thought you might be interested, and if you have time, you might provide some insight. I am no hurry! :-)  

```
# Add and remove random edges from a graph and perform some benchnarking
# as a function of graph size

using LightGraphs
using BenchmarkTools
using DataFrames
using Plots

function generateGraphs()
    graphs = []
    nnodes = [1000, 10000, 100000]
    edge_scale = [5, 10, 20]
    for i in 1:length(nnodes)
        for j in 1:length(edge_scale)
            push!(graphs, SimpleGraph(nnodes[i], nnodes[i]*edge_scale[j]))
        end
    end
    return graphs
end

graphs = generateGraphs()

edge_lists = []
randEdgeIndexes(nb_edges, nb_rand) = rand(1:nb_edges, nb_rand)
randEdgeNodes(nb_nodes, nb_rand) = rand(1:nb_nodes, 2*nb_rand)

function runGraph(n::Int64, graph, edge_list, e_indexes, en_indexes)
    for i in 1:n
        rem_edge!(graph, edge_list[e_indexes[i]])
        # 10x more expensive!
        add_edge!(graph, en_indexes[2*i-1], en_indexes[2*i])
    end
    return
end
# Estimate average time per add/remove edge pair
counts = [10, 100, 1000,10000, 100000]
function runBenchmarks()
    dict = Dict()
    #for g in graphs[1:9]
    for g in graphs[1:1]
        @show g
        edge_indexes = randEdgeIndexes(ne(g), n)
        edge_node_indexes = randEdgeNodes(nv(g), n)
        edge_list = collect(edges(g))
        for n in counts
            gg = deepcopy(g)
            @show n
            t = @benchmark runGraph(n, $gg, $edge_list, $edge_indexes, $edge_node_indexes) evals=5 samples=5
            dict[Pair(gg,n)] = t
        end
    end
    return dict
end

# Adding edges is 30 to 40x more expansive and removing them.
dict = runBenchmarks()
using StringLiterals

gnv_l = []
gne_l = []
tmin_l = []
n_l = []

for key in keys(dict)
    g = key.first
    n = key.second
    t = dict[key]
    gnv = nv(g)
    gne = ne(g)
    tmin = minimum(t).time / (1000*n) # μs
    tmax = maximum(t).time / (1000*n) # μs
    push!(gnv_l, gnv)
    push!(gne_l, gne)
    push!(tmin_l, tmin)
    push!(n_l, n)
end

df = DataFrame([n_l, gnv_l, gne_l, tmin_l],
               [:n, :nv,   :ne,    :tmin])

println(df[:,:])
```
The output for one graph. (nv,ne) are the graph parameters, `n` is the number of add/rem edge pairs, and `tmin` is the minimum time returned by the benchmarks divided by `n`. You will note the very large time in the 5th row, which I do not understand. Perhaps I have an error in my code. 
```
5×4 DataFrame
│ Row │ n      │ nv   │ ne   │ tmin       │
│     │ Any    │ Any  │ Any  │ Any        │
├─────┼────────┼──────┼──────┼────────────┤
│ 1   │ 100    │ 1000 │ 5176 │ 1.10657    │
│ 2   │ 1000   │ 1000 │ 5176 │ 0.111737   │
│ 3   │ 100000 │ 1000 │ 5176 │ 0.00112931 │
│ 4   │ 10000  │ 1000 │ 5176 │ 0.0106682  │
│ 5   │ 10     │ 1000 │ 5176 │ 11.2815    │
```

**Comment by sbromberger** [comment]
This makes sense. Adding an edge requires inserting into two sorted vectors, which can also reallocate. Removing an edge does not require reallocation.

Also, you might be running into some other biases: if you've removed the edge from `X` to `Y`, then if you try to remove the edge from `Y` to `X` you're going to shortcut the function. (Same with `add_edge!()`). You can eliminate this possible bias by using a `DiGraph`.

Finally, you can't use `@benchmark` with `rungraph` the way you're doing it. You need to use the `setup` parameter since you're modifying the graph. You're only timing the first `rem_edge!` since when `@benchmark` runs the second time, the edge has already been removed. Here's a simple example to show you what I mean:

```
julia> a = [1,2,3,4,5]
5-element Array{Int64,1}:
 1
 2
 3
 4
 5

julia> function foo!(a)
         pop!(a)
         end
foo! (generic function with 1 method)

julia> @benchmark foo!($a)
ERROR: ArgumentError: array must be non-empty
Stacktrace:
 [1] pop! at ./array.jl:1126 [inlined]
...
```

**Comment by erlebach** [comment]
Thank you, Seth. I do understand the issue regarding setup, but I did not use it because my setup was a rather large function and not a few lines. I am calling `@benchmark` from within a function but using escape characters to refer to variables in the local context. 

I changed my graphs to DiGraphs. See the `DataFrame` produced using a graph `SimpleDigraph(1000,5000)`: 
```
n = 10
3×5 DataFrame
│ Row │ n    │ nv   │ ne   │ ne_end │ tmin     │
│     │ Any  │ Any  │ Any  │ Any    │ Any      │
├─────┼──────┼──────┼──────┼────────┼──────────┤
│ 1   │ 10   │ 1000 │ 5000 │ 5081   │ 8.0449   │
│ 2   │ 100  │ 1000 │ 5000 │ 5081   │ 0.988198 │
│ 3   │ 1000 │ 1000 │ 5000 │ 5081   │ 0.102743 │
```
The `ne_end` column refers to the number of edges in the graph _after_ removing and adding `n` edges. The value of `n_end` indicates that about 81 edges were not removed because they had already been removed. The way proceeded also does not guarantee that edges are added since the same edge might be added twice. So I will now perform the experiments with just removing edges, and a second experiment just adding edges. I will do this on a graph with 10000 edges to make it less likely the same edge will be added twice.Note that I precompute the indexes of the edges to add remove prior to execution with the two functions defined in global scope: 
```
randEdgeIndexes(nb_edges, nb_rand) = rand(1:nb_edges, nb_rand)
randEdgeNodes(nb_nodes, nb_rand) = rand(1:nb_nodes, 2*nb_rand)
```
`n` refers to the number of pairs added and removed.  

Here are the results when all I do is add `n` edges: 
3×5 DataFrame
│ Row │ n    │ nv    │ ne    │ ne_end │ tmin      │
│     │ Any  │ Any   │ Any   │ Any    │ Any       │
├─────┼──────┼───────┼───────┼────────┼───────────┤
│ 1   │ 100  │ 10000 │ 50000 │ 51000  │ 0.462112  │
│ 2   │ 1000 │ 10000 │ 50000 │ 51000  │ 0.0388416 │
│ 3   │ 10   │ 10000 │ 50000 │ 51000  │ 3.83954   │

And here it is when all I do is remove 10 edges: 
```
3×5 DataFrame
│ Row │ n    │ nv    │ ne    │ ne_end │ tmin      │
│     │ Any  │ Any   │ Any   │ Any    │ Any       │
├─────┼──────┼───────┼───────┼────────┼───────────┤
│ 1   │ 100  │ 10000 │ 50000 │ 49004  │ 0.522222  │
│ 2   │ 10   │ 10000 │ 50000 │ 49004  │ 5.08742   │
│ 3   │ 1000 │ 10000 │ 50000 │ 49004  │ 0.0512528 │
```
You will note that in both cases, removing a smaller number of edges (or adding a smaller number of edges), is much more expensive per edge. Perhaps that has to do with allocation issues. I have not looked at that. Will do so next. 

It is hard to believe that using `setup` instead of placing `@benchmark` inside a function would substantially change the results. How can I use setup to do complex loops? I guess I'll answer my own questions and look into benchmark suites (have you used these)? 

Thanks.

**Comment by erlebach** [comment]
A quick question: if the setup is the result of a complicated function that returns the needed parameters, can I do something like:    
```
setup=mySetup(a,b,c)
```
