### ISSUE TITLE
How to trace vertices after removing or adding vertex?

### ISSUE THREAD

**Issue by yanyuan-wang** [JuliaGraphs/LightGraphs.jl#1458]
Hi, I got to know that for performance purpose, when using the function `rem_vertex!`, a vertex `k` would be removed from the graph by swapping it with the latest vertex, so I wanna know how could I trace the vertices after some modifications are done with the graph each time?

**Comment by abhinavmehndiratta** [comment]
I think you're looking for https://github.com/matbesancon/VertexSafeGraphs.jl

**Comment by yanyuan-wang** [comment]
Thanks for your reply!

But it seems that `VSafeGraph` is a wrapper, I don't know how to copy network structure to a `AbstractGraph` if I want to use some functions in `LightGraph.jl` requiring a `AbstractGraph`.
