### ISSUE TITLE
Missing website

### ISSUE THREAD

**Issue by zdroid** [JuliaGraphs/LightGraphs.jl#1463]
This repository is missing a website link in its description. Reasons to do this are listed in [this Discourse thread](https://discourse.julialang.org/t/a-suggestion-for-package-maintainers/44111).

https://juliagraphs.org/LightGraphs.jl/stable/ and https://juliagraphs.org/LightGraphs.jl/latest/ are examples of a good link for this purpose.

**Comment by sbromberger** [comment]
Docs are linked at the top of README and in the [Documentation](https://github.com/JuliaGraphs/LightGraphs.jl#documentation) section. We don't really use the JuliaGraphs webpage as more than a link back to the Github repos so there's no real value in creating a circular link.

**Comment by zdroid** [comment]
I've already written in that Discourse thread why docs links in Readme aren't that useful. Especially:
> People who are just exploring Julia’s ecosystem and aren’t aware of Documenter, stable/latest docs and how to find them, would just get lost without a very visible link. They are presented with undecipherable source code, and (apparently) no documentation for it. They will probably just close the tab and search for something else.
