### ISSUE TITLE
Feature request - Treewidth

### ISSUE THREAD

**Issue by ismedina** [JuliaGraphs/LightGraphs.jl#1464]
Hi all! 

As part of my work in one of [Qaintum](https://github.com/Qaintum) projects (it is not public yet because it is under construction) I have programmed routines for approximating the treewidth of a graph and give the corresponding tree decomposition. The approximating tree decomposition is done via the min-fill heuristic, inspired in great part by [Python's NetworkX implementation](https://networkx.github.io/documentation/stable/reference/algorithms/approximation.html#module-networkx.algorithms.approximation.treewidth). All the code depends on LightGraphs without having further dependencies. 

You can find  the code in the repo [https://github.com/ismedina/treewidth](https://github.com/ismedina/treewidth). There is still some issues with allocations but hopefully we can sort this out :) 

Best,
Ismael Medina

**Comment by sbromberger** [comment]
@ismedina thanks for this. I'm doing some end-of-year cleanup and will close this issue out, but if you have any problems integrating your package with LightGraphs, please feel free to create new issues.
