### ISSUE TITLE
How to find all shortest paths between two random nodes

### ISSUE THREAD

**Issue by fanyuan-lab** [JuliaGraphs/LightGraphs.jl#1465]
I find all current shortest path algorithms can find only one shortest path between two random nodes. Now I want to find all shortest paths because my goal is to choose one at random.  Thanks

**Comment by sbromberger** [comment]
That's an NP-hard problem, I think. In any case, we don't have an algorithm that will do that.

**Comment by fanyuan-lab** [comment]
> That's an NP-hard problem, I think. In any case, we don't have an algorithm that will do that.

Hi Sbromberger,

Maybe my problem is unclear for you. There is a API can solve the problem: 

https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.algorithms.shortest_paths.generic.all_shortest_paths.html?highlight=all_shortest_paths#networkx.algorithms.shortest_paths.generic.all_shortest_paths

But, I don't have enough experience to rewrite it with Julia code. Could you give me some instructions?

**Comment by sbromberger** [comment]
I understand the problem. But this is the key (taken from the networkx docstring):

> There may be many shortest paths between the source and target.

That means, in general, it's not a good match for inclusion into LightGraphs as part of our functionality. We have to ask, "will this scale?" and in this case, the answer is "no".

The python code is pretty straightforward; it should be easy to implement this with a direct translation to Julia using dijkstra, though with unweighted graphs there's a more efficient way to do it with a modified BFS. It's only a dozen lines or so.

**Comment by LovelyBuggies** [comment]
@sbromberger this is duplicated with #1456

**Comment by sbromberger** [comment]
Closing this out as it's not something we plan on implementing without a whole bunch of benchmarks and scalability studies.
