### ISSUE TITLE
Incompatible

### ISSUE THREAD

**Issue by ChetanVardhan** [JuliaGraphs/LightGraphs.jl#1468]
![Screenshot from 2020-09-12 11-55-00](https://user-images.githubusercontent.com/51269425/92989070-d4ee4400-f4ee-11ea-8056-ce4a06e8f209.png)
Installing LightGraphs.jl downgrades Optim.jl and its dependencies.

**Comment by sbromberger** [comment]
LightGraphs doesn't have Optim as a dependency, so I'm confused as to how we're involved.

**Comment by ChetanVardhan** [comment]
Must be one of the dependencies of LightGraph then
Well, this does concern LightGraph then. Can you look into which one of Calculus,DiffEqDiffTools, NLSolversBase or ChainRulesCore are giving this problem?

**Comment by ChetanVardhan** [comment]
Also, removing LightGraphs didn't remove its dependencies... And I manually couldn't remove them either... I couldn't update Optim
So I've to install all the packages again...

**Comment by sbromberger** [comment]
> Can you look into which one of Calculus,DiffEqDiffTools, NLSolversBase or ChainRulesCore are giving this problem?

LightGraphs does not use any of those as dependencies. The only external direct dependencies are 
- ArnoldiMethod = "0.0.4"
- DataStructures = "0.17.11"
- Inflate = "0.1.1"
- SimpleTraits = "0.9.1"

This information is provided in multiple places, but [Project.toml](https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/Project.toml#L25) is the official source of information.

The full list of direct and transitive dependencies can be found by going to the "Requires" section of https://juliaobserver.com/packages/LightGraphs and ensuring the box is checked.

**Comment by ChetanVardhan** [comment]
Huh... the issue solved itself in an update today!
Thank you for your responses.

**Comment by ChetanVardhan** [comment]
PS: Any idea how I can make square shaped graphs on this?

**Comment by sbromberger** [comment]
What do you mean by "square shaped graphs"?

**Comment by ChetanVardhan** [comment]
Sorry, bad choice of words.
Square shaped vertices.
You represent them by circles usually

**Comment by ChetanVardhan** [comment]
![Screenshot from 2020-09-13 13-36-16](https://user-images.githubusercontent.com/51269425/93013445-261d3700-f5c6-11ea-8264-4bcd4ffc58cc.png)
Like, can I make something like this using LightGraphs?

**Comment by sbromberger** [comment]
LightGraphs is a graph analytic toolkit, not a visualization package. While other packages like GraphPlot.jl can plot the graphs generated in LightGraphs, LightGraphs itself is used to explore mathematical properties of graphs (collections of nodes connected via edges).

Off the top of my head, I don't know how you would represent the picture you posted in LG.

**Comment by ChetanVardhan** [comment]
Thank you for the info!
