### ISSUE TITLE
]up causes LightGraphs.jl to downgrade from 1.3.3 to 1.3.0

### ISSUE THREAD

**Issue by jaakkor2** [JuliaGraphs/LightGraphs.jl#1469]
Recently JuMP.jl updated DataStructures.jl compatibility to include 0.18. When upgrading with `]up`, update of DataStructures.jl from 0.17 to 0.18 caused LightGraphs.jl to downgrade to 1.3.0 since the is the last version with very sparse [compat] section
https://github.com/JuliaGraphs/LightGraphs.jl/blob/v1.3.0/Project.toml#L28-L29
vs
https://github.com/JuliaGraphs/LightGraphs.jl/blob/v1.3.1/Project.toml#L28-L33

**Comment by 4aHxKzD** [comment]
This seems to be the same issue as the one I opened on OpenStreetMapX, which depends on DataStructures.jl

_Originally posted by @pszufe in https://github.com/pszufe/OpenStreetMapX.jl/issues/35#issuecomment-691739915_

**Comment by pszufe** [comment]
It seems that the problem is with the `[compat]` section of Project.toml
```
[compat]
...
DataStructures = "0.17.11"
```
Maybe it would be a good idea to update it to something like 
```
DataStructures = "0.17.11, 0.18.6"
```

**Comment by sbromberger** [comment]
I don't have time right now to do the testing for this, so if someone wants to make a PR and show that changing the versions of our dependencies doesn't break anything, I'll be happy to review.

**Comment by rasmushenningsson** [comment]
Since this issue has been fixed (thanks!), would it be possible to make a new patch release?

**Comment by epatters** [comment]
Seconding this, it would be great to get a patch release with support for DataStructures v0.18.

**Comment by sbromberger** [comment]
I think we've resolved this. Please let me know if not.

**Comment by rasmushenningsson** [comment]
Thanks!

**Comment by jaakkor2** [comment]
A bit related about the ArnoldiMethod compat, please see https://github.com/JuliaGraphs/LightGraphs.jl/pull/1507.

On a new project
* `]add LightGraphs` gives LightGraphs v1.3.4, StaticArrays v0.12.5, ArnoldiMethod v0.0.4
* `]add StaticArrays`, `]add LightGraphs` gives LightGraphs v1.3.4, StaticArrays v1.0.1, ArnoldiMethod v0.0.2
