### ISSUE TITLE
Rough ETA for 2.0

### ISSUE THREAD

**Issue by jfb-h** [JuliaGraphs/LightGraphs.jl#1471]
Could you provide a very rough ETA for 2.0 or a brief update on the current state of the update? I'd appreciate it a lot as it would help me to decide whether to implement the 2.0 interface or the current one for a new project.

**Comment by sbromberger** [comment]
I'd use the current stable codebase. I don't have an ETA for a public 2.0 release.

**Comment by jfb-h** [comment]
I'll do that then, thanks for the heads up.

**Comment by sbromberger** [comment]
My pleasure.
