### ISSUE TITLE
How to transform a SimpleDiGraph into a SimpleGraph

### ISSUE THREAD

**Issue by wiz21b** [JuliaGraphs/LightGraphs.jl#1472]
Hello,

I write the issue here on GitHub because I didn't find any other channel to do so. I'm still super new to LightGraphs.

So here's some code : 
```
graph = loadgraph("/tmp/graph.txt", EdgeListFormat()) 
typeof( graph)
==> SimpleDiGraph{Int64}
```

I understand the resulting type. But in fact, my data represents a SimpleGraph. How can I load/transform the data from a SimplediGraph to a SimpleGraph ?

Thank!

**Comment by sbromberger** [comment]
You can created an undirected graph from a directed graph in your example above simply by doing `ugraph = Graph(graph)`:

```
julia> using LightGraphs
g = DiGraph(10, 20)                                      
julia> g = DiGraph(10, 20)                               
{10, 20} directed simple Int64 graph                     

julia> h = Graph(g)
{10, 18} undirected simple Int64 graph
```

**Comment by wiz21b** [comment]
Works as expected, thank you for your suggestion. It'd be nice to have a word about that in the documentation. If I gain enough experience on the subject, I'll give it a shot.

**Comment by wiz21b** [comment]
answer 100% satisfying.
