### ISSUE TITLE
Should we create a docs clearinghouse and what should it look like?

### ISSUE THREAD

**Issue by LovelyBuggies** [JuliaGraphs/LightGraphs.jl#1474]
Hello, LG maintainers:

Adding tutorials for LG is one of my GSoD tasks. Here's my conversation with @kshyatt:

> I: If I understand correctly, I'm expected to add tutorials for LG, and moreover, to create a tutorial template for the whole ecosystem. But I just realized why not make the central website look like this - https://turing.ml/. We could have those parts in the top bar: overview, packages, tutorials (including beginner guides), gallery (examples like matplotlib), and news.

> Kathie: That's something we'll need to discuss with the other maintainers too.

**Should we create a docs clearinghouse and what should it look like?**

**Comment by jpfairbanks** [comment]
Using Franklin.jl for an ecosystem wide page seems very useful. I think the turing page looks good.

**Comment by sbromberger** [comment]
@LovelyBuggies have you had any additional thoughts on this?

**Comment by LovelyBuggies** [comment]
Maybe it should look like this:

![](https://tva1.sinaimg.cn/large/0081Kckwgy1gm3cz5vbwoj31hc0u0mzs.jpg)

But I haven't work on it, yet. If urgent, I can discuss it with @kshyatt.

**Comment by sbromberger** [comment]
@LovelyBuggies - are you still working on this effort? Thanks.

**Comment by LovelyBuggies** [comment]
> @LovelyBuggies - are you still working on this effort? Thanks.

Nope. The mission has stalled for some time :(

**Comment by sbromberger** [comment]
Sorry to hear. I'll go ahead and close this out then.

**Comment by LovelyBuggies** [comment]
Okay, thanks!
