### ISSUE TITLE
[BUG] Installation not matching src

### ISSUE THREAD

**Issue by B4rtDC** [JuliaGraphs/LightGraphs.jl#1477]
**Description of bug**
The source code obtained after installing the package does not match the source code that is on GitHub in the master branch.

**How to reproduce**
On a clean Julia install: 
`] add LightGraphs`

**Expected behavior**
E.g. In the folder Community one would expect the following items:
```
Community
|-Community.jl
|-clique_percolation.jl
|-cliques.jl
|-clustering.jl
|-core-periphery.jl
|-label_propagation.jl
|-modularity.jl
|-triangle_count.jl
```

**Actual behavior**
For some unknown reason a different version is downloaded with the following structure:
```
Community
|-clique_percolation.jl	
|-clustering.jl		
|-label_propagation.jl
|-cliques.jl		
|-core-periphery.jl	
|-modularity.jl
```

The same goes for the other functionalities as well (e.g. centrality, traversals etc.)

**Code demonstrating bug**
This could lead to confusion as the "old" way of working is:
```
result = LightGraphs.label_propagation(graph)
```
versus the way it works in the current master source code:
```
result = LightGraphs.communities(graph, LabelPropagation())
```

**Version information**
`versioninfo()`:
```
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```
```
] status LightGraphs
Status `~/.julia/environments/v1.5/Project.toml`
  [093fc24a] LightGraphs v1.3.3
```

**Additional context**
* The current stable documentation is aligned with the code that actually is downloaded. 
* This behaviour can be avoided by adding the package directly from the GitHub link:
```
] add https://github.com/JuliaGraphs/LightGraphs.jl.git
```

**Comment by sbromberger** [comment]
This isn't a bug (if I'm understanding your report correctly). `]add LightGraphs` is adding the v1.3.x code, which is not separated into different modules, the way we've done for our 2.0 code in `master`.

If I've misunderstood the issue, please let me know.
