### ISSUE TITLE
SimpleGraph(ne, fadjlist::Vector{Vector{T}}) is exported

### ISSUE THREAD

**Issue by etienneINSA** [JuliaGraphs/LightGraphs.jl#1478]
`SimpleGraph(ne, fadjlist::Vector{Vector{T}})` is exported.

I think this is an internal constructor exported inadvertently by the very general `export SimpleGraph`

We should either not export it or :
- remove `ne` argument and deduce it from the adjacency lists
- check coherence of the adjacency lists (symmetry)
- hide the internal constructors with no coherence checks

Personally, I find having a constructor from the adjacency lists is very convenient in a number of cases, as it is closer from the internals, and we often get adjacency lists naturally when working with graphs.

**Comment by sbromberger** [comment]
That's the inner constructor for `SimpleGraph`. It's there for folks who know what they're doing and trades speed of construction for the lack of testing that the data are sound. Not sure we want to remove it.
