### ISSUE TITLE
Precompilation interferes with _HAVE_GRAPHMX

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/LightGraphs.jl#148]
I installed LightGraphs on a machine without GraphMatrices, and ran the following session:

```julia
Pkg.add("LightGraphs")
Pkg.test("LightGraphs")
# GraphMatrices is not installed warning
Pkg.add("GraphMatrices")
Pkg.test("LightGraphs")
# GraphMatrices is still not installed! WAT?!
```

I added a print statement to LightGraphs which forced a reprecompile so now it works.
I am not sure if it is worth fixing, but it is definitely worth posting so that people (myself included) don't have to figure it out again. Maybe a note in the warning to recompile after installing Pkg.add(GraphMatrices) is useful.

**Comment by sbromberger** [comment]
Yeah, that's an side effect of precompilation. Good idea re: warning. I'll add it now.
