### ISSUE TITLE
Unify versions of JuMP across JuliaGraphs

### ISSUE THREAD

**Issue by etienneINSA** [JuliaGraphs/LightGraphs.jl#1481]
LightGraphsMatching requires JuMP version 0.20
LightGraphsFlows requires JuMP version 0.21

So it is not possible to use them together.
Is it possible to make them compatible ?

**Comment by sbromberger** [comment]
Yes, but these are probably better as issues for those packages, since they have different maintainers.

**Comment by sbromberger** [comment]
It's probably feasible, but these are probably better as issues for those packages, since they have different maintainers.
