### ISSUE TITLE
How about a GraphTraits package?

### ISSUE THREAD

**Issue by Tokazama** [JuliaGraphs/LightGraphs.jl#1483]
LightGraphs does a great job of defining generic traits for graphs and then building on that. However, it's also a pretty large package and a large dependency. Are there any plans to make a package like GraphTraits.jl so that other light weight packages can be built on top of it?

**Comment by jpfairbanks** [comment]
I don't think anyone has that on their roadmap. The Project.toml for LG is pretty lightweight, was there a specific dependency you are having trouble with?

```
[deps]
ArnoldiMethod = "ec485272-7323-5ecc-a04f-4719b315124d"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Inflate = "d25df0c9-e2be-5dd7-82c8-3ad0b3e990b9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
```

**Comment by Tokazama** [comment]
Sorry, I didn't mean that LG had a lot of dependencies. I just meant that LG is large and is in of itself a large dependency.

**Comment by jpfairbanks** [comment]
Well, graph theory is a rich field and deserves a capable library to implement the algorithms that it has delivered.
