### ISSUE TITLE
Naming convention in LightGraphs and user API

### ISSUE THREAD

**Issue by bilelomrani1** [JuliaGraphs/LightGraphs.jl#1484]
Most functions in `LightGraphs` are named based on the algorithm running behind the scenes, and not necessarily on the semantic of the operation. This is not systematically an issue, but can have an impact on the user experience. Perhaps less subjectively, I find that this pattern creates some slight inconsistencies in the API of some functions. For instance, take the graph coloring functions. We have:
- `greedy_color(g; sort_degree=false, reps = 1)`
- `degree_greedy_color(g)`
- `perm_greedy_color(g, seq)`
- `random_greedy_color(g, reps)`

All of these functions does the same thing, and yet their signature is not unified, with heuristic-specific keyword arguments. They should not be the functions the end user interacts with. A suggestion is having a single function `color(g [, method])` with possible `method`
- `Greedy()`
- `DegreeGreedy(;sort_degree=false,reps=1)`
- `PermGreedy(seq)`
- `RandomGreedy(reps)`

Something like
```julia
color(g, Greedy())
```
which is akin to what Julians do in `DifferentialEquations.jl` when they say
```julia
solve(prob, Tsit5())
```
Here, heuristic-specific arguments go into the heuristic construct itself, leaving the signature of `color` simple and heuristic-independent. Note that `LightGraphFlows` somehow uses a similar pattern, but it is not consistently used throughout the codebase.

Another example would be minimum spanning trees algorithms: instead of `kruskal_mst` and `prim_mst`, we could have one function `minimum_spanning_tree(g [, method)` with possible values of `method`:
- `Kruskal()`
- `Prim()`

The naming of the method makes it clear what is computed, and “implementation details'' are deferred to a `method` object.

One last example (perhaps more problematic): shortest-paths algorithms. We have:
- `a_star(g, s, t[, distmx][, heuristic])`
- `dijkstra_shortest_paths(g, srcs, distmx=weights(g))`
- `desopo_pape_shortest_paths(g, src, distmx=weights(g))`
- `bellman_ford_shortest_paths(g, s, distmx=weights(g))`
- `bellman_ford_shortest_paths(g, ss, distmx=weights(g))`
- `floyd_warshall_shortest_paths(g, distmx=weights(g))`
- `yen_k_shortest_paths(g, source, target, distmx=weights(g), K=1; maxdist=Inf)`

Currently, the interfaces for each of these algorithms are slightly different because some of these algorithms work with multiple sources/targets. Here is an opinionated way of unifying those: we could by default compute all shortest paths for any source and target and letting the user provide an array of sources and/or targets through optional keyword arguments. We can expect the user to know (or better, document) under what regime a specific method is efficient (single-source/multiple-targets, single-source/single-target, etc.). We thus would have a unique `shortest_path(g [, srcs, tgts, distmx, method])`. Possible values of `method` are
  - `AStar([heuristic])`
  - `Dijkstra()`
  - `DEsopoPape()`
  - `BellmanFord()`
  - `FloydWarshall()`
  - `Yen(k=1 [, method])` I noticed that `dijkstra_shortest_paths` is currently hard-coded as a subroutine, I suggest leaving the choice to the user. Also, it is not clear from the documentation what `maxdist` is and if it should be part of the common interface or belong to the `Yen()` solver.

Are some of these suggestions interesting to LightGraphs developers?

**Comment by sbromberger** [comment]
> Are some of these suggestions interesting to LightGraphs developers?

They're not only interesting, but if you check out the master branch, you'll see we've already implemented them, pretty much exactly as you've described.

**Comment by bilelomrani1** [comment]
Oh wow, didn't think about checking `master` ^^ That's super cool, I quicky checked and `minimum_spanning_tree` does not seem to be interfaced yet, is it planned to do so?

**Comment by sbromberger** [comment]
I'll need to check whether it's been changed in my local repo. But for now I'll close this out since I'm trying to clean up the issues list for the new year. Feel free to continue the discussion, though!
