### ISSUE TITLE
Eval can be replaced by getfield in _parse_header

### ISSUE THREAD

**Issue by julbinb** [JuliaGraphs/LightGraphs.jl#1490]
`getfield` would be more efficient than `eval` in getting the value of a variable/type here:

https://github.com/JuliaGraphs/LightGraphs.jl/blob/aa7fc2cc94fe269c866cf17b3a950bd3d760c55b/src/persistence13/lg.jl#L66

Toy example:

```julia
julia> using BenchmarkTools

julia> @btime getfield(Main, Symbol("Int"))
  0.015 ns (0 allocations: 0 bytes)
Int64

julia> @btime eval(Symbol("Int"))
  58.841 ns (0 allocations: 0 bytes)
Int64
```

**Comment by sbromberger** [comment]
Nice; thanks for this! Would you mind preparing a PR?

**Comment by julbinb** [comment]
Ok, will do :)

**Comment by sbromberger** [comment]
@julbinb - did you want to create a PR for this?

**Comment by julbinb** [comment]
Ah, yes, thanks for the reminder!

**Comment by sbromberger** [comment]
No worries! I'm just trying to get some of these issues resolved. I can review a PR this week.

**Comment by sbromberger** [comment]
Oh, also - make sure you're preparing a PR against (the current) master. I think the file you originally looked at was part of a development cycle that was reverted.

**Comment by julbinb** [comment]
Done in #1537

Btw, it might be nice to move some test sets outside of the single enclosing test set. Currently, it's impossible to see any progress in testing until the very end.
