### ISSUE TITLE
[BUG] SimpleGraph and SimpleDiGraph ignore RNG

### ISSUE THREAD

**Issue by oisinfaust** [JuliaGraphs/LightGraphs.jl#1495]
When creating a random SimpleGraph or SimpleDiGraph with fixed seed/RNG, the seed/RNG is ignored if the number of edges `ne` exceeds `div((2 * maxe), 3)`.
I am using `[093fc24a] LightGraphs v1.3.3`, but I can see the issue is also present in master.

```Julia
julia> using LightGraphs

julia> SimpleGraph(5, 3, seed=1) == SimpleGraph(5, 3, seed=1)
true

julia> SimpleGraph(5, 7, seed=1) == SimpleGraph(5, 7, seed=1)
false
```
Similarly for 
```Julia
julia> SimpleDiGraph(5, 3, seed=1) == SimpleDiGraph(5, 3, seed=1)
true

julia> SimpleDiGraph(5, 17, seed=1) == SimpleDiGraph(5, 17, seed=1)
false
```

On master, the fix needed is in the file `LightGraphs.jl/src/SimpleGraphs/Generators/randgraphs.jl`: 
https://github.com/JuliaGraphs/LightGraphs.jl/blob/0871c15594736717de5722b4e793bf2487d9bb6a/src/SimpleGraphs/Generators/randgraphs.jl#L21
 should be 
```Julia 
ne > div((2 * maxe), 3)  && return complement(SimpleGraph{T}(tnv, maxe - ne, rng=rng))
```
and similarly
https://github.com/JuliaGraphs/LightGraphs.jl/blob/0871c15594736717de5722b4e793bf2487d9bb6a/src/SimpleGraphs/Generators/randgraphs.jl#L56
should be 
```Julia 
ne > div((2 * maxe), 3) && return complement(SimpleDiGraph{T}(tnv, maxe - ne, rng=rng))
```

**Comment by sbromberger** [comment]
Thanks. Confirmed. Are you able to make a PR for this?

**Comment by oisinfaust** [comment]
Yes, but as you might have seen I have not contributed to a Julia package before so it will take me a while to figure things out. I'll try to do it by the end of today.

**Comment by sbromberger** [comment]
Closing via #1500. Thank you.

**Comment by oisinfaust** [comment]
> Closing via #1500. Thank you.

No problem.
