### ISSUE TITLE
Add assortativity

### ISSUE THREAD

**Issue by heliosdrm** [JuliaGraphs/LightGraphs.jl#1508]
I would like LG to have a function to obtain the [assortativity](https://en.wikipedia.org/wiki/Assortativity) coefficient. I would be willing to contribute code myself to add that feature, if only for the "global" coefficients as defined in Newman's papers for [directed](https://arxiv.org/pdf/cond-mat/0209450.pdf) and [undirected](https://arxiv.org/pdf/cond-mat/0205405.pdf) graphs. So I would like to ask:

* Taking into account that there was a frustrated attempt to do this in #275, is there any reason besides that tests failed why this was closed and never resumed - in other words, a reason to refrain from submitting a new PR?
* LG has a big file structure. Where would the code for assortativity belong in?
* Any recommendation for writing the tests. I was planning to make a test for undirected graphs using [Callaway's grown graph model](https://arxiv.org/pdf/cond-mat/0104546.pdf), whose assortativity coefficient is formulated in [Newman (2002)](https://arxiv.org/pdf/cond-mat/0205405.pdf) and could be tested for different values of the δ parameter; and a test for directed graphs based on some of the examples with given values in [Newman (2003)](https://arxiv.org/pdf/cond-mat/0209450.pdf). Is that right? And where should I write the code for such tests?

**Comment by sbromberger** [comment]
cc @jpfairbanks 

Hi @heliosdrm - thanks. I think what might make sense is for you to review #275, and if you can reuse the code there, please do so.

As far as where it goes, I'm at a loss. I'm thinking that the coefficient might be more related to a centrality measure of some sort. Your thoughts on this? Otherwise, we could create a new assortivity.jl if there are other related assortivity functions you plan on creating.

Tests should be placed in `tests/` with the same file structure/names as where the code goes. As long as you have representative tests that cover each line of code, we should be ok.

Hope this helps. Thanks again.

**Comment by heliosdrm** [comment]
Thanks for the suggestions. I think that, rather than a centrality measure, assortativity might be considered a "community measure", since it describes to what extent the graph vertices are clustered depending on some similarity measure.

This is my proposal: create an `assortativity.jl` file in `Community`, with an `AssortativityAlgorithm` abstract type that defines how assortativity should be calculated. At the moment, the only available algorithm would be the Pearson correlation coefficient between a given measure that will be used to compare the source and destination vertices of each edge. This could be something like:

```julia
struct PearsonCorrelation{Ts, Td} <: AssortativityAlgorithm
    src_measure::Ts
    dst_measure::Td
end
```

The calculation would be done by a function such as `assortativity(g::AbstractGraph, alg::AssortativityAlgorithm)`. The default algorithm in undirected graphs would be `PearsonCorrelation(excessdegree, excessdegree)`, and in directed graphs it would be `PearsonCorrelation(excessoutdegree, excessindegree)`. Now, `excessdegree`, etc. would be internal functions based on `degree`, `indegree` and `outdegree` that discount one unit from the degree of connected vertices, as normally done in the calculation of assortativity.

**Comment by heliosdrm** [comment]
What branch should I use to make the PR? The interfaces of the various branches in the repo are very different.
