### ISSUE TITLE
Documentation broken for generators

### ISSUE THREAD

**Issue by mlhetland** [JuliaGraphs/LightGraphs.jl#1520]
The various graph generators have copious docstrings, and there is a section about them in the manual, but for some reason, it seems that there's a bug in the setup, so that the "Graph Generators" section only includes things like `add_edge!` etc. (which don't belong there).

Not sure how to fix, but I'd guess it should be straightforward?

**Comment by sbromberger** [comment]
Closing because I think we've fixed the bug that prevented documentation from building correctly.

Ref: https://juliagraphs.org/LightGraphs.jl/latest/generators/ and #1527

**Comment by mlhetland** [comment]
Looks good! Though I see now that the new Watts–Strogatz docstring has some Markdown issues (with a couple of minuses turning into bullet lists, and a headline ending up in a code block).

**Comment by mlhetland** [comment]
Created a quick PR (#1533) for the docstring errors.
