### ISSUE TITLE
Update Graphs GSoC Projects 

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaGraphs/LightGraphs.jl#1522]
Hey all, if there is still interest in mentoring GSoC students, we need to get the graphs projects here: https://julialang.org/jsoc/gsoc/graphs/ updated for GSoC 2021 asap.

There are new requirements for the projects found here: https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list including adding an (easy, medium, hard) rating for each project. Please read through that link and updated the projects as needed.

If you are no long able to mentor the project or the project has been completed, please open a PR to remove it. Thanks all!

**Comment by sbromberger** [comment]
Ref: https://github.com/JuliaLang/www.julialang.org/pull/1180
