### ISSUE TITLE
File Missing in Benchmark Suite?

### ISSUE THREAD

**Issue by olynch** [JuliaGraphs/LightGraphs.jl#1526]
In the benchmark suite, there are these lines of code that open "test/testdata/graph-5k-50k.jgz":

```julia
testdatadir = joinpath(dirname(@__FILE__), "..", "test", "testdata")
benchdatadir = joinpath(dirname(@__FILE__), "data")
paramsfile = joinpath(benchdatadir, "params.jld")

println("testdatadir = $testdatadir")
println("paramsfile = $paramsfile")

dg1fn = joinpath(testdatadir, "graph-5k-50k.jgz")

DIGRAPHS = Dict{String,DiGraph}(
    "complete100"   => complete_digraph(100),
    "5000-50000"    => LightGraphs.load(dg1fn)["graph-5000-50000"],
    "path500"       => path_digraph(500)
)
```

The problem is, there is no such file. What is going on here?

**Comment by sbromberger** [comment]
We don't really use the benchmark suite for anything (especially these days; it was left over from a pre-1.0 effort). What are you trying to do, exactly?

**Comment by olynch** [comment]
Well, I was copying off of it for benchmarks for Catlab; there isn't really a need for that specific file, but I thought you all might want to know that it was missing.

**Comment by sbromberger** [comment]
Thanks. We should probably just remove the benchmarking directory. @jpfairbanks - thoughts?

**Comment by jpfairbanks** [comment]
I'm pro-benchmarking in general and I'd rather see the benchmarks get integrated into CI. But that requires effort.

**Comment by sbromberger** [comment]
I am too, and I would too, but I don't have the cycles right now. If we can't find a taker, I think it'd be better to remove these from the master branch.

**Comment by sbromberger** [comment]
Closing since it appears we have movement on this! #1529
