### ISSUE TITLE
[BUG] fix build status badge on README.md

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#1530]
**Description of bug**
The build status badge is pointing to travis. We use github actions and should change the badge to point to GA.

https://docs.github.com/en/actions/managing-workflow-runs/adding-a-workflow-status-badge

**Comment by birm** [comment]
Which badge are you expecting? The nightly job? ![Nightly Build Status](https://github.com/JuliaGraphs/LightGraphs.jl/actions/workflows/ci-nightly.yml/badge.svg?branch=master)

**Comment by sbromberger** [comment]
@birm - Ideally, we'd have -stable, since -nightly is showing some type inference issues (ref https://github.com/JuliaLang/julia/issues/39673)
