### ISSUE TITLE
connected components ordering and singletons

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/LightGraphs.jl#154]
I noticed when writing tests for my new version of connected components that the old version does not produced the components in sorted order. The faster version does produce them in sorted order.

also the vertices without neighbors were not listed as singleton components by the old version.
The new version gives them as singleton Vectors

**Comment by sbromberger** [comment]
> also the vertices without neighbors were not listed as singleton components by the old version.
The new version gives them as singleton Vectors

I think you've got the correct behavior, though this will limit any development where we just treat the underlying storage (sparsemx) as a blank canvas. If you're ok with that then let's do it.

**Comment by jpfairbanks** [comment]
I suppose we could let the lower level functions give back the label array like it does and then have the function that carves the label array into a `Vector{Vector{Int}}` just ignore singletons. This will match the existing behavior.

**Comment by sbromberger** [comment]
In your opinion, what's the more correct way to do it?

**Comment by jpfairbanks** [comment]
I think the correct way to do it is to give people back an array a such that `a[i]=component number of v_i`
then give them a function that allows that breaks it up into a Vector{Vector{Int}} b where b[i] = {v_j | v_j in component i}. That function can give them the singletons. We don't really need to worry about the performance of that function because if you want to go faster then you can just use the array a instead of b.

The function is called components and I put it in the tests (so that it wouldn't hurt coverage) https://github.com/JuliaGraphs/LightGraphs.jl/pull/153/files#diff-b5350579ff9d3ce5fb74d232af29a98eR19

By making the default use the lower level interface it will encourage people to write more performant code.

**Comment by sbromberger** [comment]
Closing out due to merge of #153.
