### ISSUE TITLE
Why there is no Vertex type but an Edge type?

### ISSUE THREAD

**Issue by liuyxpp** [JuliaGraphs/LightGraphs.jl#1550]
I'd like to implement functions that can be easily dispatched based on the type of argument which is either vertex or edge. Currently, the type of vertex is simply Int64 and I am afraid it is ambiguous to dispatch on Int64 instead of a dedicated type for the vertex. Does this thought make sense?

**Comment by liuyxpp** [comment]
I have some very specific use cases. Suppose I have a tree, I want to obtain two induced subgraphs by either specifying an edge to cut through or a vertex to split. For example:
```
1 - 2 - 3 - 4
    |   |
    5   6 - 7 - 8
```

by cutting through edge (3, 6), I expect to obtain
```
1 - 2 - 3 -4
    |
    5
```
and
```
6 - 7 - 8
```

By splitting at vertex 3, I expect to obtain
```
1 - 2 - 3
    |
    5
```
```
3 - 4
```
and
```
3 - 6 - 7 - 8
```

**Comment by liuyxpp** [comment]
I see. However, then `T <: Integer`, which I think is not so specific for graph operations. If we can do this, why not remove Edge type and simply use `Tuple{T, T}` instead?

BTW, for Edge type, I found it is not indexable and this is a little inconvenient. For example, I cannot do
```
v1, v2 = Edge(1, 2)
```
But in a more cumbersome way
```
e = Edge(1, 2)
v1, v2 = e.src, e.dst
```

**Comment by sbromberger** [comment]
> why not remove Edge type and simply use Tuple{T, T} instead?

We originally did exactly this. But it was important to understand the idea of a directed edge, and we wanted our own iterator, so we made it an explicit struct. Also, some edges carry weights.

> `v1, v2 = e.src, e.dst`

Don't do this. In LightGraphs, we don't use fields, we use accessors:

```
v1, v2 = src(e), dst(e)
```

Explicit is better here, because again - some edges might have weight information, or other metadata.

**Comment by sbromberger** [comment]
Also:

> However, then T <: Integer, which I think is not so specific for graph operations

This is only true for SimpleGraphs. You can implement your own graph type and as long as your vertex indices can be represented by a `1..n` range, you can do whatever you want.

**Comment by liuyxpp** [comment]
> v1, v2 = src(e), dst(e)

`src` and `dst` are so common that I am afraid of name collisions. Is there any particular reason to not do `v = e.src`?

**Comment by sbromberger** [comment]
> Is there any particular reason to not do v = e.src?

Because we made a decision in LightGraphs that field access is not part of the API. This way we can change the intervals without breaking the API contract.

**Comment by sbromberger** [comment]
I'll close this out since I think it's been resolved, but feel free to continue the discussion if it's not and I'll reopen. Thanks.
