### ISSUE TITLE
Topological sort function is missing

### ISSUE THREAD

**Issue by majsterkovic** [JuliaGraphs/LightGraphs.jl#1563]
Hi!
Is there any function to print nodes in topological order?
It may be based at DFS or Kahn algorithm.

````julia
topological_sort(g)

**Comment by sbromberger** [comment]
Try `topological_sort_by_dfs`.

**Comment by fpmenninger** [comment]
Please add this to the documentation.
(A search in the docs for 'topological' gives no results.)
Thank you.
