### ISSUE TITLE
[FR] add core functions

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaGraphs/LightGraphs.jl#1567]
It would be nice to have a `degree` property that has a more performant implementation than
`degree(v) = length(neighbors(graph, vertex))`

**Comment by sbromberger** [comment]
The current implementation is O(1). What are you suggesting could be more performant?

**Comment by sbromberger** [comment]
Here's a demonstration:
```
julia> g = star_graph(10_000_000)
{10000000, 9999999} undirected simple Int64 graph

julia> @btime degree(g, 1)
  16.663 ns (1 allocation: 16 bytes)
9999999

julia> h = Graph(1)
{1, 0} undirected simple Int64 graph

julia> @btime degree(h, 1)
  14.319 ns (0 allocations: 0 bytes)
0
```

**Comment by BeastyBlacksmith** [comment]
aha, I just missed that function from the documentation.
I'll make a PR

**Comment by sbromberger** [comment]
`degree()` is in the documentation: https://juliagraphs.org/LightGraphs.jl/latest/core/#LightGraphs.degree

**Comment by BeastyBlacksmith** [comment]
Thats true, but I expected it to find it among the vertex properties and in hindsight it was a bit silly to stop searching when I didn't find it there, but others might do the same

**Comment by sbromberger** [comment]
I think a better PR would be to ensure "Core Functions" is a sidebar item. I'm not generally inclined to have multiple references to functions in the documentation. That gets confusing and pollutes search results.

**Comment by BeastyBlacksmith** [comment]
Also a good idea. Changed that
