### ISSUE TITLE
adjacency matrices are technically incorrect.

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#157]
Adjacency matrix values for self-loops should be 2, not 1. Easily fixed in the old code, need to find an efficient way of doing it for sparse matrices.

**Comment by sbromberger** [comment]
https://gist.github.com/sbromberger/fada2265bfc92b98c981

cc @jpfairbanks

**Comment by jpfairbanks** [comment]
We had a chat about this issue over gist: https://gist.github.com/sbromberger/d98e48a52aa69418c8bc
cc @sbromberger

**Comment by sbromberger** [comment]
I think I got this fixed in the `v4` branch here: #169 .Will keep it open until confirmed.

**Comment by sbromberger** [comment]
Yup, this is fixed.
