### ISSUE TITLE
The getting started section has disappeared from the docs

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGraphs/LightGraphs.jl#159]

**Comment by sbromberger** [comment]
@hayd any ideas? I tried rebuilding to no effect.

**Comment by hayd** [comment]
Yeah, this is a typo https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/mkdocs.yml#L8

**Comment by sbromberger** [comment]
Thanks. I can't believe I missed that. Fixing now.
