### ISSUE TITLE
Slow to create large sub-graphs?

### ISSUE THREAD

**Issue by mkhorton** [JuliaGraphs/LightGraphs.jl#173]
Hello,

I'm trying to create large sub-graphs efficiently. I'm not sure if I'm doing this in the correct way (I'm personally new to Julia), but it seems very slow at present?

e.g.

    using StatsBase
    using LightGraph
    g = Graph(1000000)
    m = sample(1:1000000, 200000, replace=false)
    @time g[m] # also tried induced_subgraph(g,m)

For some benchmarks on my machine (Julia 0.4.0):

    length(m)    @time
    300000       329.899664 seconds (900.20 k allocations: 86.183 MB, 0.04% gc time)
    200000       145.917879 seconds (600.19 k allocations: 64.346 MB, 0.06% gc time)
    100000       38.010782 seconds (300.17 k allocations: 30.509 MB)

Is there any way to speed this up? I'm asking for a general problem with lots of edges, but even in this simple case with no edges, this seems far too slow.

I just tried writing my own naive function and tried it on one of my real graphs with lots of edges (e.g. 262144 vertices, 786432 edges):

    new_g = Graph(length(m))
    map = [m[i] => i for i = 1:length(m)]
    for edge in g.edges
        try
            new_source = map[e[1]]
            try
                new_destination = map[e[2]]
                add_edge!(new_g, new_source, new_destination)
            end
        end
    end

This seems like a terrible function, and it does run *much* much slower for small sub-graphs, but it gives the same result (`g[m]==new_g`) and seems to scale far better, e.g. for selecting a random sub-graph containing half the original vertices of my {262144, 786432} graph, the standard way takes about 10 minutes, and my naive function above takes about 30 seconds. It actually gets faster as the size of my subgraph gets larger (presumably because fewer of those `try` statements fail). For large random sub-graphs (e.g. 90% of the vertices in the original graph), the naive function takes about 7.5s while the standard way never seems to actually finish. 

Thanks for any help, and apologies if this is the wrong place to ask!

**Comment by sbromberger** [comment]
You're in the right place to discuss this. That does seem slow. I thought we had done a good job with subgraphs, but perhaps not. I'll test and update this comment when I know more.

**Comment by sbromberger** [comment]
OK, I think I've gotten it to reasonable performance. Using the zero-edge graph above,

```
julia> @time z = g[m];
  0.124825 seconds (426.34 k allocations: 60.033 MB)
```

Using the pgp2 graph from the testdata directory with `length(m)` = 30000,

```
julia> @time z = g[m]
  0.134717 seconds (148.20 k allocations: 22.637 MB, 5.13% gc time)
{30000, 173104} directed graph
```

Let me test for correctness (it's passing all tests, but I want to be extra sure), but I'm hopeful we've fixed it.

**Comment by mkhorton** [comment]
Amazing, thank you kindly for the prompt response and fix.

**Comment by sbromberger** [comment]
Also see https://github.com/JuliaLang/julia/issues/13675

**Comment by sbromberger** [comment]
@mkhorton - if you wouldn't mind, please try the "hotfix-intersect" branch and let me know whether it's producing expected (and faster) results for you? Thanks.

**Comment by mkhorton** [comment]
I can confirm that it works great–when choosing a subgraph made up of 50% vertices at random from one of my actual graphs, it now completes in less than 0.5s vs. minutes previously, and when choosing 90% vertices at random, it now takes 1.5s whereas it didn't even complete previously, so there's a huge speed-up. I can also confirm that the resulting graph in the 50% case is identical to the slower, previous version of the code, and in both the 50% and 90% case it gives identical output to my naive function above, so it seems correct to me. Thanks again!

**Comment by sbromberger** [comment]
Thanks for your help in reporting this and verifying the fix. I've merged it into master.
