### ISSUE TITLE
length(graph)

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/LightGraphs.jl#177]
What should the length of a graph be? It looks like it is nv^2. Why is that?

**Comment by sbromberger** [comment]
IIRC, it was to give the graph array-like properties. Since the graph can be constructed as a dense array of size `(nv, nv)`, this made sense. Should we reconsider?

**Comment by jpfairbanks** [comment]
That's what SparseMatrix does. When in doubt be consistent.
