### ISSUE TITLE
Metadata outside of LightGraphs.jl

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/LightGraphs.jl#179]
I felt that PR #163 had gotten off topic so I'm opening up this discussion issue.
cc @CarloLucibello @sbromberger.

### LightGraphs.jl current state and goals

I think that it is a good decision to focus on the core graph data structure, traversal, classic graph problems, and modern graph analysis. That is enough of a task for one package. As Graphs.jl shows us, there are quite a few ways to implement graphs. There are many more ways to implement metadata containing graphs. Networkx implemented their graphs in the most flexible way possible. In Networkx everything is a Dict{Any, Any} so you can store whatever metadata you want anywhere. This leads to significant performance problems.

I agree with @sbromberger's diagram about the tradeoffs between performance, simplicity, and flexibility. Since LightGraphs aims to be in the simple and performant part of the space, excluding metadata from the internal graph structure is a sound policy.

### For supporting metadata outside of the graph data structure. 

However, I think that if someone wants to use a LightGraphs.Graph and attach metadata to it in some external package; we should be supportive of that, without "supporting" it. 

A data structure that looks like:
```julia
type Network{G<:LightGraphs.SimpleGraph, TE, TV}
g::G
edgemeta::Dict{Edge,TE}
vertmeta::Dict{Int, TV}
end
```

should work fine and a `Networks.jl` package could easily support this definition.
The traversal functions in LightGraphs are flexible enough to allow you to reuse quite a bit of the code while adding support for using the metadata in the traversals.

1. While not standard usage, like the idea of a graph being just the sets `G=(V,E)` and a network as a graph with some metadata about the vertices and edges.
2. `Networks.jl` exists, but the top google hit is a github repo with 3 commits last updated 3 years ago.

### Weights work somewhat like this
Some functions that work with edge weights or distances take a graph and a distance matrix. For example, `dijkstra_shortest_path`.
```julia
function dijkstra_shortest_paths{T}(
    g::SimpleGraph,
    srcs::Vector{Int},
    distmx::AbstractArray{T, 2}=DefaultDistance();
    allpaths=false
)
```
One could formalize this pattern in a type,
```julia
type DistGraph{G<:LightGraphs.SimpleGraph, D}
g::G
distmx::AbstractMatrix{D}
end
```
then use metaprogramming to define methods for all of the functions in LightGraphs to pass them either just g, or g and distmx.

These are my thoughts on the matter. I'm not trying to start a debate. I just think it is good to get our thoughts out there so that people understand how decisions are made on these issues. What do you think?

**Comment by sbromberger** [comment]
@jpfairbanks thank you for starting this discussion (outside of the PR). It's a good one to have. Your thoughts, incidentally, mirror mine, and your proposed code is quite close to what I used for a project in which I needed to store metadata related to vertices (haven't needed edge metadata yet).

Also conveniently, your description and proposal is how I envisioned LG: fast, efficient algorithms operating on core graph structures as a base for more complex structures as necessary.

I'm all for creating add-on packages that use LG as the core. That's what it's there for.

**Comment by sbromberger** [comment]
PS: there appear to be two Networks.jl repos:

https://github.com/pranavtbhat/Networks.jl and
https://github.com/daviddelaat/Networks.jl

The latter is graph-related (the other is node.js stuff) and is the one that hasn't been active recently.

**Comment by CarloLucibello** [comment]
I totally agree with the goals for LightGraphs exposed above, and the whole point of my PR was to make LightGraphs even more "core" than it is now.  

Also having a LG as a member is a cleaner design decision than calling a LG constructor  for each Network's functions call (as I was envisioning the thing before).

Two very minor notes: 1) the edge set in LG could create some redundancy with the edge dict in Network, but, in the end, it is not really important. 2)  Present LG structure doesn't allow for multi edges: this is a limitation that maybe could be avoided eliminating the edge set, but would also require to introduce edge indexes. 

I think it would be a good idea to start a repo Networks.jl under the JuliaGraphs umbrella, if any of you is interested, so that this doesn't not become another short living personal project.

As a start it would be good to implement the really simple type

```julia
type Network{G<:LightGraphs.SimpleGraph}
g::G
end
```
and to implement the method passes to LG though metaprogramming as James proposed. I could do that in the next weeks, although I haven't ever done any metaprogramming in julia, so it could take some time.

**Comment by sbromberger** [comment]
We will not be supporting multiedges, @CarloLucibello . LightGraphs is for [simple graphs](https://en.wikipedia.org/wiki/Graph_(mathematics)#Simple_graph) only. The *only* deviation we've made was for self-loops, and even that has residual problems (see #157 for the latest).

**Comment by jpfairbanks** [comment]
As a question to help understand the case for multiedges @CarloLucibello: When do you want to use multiedges? Why can't you combine the edges into a single weighted edge?

**Comment by CarloLucibello** [comment]
I don't need multiedges, and hopefully will never need, I was just stating a limit of LightGraph. I can imagine that in some applications one can get away with it using an edge weight, in others different edges between the same two nodes express different relationships, and one wants to add and remove them idependently from the others.

**Comment by sbromberger** [comment]
Do we want to keep this issue open, or can we close it out (but keep discussion going)? I don't know what the end game is/should be here.

**Comment by jpfairbanks** [comment]
Let's deal with multiedges when someone really needs it. For now we should put a simple v0.0.0 Networks.jl in metadata.jl by creating a repo with the types proposed above

**Comment by jpfairbanks** [comment]
@sbromberger I don't have permission to make a repo under JuliaGraphs.

**Comment by CarloLucibello** [comment]
+1

**Comment by sbromberger** [comment]
https://github.com/JuliaGraphs/Networks.jl
