### ISSUE TITLE
decision: make mincut() return induced subgraphs?

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#180]
Right now, mincut returns a vector of booleans and the cut cost. I'd like to explore whether it makes more sense to return two induced subgraphs indicating the partitions instead of the vector of booleans. It will be an easy change to make, but are there any obvious drawbacks here?

Memory might be one. A boolean vector of length n takes up n bytes.

**Comment by jpfairbanks** [comment]
Either way we should definitely keep the version returning a vector of Bool. The memory is worth saving.

**Comment by sbromberger** [comment]
OK. Closing out.
