### ISSUE TITLE
WIP: Datasets

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#186]
Now that we've got our own github org, it may make sense to move smallgraphs out from LightGraphs and into its own module. The graphs are reasonably stable (despite an enhancement we made last week - see #178 / #181 ). Ref #185 for additional discussion.

Two approaches:

1) keep Smallgraphs as a submodule of LightGraphs (similar to how @andrewcooke does ParserCombinator)
2) move Smallgraphs into its own peer package.

I'm leaning towards 1). The submodule would be inextricably linked to LightGraphs, since we're calling `unsafe_add_edge!()` which is unlikely to exist in other graphs packages. Plus, we need smallgraphs for tests, so we'd have to REQUIRE smallgraphs in any case.

Thoughts?

**Comment by jpfairbanks** [comment]
I am in favor of fewer repos so that it is easier to manage the dependencies.

**Comment by sbromberger** [comment]
cc @CarloLucibello would love your input here.

**Comment by CarloLucibello** [comment]
I would find convenient a github repo or some other place where to keep small/medium/large graphs  in some format, just the plain datafiles, with no julia code at all.

graph-tool for instance mantains a nice graph collection, altough it comes with library, and stores them in a binary format:
https://graph-tool.skewed.de/static/doc/collection.html

In any case I'm also in favor of a submodule,  I don't see the point of having a separate package for SmallGraphs

**Comment by sbromberger** [comment]
I think we're agreed, then:

1) split smallgraphs into its own submodule
2) integrate #185 
3) work on a larger dataset repository

**Comment by sbromberger** [comment]
I think we should rename "smallgraphs" to something else: since we've decided to make this a submodule, there's nothing that would preclude us from adding larger graphs. Bikeshed on new name, please.

**Comment by jpfairbanks** [comment]
My free form poetry: TestGraphs, Constructions, GraphData,
LightGraphs.DataSet as analogous to RDatasets. LightGraphs.Data if you want
the fully qualified name to make sense.

James Fairbanks
PhD Candidate
Georgia Tech

**Comment by sbromberger** [comment]
I like DataSets (note plural). I also appreciate your poetry, but prefer haiku:

TestGraphs, Constructions;
GraphData, LightGraphs.Data.
LightGraphs.DataSet.

**Comment by CarloLucibello** [comment]
+1 for DataSets and GraphData

**Comment by jpfairbanks** [comment]
+1 for haiku. Between @carlolucibello options I prefer Datasets. That way the fully qualified name is Lightgraphs.Datasets which is less redundant than Lightgraphs.GraphData. Also lowercase s iff you think dataset is one word.

**Comment by sbromberger** [comment]
Sounds like we have consensus: `Datasets` it is.

**Comment by CarloLucibello** [comment]
The storage form should also be discussed. Since so many graph formats are already around, I would suggest not to rely on a custom format but using orn of the existing ones. Since LG has a simple graph structure, I think that DOT format or pajek NET format are the ideal ones. 

[Here](http://gephi.github.io/users/supported-graph-formats/) there is a good comparison of many formats

**Comment by sbromberger** [comment]
The advantage of using the native LG format is that it's super compact and doesn't rely on any third party packages to use (DOT relies on ParserCombinator, which is an awesome package, but this introduces some additional fragility). We don't have a parser for Pajek NET at all yet so that's sort of moot.

If you look at the [format of the native LG file](https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/persistence/default.jl#L1-L10), you'll see that it can easily be translated to something else, and that you can't really get more compact and simple.

If we're going to keep this as a submodule, I'd really like to use the native format.

**Comment by jpfairbanks** [comment]
Perhaps LightGraphs.Datasets should include functions for accessing datasets from the standard places, SNAP, UF-Sparse, Konnect...

We just need to curate a list of URLs, probably by using a script to parse the index of each collection. Also a function to convert from the representation used by the repo to a format supported by LightGraphs. I have use MatrixDepot to access SNAP and UF-Sparse myself and it is a good example of what we are trying to do perhaps depending on MatrixDepot and just storing the adjacency matrices is the right path.

Depending on another library for the parser, especially for a format as complicated as dot, seems risky; however, rolling our own format reminds me of https://xkcd.com/927/. 

For the worries about the repo size growing: git large file storage is now supported by github. https://github.com/blog/2069-git-large-file-storage-v1-0
This does require some extra installation for people to use. We could always use LFS to store the files and add a script to download them manually for people who don't want to use the git-lfs software.

**Comment by sbromberger** [comment]
It's not the repo size on GitHub that I'm particularly worried about; it's the size of the entire bundle that folks will have to download in order to use LG, especially if they're not planning on using canned graphs. I really like the idea of accessing datasets remotely, and now that JuliaWeb has shown some major progress, I think we can do it without too much fear of breakage/instability.

I understand about competing standards, but the LG isn't intended to be a standard. It's the most efficient* internal representation of LightGraph objects, and it requires no external modules. Find me a standard format that's efficient, easy to edit manually, and can be coded without dependencies, and I'm happy to ditch LG format and use that exclusively.

(* especially when gzipped, which they are by default.)

**Comment by CarloLucibello** [comment]
>Find me a standard format that's efficient, easy to edit manually, and can be coded without dependencies, and I'm happy to ditch LG format and use that exclusively.

actually I cannot manage to open .jgz  files. My systems correctly recognizes them as gzip archives, but fails to open them with the graphical utility. From the shell I get
```
[carlo@x1 testdata]$ gzip -d tutte-pathdigraph.jgz 
gzip: tutte-pathdigraph.jgz: unknown suffix -- ignored
```
and no file is extracted

**Comment by sbromberger** [comment]
`gzcat tutte-pathdigraph.jgz > outfile.txt`

**Comment by CarloLucibello** [comment]
is it possible to have a compression such that one can view edit the files with a couple of double clicks?

I think that the pajek NET format would be the format to use, since it is widely supported, allows for storage of vertex and edge properties, it's compact, readable and easy to edit. Also, compression is desiderable but can be done for any file format.

On the other hand i don' t want to be stubborn on this since the decision is not that strategic and can be eventually easily reverted. So let's proceed with .lgz.

Should I close my pull request #185?

**Comment by sbromberger** [comment]
The "double click" issue is entirely with the tool you choose to use. On OSX, for example, I've configured my system to recognize .jgz. We can always change the file suffix to ".gz" if that's posing a problem.

Let's close #185 pending a new one that implements what we've discussed here.

**Comment by sbromberger** [comment]
@jpfairbanks can you give an example of an external repo you'd like to see so we can use it for initial implementation/inclusion?

**Comment by jpfairbanks** [comment]
http://snap.stanford.edu/data/index.html
http://konect.uni-koblenz.de/networks/
http://www.cise.ufl.edu/research/sparse/matrices/groups.html

**Comment by sbromberger** [comment]
OK. See #250 and also https://github.com/JuliaSparse/MatrixMarket.jl/pull/14 for some works in progress.
