### ISSUE TITLE
Docs should report time complexity for each function

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGraphs/LightGraphs.jl#189]
See https://graph-tool.skewed.de/static/doc/clustering.html and http://igraph.org/c/doc/igraph-Generators.html#igraph_adjlist for good documentation examples. 

Should we consider to have some guidelines for docs formatting?

**Comment by sbromberger** [comment]
Couldn't hurt. Note that the docs are generated from docstrings and docs/build.jl.

Pinging @hayd since he's our docmeister right now. :) Any updates re: https://github.com/JuliaGraphs/LightGraphs.jl/pull/164#issuecomment-146303175 ?

**Comment by hayd** [comment]
Well, I'm giving 10 minute talk at the SF meetup on Thursday. I have some slides... but it's still very much WIP (I don't have thaat much time this week but hopefully can get something working).

I think the "proper" way to do it with Docile's rewrite branch is to create a complexity "hook" (maybe a different term) and then create some render methods for displaying that. You can probably then have a test to ensure that every function (\*) has the complexity section in the docstring. A simpler way is just be a list of the different possible complexities => methods the function has.

\* There is an issue here that complexity is *per* method, rather that per function (IIUC docstrings are very much per function now), so it becomes somewhat more difficult how to show that (without being very confusing)....

**Comment by sbromberger** [comment]
I'm very sorry I won't be able to make the meetup, @hayd – I saw you were speaking!

As far as complexity and docs being per-function, no worries. We can issue caveats inside the docstrings: "if you call foo with ints, you get O(1), with dicts, you get O(n)" or something like that.
