### ISSUE TITLE
neighbors should return a copy of adjlist

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGraphs/LightGraphs.jl#197]
... or at least docs shoud warn against modifications of the returning value, it could be really dangerous

**Comment by jpfairbanks** [comment]
It should not return a copy because then you are wasting ton of time copying memory for no reason. The docs should be updated.

**Comment by CarloLucibello** [comment]
In C++ I would have `neighbors` return a const reference, it really annoys me that julia lacks this feature

**Comment by sbromberger** [comment]
Yeah, this is one of those tradeoffs we have to make. Good point about adding to docs.
