### ISSUE TITLE
Add graph products to operators.jl

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGraphs/LightGraphs.jl#199]
and I just discovered that there are many of [them](https://en.wikipedia.org/wiki/Graph_product)

**Comment by jpfairbanks** [comment]
#236 adds a version where one operand is the path graph. It was easier to implement just that use case which I needed for my research.

**Comment by CarloLucibello** [comment]
I have implemented tensor_product and cartesian_product, I was just waiting out of laziness for some of my PR to be merged, since I implemented it on those branches. Is your crosspath one of the two (tensor/cartaesian)?

**Comment by sbromberger** [comment]
@CarloLucibello what PR are you waiting on?

**Comment by jpfairbanks** [comment]
it is cartesian

**Comment by CarloLucibello** [comment]
I was waiting for rem_vertex, but I cannot find the PR anymore. What happened?

**Comment by sbromberger** [comment]
@CarloLucibello I think it was in https://github.com/JuliaGraphs/LightGraphs.jl/pull/217 that I closed because it needs some major rebasing :)

**Comment by CarloLucibello** [comment]
I rebased in #238

**Comment by sbromberger** [comment]
@CarloLucibello - `rem_vertex!()` was merged in #242... are you still waiting on me for something?
