### ISSUE TITLE
add_edge! without error on duplicate

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/LightGraphs.jl#20]
Is there a performance benefit to saying for some applications we won't check if the edge already exists? the two possible semantics are: 

- you insert a duplicate edge and nothing changes, you don't see an error.

- you insert a duplicate and it gets appended to the incidence list, when iterating over `out_neighbors(g,v)` you see the duplicate edges twice.

Do these lead to difficulties later?

**Comment by sbromberger** [comment]
I made an early decision to error on duplicate add_edge! in order to keep things a bit sane (and to avoid the appearance of multigraphs). We could get rid of the error, but we'd still have to check `has_edge` prior to insertion because, while `edges` is a set, the incidence lists are not.

I think that creating duplicate edges in incident lists will break a bunch of stuff - certainly would not be ideal.

**Comment by sbromberger** [comment]
@jpfairbanks ok if I close this out or should we continue discussion?

**Comment by jpfairbanks** [comment]
I would like to know how much added time is taken by being safe.
I can imagine someone knowing a priori that the edges they are about to add are not already in the graph and thus wanting to skip the check. Similar to how `@inbounds` allows you to avoid the bounds check when you know that you won't read off the end of the array. I would like to know the cost of being safe before we close the issue. Although it is definitely not a priority for me at the moment.

**Comment by sbromberger** [comment]
It's a call to `has_edge`, essentially (though for some reason it's expanded in `add_edge!` - this should probably be changed). This is an set membership test since `Graph.edges` is a set, hence O(1) (see https://groups.google.com/forum/#!topic/julia-dev/_2bF02Kp1fQ).

**Comment by sbromberger** [comment]
I'm going to close this out since we've got other priorities at the moment. Feel free to reopen if you'd like to continue the discussion, though.

**Comment by sbromberger** [comment]
I am reopening this since we have an opportunity to do a really neat thing with sorted fadjlists that would make one of @jpfairbanks' first requests a reality. :)

**Comment by sbromberger** [comment]
Closed via #232.
