### ISSUE TITLE
clustering coefficients returning numerator and denominator seperately

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/LightGraphs.jl#200]
The PR #198 provides functions that compute local and global clustering coefficients. In the past, I have found it helpful to have both the number of triangles and the number of wedges separately. Since the algorithms compute both numbers and then divide, it would be nice to have a function return a tuple `(num_triangles, num_wedges)`.

The `local_clustering` function could compute the number of triangles and number of wedges for each vertex and the `local_clustering_coefficient` and `global_clustering_coefficient` functions could return the appropriate ratios. 

One example of using the both numbers separately is plotting them against each other to see what relationship there is between them. Or plotting them both against some third variable you expect to have predictive power.

**Comment by sbromberger** [comment]
Given that the PR hasn't been merged yet, perhaps we move this (very valid) discussion there?

**Comment by CarloLucibello** [comment]
seems I good idea, I'll modify the PR

**Comment by CarloLucibello** [comment]
@jpfairbanks what should be the return type of 
`local_clustering(g::SimpleGraph, v = vertices(g))` ?

a vector of tuples or two vectors? Maybe the second form could be more convenient, and the first one  could be easily obtained by the user using `[local_clustering(g, i) for i=1:nv(g)]`

**Comment by jpfairbanks** [comment]
Two vectors makes it easy and fast to get the ratios. My most common use
case will be to pass the return values to some statistical functions like
mean, median, correlation. Definitely two vectors makes it easier for me.

**Comment by sbromberger** [comment]
Closing out since we just merged #198. Feel free to reopen if needed.
