### ISSUE TITLE
v0.3.5 broke on Julia 0.3?

### ISSUE THREAD

**Issue by IainNZ** [JuliaGraphs/LightGraphs.jl#203]
http://pkg.julialang.org/logs/LightGraphs_0.3.log

**Comment by sbromberger** [comment]
Thanks, @IainNZ - I don't know how to merge the hotfix into v0.3.5 - it's a tag, not a branch. Any ideas?

**Comment by tkelman** [comment]
you should check out the last 0.3 compatible commit and create a branch from it

**Comment by sbromberger** [comment]
@tkelman - I did - the branch is called "hotfix". I don't know where to merge it now, though.

**Comment by sbromberger** [comment]
ok, I got it - 0.3.6 tagged.

**Comment by sbromberger** [comment]
Fixed via ca79aabfc81fa16cb838ccf147369bbfd59d08e7
