### ISSUE TITLE
compactify README?

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGraphs/LightGraphs.jl#208]
since it is becoming a little lenghty. Like having

- distance
  - eccentricity, diameter, periphery, radius, center

instead of

- distance
  - eccentricity
  - diameter
  - periphery
  - radius
  - center

**Comment by sbromberger** [comment]
Yes: even better,

* **distance**: eccentricity, diameter, periphery, radius, center

I can do this via direct edit.
