### ISSUE TITLE
Nonbacktracking operator without explicit construction

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/LightGraphs.jl#209]
Many things the non-backtracking operator is used for can be done with iterative solvers instead of direct solvers. I am thinking of detecting graph structures from the eigenvalues and eigenvectors or from solutions to `Mx=b` where `M` is the non-backtracking (NBT) operator. @CarloLucibello are you planning to do something with the NBT operator that needs the explicit matrix? Since some things can be done without it, we should add a function to return a `GraphMatrices.GraphMatrix` that represents the NBT operator. This would reduce storage costs from `nv(g)ne(g)` to `2ne(g)` and allow iterative solvers to answer these questions.

**Comment by CarloLucibello** [comment]
I'm not familiar with GraphMatrix, so modify the NBT and the related function for community detection, that necessitates the first `k` eigenvectors,  at your pleasure

**Comment by jpfairbanks** [comment]
Hey @CarloLucibello, which NBT eigenvectors do you want for community detection? Right now the code doesn't specify and is using the arpack default of Largest Magnitude, which can have negative real components.

**Comment by jpfairbanks** [comment]
Also how do you want to interpret complex values eigenvectors?

**Comment by jpfairbanks** [comment]
@CarloLucibello I chose to use the real part let me know if that is wrong.

**Comment by CarloLucibello** [comment]
taking the real part is ok, when community detection true the nonbacktracking matrix is feasible the first q+1 eigenvectors have real components. 

And yes, we want those of largest magnitude. We could esplicitely set `which=:LM` in `eigs` to make it more clear
