### ISSUE TITLE
code coverage to 100%

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#213]
@jpfairbanks - do we need the function not currently covered? My recollection was that the recent changes to bfs_tree deprecated the parent function.

https://codecov.io/github/JuliaGraphs/LightGraphs.jl/src/traversals/bfs.jl?ref=106ac24b2b229dcb28f3865f052d6375e82e3a9c

**Comment by jpfairbanks** [comment]
Yes that can be removed. It wasn't part of the exported api of the old way.

**Comment by sbromberger** [comment]
Cool. Thanks!
