### ISSUE TITLE
Plan for when we should define types

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/LightGraphs.jl#215]
In #182 we discussed making a new type to encapsulate the arguments for a group of functions that share a set of arguments. This issue is to raise the question of when we should make new types and when functions should pass around the same parameters.

I am in favor of making many new types because it simplifies the interface, you construct an instance of the appropriate type and then pass it around to all of the internal functions. Then you have a wrapper function that automates the creation of the instance and returns the result in a "primitive" structure like array or dict. 

However if this degrades performance significantly, then we shouldn't do it.

Anyway if anyone wants to opine on the subject this is the place to do it.

**Comment by sbromberger** [comment]
A concrete proposal or two would help frame the discussion, I think.

**Comment by jpfairbanks** [comment]
One proposal would be something like if `n` functions share `m` arguments, then those `m` arguments should be bundled into a struct. The question would be: what are the appropriate values of `n` and `m`?

**Comment by sbromberger** [comment]
`n ≥ 4`, `m ≥ 4`?

**Comment by sbromberger** [comment]
Closing this out due to inactivity. Feel free to reopen, though.
