### ISSUE TITLE
RFC: Parameterize graphs

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#22]
Right now we have Graph with vertices as a range of Integer. It might make more sense (per this thread: https://groups.google.com/forum/#!topic/julia-users/dmO6vx6icmo) to parameterize the number of vertices. This is likely a significant effort.

**Comment by jpfairbanks** [comment]
Do you mean to have the type of the graph depend on the number of vertices? Like how the type of an array depends on its dimension, which is an integer? Or do you mean to have a Range{T<:Integer}?

**Comment by sbromberger** [comment]
I was thinking more like Graph{Int32}, Graph{Int64}, Graph{BigInt}... this is on hold due to lack of responses to https://groups.google.com/d/msg/julia-users/EeAhCIXTMnk/mL1FIjXlAi8J

**Comment by sbromberger** [comment]
I've done some base work on this in a parameterization branch and am actually not convinced that the increased efficiency is worth the complexity here. For small graphs, you don't need to worry about the extra memory consumption of system (64 or 32 bit) Ints; for large graphs, you're going to be exceeding the limits of all but 32 or 64 (so things like `Int8` or `Int16` don't make sense) bits. Closing this out for now.
