### ISSUE TITLE
Add sparse matrix constructor for Graph.

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGraphs/LightGraphs.jl#223]
DiGraphs has this
```julia
function LightDiGraph{T<:Real}(adjmx::SparseMatrixCSC{T})
....
```

why Graph has not the same?

**Comment by jpfairbanks** [comment]
It should be there.

**Comment by sbromberger** [comment]
It's there: https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/graph.jl#L25-L36

**Comment by sbromberger** [comment]
It *should* be there: https://github.com/JuliaGraphs/LightGraphs.jl/pull/60

**Comment by sbromberger** [comment]
Looks like it was removed in https://github.com/JuliaGraphs/LightGraphs.jl/commit/f39cdb26d343b78dd19f1653bea07759cb70e4ff

**Comment by sbromberger** [comment]
I'm not sure we can make this more performant than it already is. `triu` seems to be faster on sparse matrices than dense ones.
