### ISSUE TITLE
Change the return values for add_*  / rem_*

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#246]
Right now, `add_edge` and `rem_edge` return the edge added or removed, `add_vertex` and `add_vertices` return the number of vertices in the graph post-operation, and `rem_vertex` returns the graph. Now that we have `_insert_and_dedup` which tells us whether or not a new edge was actually added (or merely deduplicated), I'd like to change the return values of all four add/rem functions to be boolean as follows

`add_edge`: true if edge was added; false if edge already existed.
`rem_edge`: true if edge was removed; false otherwise (will not throw an error if edge not in graph)
`add_vertex`: always true
`add_vertices`: always true
`rem_vertex`: true if vertex was removed; false otherwise (will not throw error if vertex not in graph)

This will allow us to use the result of `insert_and_dedup` in `add_edge` and will make return values consistent. It will also allow us to handle errors better.

Thoughts?

**Comment by jpfairbanks** [comment]
I am a huge fan of replacing error("bad thing happened") with returning an exit status. My primary concern is that by using bools we limit ourselves to only returning the user one bit of info. If we return ints we can say any int less than 0 is an error condition and anything nonegative is a success condition with some information in it. 

I don't have any really useful info to return in mind, but I am thinking for the future.
If you don't think it is a good idea, then the current proposal is good to go.

**Comment by sbromberger** [comment]
I'm torn, honestly. The issue is that sometimes you don't want recovery (except via extreme measures like `try/catch`). On the other hand, sometimes you do. In my experience (particularly with C), leaving interpretation and handling of the return code to the user is a nightmare: look at all the times `malloc()` is called without checking to see whether it succeeded.

On the other hand: exit codes can return very useful information, as you point out.

I appreciate the discussion and will leave this open for a bit.

**Comment by jpfairbanks** [comment]
I think that if there is no agreement on what useful information should be returned, then just return bool as you have outlined here. The biggest change is going from code that needs to try/catch to code that needs to check return values. Or in most cases, go from code that isn't catching a potential error to code that isn't checking a return value. :)

**Comment by sbromberger** [comment]
Do you think this is going to be a big problem to existing codebases to make this change?

**Comment by jpfairbanks** [comment]
I don't think it will be too big a change. Are people catching the errors these functions throw and doing something with the error? My coding style with respect to these functions is to look before I leap so that I don't have to catch the errors. 

This change will make that code superfluous but not wrong.

**Comment by sbromberger** [comment]
I'd like to do this now that we've got several more commits under our belt. Any objections?

cc @CarloLucibello

**Comment by sbromberger** [comment]
I will be implementing this shortly.
