### ISSUE TITLE
Need some support with creating a graph based on the system of overlapping spheres

### ISSUE THREAD

**Issue by Gickle** [JuliaGraphs/LightGraphs.jl#249]
I don't know if this kind of issues is appropriate here, but I guess it suits here better than in Julia-users group. If it is not, just delete this thread. 

So I'm currently doing my student project, part of which is writing a program. I use Julia language in general and LightGrpahs particularly for this. The bottleneck of my code right now is creating a graph based on the system of overlapping spheres, which is a key moment of my entire program. I described my spheres as a 'pores' type:
```
type pores
  R::Float16
  coords::Vector{Float16}
end
```
I have an array of this type:
```
lattice = Vector{pores}(N)
```
And now I need to create a graph based on the lattice. Naturally, there is an edge between spheres i and k, if they intersect. So here is the code I am using right now:

```
function GraphCreating(lattice,R_max)
    N = length(lattice)
    g = Graph(N)
    vectors = zeros(3,N)
    distances = Vector{Float16}(N)
    for i = 1:1:N
        vectors[:,i] = lattice[i].coords
    end
    for i = 1:1:N
        distances = sqrt(sum(((vectors[1,:] - vectors[1,i]).^2 + (vectors[2,:] - vectors[2,i]).^2 + (vectors[3,:] - vectors[3,i]).^2),1))
        indx = find(distances .< 2*R_max)
        indx = indx[indx .< i]
        for s = 1:1:length(indx)
            j = indx[s]
            R = distances[j]
            if R < (lattice[i].R + lattice[j].R)
                add_edge!(g,i,j)
            end
        end
    end
    return g
end
```

Here is the table showing current perfomance:

L (see below) |Number of spheres | Approximate time in seconds
------------|------------ | -------------
25 |1327 | 0.16
30 |2293 | 0.6
35 |3641 | 1.25
40 |5435 | 3.2
45 |7739 | 5.8
50 |10615 | 10.5
60 |18343 | 40
80 |43480 | 262
90 |61909 | 393
100 |84923 | 750

Here is what it looks like:

![image](https://cloud.githubusercontent.com/assets/15964792/11453161/08d8ba76-9611-11e5-8dac-d14da64cf1a5.png)

The problem is that ideally I want the system with like ~10^6 spheres. And it is pretty much obvious that this will take way too much time. Are there any tips that may help in my situation?

P.S. Here is my code to generate lattice array:
```
type pores
  R::Float16
  coords::Vector{Float16}
end

function GeometryFunc{T<:Integer,U<:AbstractFloat}(L::T,phi::U,distribution::Array{U,2})                      
  V_avg = (4*pi/3)*sum((distribution[1,:].^3).*distribution[2,:])
  N = round(Int,(L^3*log(1/(1-phi)))/V_avg)
  lattice = Vector{pores}(N)
  R_max = maximum(distribution[1,:])
  for j=1:1:N
      lattice[j]=pores(0.0,[0.0,0.0,0.0])
  end
    for i=1:1:N
        lattice[i].coords = rand(3)*L
        Q = rand()
        if Q < distribution[2,1]
            lattice[i].R = distribution[1,1]           
        else
            tempsum1 = 0
            tempsum2 = distribution[2,1]
            for k = 2:1:length(distribution[1,:])
                tempsum1 = tempsum1 + distribution[2,k-1]
                tempsum2 = tempsum2 + distribution[2,k]
                if Q < tempsum2 && Q > tempsum1
                    lattice[i].R = distribution[1,k]
                end
            end
        end
    end
    return lattice, R_max
end
```
Parametres I usually use are:
```
GeometryFunc(100, 0.3, [0.95 1.01 10.3; 0.25 0.5 0.25])
```
(dependence of N on L can be seen in table above)

I shall be really grateful for any help. Thank you in advance.

**Comment by sbromberger** [comment]
What might be of help is to use @profile to find out where your code is spending its time. If you do
```
@profile GraphCreating(...)
Profile.print()
...
```
you'll see the number of times each line of code was in the sample (higher numbers generally mean more time is spent in that code).

Can you post some output?

**Comment by sbromberger** [comment]
Also: don't use Float16 - it's not efficient at all. Your standard Float64 should do the trick.

**Comment by sbromberger** [comment]
Also also: I'm happy to help here, but you might get more (better) help in julia-users.

**Comment by Gickle** [comment]
Thank you for response, Seth

Here is profile output:

```
1     REPL.jl; anonymous; line: 87
60348 REPL.jl; anonymous; line: 92
 60348 REPL.jl; eval_user_input; line: 62
  60348 profile.jl; anonymous; line: 16
   1     ...анты\Geometry.jl; GraphCreating; line: 46
    1 ...htGraphs\src\graph.jl; call; line: 15
   57334 ...анты\Geometry.jl; GraphCreating; line: 53
    748   array.jl; fill!; line: 193
    1     array.jl; fill!; line: 200
    3959  arraymath.jl; +; line: 96
     1 operators.jl; promote_shape; line: 219
     1 operators.jl; promote_shape; line: 222
    3     arraymath.jl; +; line: 100
    4926  arraymath.jl; .-; line: 125
    2     arraymath.jl; .-; line: 127
    3     arraymath.jl; .-; line: 129
    32058 arraymath.jl; .^; line: 57
     4    array.jl; reshape; line: 145
     1085 array.jl; reshape; line: 148
    5     multidimensional.jl; _unsafe_getindex; line: 191
    1     multidimensional.jl; _unsafe_getindex; line: 194
    261   multidimensional.jl; _unsafe_getindex; line: 195
     1 abstractarray.jl; trailingsize; line: 98
    9     multidimensional.jl; _unsafe_getindex; line: 196
     2 multidimensional.jl; checksize; line: 272
     7 multidimensional.jl; checksize; line: 274
    7534  multidimensional.jl; _unsafe_getindex; line: 197
    3896  operators.jl; sqrt; line: 381
    2     reducedim.jl; _mapreducedim!; line: 188
    1     reducedim.jl; _mapreducedim!; line: 189
    291   reducedim.jl; _mapreducedim!; line: 215
    1286  reducedim.jl; _mapreducedim!; line: 218
    580   reducedim.jl; reduced_dims; line: 15
     106 tuple.jl; getindex; line: 10
      10 essentials.jl; append_any; line: 123
      2  essentials.jl; append_any; line: 130
      1  essentials.jl; append_any; line: 132
      1  essentials.jl; append_any; line: 136
      1  essentials.jl; append_any; line: 137
    38    reducedim.jl; reduced_dims; line: 19
    459   simdloop.jl; _mapreducedim!; line: 67
    416   simdloop.jl; _mapreducedim!; line: 75
    767   simdloop.jl; _mapreducedim!; line: 84
   2879  ...анты\Geometry.jl; GraphCreating; line: 54
    16  bitarray.jl; find; line: 1432
     1  bitarray.jl; countnz; line: 1273
     15 bitarray.jl; countnz; line: 1275
    3   bitarray.jl; find; line: 1433
    206 bitarray.jl; find; line: 1438
    41  bitarray.jl; find; line: 1440
    1   bitarray.jl; find; line: 1442
    289 bitarray.jl; find; line: 1444
    22  bitarray.jl; find; line: 1446
    106 bitarray.jl; find; line: 1447
    1   bitarray.jl; find; line: 1452
    1   bitarray.jl; find; line: 1460
    432 broadcast.jl; .<; line: 396
     55 bitarray.jl; call; line: 12
     13 bitarray.jl; call; line: 21
    13  broadcast.jl; .<; line: 400
    834 broadcast.jl; .<; line: 404
     4   broadcast.jl; bitcache_lt; line: 385
     816 broadcast.jl; bitcache_lt; line: 388
     3   broadcast.jl; bitcache_lt; line: 389
     10  broadcast.jl; bitcache_lt; line: 391
      7 array.jl; setindex!; line: 325
    913 broadcast.jl; .<; line: 405
     2   broadcast.jl; dumpbitcache; line: 109
     187 broadcast.jl; dumpbitcache; line: 110
     587 broadcast.jl; dumpbitcache; line: 114
     42  broadcast.jl; dumpbitcache; line: 115
     34  broadcast.jl; dumpbitcache; line: 116
     55  broadcast.jl; dumpbitcache; line: 118
     5   broadcast.jl; dumpbitcache; line: 119
   103   ...анты\Geometry.jl; GraphCreating; line: 55
    48 broadcast.jl; .<; line: 396
     36 bitarray.jl; call; line: 12
     8  bitarray.jl; call; line: 21
     3  bitarray.jl; call; line: 23
    14 broadcast.jl; .<; line: 400
    26 broadcast.jl; .<; line: 404
     1  broadcast.jl; bitcache_lt; line: 385
     25 broadcast.jl; bitcache_lt; line: 391
      3  array.jl; setindex!; line: 324
      22 array.jl; setindex!; line: 325
    1  broadcast.jl; .<; line: 405
     1 broadcast.jl; dumpbitcache; line: 114
    1  multidimensional.jl; _unsafe_getindex; line: 206
     1 bitarray.jl; countnz; line: 1273
    11 multidimensional.jl; _unsafe_getindex; line: 207
    2  multidimensional.jl; _unsafe_getindex; line: 208
     2 tuple.jl; ==; line: 95
   2     ...анты\Geometry.jl; GraphCreating; line: 56
    2 range.jl; steprange_last; line: 29
   6     ...анты\Geometry.jl; GraphCreating; line: 59
   23    ...анты\Geometry.jl; GraphCreating; line: 60
    4  ...ghtGraphs\src\core.jl; add_edge!; line: 106
     4 ...htGraphs\src\graph.jl; has_edge; line: 71
      1 dict.jl; ht_keyindex; line: 557
      2 dict.jl; ht_keyindex; line: 564
    19 ...ghtGraphs\src\core.jl; add_edge!; line: 108
     10 ...htGraphs\src\graph.jl; unsafe_add_edge!; line: 79
      8 array.jl; push!; line: 433
      1 array.jl; push!; line: 434
     3  ...htGraphs\src\graph.jl; unsafe_add_edge!; line: 81
      2 array.jl; push!; line: 433
     5  ...htGraphs\src\graph.jl; unsafe_add_edge!; line: 83
      1 dict.jl; setindex!; line: 637
      1 dict.jl; setindex!; line: 643
       1 dict.jl; ht_keyindex2; line: 591
      3 dict.jl; setindex!; line: 649
       1 dict.jl; _setindex!; line: 619
       1 dict.jl; _setindex!; line: 620
       1 dict.jl; _setindex!; line: 625
```

Lines 53 and 54 are respectively:
```
distances = sqrt(sum(((vectors[1,:] - vectors[1,i]).^2 + (vectors[2,:] - vectors[2,i]).^2 + (vectors[3,:] - vectors[3,i]).^2),1))
indx = find(distances .< 2*R_max)
```

The weird part is that N = 84923, however, line 53 appeared only 60348.

> Also: don't use Float16 - it's not efficient at all. Your standard Float64 should do the trick.

I did this in memory purpose, didn't know that might affect performance. I tried to change Float16 to Float64, but that did not change anything for some reason. 

> Also also: I'm happy to help here, but you might get more (better) help in julia-users.

Okay, I will try.

**Comment by sbromberger** [comment]
More hints:

1) Devectorize. Julia likes loops more than vector operations. Create `distances` using for loops.
2) get rid of steps. `1:1:N` is the same as `1:N`.
3) change the type of pores so that they can become truly immutable. I was playing around with
```
immutable pores
    R::Float64
    coords::Tuple{Float64, Float64, Float64}
end
```

and modifying the code appropriately, but I have to go do some errands now.

**Comment by CarloLucibello** [comment]
This issue can be closed, since it is not related to LightGraphs.

some other tips:

for profiling
```julia
@profile GraphCreating(...)
ProfileView.view()
Profile.clear()
```
>distances = sqrt(sum(((vectors[1,:] - vectors[1,i]).^2 + (vectors[2,:] - vectors[2,i]).^2 + (vectors[3,:] - vectors[3,i]).^2),1))
 indx = find(distances .< 2*R_max)
 indx = indx[indx .< i]

 lot of unnecessary memory allocations here. Use loops insted. See also Distance.jl for computing distances

- You are computing distances between any pair of points, so of course your algorithm will have O(N^2) complexity. If you want to make it scale almost linearly you have do something more sophisticated, such as partitioning your L^d box in many (but not too many) subboxes, assign each point to the corresponding box, and then check distances only between points belonging to the same box or to adjacent ones

**Comment by Gickle** [comment]
>1) Devectorize. Julia likes loops more than vector operations. Create distances using for loops.
>2) get rid of steps. 1:1:N is the same as 1:N.
>3) change the type of pores so that they can become truly immutable. I was playing around with

Okay, I will try this. Thanks again! 

> such as partitioning your L^d box in many (but not too many) subboxes, assign each point to the  corresponding box, and then check distances only between points belonging to the same box or to adjacent ones

This actually kinda what I did earlier (in MATLAB), however, I decided to skip this in Julia, since I am actually pretty bad in Julia particularly and in programming in general. :) But I will try it again. 

Thank you for your time. Really appreciate it. :)
