### ISSUE TITLE
add biconnectivity and and articulation points

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#252]
Probably best done with a modified TarjanVisitor: https://en.wikipedia.org/wiki/Biconnected_component

**Comment by athulappadan** [comment]
Could you suggest an API..?

**Comment by jpfairbanks** [comment]
I think the following is a good place to start.

```julia
function articulation_points(g::Graph)
end

function articulation_points!(g::Graph, 
                     storage::Whatever arrays you need to store scratch work)
    return [v| v is an articulation point of g]
end
```

If you want to do binconnected components too, I think the output should be an array of length nv(g) where `result[v] = index` of biconnected component that contains vertex v. This is how connected components provides its results. Then we convert them into a set of sets representation.

**Comment by athulappadan** [comment]
What if the input graph is non-connected? Should it calculate the articulation points of individual connected components? If yes, what should be the return value (array of arrays..?).

**Comment by jpfairbanks** [comment]
I think you can assume the graph is connected for the first implementation because that will make things easier. If it is not that much work to find the articulation points of each component, you can return them all in one array. If the graph has multiple components, the user is able to check which component each vertex belongs to separately.

**Comment by jpfairbanks** [comment]
We can do this in two PR's the first one handling the single connected component case, and then another PR with the multiple connected component case. That will make it easier to review the code.

**Comment by jpfairbanks** [comment]
This is tied to PR #501

**Comment by sbromberger** [comment]
ref #502

**Comment by sbromberger** [comment]
Closing with #505

**Comment by athulappadan** [comment]
@jpfairbanks  For biconnected components, how about storing the edges instead of vertices?

**Comment by athulappadan** [comment]
ref #511
