### ISSUE TITLE
Congrats to the LG team...

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#254]
Just wanted to say thanks to all the committers here. The Federal Reserve Bank of New York released their DSGE modeling system to the public (http://libertystreeteconomics.newyorkfed.org/2015/12/the-frbny-dsge-model-meets-julia.html) and one of its dependencies is QuantEcon (https://github.com/QuantEcon/QuantEcon.jl). Work that @ZacCranko and this team did resulted in QuantEcon adopting LightGraphs as one of their underlying dependencies. This is a very big deal (not least because I started my career at FRBNY).

LightGraphs is becoming the go-to graph modeling package for Julia, and I'm honored to be a part of this team with you.

**Comment by ZacCranko** [comment]
My pleasure @sbromberger, always happy to work with you on this newfangled thing called Julia.

**Comment by jpfairbanks** [comment]
Woohoo! External validation and a positive environment built around open source. :+1:
