### ISSUE TITLE
recent benchmarks

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#259]
a random watts_strogatz graph (500, 25000) (identical graphs between LightGraphs and NetworkX):

 Type | LG | NetworkX | igraph
---|---|---|---
betweenness centrality (s) | 0.211481 | 4.87 | 0.171
closeness centrality (s) | 0.144869 | 2.12 | 0.166
degree centrality (µs) | 129 | 656 | N/A
bfs tree (ms) | 3.284 | 16.9 | 1.01 (but not a graph).

**Comment by CarloLucibello** [comment]
Very very nice. The big guys to beat now are igraph and graph-tool, they should be much faster than NetworkX

**Comment by sbromberger** [comment]
So igraph is a bit of a mixed bag, but I'm not too worried about betweenness. We solve the two-language problem in LightGraphs :)

**Comment by ssllmit** [comment]
I'm a big fan of `graph-tool`, and have been running my own comparisons for Julia environments—LightGraphs is definitely competitive, and in some instances outperforms `graph-tool` on the same graph.

Here are a few results for a graph of size O(10^6) and order O(10^5) on a MacBook Pro i7 with 4 cores. `graph-tool` is compiled with OpenMP multithreading, which is used in the PageRank C++ code.

Type | ``graph-tool` | LG
----- | -------------- | --
Dijkstra | 4.93 s | 0.82 s
PageRank | 20.3 ms | 60.0 ms

Here's the code:

## `graph-tool` Dijkstra

```python
import numpy as np,numpy.random as npr,graph_tool.all as gt
import graph_tool

N = 10000
p = 22. * np.log(N)/N

print('An almost surely connected graph (p = {}*log(n)/n):'.format(p*N/np.log(N)))
g = gt.random_graph(N, deg_sampler=lambda: npr.poisson((N-1)*p), directed=False, model='erdos')

wt = g.new_edge_property('float')
for e in g.edges(): wt[e] = npr.chisquare(1)

np.savetxt('erdos_renyi_gt.csv', np.array([[g.vertex_index[e.source()],g.vertex_index[e.target()], wt[e]] for e in g.edges()]), delimiter=',',fmt=['%.0f', '%.0f', '%.15f'])

%timeit graph_tool.search.dijkstra_search(g, weight=wt, source=g.vertex(0))
```

## `graph-tool` PageRank

```python
%timeit pr = graph_tool.centrality.pagerank(g)
```

## LightGraphs Dijkstra

```julia
using LightGraphs
using DataFrames

df = readtable("erdos_renyi_gt.csv")
nv = max(int(maximum(df[1])),int(maximum(df[1]))) + 1

g = Graph()
add_vertices!(g,nv)

for i = 1 : nrow(df)
    add_edge!(g,df[1][i]+1,df[2][i]+1)
end
distmx = sparse(df[1]+1,df[2]+1,df[3])
distmx = distmx + distmx.'

@time r = dijkstra_shortest_paths(g, 1, distmx)
```

## LightGraphs PageRank

```julia
g = DiGraph()
add_vertices!(g,nv)

for i = 1 : nrow(df)
    add_edge!(g,df[1][i]+1,df[2][i]+1)
end

@time pr = pagerank(g)
```

**Comment by sbromberger** [comment]
Those are great metrics. Did you precompile `pagerank` before timing it?

I would expect pagerank to be not as optimal as it could be given that it hasn't gone through a proper efficiency review by linear algebra experts (@jpfairbanks among them). We might want to revisit.

**Comment by sbromberger** [comment]
Also: we will soon have parallel dijkstra. (We have parallel BFS now and parallel betweenness centrality is in the master branch.) I wonder – what happens if you run dijkstra with graph-tool without multithreading?

**Comment by ssllmit** [comment]
> what happens if you run dijkstra with graph-tool without multithreading?

It's more complicated than that, and single-core comparisons would be require time-consuming reinstalls of not just `graph-tool` but also Boost:

1. `graph-tool` Dijkstra doesn't use OpenMP's parallel pragmas, but does a straight call to Boost's Dijkstra: https://git.skewed.de/count0/graph-tool/blob/master/src/graph/search/graph_dijkstra.cc
2. Boost's default Dijkstra uses Crauser, and most installs turn on parallelism by default: http://www.boost.org/doc/libs/1_59_0/libs/graph_parallel/doc/html/dijkstra_shortest_paths.html

For example, I have this:

```
$ port -qv installed | grep boost
  boost @1.59.0_3+no_single+no_static+python34 (active) platform='darwin 16' archs='x86_64' date='2017-05-06T17:36:28-0400'
$ port variants boost | grep no_single
[+]no_single: Disable building single-threaded libraries
```

I'd recommend comparing multithreaded algorithms on the same box, as this will be what typical users would want compared anyway.

**Comment by sbromberger** [comment]
Can you post the graph?

**Comment by ssllmit** [comment]
The `graph-tool` code above generates an Erdős–Rényi graph and saves it as a csv file that is read by LG. It takes less than a minute or so to run, and the results are consistent across random graphs.

**Comment by sbromberger** [comment]
Just did a 5000-node ER graph comparison with betweenness centrality:

graph-tool:
```
In [41]: %timeit bc = graph_tool.centrality.betweenness(g)
1 loop, best of 3: 16.8 s per loop
```

LightGraphs (with 4 processes on a 2-core system):
```
julia> @time z = parallel_betweenness_centrality(g);
 16.777793 seconds (40.02 k allocations: 31.090 MiB, 0.15% gc time)
```

I noticed that graph-tool is using threads, so I think this is a reasonable apples-to-apples comparison.

**Comment by diegozea** [comment]
> We solve the two-language problem in LightGraphs :)

That's true! I encountered an obstacle related to the two language problem trying to use these fast python libraries coded on C/C++/Cython (there is a [benchmark here](https://www.timlrx.com/2019/05/05/benchmark-of-popular-graph-network-packages/)): **They are almost impossible (or at least annoying) to install in Windows because of compiling issues!** That is a big show-stopper if you need a graph library as a dependency of your multiplatform tool :/

Thankfully, since LightGraphs is a pure Julia library, it works like a charm in Windows while being fastest than the pure Python solution (NetworkX) :D
