### ISSUE TITLE
Community detection

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/LightGraphs.jl#279]
The function `community_detection_nback`  should be broken up.
https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/community/detection.jl#L32

As written it computes the spectral embedding of the vertices based on the Nonbacktracking randomwalk and does the spatial partitioning based on the coordinates. There are a bunch of tweakable parameters to this method which are not being exposed to the user. It is fine to have such a simple user interface at the top level but advanced users should be able to access the features separately.

For example:
   - phi[n,i] += v[u] these coordinates can be scaled by degree(g,i) or sqrt(degree(g,i))
   - number of clusters for kmeans can be independent of the number of dimensions of coordinates phi.
   - threshold cuts (on L29) need not be made at 0.

**Comment by sbromberger** [comment]
PRs would be better for this unless you're proposing that @CarloLucibello do it :)

**Comment by jpfairbanks** [comment]
I got here by looking for where Clustering.jl was used. Is this the only place?

**Comment by sbromberger** [comment]
I believe so.
