### ISSUE TITLE
The Math behind LG

### ISSUE THREAD

**Issue by tenthdimension** [JuliaGraphs/LightGraphs.jl#284]
Hello Seth, 

Is it possible to visualize the math behind the code? 

Thanks. Kevin

**Comment by sbromberger** [comment]
Not sure what you mean. LG is open source, so everything's visible. What are you trying to do, specifically?

**Comment by tenthdimension** [comment]
Seth, I'm sorry for not being specific. For instance, the math behind closeness_centrality. Is there a tool that shows me the source of that?

**Comment by tenthdimension** [comment]
In combination with the g that I defined?

**Comment by sbromberger** [comment]
Well, the code is pretty straightforward: see https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/centrality/closeness.jl but you'll need to understand Julia code. If you just want the algorithm, [Wikipedia](https://en.wikipedia.org/wiki/Centrality#Closeness_centrality) has it.

**Comment by jpfairbanks** [comment]
The documentation for each function is accessible from the repl with `?functionname` If there is interesting math behind such a function, there should be a reference to an academic article or wikipedia article (that links to an academic article).

**Comment by tenthdimension** [comment]
Thanks Seth and James!
