### ISSUE TITLE
Combining File Read, Dijkstra, and Closeness from Source (explicit) into one Script

### ISSUE THREAD

**Issue by tenthdimension** [JuliaGraphs/LightGraphs.jl#285]
Hello Seth, 

I need to combine the create vertex, open close file script, with explicit closeness_centrality and dijkstra functions, all into one script, and am a bit confused over when to fit the AbstractDijkstraState

https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/shortestpaths/dijkstra.jl

into the closeness_centrality

https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/centrality/closeness.jl

My guess is I should declare the entire dijkstra.jl before closeness.jl?

1. create vertex, open, close file script
2. declare dijkstra.jl from source, connected to graph
3. declare closeness.jl from source, connected to dijsktra and graph

**Comment by tenthdimension** [comment]
I'm reading about how to apply the dijkstra abstract state and variables to the numbers at hand, after the closeness loop directs the program to it.

**Comment by tenthdimension** [comment]
I was thinking something like this (haven't modified anything yet, just glued pieces together)

# Script for running dijkstra and closeness functions explicitly, from a digraph

# Define graph from file
using LightGraphs
g = DiGraph(100) #create 100-vertex graph
file = open("edges", "r")
for l in readlines(file)
    (u,v) = split(chomp(l),' ') 
    intu = parse(Int,u)
    intv = parse(Int,v)
    add_edge!(g,intu+1,intv+1)
end
close(file)

# Declare Dijkstra

abstract AbstractDijkstraState<:AbstractPathState

immutable DijkstraHeapEntry{T}
    vertex::Int
    dist::T
end

isless(e1::DijkstraHeapEntry, e2::DijkstraHeapEntry) = e1.dist < e2.dist

type DijkstraState{T}<: AbstractDijkstraState
    parents::Vector{Int}
    dists::Vector{T}
    predecessors::Vector{Vector{Int}}
    pathcounts::Vector{Int}
end

"""Performs [Dijkstra's algorithm](http://en.wikipedia.org/wiki/Dijkstra%27s_algorithm)
on a graph, computing shortest distances between a source vertex `s` and all
other nodes. Returns a `DijkstraState` that contains various traversal
information (see below).
With `allpaths=true`, returns a `DijkstraState` that keeps track of all
predecessors of a given vertex (see below).
"""
function dijkstra_shortest_paths{T}(
    g::SimpleGraph,
    srcs::Vector{Int},
    distmx::AbstractArray{T, 2}=DefaultDistance();
    allpaths=false
)
    nvg = nv(g)
    dists = fill(typemax(T), nvg)
    parents = zeros(Int, nvg)
    preds = fill(Vector{Int}(),nvg)
    visited = zeros(Bool, nvg)
    pathcounts = zeros(Int, nvg)
    H = Vector{DijkstraHeapEntry{T}}()  # this should be Vector{T}() in 0.4, I think.
    dists[srcs] = zero(T)
    pathcounts[srcs] = 1

    sizehint!(H, nvg)

    for v in srcs
        heappush!(H, DijkstraHeapEntry{T}(v, dists[v]))
    end

    while !isempty(H)
        hentry = heappop!(H)
        # info("Popped H - got $(hentry.vertex)")
        u = hentry.vertex
        for v in out_neighbors(g,u)
            alt = (dists[u] == typemax(T))? typemax(T) : dists[u] + distmx[u,v]

            if !visited[v]
                dists[v] = alt
                parents[v] = u
                pathcounts[v] += pathcounts[u]
                visited[v] = true
                if allpaths
                    preds[v] = [u;]
                end
                heappush!(H, DijkstraHeapEntry{T}(v, alt))
                # info("Pushed $v")
            else
                if alt < dists[v]
                    dists[v] = alt
                    parents[v] = u
                    heappush!(H, DijkstraHeapEntry{T}(v, alt))
                end
                if alt == dists[v]
                    pathcounts[v] += pathcounts[u]
                    if allpaths
                        push!(preds[v], u)
                    end
                end
            end
        end
    end

    dists[srcs] = zero(T)
    pathcounts[srcs] = 1
    parents[srcs] = 0
    for src in srcs
        preds[src] = []
    end

    return DijkstraState{T}(parents, dists, preds, pathcounts)
end

dijkstra_shortest_paths{T}(g::SimpleGraph, src::Int, distmx::AbstractArray{T,2}=DefaultDistance(); allpaths=false) =
  dijkstra_shortest_paths(g, [src;], distmx; allpaths=allpaths)

# Declare Closeness and apply Abstract Dijkstra to graph numbers

"""Calculates the [closeness centrality](https://en.wikipedia.org/wiki/Centrality#Closeness_centrality)
of the graph `g`.
"""
function closeness_centrality(
    g::SimpleGraph;
    normalize=true)

    n_v = nv(g)
    closeness = zeros(n_v)

    for u = 1:n_v
        if degree(g, u) == 0     # no need to do Dijkstra here
            closeness[u] = 0.0
        else
            d = dijkstra_shortest_paths(g,u).dists
            δ = filter(x->x != typemax(x), d)
            σ = sum(δ)
            l = length(δ) - 1
            if σ > 0
                closeness[u] = l / σ

                if normalize
                    n = l / (n_v-1)
                    closeness[u] *= n
                end
            end
        end
    end
    return closeness
end

**Comment by sbromberger** [comment]
What exactly are you trying to do with Dijkstra? Generally the only thing you need from a `DijkstraState` is one of its properties after you've run a DSP, but that's fairly low-level.

The only relationship that `closeness_centrality` has with Dijkstra is that closeness uses Dijkstra for its distance calculations.

**Comment by sbromberger** [comment]
If you're just trying to write a script to calculate closeness centrality using your notebook code, you don't need to copy any of LG if it's installed on your system (see http://quant-econ.net/jl/getting_started.html#running-julia-scripts for more details).

**Comment by tenthdimension** [comment]
Hi Seth. I am trying to add as much meaning as possible to a single script, by expanding concepts and making them as explicit as possible. For instance, if you ask me, what is triboluminescence, and I tell you that it is 'the emission of light from a substance caused by rubbing, scratching, or similar frictional contact'.... That's not science, I have only told you what a word means in terms of other words. I haven't told you anything about nature - what crystals product light when you crush them, why they produce light. You can't tweak your own entire experiment like that. 

Instead, if I told you, that when you take a lump of sugar and crush it with a pair of pliers in the dark, you can see a bluish flash, that some other crystals do that too, and nobody knows why, and that this phenomenon is called triboluminescence, then you might go home and try it. Then there's an experience of nature. 

I just want to make the why as clear as possible in the code, and I need your help. 

You already helped me with getting the results, and I thank you very much for that(!), but now I would like to experiment and understand the full integrated process myself, one execution at a time. 

I understand LG was made to make our lives easier, and it really does. The tradeoff is inevitable - less transparency in the code itself and how it works together, expanded. I honestly would prefer to just compare answers from a small graph, one computed by the computer, the other computed by hand on paper, to show the computer process and concepts are right. But I am being asked to show this on the code itself.

**Comment by tenthdimension** [comment]
I will start by reviewing each line from dijkstra and closeness and posting my questions here, and how they would work together with the graph of 100 vertices. Then you tell me if I'm going in the right direction?

**Comment by sbromberger** [comment]
It seems to me that the only way to do this ("expanding concepts...") is to write the graph processing code yourself, which means you don't need LightGraphs at all. LG just presents some fundamental graph calculations via its API. If you need to "explain" these (to yourself or to others), then I'd suggest that you'll have to learn Julia to the point where you understand the code, which is of course freely available for use/inspection per the license, and by that time the concepts and implementation should be obvious. There's no magic in LightGraphs code.

I'm really perplexed by this approach, however. I have to say that I'm not really looking forward to answering questions about Dijkstra and closeness when the code is right there and there are dozens of other resources that explain the algorithms in general. If you're having a problem understanding the LightGraphs implementation because it's written in Julia, then that's something that you'd probably want to take to another forum (like the julia-users google group). If you have a specific question about functionality in LightGraphs, or if there's some part of it that you think isn't working properly, then this is the right place for that discussion.

**Comment by sbromberger** [comment]
PS: if you want to compare your hand-executed algorithms with LightGraphs to determine correctness, then I'd recommend having a look at the LightGraphs package tests. The graphs there are, for the most part, fairly simple and lend themselves to hand-drawn examination.

**Comment by tenthdimension** [comment]
My focus isn't CS. You're right, I would need more time with Julia. Thanks Seth, I'll see what to do from here.
