### ISSUE TITLE
ID of Center Vertex in closeness_centrality function

### ISSUE THREAD

**Issue by tenthdimension** [JuliaGraphs/LightGraphs.jl#286]
Hi Seth, how do I find the ID of the center vertex?

**Comment by tenthdimension** [comment]
eccentricity(g) does it?

**Comment by tenthdimension** [comment]
then i got a vertex vector of 3s and 4s. do i consider 3 and 4 to be the graph center?

**Comment by tenthdimension** [comment]
sorry, since it's a directed graph, just the origin of the vector counts, so is 3 the center?

**Comment by sbromberger** [comment]
How are you defining the center?

**Comment by tenthdimension** [comment]
Nice, that's exactly what I did. Thanks Seth!

**Comment by sbromberger** [comment]
Cool - closing this out then. Feel free to reply if you need to reopen.
