### ISSUE TITLE
docs for StochasticBlockModel

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGraphs/LightGraphs.jl#288]
The docs for stochastic block model seems to be missing a clear example of how to produce an actual graph according  to the stochastic block model. Something like
```julia
sbm = StochasticBlockModel(internalp, externalp, sizes)
g = Graph(sum(sizes), numedges, sbm)
```
which I found in test/randgraphs.jl. Maybe it would be also convenient to add an untility function like `stochastic_block_model` that returns directly a graph
 
I can file a PR addressing this issue

@jpfairbanks you have any thought on this?

**Comment by jpfairbanks** [comment]
The utility function is probably a good idea. I just want to note that the current design was from code where I was working on dynamic graphs and so I wanted to sample some edges from an SBM distribution and then process the graph, then sample some more edges and process the combined graph. This is why the design is more complex than it needs to be. If someone wants to simplify it, that would be a good idea too. I just don't have any cycles for that. My dissertation is due in March!

**Comment by sbromberger** [comment]
> My dissertation is due in March!

Well, let's be honest. It's not *due*, really. Isn't this really more of an aspirational goal? :smiley: :wink:

**Comment by jpfairbanks** [comment]
Defense is scheduled for Mar 28th.

**Comment by sbromberger** [comment]
"Scheduled" :smile: 

In all seriousness, congratulations on this milestone. I'm looking forward to addressing you as "Dr. Fairbanks" on March 29.

**Comment by sbromberger** [comment]
Did we address this with one of the recent merges?

**Comment by CarloLucibello** [comment]
not yet, let me reopen and merge #297 first, then I'll file another PR addressing this and as many docs problem as I can
