### ISSUE TITLE
check for and add missing documentation

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGraphs/LightGraphs.jl#289]
There are a lot of functions in LightGraph documented in the code but not  here http://lightgraphsjl.readthedocs.org/en/latest/ (a few examples familiar to me: stochastic bock model, matching, community detection,...)

@sbromberger  I don't know how the docs are generated. Is it easy to fix this issue? If so I can file a PR

**Comment by sbromberger** [comment]
It's very easy to fix - I can do it directly. Basically, the docs are autogenerated from the docstrings and some template files in `doc/` - going into that directory and running `julia build.jl` will recreate the docsets.

I'll do this now and push the changes. Thanks for the heads up.

**Comment by sbromberger** [comment]
OK, so I'm working on this now. What would be a huge help (and I don't have time this week to do it, unfortunately) is if someone (@CarloLucibello?) could go through LightGraphs.jl, extract all the exported functions, and make sure there's at least one reference to each in some Markdown file in doc.

If that person could update this issue with any functions that are missing from doc/, I can edit the build.jl file to include them.

**Comment by CarloLucibello** [comment]
ok, I'll try in these days to create a script that goes through the exported functions and checks for references in  `doc/`

**Comment by CarloLucibello** [comment]
While we should always keep an eye on missing and ill formatted docs, I think this issue has been mostly addressed in #321 #325 #327
