### ISSUE TITLE
support I/O of vertex and edge properties

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGraphs/LightGraphs.jl#296]
the main reason for the existence itself of many graph file formats is the possibility to store edge and vertex properties beside the topology of the graph. 

It is a pity that LG now supports so many formats but doesn't allow users to store their data with it. Since we have all the technology in place I think we should implement this possibility, with little effort on our side and great benefit for end users.

I'll  try one specific proposal, but there could be better ones. 

We should extend the function `save` with some keyword argument, like `vprop`. `vprop` could be a Dict of Dict, or a Dict of Vector,  while `eprop` has to be a Dict of Dict. We should support the following sintax
```
c = [ rand(["green","blue"] for i=1:nv(g)]
s = rand(nv(g))
w = Dict([ e=>rand() for e in edges(g)])
save("test.gml", g, :gml, vprop=Dict("color"=>p, "size"=>s), eprop=Dict("weight"=>w))
```
The `load` function is a more complicated matter, maybe we could leave that unchanged and introduce a new function, `loadprop`, returning the graph and a dict containing the properties.

Any thought?

maybe something like this proposal has been already discussed and rejected, but I'd like tu push it forward again :)

**Comment by sbromberger** [comment]
100% support this idea.

**Comment by jpfairbanks** [comment]
Supporting metadata about the vertices and edges is a good thing. I'll just include the following for API reference:
- JLD https://github.com/JuliaLang/JLD.jl
- HDF5 https://github.com/JuliaLang/HDF5.jl

It is probably worth the time to study their interfaces and aim for some level of consistency.
I have used HDF5 to store graphs before.

**Comment by sbromberger** [comment]
I explored using hdf5 to store graphs early on, but the issue was that the disk storage was huge compared to the graph. In conversations with @timholy about this, it seemed to be just the way it was.

**Comment by timholy** [comment]
It should be quite easy to write a [custom serializer](https://github.com/JuliaLang/JLD.jl/blob/master/doc/jld.md#custom-serialization), which should generate compact files. For example, for the `Graph` type it might look like:
```jl
type GraphSerializer
    vertices::UnitRange{Int}
    ne::Int
    packed_adjlist::Vector{Int}
    n_adjlist::Vector{Int}
end

function JLD.writeas(g::Graph)
    n_adjlist = map(length, g.fadjlist)
    packed_adjlist = Array(Int, sum(n_adjlist))
    k = 0
    for lst in g.fadjlist
        for v in lst
            packed_adjlist[k+=1] = v
        end
    end
    GraphSerializer(g.vertices, g.ne, packed_adjlist, n_adjlist)
end
```
and the reverse function for `writeas`.

**Comment by jpfairbanks** [comment]
It looks like this is effectively the CSR representation of the adjacency matrix. `n_adjlist` is storing the length of each row instead of the offsets right?

@timholy: Did I understand the docs correctly that `readas` should take a `GraphSerializer` and return a `Graph`?

**Comment by timholy** [comment]
Right on both counts.

**Comment by jpfairbanks** [comment]
Cool. I think we can extend #306 to support vertex/edge data with 
```julia
type GraphSerializer{S,T}
    vertices::UnitRange{Int}
    ne::Int
    packed_adjlist::Vector{Int}
    n_adjlist::Vector{Int}
    vertexdata::Vector{S}
    edgedata::Vector{T}
end
```
Then the user is responsible for making sure their data can be wrtitten as JLD objects. @timholy would this be an efficient way to use JLD? Is it inefficient to use `Vector{Any}` compared to `Vector{AbstractString}`? 

I imagine users will want to store Strings, Numbers, Tuples, and Dicts as the metadata representing Names, Weights, Coordinates, and Properties resp.

**Comment by timholy** [comment]
Anything that's not a leaf type will result in an HDF5 reference object, and it's really the number of objects that determines whether you get great or horrible performance from HDF5/JLD. So if you want to support strings, for example, it would be bad to use a mix of `ASCIIString` and `UTF8String`; it should be one or the other.

**Comment by jpfairbanks** [comment]
Does that imply that `Vector{UTF8String}`, `Vector{Tuple{Int64,ASCIIString}}`, `Vector{Dict{ASCIIString,ASCIIString}}` are efficient?

**Comment by timholy** [comment]
The first and third, yes. The second, I suspect not. See https://github.com/JuliaLang/JLD.jl/blob/689eadce722da44b1ad2e70564b14836fc7d67ee/src/jld_types.jl#L5 and search JLD and/or HDF5 for issues that discuss it.

**Comment by sbromberger** [comment]
Closing this out now that we've merged #306. See also #278 for some discussion on planned direction.

**Comment by CarloLucibello** [comment]
Can we reopen this? We don't support yet saving properties in the formats that allow it (graphml, gexf, gml,...)

**Comment by sbromberger** [comment]
Reopened. sorry for delay.

**Comment by juliohm** [comment]
How to add properties to a vertex/edge? I couldn't find an example in the docs.

**Comment by sbromberger** [comment]
You don't. From the README:

> It is an explicit design decision that any data not required for graph manipulation (attributes and other information, for example) is expected to be stored outside of the graph structure itself. Such data lends itself to storage in more traditional and better-optimized mechanisms.

**Comment by juliohm** [comment]
Good design decision. Reading/writing from/to disk is useful though :+1:

**Comment by sbromberger** [comment]
Check out graph persistence if you just need to read/write the graph structures. We support lots:

> persistence formats: proprietary compressed, GraphML, GML, Gexf, DOT, Pajek NET

**Comment by juliohm** [comment]
Thank you @sbromberger , I will check it.

**Comment by sbromberger** [comment]
Closing this out since we don't seem to have any further action items. Feel free to continue discussion and if it needs to be reopened, I'm happy to do so.
