### ISSUE TITLE
Function to generate Graph/DiGraph from array layout

### ISSUE THREAD

**Issue by juliohm** [JuliaGraphs/LightGraphs.jl#298]
Let's say I have a matrix `M = zeros(3,3)` or just the dimensions 3x3. What is the most efficient way of generating the graph below?

![graph](https://cloud.githubusercontent.com/assets/3345261/13367045/2fe8bc78-dc94-11e5-9eb6-fcfb78304f17.png)

More generally, what do you suggest for arbitrary dimensions `nx, ny, nz, ...`?

**Comment by jpfairbanks** [comment]
You can use this
```julia
using LightGraphs
nx=10; ny = 5; nz=3;
g = crosspath(nz, crosspath(ny, PathGraph(nx)));
#to check it visually
using PyPlot
spy(adjacency_matrix(g))
```

We could include this as a provided graph under the name `grid3d(nx,ny,nz)`.

**Comment by juliohm** [comment]
Thank you @jpfairbanks, that is really helpful. Could you elaborate on `crosspath` and `PathGraph`?

**Comment by jpfairbanks** [comment]
PathGraph makes the 1d path and crosspath adds a dimension by copying the graph you have and connected the copies in the new dimension.

**Comment by juliohm** [comment]
@jpfairbanks is it equivalent to `cartesian_product()`?

**Comment by juliohm** [comment]
I did some small tests here, and it seems that `cartesian_product` is a little bit faster than `crosspath`. I just need to make sure that these are equivalent solutions.

**Comment by sbromberger** [comment]
See #299 also - once we get to 100% code coverage I'll merge this :)

**Comment by jpfairbanks** [comment]
You can check if you get the same result
```julia
using LightGraphs
using Base.Test
nx = 20; ny = 21
G = PathGraph(ny); H = PathGraph(nx)
@time c = cartesian_product(G, H)
@time g = crosspath(ny, PathGraph(nx));
@test g == c
```

`crosspath` is slower because I wrote it when I needed the case of `len == 2`
We should probably just replace it with `crosspath(len::Integer, h::Graph) = cartesian_product(PathGraph(len), h)`

**Comment by juliohm** [comment]
Thank you all, really helpful comments and additions. Should I close the issue or wait for the merge?

@jpfairbanks I like the idea of writing `crosspath` in terms of `cartesian_product` if it is always faster. :)

**Comment by jpfairbanks** [comment]
It should be. Do you want to make PR for it? You can write up your time trials to show that it is the case.

**Comment by juliohm** [comment]
You suggested the idea, I am just sharing my opinion. Code reuse whenever
possible. :)

-Júlio

**Comment by jpfairbanks** [comment]
I am offering it as an easy pull request to get you involved in the development of LG. :+1:

**Comment by juliohm** [comment]
Thank you James! I'll definitely contribute to the package, specially if I
need to implement an algorithm myself that is not implemented yet. Right
now I'm quite busy with my qualifying exam, but I want to use
LightGraphs.jl in my research. :)

**Comment by sbromberger** [comment]
Closing via #299.
