### ISSUE TITLE
Document maximum_flow() output

### ISSUE THREAD

**Issue by juliohm** [JuliaGraphs/LightGraphs.jl#300]
The function is not documented yet, what are the two outputs?

I am interested in the associated min-cut as I need to partition the graph.

**Comment by sbromberger** [comment]
Check [the docstring](https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/flow/maximum_flow.jl) - does that have what you need?

**Comment by juliohm** [comment]
@sbromberger I was using the latest stable, let me checkout the master branch...

Could you please point where the output is documented in that link? Thank you for this package :+1:

**Comment by juliohm** [comment]
I need read more about these algorithms, was trying to test them quickly as a black box, but this approach is not working.

**Comment by sbromberger** [comment]
The output is a tuple that contains the value of the maximum flow and the flow matrix. It's specifically documented [here](https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/flow/edmonds_karp.jl#L4) and [here](https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/flow/dinic.jl#L4) but probably could be better documented in the `maxiumum_flow()` docstring itself. 

It's implied by the usage notes in that docstring, however, and can be viewed in the tests as well. (This is not to argue against better documentation; it's there to provide you with other resources in the event you need to dig down into something else in the future.)

**Comment by sbromberger** [comment]
If all you need is min-cut, have you seen [this](https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/traversals/maxadjvisit.jl#L176-L180)?

**Comment by juliohm** [comment]
I am reading this paper by [Boykov et al.](http://www.csd.uwo.ca/~yuri/Papers/pami04.pdf) where they propose a new algorithm for the partition of graphs with two terminals in polynomial time. I am currently using Dijkstra's search in [my package](https://github.com/juliohm/ImageQuilting.jl/blob/master/src/boundary_cut.jl), but it has some limitations.

I really need to sit and read more about all these variations, they are slightly different.

What is the algorithm implemented by the `mincut()` function?

**Comment by sbromberger** [comment]
> What is the algorithm implemented in the mincut() function?

[It uses maximum adjacency](https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/traversals/maxadjvisit.jl#L187).

**Comment by juliohm** [comment]
@sbromberger how can we get the associated cut from the flow matrix? I understood that the cut is defined by the last residual graph after all iterations. I did the following:

```julia
f, F = maximum_flow(G, s, t, C, algorithm=DinicAlgorithm())
residualF = zeros(F)
for (u,v) in edges(G)
    residualF[v,u] = F[u,v]
    residualF[u,v] = C[u,v] - F[u,v]
end
```
I traverse the residual graph starting at `s`. All vertices that can be reached from `s` are assigned the label 1, whereas all others are assigned the label 2. Does it make sense?

**Comment by juliohm** [comment]
I am familiar with the source code now, the last question remains open, but this issue can be closed.
