### ISSUE TITLE
Removing edges of residual graph triggers an error

### ISSUE THREAD

**Issue by juliohm** [JuliaGraphs/LightGraphs.jl#302]
Is this expected behavior?

```julia
using LightGraphs

G = DiGraph(3)
add_edge!(G, 1, 2)
add_edge!(G, 1, 3)

resG = LightGraphs.residual(G)
for (u,v) in edges(resG)
    rem_edge!(resG, u, v)
end
```
>LoadError: BoundsError: attempt to access 1-element Array{Int64,1}:
 3
  at index [2]
while loading In[6], in expression starting on line 8

> in next at /home/julio/.julia/v0.5/LightGraphs/src/edgeiter.jl:52
 in anonymous at no file
 [inlined code] from essentials.jl:114

**Comment by CarloLucibello** [comment]
`edges(resG)` returns an iterator, which is invalidate if you modify the graph. yoy should go with
```julia
for (u,v) in collect(edges(resG))
    rem_edge!(resG, u, v)
end
```

**Comment by sbromberger** [comment]
Though I wonder why `residual` isn't exported.

**Comment by juliohm** [comment]
Thank you @CarloLucibello, this behavior is a little counter-intuitive for a first-time user. We should add a note in the docs, if there is none.
