### ISSUE TITLE
Functions signatures in docs

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGraphs/LightGraphs.jl#303]
The functions signatures is missing from most documentation. For example
``` julia
"""Produces a graph with edges that are only in both graph `g` and graph `h`.

Note that this function may produce a graph with 0-degree vertices.
"""
function intersect{T<:SimpleGraph}(g::T, h::T)
...
end
```
should be

``` julia
"""
    intersect(g, h)

Produces a graph with edges that are only in both graph `g` and graph `h`.

Note that this function may produce a graph with 0-degree vertices.
"""
function intersect{T<:SimpleGraph}(g::T, h::T)
...
end
```
or
``` julia
"""
     intersect{T<:SimpleGraph}(g::T, h::T)

Produces a graph with edges that are only in both graph `g` and graph `h`.

Note that this function may produce a graph with 0-degree vertices.
"""
function intersect{T<:SimpleGraph}(g::T, h::T)
...
end
```

**Comment by sbromberger** [comment]
That's because if you add them in the docstrings they'll get duplicated in the markdown. See [the docs](http://lightgraphsjl.readthedocs.org/en/latest/pathing/) for an example of how it is now.

**Comment by CarloLucibello** [comment]
I see. But if we don't put the signature in the docstring it won't show up in the help. Is there a way to cover both the help and the docs?

**Comment by jpfairbanks** [comment]
you can get the signatures using `methods(f)`. which includes the files and lines for the definitions.
it is a bit more verbose than what you expect but is auto-generated.

**Comment by sbromberger** [comment]
> But if we don't put the signature in the docstring it won't show up in the help

This isn't necessarily a bad thing. For one, @jpfairbanks rightly suggests `methods()` which will give ALL methods. Secondly, expanding on that a bit, a function can have multiple / many methods. Which ones go into the docstring? Why repeat them when `methods()` exists?

**Comment by CarloLucibello** [comment]
There are many reason for having the method signature in the 

- methods(d) doesn't show optional arguments
- in the docstrings one often refers to the name of the parameters in the signature, as in  
```
help?> save
search: save sparsevec SharedVector StackOverflowError AbstractVector AbstractVecOrMat Associative has_negative_edge_cycle isinteractive AbstractSparseVector ischardev AbstractMASVisitor SimpleGraphVisitor

  Saves multiple graphs in a dictionary mapping graph name to graph to stream io using graph type t.

  Saves a single graph g with name gname to stream io using graph type t. Returns the number of graphs written (1).
```
- the method signature is often too verbose and hard too read, especially with parametric types. One may want to write a more elegant and compact form 
- I expect the help to give me all the informations I need to use a function
- this is the standard for Base 

Having vastly different signatures is not a problem, they can all be reported in the docstring

I'm pushing a PR to (optionally) allow a signature to be included in the docstring withouth having it repeated twice in the generated docs

**Comment by sbromberger** [comment]
I'm ok with this (ref #307) but we have to make sure we're not removing any relevant information (see my comment in that PR).

**Comment by sbromberger** [comment]
Closing due to merge of #307.
