### ISSUE TITLE
Add NEWS.md file at root directory

### ISSUE THREAD

**Issue by diam** [JuliaGraphs/LightGraphs.jl#314]
Bonjour,
It would be nice to have a NEWS.md file in root directory  with the date (or some version number) and the main modifications abstract, much like the JuMP.jl package.
-- Maurice

**Comment by sbromberger** [comment]
Are you thinking this would be a changelog?

**Comment by diam** [comment]
More or less yes, a changelog with the user level selected modifications.

**Comment by jpfairbanks** [comment]
@diam can you propose a format for the entries so that they can be generated by git-log. We can start from the git-log output and summarize into a human usable CHANGELOG.md file.

**Comment by diam** [comment]
I agree that `CHANGELOG.md` would be a more adapted filename for a semi-automaticaly generated file, reserving `NEWS.md` for a higher level one.

`CHANGELOG.md` could be something like:

<pre>
## 0.0.8 - 2016-01-20
- some text for commit 5 
- some text for commit 4 
## 0.0.7 - 2016-01-01
- some text for commit 3 
- some text for commit 2 
- some text for commit 1 
## 0.0.0 - ???
- first commit 
</pre>

I also saw another example of Changelog at the bottom of ([yoo_vida/warp/README.md](https://github.com/trimf/julia/blob/master/templates/yoo_vida/warp/README.md)) which add a special prefix character for the type of commit. This could be adapted for LightGraphs.jl.

<pre>
* -> Security Fix
# -> Bug Fix
$ -> Language fix or change
+ -> Addition
^ -> Change
- -> Removed
! -> Note
</pre>

**Comment by jpfairbanks** [comment]
That looks good, would you like to write up an example for some previous releases to get us started?

**Comment by diam** [comment]
With the help of the following git command:
<pre>git log  --pretty=format:"%h%x09%an%x09%ad%x09%s" --date=short > all_git.log</pre>
I've started some `NEWS.md` file. It is mostly informative and I've not put the special prefix characters for the type of the commit.
Also there is no version number and the release date is purely arbitrary (I break the log about once a month).
Each item should probably be more self explanatory, or merge or skip or I've not keep the good ones.
Feel free to use it as you like.
-- Maurice

<pre>
## (no version) - unreleased
- reduce dependence on StatsBase (now only needed for binomial distribution)
- add savegml for GML format
- support reading/writing graphs in JLD files (Julia Data format)
- add **Boykov-Kolmogorov Max-flow/min-cut algorithm**
- test maximum_flow on multiple graphs
- add Nonbacktracking and Network types

## (no version) - 2016-01-26
- more robust graphml format support
- add StochasticBlockModel type (SBM) and tests
- add Pajek NET format support
- add function `incidence_matrix`, export and tests


## (no version) - 2015-11-30
- update edmonds_karp.jl, dinic.jl, bfs.jl
- adjacency lists are now sorted
- add crosspath, BinaryTree, and RoachGraph
- add scalar and tensor product
- change the signature of connected_components! to accept SimpleGraphs
- more consistency in randgraphs


## (no version) - 2015-10-31
- add configuration model random graph generator
- added **maxmimum_flow based on Edmond Karp's algorithm**
- performance Improvments
- **Julia v0.4.0 now required**
- docs for GraphPlot.jl
- added **maximal cliques** from Graphs.jl
- add dot graphs format (save and load)
- generalize community_detection algorithm for k>2 using kmeans clustering
- add stochastic block model
- add random walks
- add local_clustering_coefficients
- add core_periphery_deg
- **add JuMP and Clp requirement**
- implement bipartite_matching through linear programming

## (no version) - 2015-09-22
- demonstrate that most of the cost is to create the Graph structure
- manual memory management around BFS 3X improvement
- connected_components in linear time
- add the function writegraphml
- fix julia 0.3 compatibility

## (no version) - 2015-08-27
- removed DataStructures as a requirement
- rename AbstractGraph to SimpleGraph
- now requiring LightXML, ParserCombi
- new imports from Base
- add a random regular graph generator
- first cut at directed random regular graphs
- added support for precompilation
- persistence now handles multiple graphs per file
- integration of GraphMatrices with operators support
- general cleanup and doc update

## (no version) - 2015-06-30
- added Graph and Digraph generators for SparseMatrixCSC
- add katz centrality
- bfs / dfs enhancements, connectivity, and modifications to subgraphs
- implement getindex for induced_subgraph
- changed splice\! to deleteat\! for rem_edge\!, fixed uniqueness
- moved from Distributions to StatsBase

## (no version) - 2015-05-30
- new dijkstra
- move git to JuliaGraphs subproject
- make Graph, Digraph constructors more uniform
- add JuliaGraphs/pagerank

## (no version) - 2015-03-18
- test optimization
- random graphs
- now works for directed graphs
- faster induced subgraphs, fix deprecation warning in tests
- update README.md

## (no version) - 2015-02-18
- rename SimpleGraphs to LightGraphs
- allow distance matrices
- initial docs

## (no version) - 2015-01-27
- rename FastGraphs to SimpleGraphs
- bellman-ford
- edge_dists in dijkstra
- make work with GraphLayout

## 0.0.0 - 2015-01-15
- initial commit as FastGraphs.jl

## Prefix characters to be use!

* -> Security Fix
# -> Bug Fix
$ -> Language fix or change
+ -> Addition
^ -> Change
- -> Removed
! -> Note
</pre>

**Comment by jpfairbanks** [comment]
We could use https://github.com/skywinder/github-changelog-generator for this

**Comment by juliohm** [comment]
Another alternative that is even easier and clean is to take advantage of GitHub release features. We can write a draft and update it whenever we make a change that we consider should be noted.

The downside is that we don't have the changes with the code, only on the website. I've adopted GitHub releases and attobot for my packages, it is been super productive.

**Comment by sbromberger** [comment]
@Juliohm - in the past, releases were tagged automatically using the `Pkg` commands. Anything we can do to make it easier to provide change logs would be most welcome. Can you describe / provide a URL to an example of how this might be done with GitHub releases and attobot?

**Comment by juliohm** [comment]
@sbromberger the [attobot README](https://github.com/attobot/attobot) and the [GitHub Releases](https://help.github.com/articles/creating-releases) are the only pages I used to get GitHub Releases working smoothly with Julia tags.

I don't know if it solves the NEWS.md issue in its entirety, but it definitely makes our lives much easier. We can all work on a draft release and release it when we need by pressing a button. The attobot takes care of the rest.

**Comment by sbromberger** [comment]
Oh, shoot - yes. See https://github.com/JuliaGraphs/JuliaGraphs-meta/issues/4. Would you mind working on getting release notes integrated with this process?

**Comment by juliohm** [comment]
@sbromberger can you explain the level of integration you are expecting? I am not very familiar with web programming and webhooks on github to make it automatic, what I was thinking was just use the attobot to draft the NEWS when we are drafting the release, maybe that is not the issue that is being raised in this thread, please correct me if I am wrong.

**Comment by sbromberger** [comment]
I'm not expecting much of anything :) How does attobot draft the NEWS?

**Comment by juliohm** [comment]
It is just a simple draft on the GitHub Releases page, you can go to here: https://github.com/JuliaGraphs/LightGraphs.jl/releases and click in the button on the right top. We can then add bullets to the draft as we go. After we are done, we publish the draft and attobot does the magic.

**Comment by jpfairbanks** [comment]
When you publish the release, attobot goes to METADATA and handles all the julia packaging stuff right? The process is still initiated by us writing the release, right?

**Comment by juliohm** [comment]
Exactly, attobot will act only if we press the publish button. We can edit
the draft, save many times. When we are ready we press the button.

**Comment by juliohm** [comment]
Will the `NEWS.md` file be added or are we sticking to the Attobot + GitHub releases approach?

**Comment by sbromberger** [comment]
I think we might consider a NEWS.md file for this abstract stuff. I don't know yet.

**Comment by sbromberger** [comment]
Attobot and release notes seems to be the best way to do this for now, so closing out.
