### ISSUE TITLE
Random Graph Generator Validation

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/LightGraphs.jl#323]
We should validate the random graph generation by sampling from them and asserting various properties. For ER graphs there is a long catalog of such properties. For the more complex models there should still be things to assert. All of the tests would need to reflect the fact that the properties are usually with high probability. 

If someone wants to work on this I can help but I am not really an expert on testing randomized software.
This issue should serve as a reminder and opportunity for anyone looking to get involved in the project.

**Comment by CarloLucibello** [comment]
why you want to do this? the algorithms for random graph generation are usually quite simple, some basic tests and a careful review of the code should be sufficient....

**Comment by sbromberger** [comment]
See also discussion in #348 - merging the suggestion there for an MC-like test suite into this one since they're somewhat related. (hope that's ok, @jpfairbanks)

**Comment by jpfairbanks** [comment]
Yeah @arekfu mentioned some of the Monte Carlo type things I was thinking.
