### ISSUE TITLE
missing edgecolormap in BFS traversal

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGraphs/LightGraphs.jl#331]
while it is present in DFS. 

Maybe there is a way, to maximize efficiency, to choose if edge discovery has to be considered or not

**Comment by jpfairbanks** [comment]
Do you have more details?

**Comment by CarloLucibello** [comment]
on this? 
>Maybe there is a way, to maximize efficiency, to choose if edge discovery has to be considered or not

no! just whishfull thinking :)

**Comment by sbromberger** [comment]
I don't think this is correct. We have calls to `open_vertex`, `discover_vertex!`, and `examine_neighbor` in the BFS code. Am I misunderstanding your issue?

**Comment by CarloLucibello** [comment]
@sbromberger you are right, actually I misundertstood the issue. Actually what is missing in BFS with respect to DFS is an edgecolormap, whose elements should be passed to examine_neighbor. At the moment `examine_neighbor` in BFS always takes a -1 dummy argument.

This could be fixed easily, I'll do it along the other changes in #332 

@jpfairbanks For traversals not needing an edgecolormap maybe one could define a dummy dict-like type for edgecolormap that doesn't allocate memory and doesn't perform any computation...

**Comment by sbromberger** [comment]
can we close this with the merge of #332?

**Comment by CarloLucibello** [comment]
Yep
