### ISSUE TITLE
Pagerank computation

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/LightGraphs.jl#34]
Rita asked on the list for Pagerank computation.
This paper [corso2005](https://projecteuclid.org/euclid.im/1150474883) shows how to compute it as either and eigenvector problem or a linear system in the laplacian. The fastest and easiest way to do this in julia is to dump the adjacency matrix out of the Graph and do the linear algebra with either `eigs` or [Krylov.jl](https://github.com/optimizers/Krylov.jl/)

**Comment by sbromberger** [comment]
Also see

https://github.com/purzelrakete/Pagerank.jl
https://gist.github.com/domluna/2b9358ccc89fee7d5e26
http://networkx.github.io/documentation/networkx-1.9.1/reference/algorithms.link_analysis.html#module-networkx.algorithms.link_analysis.pagerank_alg

**Comment by sbromberger** [comment]
Completed via #50.
