### ISSUE TITLE
what's up with warnings when using LightGraphs?

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#349]
See https://gist.github.com/sbromberger/6a81432250b093b09d442a008177ab94. This happens on a clean install.

**Comment by sbromberger** [comment]
This is likely not directly LG-related, but it sure smells funny.

**Comment by juliohm** [comment]
@sbromberger this is because the `Combinatorics` package is being imported on Julia 0.4. We need to import inside a version check like here: https://github.com/juliohm/ImageQuilting.jl/blob/master/src/ImageQuilting.jl#L21-L23

I am getting the warnings indirectly when I load LightGraphs in my package.

**Comment by CarloLucibello** [comment]
better tag a new version now that Cominatorics has been removed

**Comment by juliohm** [comment]
Did you tag a new version? Waiting for the merge?

**Comment by sbromberger** [comment]
We tagged 0.5.3 but I haven't tested to see whether it actually resolved the problem. In any case, I closed out the issue because it seems as if it's not something LG can fix.

**Comment by juliohm** [comment]
I'll wait for the tag to be merged, thanks.

-Júlio

**Comment by sbromberger** [comment]
Not sure what you mean. 0.5.3 hit METADATA a few days ago.

**Comment by juliohm** [comment]
The last time I updated I saw LG 0.5.2, will double check. I still see the
unconditional import of Combinatorics.jl

-Júlio

**Comment by sbromberger** [comment]
See https://github.com/JuliaLang/METADATA.jl/pull/5056 - but yes. I don't think we changed the import of Combinatorics.

**Comment by juliohm** [comment]
Combinatorics.jl should only be imported in Julia 0.5 and beyond. :)

-Júlio

**Comment by sbromberger** [comment]
We're not importing Combinatorics now, yet I'm seeing the errors in 0.4. What am I missing? Is one of our dependencies importing it?

**Comment by CarloLucibello** [comment]
wasn't 0.53 tagged before the removal of Combinatorics? We should tag a 0.54

**Comment by sbromberger** [comment]
We never included Combinatorics.

**Comment by sbromberger** [comment]
Ah, yes. I see now. Let me go ahead and tag 0.54.
