### ISSUE TITLE
Removing vertices in phylogenies

### ISSUE THREAD

**Issue by Ward9250** [JuliaGraphs/LightGraphs.jl#364]
Hi,

I'm making progress over at Bio.jl creating phylogenies and I've got to the point where I'd like to code function that will prune a clade (vertex with one parent and multiple (typically two, children)) from a tree. I've had a look at the rem_vertex method and understand it swaps v with n and so you have to be careful with indexing. For the phylogenies it's slightly more complex as they have an order to the vertices. The n leaves are vertices 1:n, the root being n + 1 and the internals being (n + 1) until whatever. So I'd like some advice on perhaps the best way to maintain this numerical order. The best thing I've come up with so far is as follows:

```julia
julia> using LightGraphs

julia> g = DiGraph(9)
{9, 0} directed graph

julia> add_edge!(g, 6, 7)
edge 6 - 7

julia> add_edge!(g, 7, 1)
edge 7 - 1

julia> add_edge!(g, 7, 2)
edge 7 - 2

julia> add_edge!(g, 6, 8)
edge 6 - 8

julia> add_edge!(g, 8, 3)
edge 8 - 3

julia> add_edge!(g, 8, 9)
edge 8 - 9

julia> add_edge!(g, 9, 4)
edge 9 - 4

julia> add_edge!(g, 9, 5)
edge 9 - 5

julia> g
{9, 8} directed graph

julia> collect(edges(g))
8-element Array{Pair{Int64,Int64},1}:
 edge 6 - 7
 edge 6 - 8
 edge 7 - 1
 edge 7 - 2
 edge 8 - 3
 edge 8 - 9
 edge 9 - 4
 edge 9 - 5

# This creates a phylogeny with structure represented by Newick string: ((1,2)7,(3,(4,5)9)8)6;
# i.e. 6 is root, 7 is internal clade parent of tips, 1 & 2, 8 is internal parent of tip 3 and another internal clade 9, which is parent of tips 4 and 5.
```

Say I want to prune off clade 7, (and with it 1 and 2 as they are connected). I can use `rem_vertex!(g, 7)` which yields:

```julia
collect(edges(g))
5-element Array{Pair{Int64,Int64},1}:
 edge 6 - 8
 edge 7 - 4
 edge 7 - 5
 edge 8 - 3
 edge 8 - 7
```

I can see that basically 7 was removed, and clade 9 renamed to 7, because it was `nv(g)` and > 7. This is a simple enough thing to account for in any indexed data. But I now have the problem that 1, and 2 are still there, they're just not connected to anything! My initial solution I can think of is to take the min of the tips (3), and since the diff is 2 to get one, minus that diff of 2 from every vertex, basically shifting the connected vertices to start from 1 again, reindexing data as I go. Is this reasonable or are there better ways?

Many thanks,
Ben.

**Comment by sbromberger** [comment]
If I understand it correctly you want to prune from a vertex all its dependents S well. I think the best way to do this is to use traversal (bfs or dfs) to enumerate all the children of this directed graph and then build an induced subgraph that does not include these nodes. 

alternately you could remove vertex 7 and then rebuild the graph using a traversal or connected component from the root node, which will eliminate nodes 1 and 2.

Both of these will have the side effect of renumbering your vertices though. There's no good way to avoid this given the constraints.

**Comment by sbromberger** [comment]
You could also remove the in_edges from vertex 7 and then grab the connected component of the root. In addition, if you can 'ignore' the disconnected subgraph centered at 7, you can use the main graph without renumbering.

**Comment by CarloLucibello** [comment]
I like Seth's graph traversal solution, I think it could be implemented like this 
```julia
i = 7
p = 6 #the parent of i
vmap = Dict(p=>1)  # sets the parent of i as seen 
traverse_graph!(g, BreadthFirst(), i, GDistanceVisitor(), vertexcolormap=vmap)
for (v, w) in vmap
    v == p && continue
    rem_vertex!(g, v)
   # do your reindexing here knowing that the v has been swapped with nv(g) before removal
end
```

**Comment by Ward9250** [comment]
Thanks guys, I'll try these solutions tonight. The only other way I could think of last night for doing this and maintaining the numeric order was something like:
```
FOR t in each tip to drop:
    remove position t from fadjlist and badjlist;
# Shift all numbers in faddlist and badjlist down by the number of t's removed;
FOR i in fadjlist:
    FOR j in i:
        i[j] -= number of tips dropped;
FOR i in badjlist:
    FOR j in i:
        i[j] -= number of tips dropped;
```

I think something akin to this might work. Obviously there would need to be code to reindex the data-structures but I'll let the indexer types themselves handle that. At the end you just have to take care to remove any internal nodes without children, but the basic idea is removing vertices and then shifting the integer values of the vertices by how many vertices were removed.

**Comment by sbromberger** [comment]
In general you don't want to muck around with the internal data structures like fadjlist and badjlist. Lots of things depend on properties of those structures that, if they break or become nonconformant will cause undefined behavior in the rest of the module.

**Comment by sbromberger** [comment]
If you want to preserve the order and know which vertices you need to prune (that is, you know the graph/tree layout in advance), you might also consider a traversal to ensure that the pruned vertices are indexed at the end. That way, when you remove them, you won't impact the other vertices.

I think I'd prefer just creating a series of disconnected subgraphs by removing edges instead of worrying about renumbering issues with vertex removal. See https://github.com/JuliaGraphs/LightGraphs.jl/issues/364#issuecomment-218028890 for this idea. Basically at the end of the exercise you'd have all the vertices, but the subgraph 7-1-2 would be disconnected from the larger graph rooted at 6, and if you restrict any operations to the larger graph then you'd be guaranteed not to touch the "pruned" vertices, and you'd preserve the vertex indices.

**Comment by Ward9250** [comment]
@sbromberger I'm begining to lean towards the ignore the nodes idea. You can still specify tips as vertices 1:n and the root as always vertex n+1. The only challenge then would be in adding tips, but you typically know the number of tips before tree construction, so it should not be an issue. Thanks for discussion, I'll see what kind functions I can come up with and try the different suggestions.

**Comment by sbromberger** [comment]
Awesome. Mind if I close this out? You should always feel free to open new issues as you come across them.

**Comment by Ward9250** [comment]
I'm good for you to close. Thanks @sbromberger, @CarloLucibello !

**Comment by sbromberger** [comment]
Thanks, @Ward9250 - again, feel free to open up new issues as needed.
