### ISSUE TITLE
examine_neighbor! signature

### ISSUE THREAD

**Issue by arekfu** [JuliaGraphs/LightGraphs.jl#367]
The `examine_neighbor!` function is called with different method signatures depending on the traversal algorithm:
```julia
# BFS
examine_neighbor!(visitor, u, v, u_color, v_color, e_color)
# DFS, MaximumAdjacency
examine_neighbor!(visitor, u, v, v_color, e_color)
```
As a consequence, the visiting logic is not entirely decoupled from the traversal algorithm.

Is this done on purpose?

**Comment by CarloLucibello** [comment]
definitely a bug

**Comment by arekfu** [comment]
So which one is the buggy one? Note that the definition for the fallback implementation (the one with `SimpleGraphVisitor`) has 6 args, like BFS.

**Comment by CarloLucibello** [comment]
I would keep the 6 arguments one, let's keep it general and flexible. I don't thing there is any performance difference between the two versions, most probably and especially in the simplest cases the code gets inlined over there
