### ISSUE TITLE
Make Barabási-Albert model more flexibel

### ISSUE THREAD

**Issue by devmotion** [JuliaGraphs/LightGraphs.jl#372]
In the [paper](http://www.barabasilab.com/pubs/CCNR-ALB_Publications/199910-15_Science-Emergence/199910-15_Science-Emergence.pdf) where Barabási and Albert first proposed their scale-free model they write on page 511:

> starting with a small number (m_0) of vertices, at every time step we add a new vertex with m (<= m_0) edges that link the new vertex to m different vertices already present in the system.  [...] After t
time steps, the model leads to a random  network  with t+m_0 vertices and mt edges.

The same definition can also be found in [another paper](http://www.barabasilab.com/pubs/CCNR-ALB_Publications/200201-30_RevModernPhys-StatisticalMech/200201-30_RevModernPhys-StatisticalMech.pdf) from Barabási and Albert on page 71:

> The algorithm of the Barabási-Albert model is the following: 
(1) Growth: Starting with a small number (m_0) of nodes, at every time step, we add a new node with m (<= m_0)  edges that link the new node to m different nodes already present in the system.
(2) Preferential attachment: [...]
After t time steps this procedure results in a network with N = t + m_0 nodes and mt edges.

The current implementation only allows the creation of Barabási-Albert models with m_0 = m isolated initial nodes, but it is not possible to build a Barabási-Albert model with m_0 > m isolated initial nodes.

Since sometimes in literature the initial nodes in the Barabási-Albert model are even totally connected or randomly connected (see e.g. [this paper](http://www.guimaraes.bio.br/011.pdf)) the possibility to use any initial graph for the model would add even more flexibility.

In case you would like to add such a feature I can send a pull request (although I've never done this before...).

**Comment by sbromberger** [comment]
I'd be interested in seeing the code for this (and getting others to review it). Our priority is first on correctness, then on performance, so we'd want to make sure the tests work and we'd want to see benchmarks comparing the proposed changes to the existing code.

Let me know if you need guidance on developing a PR.
