### ISSUE TITLE
ParallelGraphs

### ISSUE THREAD

**Issue by pranavtbhat** [JuliaGraphs/LightGraphs.jl#377]
Hi Guys!
I'm working on a GSOC project, [ParallelGraphs.jl](https://github.com/pranavtbhat/ParallelGraphs.jl), a general purpose graph library. The main goal is is to allow users to label vertices and assign key value pairs to vertices and edges. I aim to support the SQL-like queries provided by GraphFrames, and also hope to have distributed graph processing using [ComputeFramework.jl](https://github.com/shashi/ComputeFramework.jl). Please do check out my work :)

I'm planning on using LightGraphs for all of the sequential algorithms, since it already has pretty much everything implemented. I'm having a bit of an issue however, as ComputeFramework may be compatible only with `Julia 0.5+`, and LightGraphs is compatible with only 0.4 as of now. Also `Julia 0.4` doesn't have `SparseVector`, a datastructure I plan to use.

I noticed that LightGraphs uses `Requires.jl`. I think this may be the reason builds fail on 0.5. Refer: https://github.com/shashi/ComputeFramework.jl/pull/33#issuecomment-219270869

**Comment by sbromberger** [comment]
We are going to attempt to remove the dependence on `Requires.jl` at some point, but it will require us to refactor some of the code out of the core LightGraphs module. Ref the (very long) discussion in https://github.com/JuliaGraphs/LightGraphs.jl/issues/278.

Best of luck with your project. Parallelism is one of those things that is on the roadmap for LG but it's a challenge to beat the performance of functional languages that don't required shared state.

**Comment by jpfairbanks** [comment]
I think a PR that added 0.5 support would be merged pretty quickly. Good luck on your gsoc project. Imo It will be a killer app for Julia!

**Comment by pranavtbhat** [comment]
Thanks!

**Comment by pranavtbhat** [comment]
Has the usage of `SparseMatrixCSC` over adjacency lists been considered?  Would this change too much in the package?

SparseMatrixCSC offers essentially the same asymptotic bounds, with better cache performance, since all the data is stored contiguously. Also subgraphing, and edge listing is much more efficient.

**Comment by sbromberger** [comment]
@pranavtbhat 

> Has the usage of SparseMatrixCSC over adjacency lists been considered?

Yes - I tried an implementation a while back.

> Would this change too much in the package?

Yes. There were significant changes to the way even the most basic operations are performed. Edge insertion, for example, was horribly inefficient, as was any operation that required random access to edge data.

**Comment by sbromberger** [comment]
Hi all,

I'm closing this out since it seems discussion has run its course. @pranavtbhat - good luck on ParallelGraphs!
