### ISSUE TITLE
triangles

### ISSUE THREAD

**Issue by juyeongkim** [JuliaGraphs/LightGraphs.jl#378]
Has [triangles](https://networkx.readthedocs.io/en/stable/reference/generated/networkx.algorithms.cluster.triangles.html) implemented in LightGraphs.jl?

**Comment by sbromberger** [comment]
Hi @juyeongkim - not yet. It would be a welcome PR though :)

**Comment by CarloLucibello** [comment]
this is related to global and local clustering coefficients, that are already implemented in LG. It would be nice to have the triangle function as well though

**Comment by juyeongkim** [comment]
@sbromberger here is my implementation of networkx's [triangles](http://networkx.readthedocs.io/en/stable/_modules/networkx/algorithms/cluster.html#triangles):

```julia
function triangles(G)
  tris = []
  fadjs = fadj(G)
  for v in vertices(G)
    vs = setdiff(Set(fadjs[v]), Set([v]))

    ntriangles = 0
    for w in vs
      ws = setdiff(Set(fadjs[w]), Set([w]))
      ntriangles += length(intersect(vs, ws))
    end
    push!(tris, ntriangles / 2)
  end
  return tris
end
```
I am new to Julia and still learning, so I am not sure if this is the right way to do it in Julia... But thank you for encouraging me to try it out!

@CarloLucibello this is great! Thank you for pointing this out. According to the documentation of `local_clustering`, `a` is the number of triangles. That means I could instead do:

```julia
function triangles(G)
  return local_clustering(G)[1]
end
```

**Comment by sbromberger** [comment]
So - do we have triangles via `local_clustering`?

**Comment by juyeongkim** [comment]
@sbromberger I think so.

```julia
local_clustering(g, v)
```
> Returns a tuple (a,b), where `a` is the number of triangles in the neighborhood of `v` and `b` is the maximum number of possible triangles. It is related to the local clustering coefficient by r=a/b.

http://lightgraphsjl.readthedocs.io/en/latest/community/#clustering-coefficients

**Comment by sbromberger** [comment]
@juyeongkim if you wanted to create a PR with an alias function for triangles, I'd be ok with merging it :)

**Comment by juyeongkim** [comment]
Done! Pull Request #381
