### ISSUE TITLE
graph dismantling

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGraphs/LightGraphs.jl#386]
Some efficient and easy to implement algorithms have appeared recently for the problem of graph dismantling. We should implement them in LightGraphs

One is here

http://arxiv.org/pdf/1506.08326

and another here

http://arxiv.org/pdf/1607.03276v1.pdf

**Comment by sbromberger** [comment]
Closing this out because it doesn't appear to have gotten any traction.
