### ISSUE TITLE
Move functions using JuMP and GraphMatrices into separate packages

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#389]
Discussion on the best way to eliminate dependencies on complex (non-leaf) packages.

Also: whatever we decide, my strong opinion is that we should explicitly import functions from third-party packages: that is,

`using Clustering: kmeans`
vs
`using Clustering`

**Comment by jpfairbanks** [comment]
I agree with explicit imports

James Fairbanks, PhD

**Comment by CarloLucibello** [comment]
You are proposing to create another package, let's say LightGraphsExtras, containing the two or three functions relying on JuMP and GraphMatrices? maybe also MatrixDepot, Clustering, GZip, ParserCombinator,...

I don't think the situation is so ugly that it's worth the extra maintenance effort. Also, what about the docs, we would have to keep separate documentations?

In absence of user's explicit complaints I would keep things as they are. Or we could just threathen to @jpfairbanks to remove GraphMatrices's related methods if he doesn't upgrade the package :)

**Comment by sbromberger** [comment]
I am proposing to create multiple packages based on dependencies, so that folks who don't need specific functionality don't have to download and precompile all the cruft that comes with certain functions. JuMP and GraphMatrices are the first of two, but I'm really less concerned with GraphMatrices since it's small.

The other current advantage is that the viability of what I'm calling "LG Core" would no longer be dependent on advances in the other packages. This just bit us with your last PR, where I had to put explicit versioning in JuMP so as not to cause errors (they renamed a function we used).

**Comment by sbromberger** [comment]
#391 has convinced me of the wisdom of this approach and has also caused me to look at our use of JuMP, which supports precisely ONE function.

**Comment by sbromberger** [comment]
Closing this because we're doing it :)

**Comment by CarloLucibello** [comment]
what about a unique package (e.g. LightGraphsExtras) wich contains 
- matching (get rids of JuMP)
- community detection (Clustering)
- GraphMatrices stuff
- the submodule Databases (MatrixDepot) 
?

also, I would not reccomend it, but notice that if we factorize out also
- randgraphs (Binomial)
- persistence (GZip, LightXML, ParserCombinator)

we would be dependence free

**Comment by sbromberger** [comment]
I'd rather not have a "dumping ground" repo that contains everything. I think splitting them up into separate repos is the right way to go, so people can pick and choose which modules they want.

I like your list. matching is pending right now, and graphmatrices is probably next. Then community detection, and then possibly matrixdepot.

I also agree that randgraphs and persistence need some more thought.

**Comment by CarloLucibello** [comment]
From JuliaGraphs/LGmatching.jl#1 and JuliaLang/METADATA.jl#5717 looks more like we are dumping and hiding functionalities

My preferences are in order 

1) keep everything in LightGraphs, since the dependencies situation is not ugly at all, it is easier to mantain, and I don't know of any graph library which comes in chunks

2) have a LightGraphsExtras.jl, again easier to mantain  then multiple repos, and would have more visibility. Of course it should be registered to METADATA. Also in this case I think that docs should be centralized in the LightGraphs page if it's not too tricky (the transition to Documenter.jl should make possible to fully automatize the process)

**Comment by sbromberger** [comment]
1) isn't viable given the problems of the last two days (and ongoing issues relating to 0.5 migration).
2) won't scale as we move stuff out of core LightGraphs.

We've discussed this for months. I'm surprised at the sudden objection now that we're actually executing.

**Comment by CarloLucibello** [comment]
my objection is longstanding and never wavered :) 
Any decision of the last two days has been taken hastily and unilaterally : whether to split or not, how to split (one or many), and even namings  (LGmatching )

> 2) won't scale as we move stuff out of core LightGraphs.
why not? I can envision a much worse situation with many packages

**Comment by sbromberger** [comment]
OK. What if we created a top-level Julia package called "LightGraphExtras" but have each of these things (matching, clustering, etc.) be separate modules within that package, sort of like how we're doing with LightGraphs.Datasets? Would that alleviate your objections?

**Comment by CarloLucibello** [comment]
Yes it would but ... still I don't see the point in creating different submodules (we are talking about one or two functions each). If the same would have been done in LightGraphs we would have a dozens of submodules, and what for? In fact I would also remove the submodule Datasets once we move it to LightGraphsExtras, since it exports only three functions (smallgraph,MDGraph, MDDiGraph) it doesn't clutter the namespace

Anyway I don't want to be always  the [Bastian Contrario](http://www.wordreference.com/iten/Bastian%20contrario), so let's do as you please

**Comment by sbromberger** [comment]
I think things like Matching will grow over time to be more than one function, and I'd like to have a modular design for that. My issue with this is that I want people to be able to use the parts of LightGraphs that they need without having to download a bunch of useless dependencies. That is, if someone wants Datasets, they shouldn't have to download JuMP.

**Comment by CarloLucibello** [comment]
But if we don't use Requires.jl we would have to put in REQUIRE of LightGraphsExtras each of the dependencies of the submodules. Am I wrong?

**Comment by sbromberger** [comment]
No, you're right - which is why I really prefer separate packages with their own REQUIRE files. But I'm willing to compromise a bit.

**Comment by CarloLucibello** [comment]
ok, let's factorize at least matching, graphmatrices and community detection  into LightGraphsExtras right away, once done that the work to make LG compatible with 0.5 is already done, while LGExtras will need some extra care

**Comment by sbromberger** [comment]
Sounds like a plan. We'll revisit once we get LG working with 0.5.
