### ISSUE TITLE
Tests fail without an LP solver

### ISSUE THREAD

**Issue by tkelman** [JuliaGraphs/LightGraphs.jl#391]
So, on PkgEval now - http://pkg.julialang.org/detail/LightGraphs.html

Rather than doing `Pkg.add("Clp")` in `.travis.yml`, it would be better to add it to a `test/REQUIRE` file.

**Comment by sbromberger** [comment]
Yup, thanks. This has pushed me to implement #389 right away for `src/matching.jl`.

cc @CarloLucibello @jpfairbanks
