### ISSUE TITLE
Tag version without Requires.jl as dependency

### ISSUE THREAD

**Issue by juliohm** [JuliaGraphs/LightGraphs.jl#394]
Requires.jl is causing a build failure in my package on Julia v0.5. Could you please confirm that LightGraphs.jl is not using Requires.jl anymore? Is there a tag for the modification already?

**Comment by sbromberger** [comment]
Make sure you're on 0.6.1.

**Comment by juliohm** [comment]
Thank you @sbromberger, I should see a successful build soon. Closing the issue.

**Comment by sbromberger** [comment]
Just FYI, it looks like GraphMatrices doesn't yet play well with 0.5.

**Comment by CarloLucibello** [comment]
@juliohm you may want to check #388

**Comment by juliohm** [comment]
My builds are failing on Julia v0.5 because of missing LightGraphs.jl tags: https://travis-ci.org/juliohm/ImageQuilting.jl/jobs/154944547. How to get it working?

Julia is getting close to release v0.5 (https://github.com/JuliaLang/julia/milestone/14), I am afraid this will cause trouble for my colleagues that are using my code.

**Comment by sbromberger** [comment]
We have 0.5 support in the works. Please note that we're only committing to ensuring proper builds on whatever Julia version is stable. Until 0.5 is released, that means the 0.4.x branch.

**Comment by juliohm** [comment]
This means that every package that depends on LG won't build successfully
on Julia nightly even if the developer is willing to maintain both builds?

-Júlio

**Comment by sbromberger** [comment]
That's probably what it means. Unless we've got people willing to submit PRs to ensure compatibility with bleeding edge versions, there's not a whole lot we can do.

**Comment by juliohm** [comment]
What is it that is breaking the build in Julia v0.5?

-Júlio

**Comment by sbromberger** [comment]
see https://github.com/JuliaGraphs/LightGraphs.jl/pull/413

**Comment by sbromberger** [comment]
@juliohm please check out the `bleeding-edge` branch for 0.5 and let me know whether it works.
