### ISSUE TITLE
possible memory issue... guesses?

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#396]
so,

```
g = Graph(30676594,62500000)
```

results in an 8-gig Julia instance, while `whos` shows `g` using ~1.2 gigs. what's with the extra memory allocations?

**Comment by jpfairbanks** [comment]
run gc() afterwards? to garbage collect some temporary arrays?

**Comment by sbromberger** [comment]
Doesn't help. The issue, I think, is that Julia's zealousness in allocating memory on vector growth is hitting each vector in `fadjlist`.

**Comment by TotalVerb** [comment]
I believe the actual problem here is that there is a lot of memory overhead (about 80 bytes) to using an array structure, and the graph being tested is very sparse, so each individual vector is small. Compared to the 80 bytes of overhead per vector, the additional space allocated is very small.

**Comment by sbromberger** [comment]
> vectors in vectors incur an additional penalty

Is there another data structure that would be better here? (I'm shuddering to think about how complicated a sparse matrix would be.)

**Comment by datnamer** [comment]
Doesnt parallelgraphs have a sparse matrix backend?

**Comment by sbromberger** [comment]
@datnamer It might. Insertions and accesses into sparse matrices are relatively expensive.

**Comment by datnamer** [comment]
I wonder if this can be made better with the array buffer concept...Just have a contiguous block of memory that julia points to and use type information to carve it into virtual chunks.
