### ISSUE TITLE
testing coverage for spectral

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#398]
@jpfairbanks I managed to clobber spectral.jl testing when we moved GraphMatrices out into LGE. Would you mind taking a look at the [coverage stats](https://codecov.io/gh/JuliaGraphs/LightGraphs.jl/src/45cbd00eedbaabd81f99e012b101ae598ba81da4/src/spectral.jl) and letting me know what we need to add / change to get things back to 💯%?

**Comment by jpfairbanks** [comment]
It is the tests for community detection with the nonbacktracking operator. We might want to put the nonbacktracking operator definition into GraphMatrices along with the Katz Centrality stuff. Do you want to bring All of GraphMatrices into a submodule of LG? LightGraphs.LinAlg for example?

**Comment by sbromberger** [comment]
Yes - per discussion last week, I think that's a great idea. For others who are reading: the proposal is to deprecate GraphMatrices.jl and move the code directly into LightGraphs as a submodule.

@jpfairbanks - I'll leave it to you to organize the new LightGraphs.LinAlg submodule. Do what you think is most appropriate.

**Comment by jpfairbanks** [comment]
I added these test back with a recent PR right?
We could close this issue.

**Comment by sbromberger** [comment]
Good idea, but I'd still love for you to merge GraphMatrices :)
