### ISSUE TITLE
Algorithms for other types of flows

### ISSUE THREAD

**Issue by Azzaare** [JuliaGraphs/LightGraphs.jl#400]
In NetworkFlows.jl, I have written (a long time ago), a couple of algorithms for variants of the max-flow problem. At that time, LightGraphs.jl was not as advanced. Instead of continuing the work on NetworkFlows, I would rather integrate the few algorithms specific to NetworkFlows.jl into LightGraphs.jl.

The algorithms are as follows:
- [x] Restricted max-flow : a max-flow f(x) where the capacities are restricted by the parameter x. Main application is to compute the next algorithm.
* Multiroute Flow : A max-flow with natural resilience on the edges with direct applications.
   - [x] Using Kishimoto Algorithm
   - [x] Using Extended Multiroute Flow (EMRF) : allows the number of routes to be non-integer
- [x] EMRF : computes the breaking points of the multiroute flow when the number of route is non-integer and parametric. Makes use of the restricted max-flow mentioned above. Can also be used to compute Network Interdiction (exactly for some category of networks)

Additionally, those 2 algorithms would be called in a set of functions in LightGraphsExtras.jl to solve the Network Interdiction problem (in conjunction with the use of JuMP).

Does that sound fine?

**Comment by sbromberger** [comment]
So, we'd be happy to take these contributions - thanks! Couple of questions:

1) do the flow functions require any dependencies not already included in master?
2) is the network interdiction problem the same as described by [Gutfraind, Hagberg, *et al*](http://arxiv.org/pdf/1009.0556.pdf)?

**Comment by Azzaare** [comment]
Nice, I will take care of it soon!

1) No, it only requires a max-flow function that is in master

2) Yes and no. It is the same family of problem (the interdiction works in the same way), but instead of minimizing the shortest path after some interdiction, the objective is to maximize the flow.
Also, it can be used to solve or approximate the Adaptive version of Network Interdiction (where the flow is computed before the attacks) as described by [Bertsimas, et al.](http://dx.doi.org/10.1016/j.orl.2015.11.005)
There exist a couple of algorithm that solve Network Interdiction in polynomial time for some category of graphs. There is also some approximation available, and of course a solver (through JuMP) can be used.
So my idea was to solve or approximate this problem in LightGraphsExtra. If the instance can be solved in polynomial time with some algorithms (including the multiroute flow), call them from LightGraphs. If not call a MILP solver through JuMP.

**Comment by CarloLucibello** [comment]
those seem nice additions to LG and LGE, a big :+1:

**Comment by Azzaare** [comment]
OK, I'm back on implementing the algorithms mentioned above. I edited some details on what to expect in the top post.

I have the code for the Kishimoto algorithm ready and tested. However I have some trouble with the doc. I thought the doc was automatically generated based (partially) on the markdown comment in the .jl files. Am I wrong? If not can I some indication on how to proceed to modify the doc?

I will proceed with the pull request(s) once I know how to handle the doc!

**Comment by sbromberger** [comment]
The markdown in the .jl files is what is used when you do a `julia doc/build.jl`.

**Comment by Azzaare** [comment]
Thank you for the answer. One last question (sorry), do I need to call `julia doc/build.jl` before my PR or will the doc be updated automatically after being merged into LightGraphs.jl ?

That aside, all the functionalities for this issue are ready and tested. I will finish the documentation part tomorrow and issue a PR.

**Comment by sbromberger** [comment]
run the build.jl right before you do your commit.
