### ISSUE TITLE
Placeholder for graph parallelism

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#41]
Just wanted to start this to collect thoughts on good ways of taking advantage of parallelism in Julia.

**Comment by jpfairbanks** [comment]
Graph algorithms building blocks are a way to phrase parallel graph algorithms in terms of parallel primitives a brief slides description with many references [ipdps summary](http://www.graphanalysis.org/IPDPS2014-workshop/Mattson.pdf) and a  [julia paper](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.381.1248) that implements some of them.

**Comment by sbromberger** [comment]
paging @amitmurthy (since I seem to recall that he's done a lot of work with parallelism) for whatever input he would care to give here :)

**Comment by sbromberger** [comment]
After some testing, the issue becomes one of (lack of) shared memory for Graph objects. Using `@parallel` to try to get multiple-source Dijkstra shortest paths resulted in worse performance than just single-threading the algorithm.

If there were a way to do d_s_p using spectral analysis, we could make the adjacency or whatever other matrix a shared array and that might solve things, but it would require a complete rewrite of the Dijkstra implementation to work. @jpfairbanks - have you heard of an implementation of Dijkstra using graphs represented by matrices?

**Comment by sbromberger** [comment]
See also https://groups.google.com/d/msg/julia-dev/yhZ5_gEgUJw/2oPZMXugCQAJ

**Comment by jpfairbanks** [comment]
Some more documents on this. [Intel](http://www.netlib.org/utk/people/JackDongarra/PAPERS/GraphPrimitives-HPEC.pdf), [GaBB14](https://www.cs.ucsb.edu/~gilbert/talks/GilbertGABB19May2014.pdf), [SharedSparseMatrix Implementation](https://github.com/madeleineudell/ParallelSparseMatMul.jl)

Based on a discussion with @sbromberger, 
Accessing Sparse Matrices without copying the columns:
```julia
function column(a::SparseMatrixCSC, i::Integer)
    return sub(a.rowval, a.colptr[i]:a.colptr[i+1]-1)
end

for u in 1:nv(g)
    for v in column(g, u)
         print("Operating on edge $u-->$v")
    end
end
```
An update to `SharedSparseMatrixCSC` should make sure to support indexing with `sub`.

**Comment by sbromberger** [comment]
Moving discussion to #150
