### ISSUE TITLE
Helper function to construct graph from adjacency matrix

### ISSUE THREAD

**Issue by juliohm** [JuliaGraphs/LightGraphs.jl#414]
Something like:

```julia
G = adjecency_to_graph(A)
```

**Comment by sbromberger** [comment]
You mean like this?

```
julia> using LightGraphs

julia> g = Graph(10,20)
{10, 20} undirected graph

julia> a = adjacency_matrix(g);

julia> h = Graph(a)
{10, 20} undirected graph

julia> h == g
true
```

**Comment by juliohm** [comment]
Missed that one too, sorry for the noise. The documentation needs improvements on these basic manipulations/constructions.

**Comment by sbromberger** [comment]
No problem, and absolutely agree re: docs. Want to make a PR with improvements?

**Comment by juliohm** [comment]
I'll try to find time tomorrow, just a few sentences on how to construct
and "slice" graphs.

-Júlio
