### ISSUE TITLE
function next(eit::EdgeIter, state) modifying state

### ISSUE THREAD

**Issue by IssamT** [JuliaGraphs/LightGraphs.jl#419]
I think `state` should not be modified by the function `next`. 

http://stackoverflow.com/questions/39181313/julia-iteration-start-next-done-side-effects

Fixing it requires a minor modification. I can suggest a PR if you don't mind.

**Comment by sbromberger** [comment]
Please do. Thanks!

**Comment by jpfairbanks** [comment]
Is the only argument against mutating the state variable is to allow caching the iteration state? Is there an example of code doing this? I can only recall seeing the start, next, done interface used in for loops, which do not cache the state variable.

**Comment by sbromberger** [comment]
@keno - your input appreciated here, especially given http://stackoverflow.com/questions/39181313/julia-iteration-start-next-done-side-effects - see also the PR (#423).

**Comment by Keno** [comment]
> Is the only argument against mutating the state variable is to allow caching the iteration state? Is there an example of code doing this? I can only recall seeing the start, next, done interface used in for loops, which do not cache the state variable.

This capability is used extensively in some of the iterator wrappers e.g. those from https://github.com/JuliaLang/Iterators.jl. In general the state variable is not very large and immutable. If that's not the case, the trade-off needs to be carefully considered.

**Comment by Keno** [comment]
In this case, I haven't looked at the code too much, but from that PR, it looks like `EdgeIterState` could be made immutable in which case the non-mutating version is probably better.

**Comment by sbromberger** [comment]
the PR shows O(n) allocations with immutable state. This looks like it would be a big problem. Your thoughts?

**Comment by Keno** [comment]
Did you change `EdgeIterState` to an `immutable`?

**Comment by jpfairbanks** [comment]
PR #423 does not. In fact it creates a new instance and then mutates it.

**Comment by IssamT** [comment]
I am sorry I just see that the conversation here and only read the messages in #423. I will try to use the immutable as @Keno suggests

**Comment by IssamT** [comment]
I m surprised of the results from using immutable. To be honest I don't understand the reason behind that... I added the results in #423

**Comment by sbromberger** [comment]
Closing via #423
