### ISSUE TITLE
possible problem with contract / contract! in spectral.jl

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#422]
https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/spectral.jl#L247-L266

Note the following loop:

```
    for i=1:nv(nbt.g)
        for j in neighbors(nbt.g, i)
            u = nbt.edgeidmap[Edge(j,i)]
            vertexspace[i] += edgespace[u]
        end
    end
```

~~Creating the Edge(j,i) there doesn't guarantee that src < dest~~. In any case, I'm probably using it wrong, but:

```
julia> g4 = PathDiGraph(5);
julia> n4 = Nonbacktracking(g4);
julia> v = zeros(Int, 16);
julia> contract(n4,v)
ERROR: KeyError: 2=>1 not found
 in contract! at /Users/bromberger1/.julia/v0.4/LightGraphs/src/spectral.jl:253
 in contract at /Users/bromberger1/.julia/v0.4/LightGraphs/src/spectral.jl:264
```

@jpfairbanks

**Comment by sbromberger** [comment]
All of this is just a longwinded way of saying we REALLY need tests for this stuff written by someone who understands what it's supposed to do :)

**Comment by jpfairbanks** [comment]
Oops. I did git branch instead of `git checkout -b`
