### ISSUE TITLE
Documentation cleanup

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#433]
I'm keeping a list of things we need to clean up now that we've moved to Documenter (#399):

- [x] remove references to readthedocs.
- [x] add Contributing.md into the docs.
- [ ] http://juliagraphs.github.io/LightGraphs.jl/latest/basicmeasures/ - the methods look funny.
- [ ] change the method names to remove `LightGraphs.` and `Base.`.
- [ ] some methods have signatures; others don't. Figure out why.

**Comment by CarloLucibello** [comment]
also, CONTRIBUTING.md should be in the docs

**Comment by sbromberger** [comment]
> also, CONTRIBUTING.md should be in the docs

I included it along with the license info using your copy-and-remove trick :)

**Comment by CarloLucibello** [comment]
> change the method names to remove LightGraphs. and Base.

As far as I know this cannot be done, I filed an issue JuliaDocs/Documenter.jl#253

>some methods have signatures; others don't. Figure out why.

this depens on whether the docstring contains the signature (as would be good practice) or not. We should insert into the Contributing section an encouragement to do it

> http://juliagraphs.github.io/LightGraphs.jl/latest/basicmeasures/ - the methods look funny.

What do you mean? Are you refferring to the index or the main part?

**Comment by MichaelHatherly** [comment]
> this depens on whether the docstring contains the signature (as would be good practice) or not. We should insert into the Contributing section an encouragement to do it

Note that https://github.com/JuliaDocs/DocStringExtensions.jl provides some basic "magic" to insert method signatures into docstrings without needing to manually sync them with the actual signature. It's pretty basic at the moment, but may be useful rather than having to write then all out by hand.

**Comment by sbromberger** [comment]
> What do you mean? Are you refferring to the index or the main part?

They're prefixed by `#` which is a bit distracting. I guess that's the HTML anchor but it'd be nice to get rid of them.

**Comment by Azzaare** [comment]
Hi there, I see we switch to another documentation hosting platform (that is github). In the process, my updates of the doc regarding flow algorithms disappeared.

1. Is it normal?
2. How do I fix that?

It is actually in a rush since I refer to that documentation in different things under review at the moment ...

Thanks in advance!

**Comment by sbromberger** [comment]
We switched to Documenter / github pages a while back (see #399). Can you point me to your updates? I'll see what happened.

**Comment by Azzaare** [comment]
I had some documentation changes going with the add of the multiroute_flow functions in #416 . I think the changes in the documentation were generated through `julia docs/make.jl`.

After checking, it seems the multiroute_flow.jl file is not included in the list of files to add to the documentation. Should I add it, run make.jl and make a PR?

**Comment by sbromberger** [comment]
Ah, ok. Sorry about that. Yes. Add the files to the `Pages` statement in `docs/src/flowcut.md` - follow the existing format - and then make a PR. You don't have to build the docs - it should take care of it automatically.

**Comment by sbromberger** [comment]
OK, closing this out for now.
