### ISSUE TITLE
Infinite loop in push-relabel

### ISSUE THREAD

**Issue by Azzaare** [JuliaGraphs/LightGraphs.jl#438]
I found out a couple of instances where push-relabel enter an infinite loop. The loop in question is in the push_relabel.jl file around line 55.
```julia
    while length(Q) > 0
      println("Debug Max-Flow")
        v = pop!(Q)
        active[v] = false
        discharge!(residual_graph, v, capacity_matrix, flow_matrix, excess, height, active, count, Q)
    end
```

Below is a small instance, with source = 1 and target = 1, that is enough to enter the infinite loop.
[0 1 0 0 1 0 1 0
 1 0 0 0 1 1 0 1
 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0
 1 0 1 0 0 0 1 0
 0 0 0 0 1 0 0 0
 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0]

**Comment by sbromberger** [comment]
cc @pranavtbhat

**Comment by Azzaare** [comment]
I did some testing with other flow algorithms, just in case, I can confirm it only concerns push-relabel.

**Comment by pranavtbhat** [comment]
does it work fine when you don't have the same vertex as source and target?

**Comment by Azzaare** [comment]
My bad, I have source = 1 and target = 2. Sorry for the typo

**Comment by sbromberger** [comment]
Wait - so is this still an issue (with s=1, t=2)?

**Comment by Azzaare** [comment]
Hi, sorry for late answer, I still have no internet in my hotel …

So yes, it still an issue. The following code enter an infinite loop (killed it after 10 minutes):

```julia
using LightGraphs
M = [0 1 0 0 1 0 1 0
       1 0 0 0 1 1 0 1
       0 0 0 1 0 0 0 0
       0 0 0 0 0 0 0 0
       1 0 1 0 0 0 1 0
       0 0 0 0 1 0 0 0
       0 0 0 0 1 0 0 0
       0 0 0 0 0 0 0 0]

g = DiGraph(M)

maximum_flow(g, 1, 2, M)

```

ERROR: InterruptException:
 in gap! at C:\Users\jeanf\.julia\v0.4\LightGraphs\src\flow/push_relabel.jl:158
 in discharge! at C:\Users\jeanf\.julia\v0.4\LightGraphs\src\flow/push_relabel.jl:239
 in push_relabel at C:\Users\jeanf\.julia\v0.4\LightGraphs\src\flow/push_relabel.jl:56
 in maximum_flow at C:\Users\jeanf\.julia\v0.4\LightGraphs\src\flow/maximum_flow.jl:197

**Comment by sbromberger** [comment]
@pranavtbhat are you able to look into this?

**Comment by pranavtbhat** [comment]
I'm sorry I just started graduate school. I'll look into this in a while

**Comment by Azzaare** [comment]
I have no time to look now either, but I wonder if it might be related to networks with (just?) a link between source and target. I will look into it next week if I find some time.

**Comment by IssamT** [comment]
There is an error in counting the nodes at each height. In line 199 of `src/flow/push_relabel.jl` this
`count[height[v]] += 1`
should be:
`count[height[v]+1] += 1`

Fixing it solves the issue.

With the current code, the infinite loop can be also reproduced on a subgraph of the one provided by @Azzaare using:

```
using LightGraphs

#      1 2 3 4 5 6
#---------------------#
M =   [0 1 0 0 1 1    # 1  
       1 0 0 0 1 0    # 2
       0 0 0 1 0 0    # 3
       0 0 0 0 0 0    # 4
       1 0 1 0 0 1    # 5
       0 0 0 0 1 0 ]  # 6

g = DiGraph(M)

maximum_flow(g, 1, 2, M)
```

**Comment by sbromberger** [comment]
PR welcome :)

**Comment by sbromberger** [comment]
Closing out thanks to @IssamT's great work in #448.
