### ISSUE TITLE
Graph Distance Testing

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/LightGraphs.jl#439]
This is a discussion issue to organize some thoughts about how to test graph distances, that is functions that measure the distance between graphs.

While full coverage is necessary as we have discussed before, for functionality as subtle as graph distances, it is not sufficient for confidence in the software. Any paper that introduces a graph distance should show some examples where the distances are computed. The researchers need to show that their metric is useful, which means demonstrating that it has some properties. We should encode those demonstrations into software tests.

We should also be able to take test cases from one paper and apply metrics from other papers.

I would like to develop some guidelines for these issues as they come up. We all agree that highly tested code is an important feature of LG and want to maintain that feature. If you have any ideas, please write them here.

**Comment by rotten** [comment]
Did you mean distances within a graph between vertices, or differences between two graphs?  Or distances between two subgraphs within a graph?

**Comment by jpfairbanks** [comment]
I was thinking of metrics on the set of all graphs of size n, but these remarks apply to to all three of the classes you mentioned.

**Comment by juliohm** [comment]
I fully agree with this issue, if you have a paper in mind with a good benchmark case for testing distances, please let me know and I will read it and try incorporate the case into the tests.

**Comment by sbromberger** [comment]
I'm going to close this out since we haven't had any discussion in many months (winter cleaning!)
