### ISSUE TITLE
Parallel Push-Relabel algorithm

### ISSUE THREAD

**Issue by Azzaare** [JuliaGraphs/LightGraphs.jl#445]
With the issue of Push-Relabel algorithm in #438 , I was thinking of ways to improve our max-flow algorithm. One of the reason to use Push-Relabel is its high degree of (possible) parallelization.

There are many things about it in the literature such as this article by [Anderson and Setubal](http://dx.doi.org/10.1006/jpdc.1995.1103). 

If it is OK with you, I will give it a try next month. Someone else could be interested to.

On a general note, there are many graph algorithms in JuliaGraphs that would gain from the parallelization (usually easy in Julia). Could it be a project? I would be glad to give time to something like that.

**Comment by sbromberger** [comment]
Yes. See #41 and #150 for some previous efforts here. I think we're at the point where this deserves some further research. See also @pranavtbhat's work in https://github.com/pranavtbhat/Graft.jl which is an offshoot of his earlier ParallelGraphs package.

**Comment by sbromberger** [comment]
PS: if you want a place to start, look at doing a parallel betweenness centrality measure. I'd love to use that as a benchmark :)

**Comment by Azzaare** [comment]
OK, I will give it a try next month.

I think the members of a github group can open projects, maybe it is worth it to do it for parallel implementation (when relevant) of current algorithms in JuliaGraphs.

**Comment by CarloLucibello** [comment]
Consider taking a look at
http://julialang.org/blog/2016/08/GSoC2016-Graft
which points to 
http://www.frankmcsherry.org/graph/scalability/cost/2015/01/15/COST.html
before venturing into this

**Comment by sbromberger** [comment]
I did some basic tests with parallelism on betweenness centrality a while back and was able to get 4.7x speedup (vs a single core) on 8 cores. I think it's worth another look.

**Comment by jpfairbanks** [comment]
I think the parallel situation in 0.5 is much improved over 0.3/4 when you last tried this. It should be easier to get good speedup now.

**Comment by sbromberger** [comment]
@Azzaare are you still interested in this? If so, we have some examples in the code of parallel algorithms (see some of the centrality and distance measures). I'd love to see where else we can parallelize.

**Comment by Azzaare** [comment]
Sorry, I forgot to answer. I have a lot of work that piled up in the last month and I can't take care of it for a while. It is probably better to close the issue. I will come back to it if I can.

**Comment by sbromberger** [comment]
Closing per @Azzaare - feel free to comment again when you're available and we can open it back up.
