### ISSUE TITLE
Including GraphMatrices into LG

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/LightGraphs.jl#447]
I have removed the dependency on Factcheck from GraphMatrices.jl on this branch.
https://github.com/jpfairbanks/GraphMatrices.jl/tree/no_factcheck.

Do you want this code to go into Extras or a submodule of LG something like LightGraphs.LinAlg, which is consistent with Base.LinAlg?

**Comment by sbromberger** [comment]
I think this belongs in LG proper, and I like LinAlg (can we move other things in there too? Perhaps the spectral stuff?). There are no other dependencies (once Compat and Docile are removed, which I think should be fairly straightforward). Go for it.

**Comment by sbromberger** [comment]
I just saw your branch - it might be better to have `LinAlg` as a directory, with the module inside there.

**Comment by jpfairbanks** [comment]
Sound reasonable. Do you want 3 files in that directory: what was graphmatrices, nonbacktracking, and the spectral graph distance?

**Comment by sbromberger** [comment]
Yeah, I think that's right. The submodule can export all appropriate functions in each file, and we can have a separate test directory as well.
