### ISSUE TITLE
Build benchmarks into the repo

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#45]
@jpfairbanks suggested in https://github.com/JuliaGraphs/LightGraphs.jl/pull/31#issuecomment-87030715 that we develop performance benchmarks into the repo (so that we can compare the effects of changes to data structures and algorithms). 

IMO, this is an excellent idea. I've opened this issue to figure out how we do this.

**Comment by jpfairbanks** [comment]
I said we can put them in `test/perf/filename.jl`

Just run them and have them write out the timing information to STDOUT. Using JSON is good because it has the flexibility to expand the schema as you add performance tests to run. Later we can write a script to process all the json and determine if there are performance regressions.

just a `{filename/functionname": time-it-took}` format is good enough for now.

**Comment by sbromberger** [comment]
We should also include version info as well, I think. Could we get started once we make a decision on merging the `noincidence` branch? I'd like to do that next Wednesday assuming there are no objections / showstoppers.

cc @jiahao

**Comment by jpfairbanks** [comment]
Golang does a really good job of implementing a dead simple testing and benchmarking framework.
https://golang.org/pkg/testing/#BenchmarkResult
We might want to copy their interface but make the necessary changes because we aren't a statically typed compiled language.

**Comment by sbromberger** [comment]
I started a "benchmarks" branch with the first cut at benchmarking common functions. You'll find the code in `src/benchmarks.jl` - I'm sure it can be done more elegantly. Input appreciated.

Each benchmark test is represented by two functions: an init function that results in precompilation, and the main benchmark. Right now the benchmark includes loading the necessary graph data, and I'd love to figure out a nice way to remove the graph loading from the results.

**Comment by weijianzhang** [comment]
:+1:

**Comment by hayd** [comment]
It'd also be interesting to compare against other libraries, e.g. NetworkX or Graphs.jl, for specific tasks. Similar to how julia base compares itself to other languages. This could make it easier to see which aspects are (relatively) slower / could potentially be improved.

**Comment by sbromberger** [comment]
We know that LightGraphs knocks the socks off NetworkX on pretty much everything... in fact, my original goal for LightGraphs was to have something as simple, yet faster, than NetworkX.

For Graphs.jl, I think it's safe to say we'll beat (timing-wise) all non-simple graphs, and even with simple graphs I think we're even in the worst case and faster in most cases given the optimization LightGraphs can do that Graphs can't (due primarily to the limitations we imposed on Graph/Digraph models).

In any case, I was alerted to https://github.com/johnmyleswhite/Benchmarks.jl today, so I'm going to hold off to see what @johnmyleswhite does with this package before I spend too much more time developing benchmarks here. :)

**Comment by sbromberger** [comment]
[Benchmarks.jl](https://github.com/johnmyleswhite/Benchmarks.jl) is actually shaping up very nicely. I think we should use this for tracking.

**Comment by jpfairbanks** [comment]
Just read the readme and the macro defs. looks good. Definitely a good thing to have be able to depend on external resources. Their "parsing an external file" example fits in exactly with the Graphio stuff.

**Comment by jpfairbanks** [comment]
I think this is now the right way to solve this problem.
https://github.com/JuliaCI/BenchmarkTools.jl

**Comment by sbromberger** [comment]
@jpfairbanks I know you created some benchmarks for a recent PR. Do you have the bandwidth to get us started on a general benchmarking suite? (Right now there are only a few types of functions I think need to be benchmarked: the core functions and then selective advanced stuff that tests multiple core accesses.)

**Comment by henripal** [comment]
I recently ran some benchmarks comparing LightGraphs to the Python APIs of all big graph libraries, so it's easy enough for me to run some benchmarks for NX, iGraph, Snap & Graph-Tool. Let me know if you want me to run specific tests on these to add it to the repo?

**Comment by sbromberger** [comment]
@henripal I'd love to see them. The benchmarks under discussion here are to make sure new code doesn't cause performance of LightGraphs to get worse, but it's always great to see what the competition is doing.
