### ISSUE TITLE
Cycles

### ISSUE THREAD

**Issue by AsileBcd** [JuliaGraphs/LightGraphs.jl#463]
Hi everyone,
I am following the recommendation of one yours and post my issue  here, but I am not sure LightGraphs' core ideas is compatible with what I would like to do.
 Namely, I would like to compute cycles in a directed graph, using Johnson's cycles algorithm (as networkx's simple_cycles algorithm in Python, for those who know it). The theoretical paper is [here](http://www.cs.tufts.edu/comp/150GA/homeworks/hw1/Johnson%2075.PDF). 
I know how to implement the algorithm in general, but I don't know how to implement it efficiently in LightGraphs. Indeed, the main problem I am facing is that an efficient implementation of the algorithm should first divide the graph along the strongly connected components and then apply the algorithm on each subgraph. However, as far as I understand, getting subgraphs in Lightgraphs will restart the indexing from 1 and lose the original indexing, which is undermining my final aim, which is to remove the cycles from the original graph. I imagine it is possible to store the correspondences in a dictionary, but that is not IMO a very straightforward way. Indeed, the easiest way would be to keep the indices as is when a subgraph is created, but I imagine it requires a substantial shift of paradigm.
I hope my exposition is clear. If not, do not hesitate to ask for more explanations.
Best,

**Comment by CarloLucibello** [comment]
Hi,
maybe you could use `induced_subgraph!` here #464  that I pushed just for you :) 

Also when dealing with directed graphs and connected components you may want to read the discussion here #368, and propose some changes if needed. Bye

Carlo

**Comment by AsileBcd** [comment]
So fast! Thank you! 
That's indeed something like that I need. I am not sure I understand the whole algorithm though ^^

**Comment by sbromberger** [comment]
I think the best way to do this (once we merge #464) is to compute the strongly connected components, and then induce subgraphs for each component, using the new `vmap` vector that's returned from `induced_subgraph()` to map each "new" vertex to its original vertex index.

**Comment by sbromberger** [comment]
#464 is now merged. Give it a try and let me know if we need to reopen.

**Comment by AsileBcd** [comment]
I agree, that's normally the best strategy.
Thank you! I won't do that this week, but I will try to do it this weekend and tell you if it works.
