### ISSUE TITLE
DiGraph flipped when constructed from adjacency_matrix()

### ISSUE THREAD

**Issue by tomyun** [JuliaGraphs/LightGraphs.jl#466]
A new `DiGraph` constructed from `adjancency_matrix()` returns a graph with all edge directions reversed. I wonder if this is an intended behavior.

```julia
julia> using LightGraphs

julia> g0 = DiGraph(4, 4)
{4, 4} directed graph

julia> adjacency_matrix(g0)
4×4 sparse matrix with 4 Int64 nonzero entries:
	[3, 1]  =  1
	[1, 2]  =  1
	[2, 3]  =  1
	[4, 3]  =  1

julia> g1 = DiGraph(ans)
{4, 4} directed graph

julia> adjacency_matrix(g1)
4×4 sparse matrix with 4 Int64 nonzero entries:
	[2, 1]  =  1
	[3, 2]  =  1
	[1, 3]  =  1
	[3, 4]  =  1

julia> g0 == g1
false
```

Meanwhile, more elaborate construction gives you the same graph as expected.

```julia
julia> g2 = DiGraph(vertices(g0), ne(g0), fadj(g0), badj(g0))
{4, 4} directed graph

julia> adjacency_matrix(g2)
4×4 sparse matrix with 4 Int64 nonzero entries:
	[3, 1]  =  1
	[1, 2]  =  1
	[2, 3]  =  1
	[4, 3]  =  1

julia> g0 == g2
true
```

I'm on Julia 0.5.0 with LightGraphs 0.7.0.

**Comment by sbromberger** [comment]
Definitely not correct behavior, but I can't seem to reproduce it on 0.5/0.7.0. Let me try your specific example.

```
julia> using LightGraphs

julia> g = Graph(4,4)
{4, 4} undirected graph

julia> h = DiGraph(g)
{4, 8} directed graph

julia> h
{4, 8} directed graph

julia> a = adjacency_matrix(g)
4×4 sparse matrix with 8 Int64 nonzero entries:
	[2, 1]  =  1
	[3, 1]  =  1
	[1, 2]  =  1
	[3, 2]  =  1
	[1, 3]  =  1
	[2, 3]  =  1
	[4, 3]  =  1
	[3, 4]  =  1

julia> i = DiGraph(a)
{4, 8} directed graph

julia> h == i
true
```

**Comment by sbromberger** [comment]
This also affects full adjacency matrix creation. Patch incoming.

**Comment by sbromberger** [comment]
Patch breaks distance calculations. Ugh.

**Comment by sbromberger** [comment]
The issue is that adjacency_matrix is transposed:

```
julia> g = DiGraph(4,4)
{4, 4} directed graph

julia> collect(edges(g))
4-element Array{Pair{Int64,Int64},1}:
 3=>1
 3=>2
 4=>2
 4=>3

julia> a = full(adjacency_matrix(g))
4×4 Array{Int64,2}:
 0  0  1  0
 0  0  1  1
 0  0  0  1
 0  0  0  0
```

**Comment by jpfairbanks** [comment]
Yeah. We need to make a decision about which direction the adjacency matrix for directed graphs should point. Does A_ij = 1 mean that there is an edge from v_1 to v_j or from v_j to v_i? Both are equivalent, you can just transpose to get from one to the other. Consistency is definitely needed. So that DiGraph(adjacency_matrix(g) ) == g should be correct.

We can pick either direction for the adjacency matrix and then fix all the code that breaks. The fix will be to either compute the transpose at the beginning,  or to replace A[i,j] with A[j,i] in the code that breaks. We could use the amount of code that breaks as a heuristic for which convention to adopt.

**Comment by sbromberger** [comment]
A_ij = 1 means that there is an edge from i to j.

**Comment by sbromberger** [comment]
@tomyun sorry - this is taking a bit longer than expected.

**Comment by tomyun** [comment]
@sbromberger never mind. I could keep off adjacency matrix and still try what I'd like to do. Thanks for your prompt response and all these efforts from the community.

**Comment by sbromberger** [comment]
Thanks - but this is definitely a bug that needs to be fixed. Give us a few days.

**Comment by sbromberger** [comment]
@tomyun - should be fixed in latest master. Give it a try pleasE?

**Comment by tomyun** [comment]
It works for the example I posted. Thanks!

```julia
julia> using LightGraphs

julia> g0 = DiGraph(4, 4)
{4, 4} directed graph

julia> adjacency_matrix(g0)
4×4 sparse matrix with 4 Int64 nonzero entries:
	[3, 1]  =  1
	[3, 2]  =  1
	[4, 2]  =  1
	[2, 3]  =  1

julia> g1 = DiGraph(ans)
{4, 4} directed graph

julia> adjacency_matrix(g1)
4×4 sparse matrix with 4 Int64 nonzero entries:
	[3, 1]  =  1
	[3, 2]  =  1
	[4, 2]  =  1
	[2, 3]  =  1

julia> g0 == g1
true
```
