### ISSUE TITLE
Warning in euclidean graphs testing

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#468]
Got this when doing a test:

```
running /Users/me/.julia/v0.5/LightGraphs/test/generators/euclideangraphs.jl ...
WARNING: Some points are outside the box of size 0.01.
                Setting box size to L=0.8765400135387236.
```

**Comment by CarloLucibello** [comment]
it'ok, this is intended. unfortunately there is no @test_warning

**Comment by sbromberger** [comment]
Will users get this warning during normal use?

**Comment by CarloLucibello** [comment]
no no, just if they use the euclidean grap function in a way they should be warned about

I'm closing this, please reopen if you have any doubt left

**Comment by sbromberger** [comment]
Well hold on a second. I don't think our tests should throw warnings. If Base.Test can't accommodate warnings, we should change the test to something that exercises the desired functionality and passes  tests. Leaving it this way will be (has been) confusing to users.

**Comment by CarloLucibello** [comment]
but the point of that test is exactly testing  the use-case that generates the warning! I don't see a solution around this

**Comment by sbromberger** [comment]
Throw an error, then test it with test_throws.

**Comment by sbromberger** [comment]
The other way to do it is println a message before and after saying "Warnings in this set of tests are expected" and then "End warnings" or something.
