### ISSUE TITLE
problem with maximal_cliques

### ISSUE THREAD

**Issue by joachimdahl** [JuliaGraphs/LightGraphs.jl#470]
On a chordal graph, maximal_cliques() does not return maximal cliques.

```
julia> using LightGraphs

julia> A=[ 1  0  1  1  0  0  1
           0  1  0  1  0  1  0
           1  0  1  1  0  1  1
           1  1  1  1  0  1  0
           0  0  0  0  1  1  1
           0  1  1  1  1  1  1
           1  0  1  0  1  1  1 ];

julia> maximal_cliques(Graph(A))
6-element Array{Array{Int64,N},1}:
 [6,7,3]
 [6,7,5]
 [6,4,2]
 [6,4,3]
 [1,3,7]
 [1,3,4]

```

but the maximal cliques are easily identified as [1,3,4,7], [2,4,6], [3,4,6,7], [5,6,7].  I was hoping to replace the clique extraction in Polyopt.jl with the functionality in LightGraphs.

**Comment by IssamT** [comment]
```
julia> collect(edges(Graph(A)))
19-element Array{Pair{Int64,Int64},1}:
 1=>1
 1=>3
 1=>4
 1=>7
 2=>2
 2=>4
 2=>6
 3=>3
 3=>4
 3=>6
 3=>7
 4=>4
 4=>6
 5=>5
 5=>6
 5=>7
 6=>6
 6=>7
 7=>7
```

I am maybe missing something here but I don't think 4 and 7 can be in the same clique if they are not connected to each other.

**Comment by joachimdahl** [comment]
You are right - what an embarrasment!  I am closing this ticket.

**Comment by sbromberger** [comment]
Yeah, wait a second. Good catch. Is this in fact chordal, and what's with the self-loops?

**Comment by sbromberger** [comment]
Ah, good. Very relieved since this was a function derived from Graphs.jl :)
