### ISSUE TITLE
LG failing nightly in label_propagation

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#471]
https://travis-ci.org/JuliaGraphs/LightGraphs.jl/jobs/162684388#L681-L685

**Comment by sbromberger** [comment]
cc @afternone

**Comment by sbromberger** [comment]
also cc @jpfairbanks :)

**Comment by afternone** [comment]
Due to the frequent tie-breaks and the random order update strategy, the label propagation (LP) algorithm could deliver multiple partitions in different runs. LP may merge two cliques even they are connected by a single edge. Thus, the test code some times pass and some times not pass. We should make a more appropriate test condition for LP. Do you have any ideas?

**Comment by sbromberger** [comment]
This is so far outside my area of study that I can't comment intelligently :) Hoping @jpfairbanks or @CarloLucibello can weigh in here.

**Comment by afternone** [comment]
May be we can use a kind of network made of some disconnected cliques to test the LP algorithm.

**Comment by sbromberger** [comment]
It's easy enough to do, but is the behavior expected? That is:

>  the label propagation (LP) algorithm could deliver multiple partitions in different runs

is that a known property of LP or does it represent a bug in the implementation?

**Comment by sbromberger** [comment]
to make disconnected cliques, just make a bunch of them and then use `blkdiag` to merge them into a single graph.

**Comment by afternone** [comment]
Yes, it is the property of LP, not a bug.

**Comment by sbromberger** [comment]
Ah, in that case can you see whether https://github.com/JuliaGraphs/LightGraphs.jl/issues/471#issuecomment-250363335 will provide deterministic tests?

**Comment by sbromberger** [comment]
Paging @afternone - should we address this or just close it out? Your call.

**Comment by afternone** [comment]
@sbromberger How about setting a suitable random seed for the test?

**Comment by sbromberger** [comment]
Haven't seen this in a while so closing out.
