### ISSUE TITLE
Travis using PR and push to run checks twice

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/LightGraphs.jl#475]
What is the difference between these checks, can we just use the PR one because nothing should be committed without going through a PR? seems like it should reduce our travis load.

**Comment by sbromberger** [comment]
I think it allows us to run codecov on each so we have details of coverage for both the PR and the push.

**Comment by jpfairbanks** [comment]
Based on reading [Travis Docs](https://docs.travis-ci.com/user/pull-requests):
> Travis CI builds a pull request when it is first opened, and when commits are added to the pull request .

> Rather than test the commits that have been pushed to the branch the pull request is from, we test the merge between the origin and the upstream branch. To only build on push events, you can disable Build on Pull Requests from your repository settings.


I think the "Push" check is running on the commit as is, and the "PR" check is running on the commit after merging in to the target branch of the PR (in our case master).

Probably shouldn't disable either of those checks.

**Comment by sbromberger** [comment]
OK :)
