### ISSUE TITLE
Prim's algorithm

### ISSUE THREAD

**Issue by athulappadan** [JuliaGraphs/LightGraphs.jl#481]
I am trying to implement Prim's algorithm but I am getting stuck on a few things. I posted my doubts in julia forums but got no response. It will be helpful if someone can clarify my doubts so that I could complete the implementation soon

**Comment by sbromberger** [comment]
It would be helpful to post a link to your topic in julia-users.

**Comment by athulappadan** [comment]
Is it okay to use Match package..?

**Comment by sbromberger** [comment]
If you do it should probably go into LightGraphsExtras.

**Comment by sbromberger** [comment]
ref: #488

**Comment by athulappadan** [comment]
Should I close this issue?

**Comment by sbromberger** [comment]
Since we merged the code, I think so - unless you have something else to discuss :)
