### ISSUE TITLE
Rework bfs and dfs visitor framework

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#497]
Right now the bfs and dfs visitor framework is confusing and not terribly flexible. (It also may have some performance issues.)

Given that functions appear to be first-class now in Julia 0.5, I'd like to propose a rework of the traversals to simplify and perhaps streamline traversals.

What I'm currently thinking (in not-so-proper Julia pseudocode):

`function bfs(vertex_open_function = () -> true, vertex_close_function = () -> true, edge_visit_function = () -> true, visitor_data::SimpleGraphVisitor)`

This would allow devs to specify their own open/close/visit functions instead of having to override `examine_neighbor!`, `discover_vertex!`, `close_vertex!`, etc.

Thoughts? Partially inspired by #495 and the fact that we've had a performance regression there for months that went undetected.

**Comment by jpfairbanks** [comment]
Yeah that sounds better than the weirdly half-OO way of doing it now.

**Comment by jpfairbanks** [comment]
All of the functions would need to get the state of the iteration, the graph and the visitor as arguments right?

**Comment by sbromberger** [comment]
> All of the functions would need to get the state of the iteration, the graph and the visitor as arguments right?

Yes - I think, off the top of my head, it looks like this:

```
function bfs(vertex_open_function = (state) -> true, vertex_close_function = (state) -> true, edge_visit_function = (state) -> true, visitor_data::SimpleGraphVisitor)
```

where `state` contains (u, v, some mutable data structure, and the graph),
but I need to think about this some more.

**Comment by sbromberger** [comment]
@rohitvarkey I heard you might have some improvements here? Let me know, please!

cc @jpfairbanks

**Comment by rohitvarkey** [comment]
I have a pretty straightforward implementation of bfs without using the visitor framework. The basic code is something like
```julia
function bfs(next::Vector{Int}, g::SimpleGraph, source::Int64)
    parents = fill(-2, nv(g)) #Initialize parents array with -2's.
    parents[source]=-1 #Set source to -1
    while !isempty(next)
        src = shift!(next) #Get first element
        vertexneighbors = neighbors(g, src)
        for vertex in vertexneighbors
            #If not already set, and is not found in the queue.
            if parents[vertex]==-2
                push!(next, vertex) #Push onto queue
                parents[vertex] = src
            end
        end
    end
    return parents
end
```
In my benchmarks, I find that this version turns out to be around 3x faster than the current bfs implementation. I can whip up a PR if you'd like!

**Comment by jpfairbanks** [comment]
What about the state being 

```julia
mutable struct VisitorState{V,E,T}
    vertex::V
    edge::E
    open::Bool
    close::Bool
    storage::T
end
```

And then when you go to call the bfs function you give it a visit function like this:

```julia
function visitfunc{S}(state::S)
     if state.open
        # do what vertex open visitor did
     else if state.close
       # do what vertex close visitor did
     else
       # do what edge visitor did
    end
end
bfs{S}(visitfunc, g::AbstractGraph)
```

That way you only need to define one function for the interface.

**Comment by sbromberger** [comment]
I'd prefer to have `state.status` be some sort of enum instead of checking two booleans. You want to prevent `open` and `close` from both being true at the same time.

Plus I'm not quite sure how this would work. Need to think about it.

Also, @rohitvarkey - it looks like you need two sentinel values. Consider using a `bitarray` for `-2` and `0` for `-1`; this will allow you to use the eltype of `g` for your parents vector, which could save significant space.

**Comment by rohitvarkey** [comment]
> it looks like you need two sentinel values. Consider using a bitarray for -2 and 0 for -1;

I'm not sure I understand how to use a `bitarray` here. I didn't use `0` for `-1` to consider the possibility of a graph representation that uses a 0-based index that wants to use this code.

> this will allow you to use the eltype of g for your parents vector, which could save significant space.

Would `fill(eltype(g.vertices)(-2), nv(g))` work for this?

**Comment by sbromberger** [comment]
> I'm not sure I understand how to use a bitarray here. I didn't use 0 for -1 to consider the possibility of a graph representation that uses a 0-based index that wants to use this code.

Then you can use two bitarrays, `notfound` and `issource`. `notfound[i]` would be `true` if `parents[i]` would equal `-2` in your code above, and `issource[i]` would be true if `parents[i]` would equal `-1`.

> Would fill(eltype(g.vertices)(-2), nv(g)) work for this?

not if the eltype is unsigned.

**Comment by rohitvarkey** [comment]
Oh. Okay! So the function would return `parents`, `notfound` and `issource` and the user has to check the 2 bitarrays before reading the value from `parents`?

**Comment by sbromberger** [comment]
No, it would just return `parents`. `notfound` will not have any `true` values at the end of the BFS, since when it's `true` inside the function you replace the parent with the current source vertex, and you'd then set it to `false`. Similarly, `issource` doesn't need to be returned since you will set the `parents` value to 0 for all sources.

**Comment by timholy** [comment]
:+1: to passing in functions to "filter" the graph.

**Comment by sbromberger** [comment]
I want to come back to this (pinging all):

My current thinking is that we cannot have a generic bfs traversal function that is performant or simple (see below). I am also unaware of anyone currently writing their own specialized BFS traversals using the current generic function. (The knowledge barrier to entry is too high, IMO.)

I'm therefore leaning towards the following philosophy:

1) deprecate the current generic BFS traversal functionality, with an eye towards removing it soon.
2) implement specialized, performant BFS functions (that do specific things) by adding them to `src/traversals/bfs.jl`. Define an interface for these BFS functions somehow, perhaps wrapping them in some sort of struct that we can use for dispatch.
3) enjoy fast, simple, flexible BFS that is specialized for the use case.

Implementers of functions that need BFS will be encouraged to use the existing traversals where possible, but if they need some special tracking, for example, they would write their own.

The current "get the parents" BFS using the generic BFS method is 100x slower than Rohit's specialized version (~860ms vs 9ms).

cc @timholy @jpfairbanks @issamt @rohitvarkey for feedback.

**Comment by sbromberger** [comment]
Here's an example of specialized BFS providing really great gains:
```
julia> g = loadgraph("testgraph.jlg")
{10000, 2000000} undirected simple Int64 graph

julia> @benchmark LightGraphs.newbfstree(g, 1)
BenchmarkTools.Trial:
  memory estimate:  4.57 MiB
  allocs estimate:  50639
  --------------
  minimum time:     12.736 ms (0.00% GC)
  median time:      15.433 ms (0.00% GC)
  mean time:        18.529 ms (3.33% GC)
  maximum time:     134.255 ms (2.12% GC)
  --------------
  samples:          270
  evals/sample:     1

julia> @benchmark LightGraphs.newbfstree(g, 1)
BenchmarkTools.Trial:
  memory estimate:  4.57 MiB
  allocs estimate:  50639
  --------------
  minimum time:     12.759 ms (0.00% GC)
  median time:      14.500 ms (0.00% GC)
  mean time:        15.218 ms (3.83% GC)
  maximum time:     30.774 ms (10.63% GC)
  --------------
  samples:          329
  evals/sample:     1

julia> @benchmark LightGraphs.bfs_tree(g, 1)
BenchmarkTools.Trial:
  memory estimate:  301.85 MiB
  allocs estimate:  15509402
  --------------
  minimum time:     940.392 ms (2.27% GC)
  median time:      1.026 s (2.27% GC)
  mean time:        1.014 s (2.27% GC)
  maximum time:     1.065 s (2.34% GC)
  --------------
  samples:          5
  evals/sample:     1

julia> z = LightGraphs.newbfstree(g, 1)
{10000, 9999} directed simple Int64 graph

julia> y = bfs_tree(g, 1)
{10000, 9999} directed simple Int64 graph

julia> z == y
true
```

This uses a slightly modified version of @rohitvarkey's bfs traversal, above.

**Comment by jpfairbanks** [comment]
> I'm therefore leaning towards the following philosophy:

> deprecate the current generic BFS traversal functionality, with an eye towards removing it soon.
> implement specialized, performant BFS functions (that do specific things) by adding them to src/traversals/bfs.jl. Define an interface for these BFS functions somehow, perhaps wrapping them in some sort of struct that we can use for dispatch.
> enjoy fast, simple, flexible BFS that is specialized for the use case.
> Implementers of functions that need BFS will be encouraged to use the existing traversals where possible, but if they need some special tracking, for example, they would write their own.

Yes I think this is the right thing to do.

### Proposed Interface
Does the following interface make sense?

```julia
# define a custom struct for holding the results, must contain at least a parents array.
struct MyTraversalResult{T,W, U}
    parents::T
    dists::W
    extras::U
end

# an algorithm type for dispatching.
abstract MyTraversalAlg <: Algorithm

# an in-place version to enable reusing memory.
function traverse!(alg::MyTraversalAlg, r::MyTraversalResult, g)
    # meat of algorithm here
    return r
end

# a convenience version.
function traverse(alg::MyTraversalAlg, g)
    r = MyTraversalResult(zeros(nv(g)), zeros(nv(g)), Extras())
    # meat of algorithm here
    return traverse!(alg, r, g)
end
```

### Benefits
1 . Having a result type and an algorithm type is good so that you could have multiple algorithms that share a common return type. Post-processing output can be shared across algorithms.
2. Algorithm as input type enables type stability
3. All traversals fall into one framework, no need for DFS and BFS to have redundant code.

**Comment by sbromberger** [comment]
except we've just implemented something that doesn't require a `parents` vector :) See https://gist.github.com/sbromberger/0d95492c4ffba12daa3394f62fffe1cc.

**Comment by jpfairbanks** [comment]
Ok then we don't need to store a parents field. Although, you could have that function return the path that it finds as a parents array which would probably be helpful to someone.

**Comment by sbromberger** [comment]
In progress with #713. Need to do DFS next.

**Comment by sbromberger** [comment]
Closing out via #712 #717 #720 #723.
