### ISSUE TITLE
Dijkstra finds wrong shortest distance

### ISSUE THREAD

**Issue by mathtd** [JuliaGraphs/LightGraphs.jl#499]
```
b = DiGraph(3)
add_edge!(b,2,2)
add_edge!(b,2,3)
add_edge!(b,3,2)
dijkstra_shortest_paths(b,2).dists
```

This code returns
```
3-element Array{Int64,1}:
 9223372036854775807
                   0
                   2 
```

The distance from 2 to 3 is incorrect and should be 1. `bellman_ford_shortest_paths(b,2).dists` returns the correct vector.

**Comment by sbromberger** [comment]
Support for self loops is sketchy at best, especially for shortest paths calculations. What happens if you get rid of the self loop?

**Comment by mathtd** [comment]
Everything works fine without the self-loop.

**Comment by sbromberger** [comment]
Yup, that's probably it then. If you want to propose a patch, I'm happy to consider/merge it.

We used to error on self-loops, but the quantecon folks needed to use them for something, so we did a quick-n-dirty change to allow them to model using self-loops. We never really went back to ensure that the other algorithms worked, though.

**Comment by mathtd** [comment]
Thanks for the explanation. I'll see how robust the other algorithms are.

**Comment by sbromberger** [comment]
If you want to make a PR that fixes this issue, please do. Otherwise I'll put in a check and a warning.
