### ISSUE TITLE
using Test Sets

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/LightGraphs.jl#504]
We currently have informal test sets isolated into files, but they could be in TestSets http://docs.julialang.org/en/release-0.5/stdlib/test/#working-with-test-sets which seems to be a standardization of what we are currently doing.

**Comment by sbromberger** [comment]
This is pretty cool - are you suggesting one test set per file (which is, as you note, a collection of common tests)? Should be fairly easy to change.

**Comment by jpfairbanks** [comment]
Yeah I think that is the easiest change.

**Comment by juliohm** [comment]
This was solved by https://github.com/JuliaGraphs/LightGraphs.jl/pull/544
