### ISSUE TITLE
Maximum/Minimum cycle mean of weighted digraph

### ISSUE THREAD

**Issue by blegat** [JuliaGraphs/LightGraphs.jl#512]
Is [Karp's algorithm](http://www.sciencedirect.com/science/article/pii/0012365X78900110) or [faster](http://ieeexplore.ieee.org/document/728912/?denied) implemented for Max/Minimum cycle mean on weighted digraph ?
If not, in which package of `JuliaGraphs` should this be added ?

**Comment by jpfairbanks** [comment]
I don't think we have it. We should probably make a directory of cycle related algorithms. So a new file cycles/karp.jl would be a good place to start.

**Comment by sbromberger** [comment]
We have Edmonds-Karp for flow, but not for cycle detection.

**Comment by blegat** [comment]
Thanks for the quick answers ! I will probably not do the PR immediately but I need this functionality for the [SwitchedSystems](github.com/blegat/SwitchedSystems.jl) package so it will be submitted eventually.

**Comment by blegat** [comment]
Shouldn't #486 and #509 also be in the `cycle` directory ?

**Comment by sbromberger** [comment]
> Shouldn't #486 and #509 also be in the cycle directory ?

Probably.

**Comment by sbromberger** [comment]
Closing this out for now since the PRs are still outstanding. @blegat, if you'd like to make a PR for this, please do so! We'd love to have your contribution.

**Comment by blegat** [comment]
Should it go in a new `cycle` folder or in `digraph/cycles` ?
