### ISSUE TITLE
Performance comparison

### ISSUE THREAD

**Issue by rlouf** [JuliaGraphs/LightGraphs.jl#52]
How well a library performs compared to others is a major factor (along with comprehensiveness and ease of use) in its adoption. This information is in particular useful for people like me who are generally curious about Julia's alleged [performance](http://julialang.org/benchmarks/), but are not ready to make the jump unless there is something to be gained---the typical position of someone in technical computing. So far, there is only speedups evidence for scripts that are not used very often (fibonacci numbers, anyone?), a performance comparison in an applied context would go a long way to show Julia's relevance.

A first list of contenders based on my own experience of graph libraries (add yours!)

* [NetworkX](https://networkx.github.io/) is a pure Python library.
* [Graph-tool](https://graph-tool.skewed.de/) is a Python interface to the C++ Boost Graph Library.
* [igraph](http://igraph.org/) is a C library with a Python and R interface.
* [Boost Graph Library](http://www.boost.org/doc/libs/1_58_0/libs/graph/doc/index.html) is a C++ library.

A first list of benchmark algorithms

* Building large graphs (Erdos-Renyi, BA...)
* Random deletion of nodes/edges
* PageRank
* Single-source shortest path
* Betweenness centrality

All these would go in ```test/perf``` along with the LG-only benchmarks, as mentioned in #45 and following what is done in Julia's [repo](https://github.com/JuliaLang/julia/tree/master/test/perf).

**Comment by rlouf** [comment]
In #51 , @sbromberger performed a first (encouraging) comparison between LightGraph's PageRank and the numbers indicated on graph-tool's [performance comparison](https://graph-tool.skewed.de/performance) page.

```
julia> @time z=pagerank(g);
  69.840 milliseconds (109 k allocations: 43585 KB, 7.41% gc time)
```

On a 3.1 GHz i7 while graph-tool reports, for a 2.7GHz i7

Single-core graph-tool: 0.555 s
igraph: 0.781 s
NetworkX: 34.26 s

**Comment by sbromberger** [comment]
Can we please merge this with #45?

**Comment by rlouf** [comment]
Sure!

**Comment by sbromberger** [comment]
Closing out in favor of discussion in #45.
