### ISSUE TITLE
Bug (?) in dijkstra_shortest_paths implementation

### ISSUE THREAD

**Issue by Beatzekatze** [JuliaGraphs/LightGraphs.jl#520]
Following code is needed to reproduce what I think is a bug.

```
using LightGraphs
# small function to reconstruct the shortest path; I copied it from somewhere, can't find the original source to give the credits
spath(target, dijkstraStruct, sourse) = target == sourse ? target : [spath(dijkstraStruct.parents[target], dijkstraStruct, sourse) target]

G = LightGraphs.Graph()
add_vertices!(G,4)
add_edge!(G,2,1)
add_edge!(G,2,3)
add_edge!(G,1,4)
add_edge!(G,3,4)
add_edge!(G,2,2)
w = [0. 3. 0. 1.; 
    3. 0. 2. 0.;
    0. 2. 0. 3.;
    1. 0. 3. 0.]
ds = dijkstra_shortest_paths(G,2,w)
shortest_paths = []
# this loop reconstructs the shortest path for nodes 1, 3 and 4
for i in [1,3,4]
    push!(shortest_paths,spath(i,ds,2))
end

# output; just as we expect
# 3-element Array{Any,1}:
# [2 1]  
# [2 3]  
# [2 1 4]


w[2,2] = 10.    # here a selflink at source is introduced; it should not change the shortest paths
ds = dijkstra_shortest_paths(G,2,w)
shortest_paths = []
# this loop reconstructs the shortest path for nodes 1, 3 and 4
for i in [1,3,4]
    push!(shortest_paths,spath(i,ds,2))
end

# output where weird things happen
# 3-element Array{Any,1}:
# [2 1]  
# [2 1 4 3]
# [2 1 4]
```

What happens (as far as I understood) is that the source pops up in own neigbour list and its shortest distance is set to the self-link distance (since the value of `visited[source] == false`). At the loop for the next neighbour the error propagates leading to wrong distances. That issue can be fixed by changing lines 43 - 45 from
```
    for v in srcs
        heappush!(H, DijkstraHeapEntry{T}(v, dists[v]))
    end 
```
to
```
    for v in srcs
        heappush!(H, DijkstraHeapEntry{T}(v, dists[v]))
        visited[v] = true
    end
```
Then it is also safe to remove line 80 (or so, I might have shifted it while tinkering)
``` dists[srcs] = zero(T)```

**Comment by jpfairbanks** [comment]
Thanks for this really informative bug report!

Since you have a solution, can you file a PR with the proposed change?

**Comment by sbromberger** [comment]
👍 on this great bug report. I think there are a couple of issues here that deserve further scrutiny:

1) self-loops are a recent addition and have not been fully tested with all methods. This should happen if we're going to keep them. (The original reason for self-loops was a request from the QuantEcon folks; I'm not even sure they need them anymore so we might consider just dropping support for self-loops entirely. This is consistent with the idea of simple graphs in any case.)

2) External weight matrices should work but testing has been sporadic. We need to boost test coverage for weights as well.

In any case, echoing @jpfairbanks - please file a PR (if you don't know how or don't have time, post here) and we'll get it merged.

Thanks!

**Comment by jpfairbanks** [comment]
I think it is good to support self loops as much as is practical. We should just make it clear that support is not complete and that if they find bugs related to self loops they should open an issue about it. The two extremes of investing a lot of time in getting 100% coverage of self loops or drooping them are not appealing to me.

I am willing to pay the performance cost of the extra `nv(g)` store operations in order to make Dijkstra's Algorithm work for graphs with self loops.

@Beatzekatze: you can base your PR on branch `bug/520` which has a version of your bug report added as a test.

**Comment by Beatzekatze** [comment]
Submitted the PR. I hope the PR is fine, it's my first one :)

**Comment by jpfairbanks** [comment]
You made the PR on your fork, it needs to be on this repo and also add some tests.

**Comment by jpfairbanks** [comment]
Actually, I have already written the tests, so you can just make a PR onto this repo with the fix

**Comment by jpfairbanks** [comment]
I cherry picked it from your so you don't have to do anything else. Thanks for the fix.

**Comment by Beatzekatze** [comment]
Okay, sorry; I am new to the whole git- story x.x

**Comment by sbromberger** [comment]
> I think it is good to support self loops as much as is practical. We should just make it clear that support is not complete and that if they find bugs related to self loops they should open an issue about it. 

That's the way I'm leaning as well. Self-loops were introduced over a year ago, IIRC; there's no way of knowing who's depending on them at this point. Agree about being explicit about their untestedness.

**Comment by jpfairbanks** [comment]
No Problem @Beatzekatze see PR #521

**Comment by sbromberger** [comment]
PS: @Beatzekatze and @jpfairbanks - congrats on making the 1100th commit :)
