### ISSUE TITLE
Test sets in LG

### ISSUE THREAD

**Issue by juliohm** [JuliaGraphs/LightGraphs.jl#539]
This issue expresses our desire to make use of the test set feature introduced by recent versions of Julia.

The idea is to create at least one test set per file in LG's test suite. Please let me know if you have ideas of how you would like the test set boundaries to be defined.

**Comment by sbromberger** [comment]
I think that, to start, each file should be its own test set. We can then look at what that does and make iterative improvements.

**Comment by jpfairbanks** [comment]
yes each file as its own test set is a good start. The biggest potential roadblock is the possibility that a test in some file depends on variables defined in a different file.

**Comment by juliohm** [comment]
I am closing this issue, but feel free to reopen it if you have something specific in mind. I believe we can have finer granularity in the test sets at any point if we find this is needed.
