### ISSUE TITLE
Nonbacktracking matrix eigenvalues are sometime NaN

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/LightGraphs.jl#542]
Sometimes when you compute the eigenvalues of the Nonbacktracking matrix the leading eigenvalue comes out as NaN. This is happening on the explicitly computed matrix and happens on both 0.5 and 0.6. I need to investigate for changes to eigs that make it more common on 0.6.

**Comment by sbromberger** [comment]
Is it safe to ignore these errors for builds / PRs that don't touch this code? If so, perhaps we disable / make the tests optional until we fix this?
