### ISSUE TITLE
NormalizedAdjacency{Float64}(::CombinatorialAdjancy{Int}) on 0.6

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/LightGraphs.jl#543]
Changes to the inner constructors in 0.6 have exposed a lack of promotion in the constructors in graphmatrices.jl

The problem is that if you have ` M::CombinatorialAdjacency{Int}` and want to construct the `An::NormalizedAdjacency` matrix, then you need to decide what element type to store the `NormalizedAdjacency{T}` matrix in. You don't know what precision to use for `1/sqrt(degree(g,v))`. Or if you should cast the backing matrix `M.A` once to type T, and potentially doubling the storage requirements, or do the conversion before every flop.

Right now this is all undocumented behavior but if `M::CombinatorialAdjacency{Float64}` then `NormalizedAdjacency(M)` should just work. We can sort this out when a need arises.

**Comment by sbromberger** [comment]
I appear to have fixed this by getting rid of the inner constructors and loosening the types for conversion. You no longer have to specify the type parameter when converting: that is, 
```
adjmat = CombinatorialAdjacency(mat)
StochasticLaplacian(StochasticAdjacency(adjmat))
```

will just work (tm).
