### ISSUE TITLE
Proposal: replace distmx with an accessor function

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#546]
Now that functions are first-class, I think it makes sense to pass an accessor function in wherever we now require a distance matrix. The accessor would take some input and would return a distance value.

For an example of a benefit, this would allow us to create a `WeightedEdge` type that contained
```
type WeightedEdge{T<:Integer, U<:Number} <: AbstractEdge
  src::T
  dst::T
  weight::U
```
and then the accessor function would be
```
distance(e::WeightedEdge) = e.weight
```

For Edges with no weights (the default), we can just have
```
distance(e::AbstractEdge) = 1
```
and get rid of the `DefaultDistance` cruft.

Then, using `dijkstra_shortest_paths` as an example, we could simply do
```
dijkstra_shortest_paths(g, 1, distance)
```

or
```
dijkstra_shortest_paths(g, 1, (e)->e.weight)
```
instead of
```
dijkstra_shortest_paths(g, 1, distmx)
```

Other applications: `distance` could be a function that looked up the distance from an external datastore, or it could be simply looking up the value from a matrix (`distance(e::Edge) = distmx[e.src, e.dst]`).

Thoughts?

**Comment by jpfairbanks** [comment]
yes I think this is a good idea. We should add it to the milestone for LGv1.0.0. Removing DefaultDistance is a breaking change so should not be done until LGv1.0.0. We could introduce the function versions and deprecate the matrix versions before then.

**Comment by sbromberger** [comment]
OK. I think we can do this. Do you recommend making a new branch off of #541 for this work, since it looks like the majority of changes for 1.0 will be in that branch?

**Comment by sbromberger** [comment]
or we could go ahead and do the deprecations now (for Julia v0.5)....

**Comment by jpfairbanks** [comment]
Can we start it after merging #541? Or at least finishing the parts of #541 that affect these files?

**Comment by sbromberger** [comment]
we can wait, but my hope is that the time between merging #541 and tagging 1.0 will be very short.

**Comment by sbromberger** [comment]
My new thought is that we keep the distance matrix as "array-like" and require the edge implementations to create something that looks like an array. This makes it more straightforward and intuitive. For example, with this new approach, we'd still be able to pass in distance matrices, and an implementation of weighted edges would so something like
```
struct WeightedEdge{T<:Integer, U<:Real} <: AbstractEdge
  src::T
  dst::T
  weight:U
end

struct EdgeWeights{U<:Real} <: AbstractMatrix{U} end
getindex(::EdgeWeights{U}, u, v) with U <: Real = getEdge(u,v).weight
# getEdge is an accessor to the edge list that returns an edge given its source and dest indices
# will also need the other getindex methods, along with size, transpose, and ctranspose
```

**Comment by sbromberger** [comment]
Closing this out since I'm now more convinced of my latest position.

**Comment by jpfairbanks** [comment]
Yeah I think that is good. On revisiting this topic I think that the same graph with multiple distance matrices will be common enough to think of as a primary use case.
