### ISSUE TITLE
graphmatrices: weird convert, and also tests required

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#555]
@jpfairbanks 

in https://github.com/JuliaGraphs/LightGraphs.jl/blob/9dd2b872a7d8bd5355fc85daca96fd7a63d6670c/src/linalg/graphmatrices.jl#L234, the conversion to a `CombinatorialAdjacency` actually produces a `SparseMatrix`. Is this intended?

Also - see https://codecov.io/gh/JuliaGraphs/LightGraphs.jl/compare/9dd2b872a7d8bd5355fc85daca96fd7a63d6670c...faff97a7c5b7df545861afd4c5b344a5986a49f8/src/src/linalg/graphmatrices.jl for the latest test coverage.

**Comment by jpfairbanks** [comment]
The tests on #541 sbromberger/simplegraphs are working for me. Is there anything still broken there?

**Comment by sbromberger** [comment]
they're working but I'd like the conversion issue fixed, and more tests, in graphmatrices. I'm not knowledgeable enough to fix this myself.

**Comment by jpfairbanks** [comment]
So the problem as I understand it is that if you have a 
```julia
A::CombinatorialAdjacency(g)
B = CombinatorialAdjacency(A)
B == g #current behavior
B == A #intended behavior
```

Is that what you are concerned about?

**Comment by sbromberger** [comment]
Yes. Is this significant? You're converting to a `CombinatorialAdjacency` which implies that you should be returning a `CombinatorialAdjacency`, but instead you're returning a matrix.

**Comment by jpfairbanks** [comment]
Yeah the current behavior is incorrect. `CombinatorialAdjacency(CombinatorialAdjacency(g)) == CombinatorialAdjacency(g)` should be true for all g.

**Comment by jpfairbanks** [comment]
This never came up in my usage because I never tried to use it like that.

**Comment by sbromberger** [comment]
That's what you get when you put someone who doesn't know what he's doing in charge of moving your code to 0.6 :)

**Comment by jpfairbanks** [comment]
PR incoming.
