### ISSUE TITLE
Infix operators for set interface

### ISSUE THREAD

**Issue by juliohm** [JuliaGraphs/LightGraphs.jl#558]
In this proposal, I would like to ask if you like the idea of having infix operators as shortcuts for the set interface in LG:

```julia
using LightGraphs

G = Graph(1)
H = Graph(2)

G ∪ H # dispatches union
G ∩ H # dispatches intersection
G × H # dispatches cartesian product
...
```

I can submit a PR if you think it is a good idea, please let me know.

**Comment by sbromberger** [comment]
We already have infix operators as a result of having `union` and `intersect`, but we don't have `×` yet. It's a good idea to implement, but is `cross()` the same as `cartesian`?

**Comment by juliohm** [comment]
Where the infix operators for union and intersect are defined? Sorry, I missed them...

**Comment by juliohm** [comment]
Oh, this is imported from Base, nevermind :blush:

**Comment by sbromberger** [comment]
They don't need to be explicitly defined: like `issubset`, the unicode infix automatically get generated once you define `union` and `intersection`.

**Comment by juliohm** [comment]
Julia is amazing, I sometimes forget, closing this.

**Comment by sbromberger** [comment]
Well, we still have `cross` (`x`) to discuss.

**Comment by juliohm** [comment]
The cross-product is a different concept, I think we are set in terms of infix operators, what do you think?

**Comment by sbromberger** [comment]
If you say so. I like infix :)

**Comment by juliohm** [comment]
It makes code look exactly like in textbooks, which is welcome. Since cross-product is different than cartesian-product, I think we have it all. Alternatively, we could define another unicode for cartesian, something not used in Base already.

**Comment by sbromberger** [comment]
is there such a thing as a cross-product for a graph? If so, we should define it in `operators.jl`. :)

**Comment by juliohm** [comment]
I don't think so, cross product is an operation performed between vectors instead of sets, I will close this, but feel free to reopen or continue the discussion :blush:

**Comment by sbromberger** [comment]
We could always define ` 
◻` (`\square`)  as the cartesian product :)

**Comment by juliohm** [comment]
I think that square on Wikipedia is some unicode issue, never seen this symbol used as cartesian product, only \times or \bigtimes

**Comment by juliohm** [comment]
But we can use it, maybe it is standard?

**Comment by sbromberger** [comment]
Is this a case where `x` is overloaded?http://www.cs.odu.edu/~cs381/cs381content/set/set_operations.html

**Comment by sbromberger** [comment]
also: via http://mathworld.wolfram.com/CartesianProduct.html

> The Cartesian product of two sets A and B (also called the product set, set direct product, or cross product) is defined to be the set of all points (a,b) where a in A and b in B. It is denoted A×B, and is called the Cartesian product since it originated in Descartes' formulation of analytic geometry. 

so I guess they *are* the same?

**Comment by juliohm** [comment]
The term cross-product is widely used for another operation: https://en.wikipedia.org/wiki/Cross_product

I don't know why that wolfram link is calling these two operations the same name, I don't see a relation, at least for now.

**Comment by sbromberger** [comment]
Let's do it. all we have to do is import `Base.cross`, and then, in `operators.jl`, add

`cross(g::G, h::G) where G<:AbstractGraph = cartesian_product(g, h)` and a test or two.

**Comment by juliohm** [comment]
I still think cross and cartesian are very different beasts in the literature, let's get input from @jpfairbanks ?

**Comment by sbromberger** [comment]
well:

> The notation G × H is occasionally also used for Cartesian products of graphs, but is more commonly used for another construction known as the tensor product of graphs. The square symbol is the more common and unambiguous notation for the Cartesian product of graphs. It shows visually the four edges resulting from the Cartesian product of two edges.[2]

**Comment by juliohm** [comment]
The square would be safer :+1: but cross != cartesian, almost 100% sure.

**Comment by sbromberger** [comment]
Turns out we also have `tensor_product` defined.

**Comment by sbromberger** [comment]
let's do the square for cartesian, and the `x` for tensor :)

**Comment by sbromberger** [comment]
I will leave these to you to implement :)

**Comment by juliohm** [comment]
Ok, I will wait a little to see if someone jumps in with a different opinion :+1:

**Comment by jpfairbanks** [comment]
"Introduction to Graph Theory" by  Douglas B. West says square for cartesian product. No notation for tensor product. I think we can move ahead on square for cartesian product.

The authors of Base thought there was a good enough reason not to make \times to cartesian products of sets and I think we should follow their lead.
```
julia> Set([1,2]) × Set([3,4])
ERROR: MethodError: no method matching cross(::Set{Int64}, ::Set{Int64})
```

The also did not use `\otimes` for `kron(A,B)` which makes me think that we don't need an infix for tensor product.

**Comment by juliohm** [comment]
Awesome, I will submit a PR with the \square cartesian product soon.

**Comment by juliohm** [comment]
Apparently we can't define custom infix operators in Julia yet, please let me know if I am wrong.

**Comment by sbromberger** [comment]
Crud. OK. Closing this out until we can :)
