### ISSUE TITLE
Parallel Execution of tests

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/LightGraphs.jl#562]
We have a lot of tests. 7 idle cores when running the tests makes me sad.

**Comment by sbromberger** [comment]
hahaha. Yes. `Tasks.@tasks`? How do we do that without having to hit every file?

**Comment by jpfairbanks** [comment]
The file level would be a good start for parallelization. Each test file should be independent in terms of not sharing state.

**Comment by sbromberger** [comment]
`@parallel` or `@threads` ?

**Comment by sbromberger** [comment]
I just tried this with `@sync @parallel for t in ...` in `runtests.jl`, but it didn't parallelize.

**Comment by SohamTamba** [comment]
@sbromberger 
I tried running the tests in parallel.
According to the attachment, all 4 CPU's are being used to execute the test but the improvement in runtime is negligible. (Reduces from 180 seconds to 160 seconds)

![test_performance](https://user-images.githubusercontent.com/11683616/37357539-b8e6dad4-270e-11e8-8c39-34dd33dca17c.png)

**Comment by SohamTamba** [comment]
@sbromberger
I tried running the tests in parallel.
According to the attachment, all 4 CPU's are being used to execute the test but the improvement in runtime is negligible. (Reduces from 180 seconds to 160 seconds) 
![test_performance](https://user-images.githubusercontent.com/11683616/37358714-c7b0c662-2711-11e8-8122-31c58030c78a.png)

**Comment by SohamTamba** [comment]
Is it possible that the tighter bottle neck is file input?
Perhaps only one file can be read at a time.

**Comment by mbesancon** [comment]
you could compare sequential vs parallel after loading the graph in memory.

**Comment by SohamTamba** [comment]
Each test case has its own graph and it is quite small.
I think the interleaving of reading of the **test code** is causing the inefficiency. 
(When include is run)
I'm trying to find a way to make a worker read an entire test file and store it in local memory before starting the execution of the test.
