### ISSUE TITLE
Rework persistence

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#569]
Followup discussion from https://github.com/JuliaGraphs/LightGraphs.jl/issues/561#issuecomment-289568154 - my preference is to keep the native LightGraphs format inside LG core, but move all other graph format loaders/savers to an external package, and move to [FileIO.jl](https://github.com/JuliaIO/FileIO.jl).

**Comment by jpfairbanks** [comment]
We can have load(file, T::Type) and use the constructor T() to make an empty graph, then fill that graph in with the edges from the file.

**Comment by sbromberger** [comment]
I like that, but we'd need two types: one for graph, the other for edges.
