### ISSUE TITLE
Random walk with optional transition probabilities

### ISSUE THREAD

**Issue by juliohm** [JuliaGraphs/LightGraphs.jl#571]
Would you be interested in having a random walk with optional transition probabilities?

Currently, the random walk is performed with uniform transitions until a predetermined maximum number of vertices is reached.

What do you think of passing an additional (sparse) transition matrix initially, and maybe later on also generalize the stop criterion? Maybe we can leverage Julia syntax to pass in an arbitrary code to be checked in the current while loop?

**Comment by sbromberger** [comment]
yes. I like this idea, but have an alternative idea: two methods.

One takes an `AbstractMatrix` of transition probabilities. The other (main method) takes an accessor function that, given an edge, returns a transition probability. See #546 for the original idea. If you did this quickly, you'd be in a position to help guide resolution of #546 in the long term :)

**Comment by jpfairbanks** [comment]
Would it be better to use and Algorithm type so that you can have complete freedom in the sampling strategy?

```julia
type UniformTransition <: Algorithm
type WeightedTransition <: Algorithm
type FancyTransition <: Algorithm
function random_walk(alg::Algorithm, g::AbstractGraph, steps::Integer)
end
```

Then the generation of the transition weights and the stopping criterion could be controlled by the implementation of Algorithm?

**Comment by juliohm** [comment]
That is a very good idea @jpfairbanks, I will sketch a first implementation soon I find some time.

**Comment by juliohm** [comment]
I am predicting that I will have time to touch this issue after the next 2 weeks. I was spying the code today and would like ask you a few questions before I draft a solution:

1. I was thinking of creating a `AbstractGraphWalkAlgorithm` as suggested by @jpfairbanks, but I noticed that we already have some similar concepts like `AbstractGraphVisitAlgorithm`, should I instantiate this concept instead?

2. To what extent can we unify graph traversal algorithms? Regardless if they are random or deterministic, do you think we should put all under the same interface with something like the `AbstractGraphVisitAlgorithm` concept?

3. I noticed that `TrivialGraphVisitor` is not used anywhere else in the codebase, should it be removed?

4. Could you please give a brief overview of how the concepts `AbstractGraphVisitAlgorithm` and `AbstractGraphVisitor` interplay?

**Comment by jpfairbanks** [comment]
For issue 1: it makes sense to have AbstractWalkAlgorithn to be a subtype of AbstractVisitAlgorithm. As you might have functions that apply the same way to either. Definitely don't make the WalkAlgorithms direct subtypes of AbstractVisitAlgorithm so that we can group the random walks for things like initialization and postprocessing. 

For issue 2, what basis do you have for distinction? I see one distinction that traversal algorithms produce one value per vertex and walks produce a list of vertices that they saw. Does this distinction hold up, or matter? 

3: probably
4:  IIRC the Visitor concept was a CPP/OOP style from the original implementation. We are moving to Algorithm types now that anonymous functions are faster and this style is more idiomatic Julia.

**Comment by juliohm** [comment]
@jpfairbanks could you please elaborate on your comment on item 4? I am interested in learning more about these idioms in Julia v0.6. Perhaps sketch some pseudo-code that compares the CPP/OOP Visitor solution with the new idiom using anonymous functions? That would be super helpful.

**Comment by sbromberger** [comment]
hey all - are we planning on doing this? If not I think I'll close this out.

**Comment by juliohm** [comment]
Hi Seth, I couldn't find the time, got distracted with other things. You can either leave it open as a reminder or close it to clean up the issue tracker. Sorry for not catching up, too much work around here...

**Comment by sbromberger** [comment]
@juliohm I'll close it out, but I'd love to see this code when you get time.
