### ISSUE TITLE
post-merge of #541

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#573]
Post merge:
- [x] merge fix for #368 (`sbromberger/fix368`)

For 8.1:
- [ ] tag upper bounds on previous releases (#570 and https://github.com/JuliaLang/METADATA.jl/pull/8817)

**Comment by sbromberger** [comment]
@tkelman - could I ask you for your help here? I would like to tag upper bounds on previous LightGraphs releases as follows:

 LG version | Julia upper bound
-----------|--------------------
 <= 0.3.7 | 0.3 
0.3.8 - 0.6.3 | 0.4
0.6.4 - 0.7.5 | 0.5

What needs to be done to make this happen?

**Comment by tkelman** [comment]
Are those respective version combinations known to be broken even at the very earliest possible version? For upper bounds it's usually a better idea to choose a known-broken specific release version, rather than a pre-release that would rule out the very first commit after the previous commit branched even though it would likely work fine.

**Comment by sbromberger** [comment]
I don't know. All I have for history is that we switched to the new versions upon the Julia release. I don't think we ever really tested against pre-release versions, but my guess is that things broke at least somewhere in the pre-release cycle, necessitating the minimum bound change.

**Comment by sbromberger** [comment]
So, if we want to pick a known-broken, then we should remove the `-` from each of those versions - but there's no guarantee that the version won't have broken at a pre-release. (That is, even if v0.6.0 is known to be broken on Julia 0.5, it might have broken earlier (that is, it works on all Julia 0.4 but breaks at some unknown place in the `0.5-` prerelease cycle.)

I'll defer to your judgement on this, of course.

**Comment by sbromberger** [comment]
Also - we should probably merge https://github.com/JuliaLang/METADATA.jl/pull/8739 before we do anything with upper bounds here.

**Comment by sbromberger** [comment]
@tkelman I think we're ready to go with upper bounds here. What do I need to do?

**Comment by tkelman** [comment]
Can modify the requires files in-place in a branch of your metadata fork and submit a PR, we'll look at the details there. I do recommend using actual releases for upper bounds rather than prereleases, since upper bounds are exclusive and prereleases include the very first commit after branching.

**Comment by sbromberger** [comment]
Got it. Thanks. I'll try to get to this soon.

**Comment by sbromberger** [comment]
See https://github.com/JuliaLang/METADATA.jl/pull/8817

**Comment by sbromberger** [comment]
Closing because I don't think we're going to be doing upper bounds.
