### ISSUE TITLE
Verify new binomial random generator code

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#590]
Following a failure of erdos renyi graph test (mean degree slightly less than the test expected), I think we should make sure we haven't botched binomial randomness. @jpfairbanks has graciously offered to test the new code against the Distributions code so assigning to him.

**Comment by sbromberger** [comment]
Just FYI, I kept getting (random) failures, so I increased the bounds checking for randgraphs when it tests against mean degree.

**Comment by jpfairbanks** [comment]
It looks like the binomial test made it in, is there an update on this issue?

**Comment by sbromberger** [comment]
It failed again, but close to the bounds. It probably could use some real validation.

**Comment by sbromberger** [comment]
Closing this because it's not failing as often now.
