### ISSUE TITLE
Implementing the is_directed trait correctly

### ISSUE THREAD

**Issue by rohitvarkey** [JuliaGraphs/LightGraphs.jl#591]
I've been trying to get the abstraction to LightGraphs working with an `AbstractGraph`. But I've have not been able to get the `is_directed` trait to work. I was following the example from the [SimpleDiGraphs](https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/graphtypes/simplegraphs/simpledigraph.jl#L106-L108) implementation. I keep getting an `Not Implemented` error. 

This is an minimal example of the error.

```julia
julia> import LightGraphs: AbstractGraph, is_directed

julia> struct LGTest <: AbstractGraph
           g::Int64
       end

julia> is_directed(::LGTest) = true
is_directed (generic function with 8 methods)

julia> is_directed(::Type{LGTest}) = true
is_directed (generic function with 9 methods)

julia> LightGraphs.maximal_cliques(LGTest(15))
ERROR: Not implemented: is_directed
Stacktrace:
 [1] is_directed(::Type{LGTest}) at /Users/rohitvarkey/.julia/v0.6/LightGraphs/src/interface.jl:116
 [2] trait(...) at /Users/rohitvarkey/.julia/v0.6/SimpleTraits/src/SimpleTraits.jl:186
 [3] maximal_cliques(::LGTest) at /Users/rohitvarkey/.julia/v0.6/SimpleTraits/src/SimpleTraits.jl:319
```

Is this the correct way of implementing the `is_directed` trait?

**Comment by sbromberger** [comment]
That's pretty strange. The only thing I can think of is to remove the method definitions at L116.

**Comment by sbromberger** [comment]
That's non-intuitive. Paging @mauro3 for some assistance here.

**Comment by sbromberger** [comment]
see https://github.com/JuliaLang/julia/issues/21356 and https://github.com/mauro3/SimpleTraits.jl/issues/38 as possibly related.

**Comment by mauro3** [comment]
Let's re-check this after the fix of https://github.com/mauro3/SimpleTraits.jl/pull/39, which should hopefully be done very soon.

**Comment by sbromberger** [comment]
Closing as fixed via https://github.com/mauro3/SimpleTraits.jl/pull/41.
