### ISSUE TITLE
should is_cyclic return true on a 2-node PathGraph?

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#592]
```
g = Graph(2)
add_edge!(g, 1, 2)
is_cyclic(g)
```
returns `true`.

This seems possibly correct but not useful. What is the correct behavior for cycles in undirected graphs?

**Comment by sbromberger** [comment]
paging @juliohm and @jpfairbanks for opinions here.

**Comment by juliohm** [comment]
I believe the behavior is consistent with the definition. Changing it would lead to unexpected results from a user's perspective.

**Comment by juliohm** [comment]
What is a situation where an undirected graph is the natural representation when the user is interested in cycle detection? I think if someone is interested in detecting cycles, he/she will start with a directed graph by design. Makes sense?

What is your opinion on this @jpfairbanks?

**Comment by sbromberger** [comment]
I agree with you, @juliohm – but if we're saying that cyclicity doesn't apply to undirected graphs, should we disable the ability to detect cycles in undirected graphs?

**Comment by juliohm** [comment]
It applies in the sense that two vertices in the same component form a cycle whereas vertices in different components don't. It feels strange to me having another definition for cycles in undirected graphs. If we need something more useful or another behavior, we should call it something else? This something else may already exist in the literature.

**Comment by sbromberger** [comment]
> It applies in the sense that two vertices in the same component form a cycle whereas vertices in different components don't.

Isn't it easier and cheaper to see whether a path exists between those two vertices?

**Comment by juliohm** [comment]
Definitely :blush: The idea of implementing the function only for directed graphs makes sense if it improves performance or code readability, otherwise I don't think we gain much in removing a working (yet useless) feature.

For example, consider the scenario in which someone needs to loop over graphs (directed or undirected) generically. He/she would expect to have the same code in the loop working for both types instead of getting an error when the graph is undirected. Maybe I am overthinking it, I don't know.

Thank you for starting the discussion by the way.

**Comment by sbromberger** [comment]
Yup, that's a reasonable approach. I was considering removing `is_cyclic()` for undirected graphs but there's really no reason to do it.

This came up during a gitter conversation a few weeks ago, btw. The person asking was unsure why `is_cyclic()` on a `PathGraph` was `true`.

**Comment by sbromberger** [comment]
Thinking about this some more, couldn't we just write
```
is_cyclic(g::::!IsDirected) = ne(g) > 0
```
and skip all the drama?

**Comment by juliohm** [comment]
That definitely improves performance and makes sense to me! :+1:

**Comment by sbromberger** [comment]
Closing via #603.
