### ISSUE TITLE
all_simple_paths in Julia

### ISSUE THREAD

**Issue by ghost** [JuliaGraphs/LightGraphs.jl#599]
Are there any existing functions to compute all simple paths between any two vertices in an undirected graph? If not, could we have one in Julia similar to a function in NetworkX package?

**Comment by sbromberger** [comment]
See #266. My previous efforts involved recursion which caused massive allocations even on moderately-large, moderately-dense graphs. If you have a method that scales, it'd be great to get a PR.

That said, you can check the  `dijkstra_shortest_paths(u,  allpaths=true)` output - specifically, the `predecessors` field of the `DijkstraState`, and you should be able to reconstruct all simple paths (again, it could result in very large allocations).

**Comment by sbromberger** [comment]
@varun7rs I assume you're very close with this given https://discourse.julialang.org/t/updating-an-empty-list-within-a-recursive-function/3406/3 - I hope you file a PR!

**Comment by varun7rs** [comment]
Hello Mr. Bromberger,

I would love to see the function included in LightGraphs but I have no 
idea on how to work with Github. Could you please advise the further 
course of action?

Thanks

Varun

**Comment by sbromberger** [comment]
Hi Varun,

I'd be happy to help via Gitter if we can find a good time to chat. Basically, you follow these steps:

1) fork the repository by visiting [https://github.com/JuliaGraphs/LightGraphs.jl](https://github.com/JuliaGraphs/LightGraphs.jl) and clicking the "Fork" icon in the upper right. This will make a copy of LightGraphs in your github account.

2) clone your copy of the respository via `git clone` (visit your github page, select the new LightGraphs repo, and then look for the "clone or download" link - this will copy the LightGraphs.jl code to your local machine.

3) create a new working branch for your changes using `git checkout -b <branchname>`.

4) make changes on your local machine to the code in LightGraphs.jl by adding your function (probably somewhere in `traversals`).

5) push your changes to your github repository using `git push`.

6) go back to your github account and there should be a yellow bar that says "create pull request". Click that and it will make a pull request (PR) here with your changes, which we can then review.

More info here: https://help.github.com/articles/proposing-changes-to-your-work-with-pull-requests/.

**Comment by sbromberger** [comment]
@varun - are you still interested in this? We got off track on your last PR but if you're willing to give it another shot I'm happy to help. Let me know?

**Comment by sbromberger** [comment]
Hm. Closing out.

**Comment by jpfairbanks** [comment]
Well he deleted his github acct. So :ghost:

**Comment by sbromberger** [comment]
and yet he persists: :)

Ref https://discourse.julialang.org/t/iteratively-adding-violated-inequalities/5413
