### ISSUE TITLE
Parallel betweenness centrality using threads

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#606]
[ ] Create a threaded version of betweenness centrality.
[ ] Write appropriate tests
[ ] Ensure accuracy / consistency with serial betweenness

**Comment by somil55** [comment]
@sbromberger Do you still need this? I can push code for this

**Comment by sbromberger** [comment]
if you have code for it, sure! If not, I don't know that we need it right now.
