### ISSUE TITLE
Parallel betweenness centrality using multiprocessing

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#607]
[ ] Create a parallel (multi-processor) version of betweenness centrality.
[ ] Write appropriate tests
[ ] Ensure accuracy / consistency with serial betweenness

**Comment by jpfairbanks** [comment]
Is this with a replicated graph multiple workers approach?

**Comment by sbromberger** [comment]
Yes... the graph structure is copied to (and cached on) the worker processes.

**Comment by sbromberger** [comment]
This is done.
