### ISSUE TITLE
explore using JuliaDB as storage for metadata

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#608]
https://github.com/JuliaComputing/JuliaDB.jl might be an interesting way to store graph metadata.

**Comment by jpfairbanks** [comment]
Yes this look good. It makes sense for JuliaDB to be used for one of the new AbstractGraph subtypes. 

Store a CSV

`rowid, src, dst, weight, timestamp`

and you can do graph calculations using indexes on src and dst.

**Comment by sbromberger** [comment]
Closing this out since I think we have a prototype in https://github.com/JuliaGraphs/DBGraphs.jl.
