### ISSUE TITLE
Yen's Algorithm

### ISSUE THREAD

**Issue by Thuener** [JuliaGraphs/LightGraphs.jl#613]
I was doing a project that need the K-shortest loopless paths for a graph with non-negative edge cost, the Yen's Algorithm(https://en.wikipedia.org/wiki/Yen%27s_algorithm) was the best solution for me. I didn't found any impementation in Julia so I did it using LightGraphs. Do you have interest in adding the code to LightGraphs?

**Comment by juliohm** [comment]
Of course! Please follow the conventions in the `shortestpaths` folder of the project and let us know if you have any questions.

**Comment by sbromberger** [comment]
👍 - as @juliohm said, we welcome contributions here. Please also take a look at [our contributing guidelines](https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/CONTRIBUTING.md) and let us know if you have any questions.

Bonus points if you can get parallel (multithreaded / multiprocess) implementations working, though it's not necessary. (We have a GSoC effort this year to parallelize various LG functions.)

**Comment by Thuener** [comment]
Great!
I'm using Julia 0.5.1 so my version of LightGraphs is 0.7.5. I'm going to fork the repository and adjust my code for the master branch.
