### ISSUE TITLE
Bug in dijkstra_shortest_paths with distance matrix

### ISSUE THREAD

**Issue by somil55** [JuliaGraphs/LightGraphs.jl#615]
I tried to run dijkstra_shortest_path with edge weight matrix `m` and the following graph `z`
```
m = [0 2 2 0 0; 2 0 0 0 3; 2 0 0 1 2;0 0 1 0 1;0 3 2 1 0]
z = Graph(5);
add_edge!(z,1,2)
add_edge!(z,1,3)
add_edge!(z,2,5)
add_edge!(z,3,5)
add_edge!(z,3,4)
add_edge!(z,4,5)
```
On executing `dijkstra_shortest_paths(z,1,m;allpaths=true)`, I get the following  `LightGraphs.DijkstraState{Int64}([0,1,1,3,3],[0,2,2,3,4],Array{Int64,1}[Int64[],[1],[1],[3],[2,3,4]],[1,1,1,1,3])`. But shouldn't the number of shortest paths between vertex-5 and vertex-1 be 2 instead of 3?

**Comment by sbromberger** [comment]
I've confirmed this bug. For the graph listed, `predecessors` is
```
5-element Array{Array{Int64,1},1}:
 Int64[]
 [1]
 [1]
 [3]
 [2, 3, 4]
```
but should be
```
5-element Array{Array{Int64,1},1}:
 Int64[]
 [1]
 [1]
 [3]
 [2, 3]
```

and `pathcounts` is
```
5-element Array{Int64,1}:
 1
 1
 1
 1
 3
```
but should be
```
5-element Array{Int64,1}:
 1
 1
 1
 1
 2
```
