### ISSUE TITLE
Improve the interface documentations

### ISSUE THREAD

**Issue by LewisHein** [JuliaGraphs/LightGraphs.jl#642]
I tried implementing a DenseGraphs package, and I've run into some things that I think could be better in the interface documentation.

I think we should specify for each function
- What arguments does it expect?
- What should it return?

Also, `is_directed` seems to be missing from the list.

**Comment by sbromberger** [comment]
What, specifically, is missing? See, e.g., http://juliagraphs.github.io/LightGraphs.jl/latest/basicmeasures/ - this documentation is intended to follow the [Julia doc guidelines](https://docs.julialang.org/en/stable/manual/documentation/). 

Good catch on `is_directed`. We have docstrings for everything (so `?is_directed` will work in the REPL) but for some files we're not using `@autodocs` so we have to include the functions manually.

**Comment by LewisHein** [comment]
What i'm talking about is in the interface documentation in README.md for those who are trying to implement subtypes of AbstractGraph.

Sorry if I wasn't clear

**Comment by sbromberger** [comment]
Ah, gotcha. That's really intended to be a list of things that one needs to implement, not the interface descriptions themselves. But you did find an omission that we need to fix - stand by. :)

**Comment by LewisHein** [comment]
Another one to add: `eltype()`

It makes sense that that's just a list. But it would be helpful to have the interface description available some other way than by digging through the source code.

**Comment by sbromberger** [comment]
Yup, you've convinced me. We need to split `basicmeasures.md` out into `interface.md` and some other stuff. I might have time to do that in the next week, or - if you wanted to - you could make a larger docfix that does what you would like (and possibly fix #639 as well :) ). Let me know if you have time for this diversion.

**Comment by sbromberger** [comment]
@LewisHein wanted to follow up here. Are we good to go?

Just FYI, I've made an implementation of [SimpleWeightedGraphs](https://github.com/JuliaGraphs/SimpleWeightedGraphs.jl) which demonstrates the ease with which one can create custom graph types. I hope this helps.

**Comment by LewisHein** [comment]
I think this looks good, on a cursory inspection.

Thanks.

**Comment by mbesancon** [comment]
Guess this issue is still relevant? Otherwise people will tend to use `Graph` instead of `AbstractGraph` and the struct fields instead of methods

**Comment by sbromberger** [comment]
I don't know that it is given the doc changes you made :) - Do you think it's ok to close, or should we keep it open? (Is there a specific action item that will close this?)

**Comment by mbesancon** [comment]
I just checked the docs, I guess it is all good for the interface - concrete types separation :)

**Comment by sbromberger** [comment]
OK, cool. Closing this out - but will reopen if people want to discuss more.
