### ISSUE TITLE
Paragraphs repeated and dead links in the documentation

### ISSUE THREAD

**Issue by IssamT** [JuliaGraphs/LightGraphs.jl#652]
1) the following paragraph is repeated twice in the documentation.

For Floyd-Warshall path states, please note that the output is a bit different, since this algorithm calculates all shortest paths for all pairs of vertices: enumerate_paths(state) will return a vector (indexed by source vertex) of vectors (indexed by destination vertex) of paths. enumerate_paths(state, v) will return a vector (indexed by destination vertex) of paths from source v to all other vertices. In addition, enumerate_paths(state, v, d) will return a vector representing the path from vertex v to vertex d.

2) Also links in that page like `DijkstraState` seem to be broken.

**Comment by sbromberger** [comment]
I can fix 1). Links are a larger issue. Will create a new issue to track link failures.
