### ISSUE TITLE
Induced subgraph on a pathgraph is giving strange results

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#660]
```
julia> g = PathGraph(5)
{5, 4} undirected simple Int64 graph

julia> j = g[[4,3,2,1,5]]
{5, 4} undirected simple Int64 graph

julia> collect(edges(j))
4-element Array{LightGraphs.SimpleGraphs.SimpleEdge,1}:
 Edge 1 => 2
 Edge 1 => 5
 Edge 2 => 3
 Edge 3 => 4
```
I'm not sure this is the correct output. @jpfairbanks?

**Comment by sbromberger** [comment]
ref https://github.com/JuliaGraphs/LightGraphs.jl/pull/659

**Comment by jpfairbanks** [comment]
The right output would be to permute the vertex labels. And of course the corresponding labels in the edges. I drew it on paper and it looks right to me.

**Comment by sbromberger** [comment]
Actually, this is right, since it's an undirected graph. `1 => 5` is the same as `5 => 1` so we may be good.

**Comment by sbromberger** [comment]
need more caffeine.
