### ISSUE TITLE
Implementing LG's traits in external packages is too hard

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/LightGraphs.jl#668]
The current issues with traits are too complicated to expect new package authors to define their own versions of the traits. In particular the IsDirected trait and is_directed function.

**Comment by sbromberger** [comment]
Theoretically they just need to define `is_directed(g)` and `is_directed(::Type{ExtGraph})`. If this doesn't work please paste an example.

**Comment by jpfairbanks** [comment]
We need better docs at least. Rohit, Igor, and I have spent 2 hours at the juliacon hackathon trying to get it to work for Junet.jl. See the DBGraphs package for an example that is broken.

**Comment by sbromberger** [comment]
```
julia> using LightGraphs

julia> struct MyGraph <: AbstractGraph end

julia> struct MyDiGraph <: AbstractGraph end

julia> g = MyDiGraph()
MyDiGraph()

julia> import LightGraphs:is_directed

julia> is_directed(g::MyDiGraph) = true
is_directed (generic function with 9 methods)

julia> is_directed(g::MyGraph) = false
is_directed (generic function with 10 methods)

julia> is_directed(::Type{MyDiGraph}) = true
is_directed (generic function with 11 methods)

julia> is_directed(::Type{MyGraph}) = false
is_directed (generic function with 12 methods)

julia> is_directed(MyDiGraph)
true

julia> using SimpleTraits

julia> import LightGraphs:IsDirected

julia> @traitfn foo(g::::(!IsDirected)) = 1
foo (generic function with 2 methods)

julia> @traitfn foo(g::::IsDirected) = 2
foo (generic function with 3 methods)

julia> foo(g)
2

julia> foo(MyDiGraph())
2

julia> foo(MyGraph())
1

```

**Comment by sbromberger** [comment]
@jpfairbanks your latest commit shows that you have it working. Can we close this out?

**Comment by jpfairbanks** [comment]
This should be a more broad discussion of the role of traits in LG.
Paging @inguar and @rohitvarkey.

 We had some in person discussion of traits with @iamed2 today. Based on experience, @iamed2 prefers to use explicit "Holy Traits" over some automagic like SimpleTraits.jl. The explicit definition of the types `Directed, Undirected` and the corresponding function `isdirected(::MyDiGraph) = Directed(); isdirected(::MyGraph) = Undirected()` would be simpler and less prone to hard to inspect SimpleTraits magic.

I was convinced of the simplicity of this approach. Then functions that only work on directed graphs just take a first argument `f(::Directed, g::AbstractGraph, otherargs...)` and functions that only work on undirected graphs take a first argument `f(::UnDirected, g::AbstractGraph, otherargs...)` with a dispatching wrapper function `f(g::AbstractGraph, otherargs...) = f(isdirected(g), g, otherargs...)`

I think a design based on explicit *Holy Traits* would be simpler and more robust to future development in the trait based design ecosystem.

@iamed2: did I recap our discussion appropriately?
@ttimholy: Is this a good use of explicit traits?

**Comment by sbromberger** [comment]
I'm open to this but I don't see this as particularly appealing right now. It's certainly not as simple, and (at least for me) the use of `::::` for traits makes things explicit (that is, you *know* this is a trait you're dealing with), as opposed to including some random type.

Also, I don't think there's a way to do "defaults", so while we have a single binary trait (like `IsDirected`), we're ok, but it doesn't look like it'll scale if we want more traits: we'll have to explicitly create multiple combinations. (Show me how you'd handle "IsDirected", "HasSelfLoops", and "IsWeighted" where a function needs to do something special on directed graphs with self loops, and something else on undirected weighted graphs. Add in non-binary traits and it becomes even more complex).

Anyway - open to discussion but there has to be a pretty compelling reason to switch from SimpleTraits right now. I wasn't present in today's coding session and don't claim to have perfect knowledge but I don't understand why it was giving you such difficulties. I looked at your code when I got back and it was working, and I think it was pretty much as I had suggested in Slack.

**Comment by jpfairbanks** [comment]
> I'm open to this but I don't see this as particularly appealing right now. 
  I don't think it is urgent at the moment either.

> It's certainly not as simple,
  I think it is a different kind of simple, when SimpleTraits.jl is working it is very simple. When it is not working, it is just random error messages and you need to understand a bit about the internals of that package. There were several points in our coding sesh where people exclaimed "What is this voodoo magic" before we got it to work.

> the use of :::: for traits makes things explicit (that is, you know this is a trait you're dealing with), as opposed to including some random type.

Perhaps a convention like `TRDirected` to indicate that the type is a trait would be sufficient. 

> Also, I don't think there's a way to do "defaults", so while we have a single binary trait (like IsDirected), we're ok, but it doesn't look like it'll scale if we want more traits: we'll have to explicitly create multiple combinations. (Show me how you'd handle "IsDirected", "HasSelfLoops", and "IsWeighted" where a function needs to do something special on directed graphs with self loops, and something else on undirected weighted graphs. Add in non-binary traits and it becomes even more complex).

I am now very concerned that the complexity of multiple traits will not be handled by SimpleTraits and that debugging trait definition problems will be very hard.

> Anyway - open to discussion but there has to be a pretty compelling reason to switch from SimpleTraits right now.

Yeah I agree there is no urgent need. Just something to consider going forward.

> I wasn't present in today's coding session and don't claim to have perfect knowledge but I don't understand why it was giving you such difficulties. I looked at your code when I got back and it was working, and I think it was pretty much as I had suggested in Slack.

The problem is that we tried approximately 10 alternatives that didn't work before I found the one version that does work. Also adding code will make it go from working to not working and I don't really know why this version works and the others don't.

Anyway the current system works, but adding the trait was definitely the highest barrier to entry for implementing the interface.

**Comment by sbromberger** [comment]
> Also adding code will make it go from working to not working and I don't really know why this version works and the others don't.

This seems to me to be the key point and one that makes this issue worthy of discussion. The proof of the pudding, of course, is in the tasting. I'd suggest (when you have time) that you show the equivalent of, say, `density` using HolyTraits (do we need the ™ for this? I feel funny not including it) and then we can compare.

**Comment by timholy** [comment]
No ™ required :smile:. Last I looked, @jpfairbanks was right that simultaneous multi-trait dispatch couldn't be easily handled with SimpleTraits. Of course there's some chance that will change in the next year or so.

**Comment by jpfairbanks** [comment]
@Timholy Is official trait support on the 1.0 roadmap? Without that I would have a hard time using traits as a critical piece of this library.

**Comment by iamed2** [comment]
"Traits" in the Holy trait sense will be supported. They are just pure functions on types, and optimizing those in the way that makes them useful here is critical to the way Base is implemented. Holy traits are used in Base and will continue to be used and supported in 1.0. 

SimpleTraits.jl and Traits.jl are just packages, and are supported at the discretion of maintainers. I do not expect those to be _officially_ supported, but SimpleTraits.jl will probably be supported by maintainers to work on 1.0.

**Comment by sbromberger** [comment]
I'm going to close this out since things seem to be working decently well.
