### ISSUE TITLE
Tagging a new version

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#669]
We have several new features in LG since 0.9.0:
- all sorts of parallel stuff
- kcores / decomposition
- doc mods
- (backwards-compatible) change to `DefaultDistance()`
- more

I'd like to tag a new version. The options are `v0.9.1` and `v0.10.0`. I'm in favor of the former, since we don't have breaking changes, but would like to hear opinions and votes. I'd like to do this by end of week. Thanks.

**Comment by jpfairbanks** [comment]
I had mentally prepared for not having a v0.10 and going right to v1.0. But we also decided that v1.0 of LG would coincide with v1.0 of Julia. These features are significant but only add things. Things will be more cut and dry once we escape the v0.X wild west.

Maybe to answer this question we can ask subquestion.

- [ ] How do people feel about having two digit minor versions within 0.X?
- [ ] How much do people care about LGv1.0 being released after JLv1.0 (ie Dec2017)?
- [ ] Are there any breaking API changes in this update?

If there are any breaking api changes we should do v0.10.0 if not we have some freedom.

**Comment by sbromberger** [comment]
Thanks, @jpfairbanks . As always, thoughtful questions.

> How do people feel about having two digit minor versions within 0.X?

Better than forcing a major version number.

> How much do people care about LGv1.0 being released after JLv1.0 (ie Dec2017)?

I don't much care. If we're not ready to stabilize the API (assuming we're using semver; I'm not in favor at this point), then we shouldn't do it.

> Are there any breaking API changes in this update?

There shouldn't be.

**Comment by jpfairbanks** [comment]
Then I think we should go with 0.9.1. when all the parallel API stuff stabilizes we can bump the minor. 

I think we have to use SemVer for Pkg3 to work.

**Comment by sbromberger** [comment]
OK, that sounds good. I'd like to resolve #670 before tagging.

**Comment by sbromberger** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/10010
