### ISSUE TITLE
Direction of community detection development

### ISSUE THREAD

**Issue by nickeubank** [JuliaGraphs/LightGraphs.jl#675]
Just getting into Julia and am trying to get the lay of the land in the JuliaGraphs ecosystem, and was hoping someone would be kind enough to answer a couple quick questions:

1. Is there a set home for community detection algorithms? Seems there's one [stand-alone repo](https://github.com/JuliaGraphs/CommunityDetection.jl), one set of community detection algorithms in [LightGraphs.jl](https://github.com/JuliaGraphs/LightGraphs.jl/tree/master/src/community), and another set in [LightGraphsExtras.jl](https://github.com/JuliaGraphs/LightGraphsExtras.jl/tree/master/src/community). And maybe others I am not aware of?

2. I'm looking for a specific community optimization algorithm -- a (resolution-free) [Constant Potts Model](http://www.traag.net/wp/wp-content/papercite-data/pdf/traag_narrow_2011.pdf). I haven't been able to find it in the library, but am curious if it's hiding somewhere I don't see, of if there's a community detection optimizer that takes an arbitrary objective function hiding somewhere (like a Louvain optimizer (something like [this](https://github.com/vtraag/louvain-igraph)?)). 

    2a. If not, curious if there are any efforts already underway to expand. Just getting my feet wet in Julia, but adding may be a good way to dive in if not.

**Comment by sbromberger** [comment]
Hi @nickeubank - welcome.

> Is there a set home for community detection algorithms? Seems there's one stand-alone repo, one set of community detection algorithms in LightGraphs.jl, and another set in LightGraphsExtras.jl. And maybe others I am not aware of?

CommunityDetection.jl was split off from LightGraphsExtras.jl in order to simplify the dependency requirements and should be preferred over LGE. There's some stuff in LightGraphs.jl as well (cliques, label propagation, clustering, core-periphery, modularity). Depends on what you want.

> I'm looking for a specific community optimization algorithm -- a (resolution-free) Constant Potts Model. I haven't been able to find it in the library, but am curious if it's hiding somewhere I don't see, of if there's a community detection optimizer that takes an arbitrary objective function hiding somewhere (like a Louvain optimizer (something like this?)).

We don't have CPM implemented. We're always accepting PRs (to your implied 2a. question :) ). Check out [CONTRIBUTING.md](https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/CONTRIBUTING.md) for more info, and feel free to grab us here or on gitter.

**Comment by nickeubank** [comment]
@sbromberger Excellent, thanks so much for the guidance! Like I said, I'm just diving into Julia, so I doubt I'll have anything soon, but I use CPM a lot, so this might be a good way to force myself to commit to the language and contribute while I'm at it! 

(Feel free to close if you'd like)

**Comment by sbromberger** [comment]
Well, we're a pretty friendly bunch. If you haven't seen the general Julia resources, check out

- https://discourse.julialang.org
- julialang/julia on gitter (also, check out JuliaGraphs/LightGraphs.jl!)

Looking forward to your participation!

**Comment by jpfairbanks** [comment]
Welcome @nickeubank we are happy to have more people join our community of JuliaGraphs. Potts models and Community detection would be good to have supported for LightGraphs. If you want to use another package that provides optimization or Monte Carlo functionality, then it should probably go in LightGraphsExtras. If it doesn't need any external dependencies, then it can go in a file LightGraphs.jl `./src/community/potts.jl`

**Comment by sbromberger** [comment]
Ref https://github.com/PoisotLab/EcologicalNetwork.jl/blob/master/src/louvain.jl

Something relevant that we can adapt?
