### ISSUE TITLE
BUG: rem_vertex! not adjusting edge vertices correctly?

### ISSUE THREAD

**Issue by nickeubank** [JuliaGraphs/LightGraphs.jl#677]
Looks to me like `rem_vertex!` is mis-adjusting edge indices. 

![screen shot 2017-07-07 at 1 28 15 pm](https://user-images.githubusercontent.com/9683693/27973714-3f9099be-6318-11e7-91e2-26416a87ebfd.png)

**Comment by sbromberger** [comment]
Nope. What's happening is that vertices 3 and 7 are being swapped, and then vertex 3 is deleted. This is a more efficient way of removing a vertex. Check out the `rem_vertex!` documentation for more info.

**Comment by nickeubank** [comment]
Oh! Sorry, used to igraph style of shifting indices down.

**Comment by sbromberger** [comment]
yeah. That's very expensive given our graph structure. We *used* to do that but found that this is much more performant.
