### ISSUE TITLE
Discussion: Vertex Re-labeling Promises

### ISSUE THREAD

**Issue by nickeubank** [JuliaGraphs/LightGraphs.jl#683]
Related to #676: I think it makes sense to establish a general rule for the promises we want to make when vertices are added or removed. 

Seems there are two choices:

- Require each function to have a fixed re-mapping behavior, preserved across Graph types
- Make no promises on how things will be relabeled, but require the functions return an Array mapping old vertex IDs to new vertex IDs in a consistent manner. 

The former seems a little easier for users, though honestly not that much easier -- I think in most cases one is modifying graphs (merging multiple vertices or doing more than one swap&pop), it's hard for a user to easily keep track of what's going on, even if it's deterministic. 

The later, by contrast, is stable and also flexible enough to allow people to adapt behavior to make it maximally performant for the application and Graph type in question. 

One thing I'm not sure I would support would be allowing these functions to vary in their behavior across Graph types -- that, I think, is just inviting users to get in trouble.

**Comment by jpfairbanks** [comment]
Yeah I think that this summarizes things correctly. The performance issues regarding all data structures using the same ordering appear insurmountable. So we should definitely require operations to return enough information for the caller to deduce the new vertex ordering.

Ideally the graph modifications are happening in a higher level operation for example, merging vertices happens inside a community detection algorithm so only people writing algorithms need to be aware of this problem. The higher level operation will return the new vertex ordering anyway no matter how the ordering is changed by the lower level primitives such as `merge_vertices!`

**Comment by sbromberger** [comment]
> Make no promises on how things will be relabeled, but require the functions return an Array mapping old vertex IDs to new vertex IDs in a consistent manner.

I'm not sure I like this approach. What it means is that `rem_vertex!` would return something different from both `rem_edge!` and `add_vertex!`.

**Comment by jpfairbanks** [comment]
Oh because the add and remove edge only return information about success.
Also we can't return the whole array of new labels, because that would require O(n) just to construct it.

**Comment by sbromberger** [comment]
> Require each function to have a fixed re-mapping behavior, preserved across Graph types

Does this imply that swap-n-pop is not a "fixed behavior"? If so, this will have performance implications across any graphs that use adjacency lists as a backend.

**Comment by jpfairbanks** [comment]
swap and pop is a "fixed-behavior." We need to have a system where every type can choose the optimal behavior for them.

**Comment by jpfairbanks** [comment]
I think that is why modification routines need to return enough information for the caller to infer the change in labels. 

For example `rem_vertex!(g,i)` can return the old label for the vertex now at position `i`. 
This would work as follows:

```julia
g = Graph()
#add some edges

i = 10
u = rem_vertex(g, i)
if u == i+1
    # shifting semantics are being used
elseif u = nv(g) + 1
    # swap and pop semantics
else
    # chaos
end
```

We could also use a Holy Trait to solve this problem. Every graph type defines a function `removalsemantics(g::T) = RemoveSwap`  or `removalsemantics(g::T) = RemoveShift` and then the higher level functions such as merging can do the right thing based on that trait. 

@nickeubank for reference this is called the [Holy Trait Trick](https://github.com/mauro3/Traits.jl/blob/master/docs/presentation/juliacon-presentation.org)

**Comment by sbromberger** [comment]
👎 for making this a trait at this point. If the function is written with an arg or kwarg, then we can just have implementation on a case-by-case basis.

The argument against making this a trait is that it affects precisely one (now possibly two) functions.

**Comment by nickeubank** [comment]
> Where does this end?

Very fair point. I know I'll probably only ever use SimpleGraphs, and that's probably true for most users. 

> because that would require O(n) just to construct it.

It's O(n), but it's a pretty darn fast O(n) isn't it, especially if it's applied in bulk (pass a set of vertices to change, only get back one new address vector)?

The only alternative I see is to offer something like an Nx2 Array with original and new labels for everything that's changed -- it'd work, but kinda a pain for users, who then have to work with merge semantics all the time. Plus, when we get into something with shifting behavior, it may end up being slower than a simple vector.

**Comment by nickeubank** [comment]
Relatedly, seems like what we do here with more or less determine the viability of https://github.com/JuliaGraphs/Networks.jl .

**Comment by sbromberger** [comment]
> It's O(n), but it's a pretty darn fast O(n) isn't it

I don't know how one O(n) is faster than another O(n). It's certainly O(n) in time (at least) AND memory and isn't something that I'd support in a core function, especially for SimpleGraphs, which are designed to be optimally performant.

What I would suggest is, if you really want a graph that is performant for dynamic modifications, you consider writing your own backend storage that does this very efficiently. Now that we've got abstractions, it's really not that hard to do. SimpleWeightedGraphs is a good example, I think. It's 275 lines of code WITH the docstrings.

**Comment by nickeubank** [comment]
O(N) isn't a speed, it's a scaling factor (with size of data). If an operation is super quick (in comparison to other things being done), it's not as big a deal that it increases in run time linearly as if it were 50% of run time even at small scales. I can have a function that's O(N^2) that's faster than a function that's O(N) for all N below some limit. 

Re: connection to networks: if networks store vertex attributes, don't they have to keep track of index remappings?

**Comment by sbromberger** [comment]
> O(N) isn't a speed, it's a scaling factor (with size of data)

Yes, I understand, but you can't then assume the size of your data (which is what you did when you described your O(N) as "fast"). Just because *your* use case isn't N ~ |V|, doesn't mean someone else's won't be.

...and I see what you're saying regarding Networks.jl. The way it works is that there is a dictionary that maps vertex indices to some set of vertex properties. Any modification to vertex indices needs to propagate to the dicts.

**Comment by nickeubank** [comment]
I'm just saying the fact making a vector of new assignments is O(n) does not mean it's not the best solution. Seems it was quickly getting discarded on that basis alone, which I don't think makes sense unless we have an alternative that's faster at plausible network sizes.

**Comment by sbromberger** [comment]
> I'm just saying the fact making a vector of new assignments is O(n) does not mean it's not the best solution

When the alternative is doing what we've been doing and not providing O(n) mapping on return, it's axiomatically not the best solution (performance wise - note that I'm not making any comment on its utility, of which I happen to see the benefit.)

**Comment by jpfairbanks** [comment]
Yeah the idea of a graph package designed for dynamic graphs would be fun to implement using the abstractions we have here. I'm glad we delayed opening up the interface because it really is hard to make decisions about performance against arbitrary backing stores.

I think for now we should focus on getting Community detection implemented for SimpleGraph and then making it more general and performant after we have a working implementation.

**Comment by nickeubank** [comment]
@jpfairbanks sounds good. I've burned much of my free time for julia exploration for a little while, but will let you know if / when I get it pulled together!

**Comment by jpfairbanks** [comment]
Sorry to hear that. We got your merge_vertices code merged in, so that is a good step!

**Comment by nickeubank** [comment]
@jpfairbanks Thanks! I'll be back I'm sure -- this is a great library. Just gotta focus on that other job I get paid for a little while. :)

**Comment by sbromberger** [comment]
you don't get paid to help out with LightGraphs?? :)

**Comment by nickeubank** [comment]
@sbromberger :) not directly at least...

Though having to write little diffusion model for research. https://github.com/nickeubank/julia_diffusion_model/ Will try and generalize and add to library when done.

**Comment by sbromberger** [comment]
Closing this out since I think we've got a good direction now.
