### ISSUE TITLE
Interest in diffusion model in LightGraphs.jl?

### ISSUE THREAD

**Issue by nickeubank** [JuliaGraphs/LightGraphs.jl#699]
Had to write a diffusion model for my own work -- any interest in integration into LIghtGraphs?

https://github.com/nickeubank/julia_diffusion_model

**Comment by jpfairbanks** [comment]
Yes this should go in `/src/traversals/diffusion.jl` next to the `randomwalks.jl` in that directory. of course the tests should go in with the tests and update the docs.

**Comment by nickeubank** [comment]
Great, thanks!

**Comment by nickeubank** [comment]
If either of you have a chance, could I ask for your help in generalizing in #700 ? I wrote this for `Graph` types (my use-case), and seems like I can generalize to `AbstractGraphs` given it only relies on functions in the API. But unfortunately I seem to be getting the parametric type specifications wrong somewhere... 

Getting: 


    LoadError: TypeError: Type{...} expression: expected UnionAll, got Type{LightGraphs.AbstractGraph}
    while loading /users/nick/github/julia_diffusion_model/simple_diffusion.jl, in expression starting on line 5
    in include at base/sysimg.jl:14
    in include_from_node1 at base/loading.jl:569

(If too much trouble, can just submit the less generalized version for Graph only)

**Comment by nickeubank** [comment]
Closed by #700
