### ISSUE TITLE
Communicability centrality

### ISSUE THREAD

**Issue by kshyatt** [JuliaGraphs/LightGraphs.jl#703]
[networkx](https://networkx.github.io/documentation/networkx-1.10/reference/algorithms.centrality.html#communicability) provides this measure and a description is available [here](https://arxiv.org/pdf/0905.4102.pdf).

**Comment by sbromberger** [comment]
This is actually in process now. It will be a few weeks before it can be released. In the meantime, for small graphs, `diag(expm(full(adjacency_matrix(g))))` will give you the centralities.

**Comment by jpfairbanks** [comment]
The NetworkX code does use full EVD and then compute matrix exponential from the eigenvalues and eigenvectors. 

```python
    import numpy
    import scipy.linalg
    nodelist = G.nodes() # ordering of nodes in matrix
    A = nx.to_numpy_matrix(G,nodelist)
    # convert to 0-1 matrix
    A[A!=0.0] = 1
    w,vec = numpy.linalg.eigh(A)
    expw = numpy.exp(w)
    mapping = dict(zip(nodelist,range(len(nodelist))))
    sc={}
    # computing communicabilities
    for u in G:
        sc[u]={}
        for v in G:
            s = 0
            p = mapping[u]
            q = mapping[v]
            for j in range(len(nodelist)):
                s += vec[:,j][p,0]*vec[:,j][q,0]*expw[j]
            sc[u][v] = float(s)
    return sc
```

The snippet that @sbromberger supplied will work and is similar on the space,time,accuracy tradeoff space.

**Comment by sbromberger** [comment]
I'm going to close this out since we have a workaround until my code is releasable.
