### ISSUE TITLE
Edit on github link broken

### ISSUE THREAD

**Issue by mauro3** [JuliaGraphs/LightGraphs.jl#715]
On http://juliagraphs.github.io/LightGraphs.jl/latest/index.html, the "Edit on Github" link is broken
http://juliagraphs.github.io/LightGraphs.jl/latest/index.html

**Comment by sbromberger** [comment]
There are a couple pages - the index, LICENSE, and one other - that are not actually part of the docset; they're markdown files copied over from `src`, built, and then removed. To edit them, just find them in the source tree and propose a PR.

All the other pages should be editable.
