### ISSUE TITLE
Rewrite strongly_connected_components to use non-visitor based DFS

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#720]
@jpfairbanks per discussion. Thanks. DFS code should be as close to what's proposed in https://github.com/JuliaGraphs/LightGraphs.jl/pull/717/files#diff-02699da1fd8d4dfe35842230df7838efR318 as possible.

**Comment by sbromberger** [comment]
@jpfairbanks - I've asked @somil55 to take a look as well.

**Comment by somil55** [comment]
@sbromberger I am on this

**Comment by somil55** [comment]
#723

**Comment by sbromberger** [comment]
Closed via #723.
