### ISSUE TITLE
Connected Components of Sparse Matrices

### ISSUE THREAD

**Issue by ranjanan** [JuliaGraphs/LightGraphs.jl#741]
Hi, I wanted to know if there's an API to find connected components of a sparse matrix directly. I realise I could convert to a Graph object and then call the connected_components function on it, but I was wondering if there was a better way
```julia
a = sprand(10^6, 10^6, 1e-6)
a = a + a'
@time connected_components(Graph(a))
```
gives
```
1.811438 seconds (4.60 M allocations: 402.428 MiB, 42.82% gc time)
```
which is a fair bit of memory.

**Comment by sbromberger** [comment]
The best way to do this is to create a `SimpleWeightedGraph` which uses a sparse matrix as its backend, and then run `connected_components` on it:

```
julia> using LightGraphs, SimpleWeightedGraphs

julia> a = sprand(10^6, 10^6, 1e-6);

julia> g = SimpleWeightedGraph(a + a')
{1000000, 999139} undirected simple Int64 graph with Float64 weights

...

julia> @time connected_components(g);
  0.535248 seconds (1.69 M allocations: 164.101 MiB, 10.76% gc time)
```

**Comment by ranjanan** [comment]
Oh okay. I have some code that does a simple breadth first search directly on the sparse matrix to find neighbours and mark connected components. It takes less memory and a little less time. Can I submit a PR here? Or is there another package in the ecosystem that I should submit it to?

**Comment by sbromberger** [comment]
If it works directly on sparse matrices, it might be worth making a specialized algorithm for `SimpleWeightedGraphs`. If so, feel free to file a PR over there in the `overrides.jl` file.

**Comment by ranjanan** [comment]
https://github.com/JuliaGraphs/SimpleWeightedGraphs.jl/pull/8

**Comment by sbromberger** [comment]
Closing out since we merged https://github.com/JuliaGraphs/SimpleWeightedGraphs.jl/pull/8
