### ISSUE TITLE
New Docs

### ISSUE THREAD

**Issue by nickeubank** [JuliaGraphs/LightGraphs.jl#759]
I'd like to suggest that `LightGraphs` has outgrown its current README, and ask for some input on best ways to move forward with new docs. 

Format
-------

Seems like the two choices are (a) updated README, or (b) a stand-alone readthedocs page. 

Content
--------

Some thoughts on useful content:

- Types
   - **Abstract Graph**: what's promised in API
   - **Graph** and **DiGraph: The library implemented concrete types, with note on parameterizations. (Do we have weighted graphs now?)

- Construction
    - Inbuilt constructors: `smallgraphs`, `randgraphs`, `staticgraphs`
    - Building graphs by hand (adding edges/vertices, removing edges/vertices, etc.)

- IO
    - Pointer to the `GraphIO` library

- Accessing state (`ne`, `nv`, etc.)

- Analysis
    - Transversals
    - Properties (diameter, degree, etc.)

**Comment by sbromberger** [comment]
:+1 to this. I've been mulling over how best to update the docs for a while. I think the README (option a) is the better choice.

FWIW, we don't use RTD anymore. We migrated to Github Pages a while back.

PRs gratefully accepted.

**Comment by jpfairbanks** [comment]
Yeah I was using RTD as the generic term for standalone documentation that is generated from markedup files in the repo.

**Comment by nickeubank** [comment]
OK -- if someone has experience with setting up a Github Page and can PR that, I'm happy to then work on content.

**Comment by jpfairbanks** [comment]
https://juliagraphs.github.io/LightGraphs.jl/latest/

**Comment by sbromberger** [comment]
> Do we have weighted graphs now?

[SimpleWeightedGraphs](https://github.com/JuliaGraphs/SimpleWeightedGraphs.jl) and [MetaGraphs](https://github.com/JuliaGraphs/MetaGraphs.jl) support weights.

**Comment by nickeubank** [comment]
great, thanks! will start play with.

**Comment by nickeubank** [comment]
Not to get too meta, but would someone mind updating the `contributing.md` doc with some notes about how to build the docs on ones own computer so I can work on... updating the docs? :)

**Comment by sbromberger** [comment]
hah. I don't generally build the docs, but I think it's as simple as `julia make.jl` from the `docs/` directory.

**Comment by nickeubank** [comment]
perfect, thanks!

**Comment by nickeubank** [comment]
closed by #762
