### ISSUE TITLE
`src` and `dst` for undirected graphs

### ISSUE THREAD

**Issue by nickeubank** [JuliaGraphs/LightGraphs.jl#760]
Playing with some functions I haven't used before while working on docs. What should one make of the output of `src` and `dst` on an undirected graph?

**Comment by sbromberger** [comment]
`src` and `dst` are methods on edges, not on graphs. If the edge is used in an undirected graph, then they just represent the two endpoints, and `has_edge(g, src(e), dst(e)) == has_edge(g, dst(e), src(e))` for all edges in the undirected graph.

**Comment by nickeubank** [comment]
ok, so each edge in an undirected graph has one end arbitrarily assigned as `src` and the other end arbitrarily assigned as `dst`?

**Comment by sbromberger** [comment]
depends on what you mean by `arbitrarily`. The guarantee of `edges()` is that `src` <= `dst` but we don't hold the user to that when he adds an edge to the undirected graph, or checks to see whether an edge is in an undirected graph.

**Comment by nickeubank** [comment]
> The guarantee of edges() is that src <= dst

Oh, I assumed source and destination had clear meaning in directed graphs (i.e. `dst(e)` would be the `out_neighbor(src(e))`). Is that intuition incorrect?

**Comment by sbromberger** [comment]
See edit. We are only talking about undirected graphs in this discussion.

**Comment by nickeubank** [comment]
OK -- so for a directed graph, they have a sense of direction; for undirected we order by vertex index. Thanks.

**Comment by sbromberger** [comment]
yup, that's pretty much it, though we don't require the user to preorder by vertex index for undirected graphs.

**Comment by nickeubank** [comment]
ok!
