### ISSUE TITLE
Kruskal's algorithm

### ISSUE THREAD

**Issue by Ward9250** [JuliaGraphs/LightGraphs.jl#766]
Can LightGraphs be used to do Kruskal's algorithm or similar to get the minimum spanning tree of a set of vertices?

**Comment by sbromberger** [comment]
We have `kruskal_mst`, though the docs seem to have disappeared:

```
"""
    kruskal_mst(g, distmx=weights(g))

Return a vector of edges representing the minimum spanning tree of a connected, undirected graph `g` with optional
distance matrix `distmx` using [Kruskal's algorithm](https://en.wikipedia.org/wiki/Kruskal%27s_algorithm).
"""
```

**Comment by sbromberger** [comment]
@Ward9250 I hope this solved your issue - if not, feel free to respond here and I'll re-open.
