### ISSUE TITLE
incidence_matrix not defined

### ISSUE THREAD

**Issue by BoundaryValueProblems** [JuliaGraphs/LightGraphs.jl#767]
I'm using the latest version of LightGraphs v0.11.0. I generated a simple graph ```G```, and tried to get its incidence matrix but got the following error.
```
Q=incidence_matrix(G)
UndefVarError: incidence_matrix not defined
```
On the other hand, I don't have any problem with ```adjacency_matrix``` and ```laplacian_matrix``` functions. I checked the sources, and the function ```incidence_matrix``` is defined in ```src/linalg/spectrum.jl```, but why is it undefined in the julia session?
Thanks for your help!
BVPs

**Comment by sbromberger** [comment]
It's a reexport bug. As a workaround, you can use `LightGraphs.LinAlg.incidence_matrix()` to get to the function.
