### ISSUE TITLE
Issue with reading in a graph

### ISSUE THREAD

**Issue by pavanefpm** [JuliaGraphs/LightGraphs.jl#769]
Hello, I am reading in graph data from a edgelist file from here (http://konect.uni-koblenz.de/networks/digg-friends) and have run into a weird issue. The network has 279630 nodes and 1731653 edges.
This is what I am doing currently

    digg = readdlm("../../Modeling\\ABM\\NetworkAnalysis\\out.digg-friends", skipstart = 1)
    connectivity_data = digg[1:end, 1:2]
    connectivity_data = round.(Int64, connectivity_data)

    g1 = LightGraphs.Graph(maximum(connectivity_data))

    for i = 1:size(connectivity_data)[1]
      LightGraphs.add_edge!(g1, connectivity_data[i, 1], connectivity_data[i, 2])
    end

While the `connectivity_data` is showing the edge count of the network correctly

    summary(connectivity_data)
    "1731653×2 Array{Int64,2}"

The graph structure is not adding all the edges

     g1
     {279630, 1548126} undirected simple Int64 graph

I am not sure what is happening here?

**Comment by sbromberger** [comment]
First, you're creating an undirected graph from a directed edgelist. You probably want `DiGraph`:
```
digg = Int.(readdlm("out.digg-friends", skipstart = 1)[:,1:2])
g = DiGraph(maximum(digg))
for e = zip(digg[:,1], digg[:,2])
    add_edge!(g, e)
end
```
yields
```
julia> g
{279630, 1731653} directed simple Int64 graph
```

**Comment by pavanefpm** [comment]
Thank you!
