### ISSUE TITLE
Export to compressed lg format by default in doc

### ISSUE THREAD

**Issue by Azzaare** [JuliaGraphs/LightGraphs.jl#770]
In the doc, it is said that LG supports by default two format of exportation that are .lg and .lgz (the second one being the compressed one).
It seems that by default the `savegraph` function uses `compress=true`. Shouldn't the first example in the doc (`.lg`) uses `compress=false`?

**Comment by sbromberger** [comment]
Yeah, it's definitely misleading. I'll make a change.
