### ISSUE TITLE
Change capacity and residual matrices to weights in flow algorithms

### ISSUE THREAD

**Issue by Azzaare** [JuliaGraphs/LightGraphs.jl#772]
Following a [discussion](https://github.com/JuliaGraphs/MetaGraphs.jl/issues/14#) in `MetaGraphs.jl`, we might want to consider changing flow algorithms so that they use `weights` instead of capacity and residual matrices.

**Comment by sbromberger** [comment]
See also #783

**Comment by sbromberger** [comment]
Closing this out because it should be addressed in LightGraphsFlows.jl. If this is a mistake, please let me know and I can reopen.

**Comment by sbromberger** [comment]
(cc @mbesancon )
