### ISSUE TITLE
We need graph coloring

### ISSUE THREAD

**Issue by juliohm** [JuliaGraphs/LightGraphs.jl#773]
It would be great to have some [graph coloring](https://en.wikipedia.org/wiki/Graph_coloring) algorithms in LG. I am opening the issue just in case someone with time and experience can contribute with code.

Dear Prof. @scheinerman,

I see you have implementations of graph coloring in your package [simple_corloring.jl](https://github.com/scheinerman/SimpleGraphs.jl/blob/master/src/simple_coloring.jl). Would you mind sharing them with us with the appropriate credit given to you? :blush: Also, if you have good references on the subject, that would be very helpful.

**Comment by scheinerman** [comment]
You’re welcome to adapt this code into LightGraphs, of course. I’m not really a graph algorithms expert though and the random coloring algorithm I have in that file is pretty basic. You may also wish to look at

https://github.com/scheinerman/SimpleGraphAlgorithms.jl/blob/master/src/kcolor.jl

which uses integer linear programming to find colorings. Again, it’s hardly state of the art, but it’s a start.



On Nov 1, 2017, at 20:46, Júlio Hoffimann <notifications@github.com<mailto:notifications@github.com>> wrote:


It would be great to have some graph coloring<https://en.wikipedia.org/wiki/Graph_coloring> algorithms in LG. I am opening the issue just in case someone with time and experience can contribute with code.

Dear Prof. @scheinerman<https://github.com/scheinerman>,

I see you have implementations of graph coloring in your package simple_corloring.jl<https://github.com/scheinerman/SimpleGraphs.jl/blob/master/src/simple_coloring.jl>. Would you mind sharing them with us with the appropriate credit given to you? 😊 Also, if you have good references on the subject, that would be very helpful.

**Comment by juliohm** [comment]
Thank you for the directions, very helpful information. Feel free to contribute code directly as well, currently I am not able to write any code that is not related to my PhD. :blush:

**Comment by jpfairbanks** [comment]
@sbromberger @juliohm How did miss the great work happening at https://github.com/scheinerman/SimpleGraphs.jl The whole collection of SimpleWorld packages looks like a really great tool for teaching and studying combinatorics.

**Comment by sbromberger** [comment]
Didn’t miss it. I’ve been following it for a couple of years :)

**Comment by mbesancon** [comment]
still a feature to integrate to LightGraphs I guess?

**Comment by juliohm** [comment]
Yes, that would be awesome to have in LG. Please feel free to go ahead and implement it if you have time, I am stuck with a bunch of deadlines.

**Comment by scheinerman** [comment]
I don't have the time ... I hope someone else picks this up :-)

**Comment by SohamTamba** [comment]
I'm working on a pull request for Graph coloring. I already have some code ready but I'm not sure where to place it, would /src/traversals/color.jl be appropriate for this particular problem?
