### ISSUE TITLE
How to assign weights to a graph?

### ISSUE THREAD

**Issue by SamZhou1996** [JuliaGraphs/LightGraphs.jl#775]
Excuse me, although graphs have the filed weights, but I can't seem to find the right way to explicitly assign costumed weights to the edges of a graph... Is there an easy way to do this?

**Comment by juliohm** [comment]
You want one of the following:

https://github.com/JuliaGraphs/SimpleWeightedGraphs.jl

https://github.com/JuliaGraphs/MetaGraphs.jl

**Comment by sbromberger** [comment]
The other way to do it is to keep your own matrix of weights, and pass that in to functions that require it.
