### ISSUE TITLE
linalg docs are not showing up on the website

### ISSUE THREAD

**Issue by harryscholes** [JuliaGraphs/LightGraphs.jl#779]
See https://juliagraphs.github.io/LightGraphs.jl/latest/linalg.html

**Comment by sbromberger** [comment]
This fixes it locally but for some reason it's not working online.

**Comment by harryscholes** [comment]
Does this work?

```
Modules = [LightGraphs]
Pages   = [
    "linalg/graphmatrices.jl",
    "linalg/nonbacktracking.jl",
    "linalg/spectral.jl"
]
Private = false
```

**Comment by sbromberger** [comment]
Al there we go. It works now - just took a while for the docs to be pushed. Can you confirm?

**Comment by harryscholes** [comment]
Confirmed 😄

**Comment by sbromberger** [comment]
Thanks for reporting this, @harryscholes !
