### ISSUE TITLE
Broken @ref in docs

### ISSUE THREAD

**Issue by kshyatt** [JuliaGraphs/LightGraphs.jl#782]
In the [docs](http://juliagraphs.github.io/LightGraphs.jl/latest/pathing.html#LightGraphs.dijkstra_shortest_paths) for `dijkstra_shortest_paths`, the link to `DijkstraState` is broken.

**Comment by sbromberger** [comment]
Thanks, @kshyatt - making this a "help wanted" issue. Appreciate the heads up.

**Comment by sbromberger** [comment]
Fixed via #784. Thanks1
