### ISSUE TITLE
Documentation Flow and Cut

### ISSUE THREAD

**Issue by roflmaostc** [JuliaGraphs/LightGraphs.jl#786]
Hello,

in the usage example in the documentation is one line which is for me confusing.
There is two times the same command `f, F = maximum_flow(flow_graph, 1, 8)`.
But after the first is `# Run default maximum_flow without the capacity_matrix`.
After the second it says `# Run default maximum_flow with the capacity_matrix`

I would say the first is wrong because you can't do the graph cut without capacity matrix.

[Link to Documentation](http://juliagraphs.github.io/LightGraphs.jl/latest/flowcut.html#LightGraphs.maximum_flow)

Cheers,

Felix
PS.: Sorry, I didn't know how to provide the file for you.

**Comment by sbromberger** [comment]
@roflmaostc - thanks for the heads-up. Both are correct, though the comments are misleading. The default capacity matrix is used when it is not specified. I hope #787 clears things up.
