### ISSUE TITLE
Justify all errors

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#789]
per https://github.com/JuliaGraphs/LightGraphs.jl/pull/788#pullrequestreview-79254916 - we should opt to return some sane value instead of erroring wherever possible.

This issue is to track going through the codebase and checking all `error` and `assert`s to make sure there isn't a way to return something that doesn't require a try/catch.

**Comment by jpfairbanks** [comment]
For more context the discussion was: 

> src/traversals/maxadjvisit.jl
>  ) where T<:Real
>  
>      U = eltype(g)
>      pq = DataStructures.PriorityQueue{U, T}(Base.Order.Reverse)
>      vertices_order = Vector{U}()
>      has_key = ones(Bool, nv(g))
>      sizehint!(vertices_order, nv(g))
>      -    @assert nv(g) >= 2
>      +    nv(g) >= 2 || error("nv(g) must be greater than 1")
>  @jpfairbanks
> This is good, because we are replacing an assertion error with a regular error, but I think in general returning an empty output for graphs with nv==1 is better than raising an exception. You might reasonably have a list of graphs of various sizes, and some could be nv==1. Everything should work without exceptions producing a sensible meaningless value such as empty array, or array with only one element rather than introducing a try catch block around every method call.
> 
> But for consistency with existing API, I think this is fine for now.
>       @sbromberger
> You're right. I'm going to change this now. I don't like errors.

**Comment by jpfairbanks** [comment]
@sbromberger, here are all the errors according to grep

```
src/SimpleGraphs/simpledigraph.jl:    ArgumentError("Adjacency / distance matrices must be square")
src/SimpleGraphs/simplegraph.jl:    ArgumentError("Adjacency / distance matrices must be square")
src/SimpleGraphs/simplegraph.jl:    AssertionError("invalid edgect in graph creation - please file bug report")
src/SimpleGraphs/simplegraph.jl:    ArgumentError("Adjacency / distance matrices must be symmetric")
src/centrality/pagerank.jl:    error("Pagerank did not converge after $n iterations.") # TODO 0.7: change to InexactError with appropriate msg.
src/centrality/pagerank.jl:the centrality calculated for each node in `g`, or an error if convergence
src/community/label_propagation.jl:    ArgumentError("Labels must between 1 and |V|") # TODO 0.7: change to DomainError?
src/community/label_propagation.jl:    ArgumentError("range indices are out of bounds") # TODO 0.7: change to DomainError?
src/connectivity.jl:    ArgumentError("Graph must be strongly connected")
src/connectivity.jl:Will throw an error if the graph is not strongly connected.
src/degeneracy.jl:    ArgumentError("graph must not have self-loops")
src/generators/euclideangraphs.jl:    ArgumentError("$bc is not a valid boundary condition")
src/generators/euclideangraphs.jl:    ArgumentError("Some points are outside the box of size $L") # TODO 0.7: change to DomainError with text.
src/generators/randgraphs.jl:                error("Mean degree cannot be greater than available neighbors in the block.") # TODO 0.7: turn into some other error?
src/generators/randgraphs.jl:        (fitness_out[i] < zero(T) || fitness_in[i] < zero(S)) && error("fitness scores must be non-negative") # TODO 0.7: change to DomainError?
src/generators/randgraphs.jl:    ArgumentError("fitness scores must be non-negative")
src/generators/randgraphs.jl:    ArgumentError("degree sequence must be graphical")
src/generators/randgraphs.jl:    ArgumentError("Barabási-Albert model requires 1 <= k <= nv(g) <= n")
src/generators/randgraphs.jl:    ArgumentError("the 0 <= k < n inequality must be satisfied")
src/generators/randgraphs.jl:    ArgumentError("the 0 <= k[i] < n inequality must be satisfied")
src/generators/randgraphs.jl:    ArgumentError("sum(k) must be even")
src/generators/randgraphs.jl:    ArgumentError("n * k must be even")
src/generators/randgraphs.jl:    ArgumentError("fitness_in must have the same size as fitness_out")
src/generators/randgraphs.jl:    ArgumentError("number of edges must be positive")
src/generators/randgraphs.jl:    ArgumentError("too many edges requested ($m > $max_no_of_edges)")
src/generators/randgraphs.jl:    ArgumentError("a degree sequence of length n must be provided")
src/generators/randgraphs.jl:    ArgumentError("number of vertices must be positive")
src/generators/randgraphs.jl:    ArgumentError("Inconsistent input dimensions: internalp, sizes")
src/generators/randgraphs.jl:    ArgumentError("matrix-vector size mismatch")
src/generators/randgraphs.jl:    ArgumentError("out-degree exponent must be >= 2")
src/generators/randgraphs.jl:    ArgumentError("out-degree exponent must be >= 2")
src/generators/randgraphs.jl:    ArgumentError("out-degree exponent must be >= 2")
src/generators/smallgraphs.jl:    ArgumentError("$s is not a valid graph")
src/interface.jl:# TODO 0.7: reevaluate use of errors here.
src/interface.jl:_NI(m) = error("Not implemented: $m")
src/linalg/graphmatrices.jl:    ArgumentError("$which is not a supported method of symmetrizing a matrix")
src/linalg/nonbacktracking.jl:    length(x) == nbt.m || error("dimension mismatch")
src/linalg/spectral.jl:        error("Not implemented")
src/linalg/spectral.jl:    ArgumentError("Spectral distance not defined for |G₁| != |G₂|")
src/operators.jl:    ArgumentError("Vertices in subgraph list must be unique")
src/operators.jl:    ArgumentError("Vector size must equal number of vertices")
src/operators.jl:    ArgumentError("dimension must be <= 2")
src/operators.jl:    ArgumentError("invalid vertex ID: $v0 in list of vertices to be merged")
src/operators.jl:    ArgumentError("vertex $vm not found in graph") # TODO 0.7: change to DomainError?
src/operators.jl:Preserves the eltype of the input graph. Will error if the
src/operators.jl:Preserves the eltype of the input graph. Will error if the number of vertices
src/persistence/lg.jl:    ArgumentError("graph $gname not found")
src/shortestpaths/bellman-ford.jl:        isa(e, NegativeCycleError) && return true
src/shortestpaths/bellman-ford.jl:    NegativeCycleError()
src/shortestpaths/bellman-ford.jl:struct NegativeCycleError <: Exception end
src/traversals/dfs.jl:                    error("The input graph contains at least one loop.") # TODO 0.7 should we use a different error?
src/traversals/randomwalks.jl:    BoundsError()
src/utils.jl:    ArgumentError("vector must be at least size $minsize")
```

**Comment by jpfairbanks** [comment]
@sbromberger do you want to make a table of all functions that throw exceptions and what those exceptions are? I would find that handy when programing so that I don't get an unhandled exception when I run my program. Of course we would have to automate generation of that table to keep it synchronized.

**Comment by sbromberger** [comment]
Yes, but I want to do this after 0.7 comes out since we will have more flexibility in what type of exceptions we through (currently, for example, `InexactError` can't take any message or arguments, but it would be great for the non-converging pagerank exception).

**Comment by jpfairbanks** [comment]
From the Julia Docs 


"""
    InexactError(name::Symbol, T, val)
Cannot exactly convert `val` to type `T` in a method of function `name`.
# Examples
```jldoctest
julia> convert(Float64, 1+2im)
ERROR: InexactError: convert(Float64, 1 + 2im)
Stacktrace:
 [1] convert(::Type{Float64}, ::Complex{Int64}) at ./complex.jl:37
```
"""
InexactError

So I don't think that InExactError is appropriate for Failure to converge. I would rather make a `ConvergenceError` type to raise which is more precise.

**Comment by mschauer** [comment]
I still think that you should reconsider your idea that raising an error is something that should not happen and if it can happen, that it should be in a `try`-`catch` block. My quite different view is that often raising an error is the sensible thing to do, especially if the alternative is to ignore the inputs of a function. This difference was is possibly also the reason why https://github.com/JuliaGraphs/LightGraphs.jl/pull/755 did not go anywhere. I guess we should not even discuss this further, I only want to log my position here for my own inner peace. Cheers.

**Comment by mbesancon** [comment]
This still seems like pretty important. Could we consider using something like https://github.com/iamed2/ResultTypes.jl ?

**Comment by jpfairbanks** [comment]
I think ResultTypes is a great idea.

mbesancon writes:

**Comment by sbromberger** [comment]
I'm not 100% convinced that this is the right approach. I know Go does it, but it's still a bit of a mixed bag in my mind. I don't want users to have to check results for error all over the place, and if we do it in some places but not in others, by what rule do we decide what gets a `Result`?

**Comment by jpfairbanks** [comment]
@iamed2 Could have some some good insights based on experience. I think we have two audiences to design for, the scripting user who doesn't want to check errors or write try/catch, and people writing applications that need to correctly handle errors.

Are exceptions better for the scripting users? I guess programs crashing is better than silently getting wrong answers. But could we get a better UX with ReturnTypes?

**Comment by iamed2** [comment]
Using ResultTypes in a public API is only a good idea if the caller is expecting to do error handling. I think that's often not true with Julia users (i.e., if errors occur they're usually due to a bug in the program that can be fixed).

**Comment by sbromberger** [comment]
Keeping this open as a placeholder to discuss issue in https://github.com/JuliaGraphs/LightGraphs.jl/pull/962#discussion_r206963708
