### ISSUE TITLE
Proposed API changes

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#800]
I'd like to propose the following API changes:

1) remove all functions that are preceded by `in` and `out` in favor of either a positional argument with a symbol (`:in` or `:out`), or a kwarg (`; dir=:in`) with appropriate defaults (that is, for `neighbors`, we'd default to `:out`).

2) ~~get rid of `has_vertex` and `has_edge` in favor of `in` with multiple dispatch. This basically abstracts a graph into two sets (one of vertices and one of edges). `has_vertex(g, v)` is already defined as `v in vertices(g)`, so this is not a huge deal:~~
```
in(v::Int, g) = v in vertices(g)
in(e::AbstractEdge, g) = e in edges(g) # has_edge(g, e)
in(u::Int, v::Int, g) = in(Edge(u,v), g)
...
```

~~This allows us to do things like `4 ∈ g` (`has_vertex(g, 4)`).~~

Thoughts?

**Comment by sbromberger** [comment]
On second thought, I really don't like 2). It seems needlessly complex.

**Comment by jpfairbanks** [comment]
I liked 2. but it is kind of punny.

**Comment by mschauer** [comment]
Hehe, are we running in circles? #748

**Comment by sbromberger** [comment]
> Hehe, are we running in circles?

Indeed. I knew we had discussed this before, and I came to the same conclusion again, so at least I'm consistent in my opposition. :)

**Comment by sbromberger** [comment]
Closing this because there's no good way to do this without a hit to performance, however minor.
