### ISSUE TITLE
Massive memory spikes in diffusion

### ISSUE THREAD

**Issue by nickeubank** [JuliaGraphs/LightGraphs.jl#802]
I've been getting some rare but huge memory spikes in `diffusion_run`, but can't figure out why. 

One possibility that occurs to me is that `new_infections` is a `Set`, which I assume is not super efficient when it gets too many items in it, which may occur late in a diffusion process (if the diffusion spreads a lot in a huge graph, then in each step there may be a huge number of "new" infections since we don't check whether infections are new before adding to set for speed). 

Was thinking of converting `new_infections` to an `IntSet`. Seem reasonable?

**Comment by sbromberger** [comment]
Is the set likely to be dense? If so, `IntSet` will provide advantages. If not, then it will be suboptimal.

**Comment by nickeubank** [comment]
I think the tension is that it's sparse in early stages (only a few vertices infected), but dense in later stages (most vertices infected). I suppose I could flip it based on how far diffusion has run, but I think that introduces a type instability. 

The problem is I'm bringing down research-cluster scale computers when memory use is getting up around 30 / 50 GB, and I was wondering whether a sparse set with 5_000_000 entries might be the problem...

**Comment by jpfairbanks** [comment]
One way to avoid the "bringing down the cluster" part in the future is to set a ulimit in your submission script. https://www.osc.edu/book/export/html/3851 the -m flag sets a limit on memory. I do this when I run big julia or matlab because invariably I accidentally convert a sparse matrix to a dense one and it crashes the machine. ulimit ensures that you only crash the program instead of the whole machine.

**Comment by nickeubank** [comment]
Thanks @jpfairbanks . I'm increasingly convinced this is actually a bug in the `slurm` task manager -- I think it's letting zombie processes live, which are sucking up memory, leading to memory crashes that LOOK like they're caused by a memory spike... I've been tracking the heck out of memory allocations in my code (thanks @sbromberger ) and just can't explain that kind of memory spike... And I've found hte zombie processes...

**Comment by jpfairbanks** [comment]
Bugs in Slurm sounds 😱

**Comment by nickeubank** [comment]
https://discourse.julialang.org/t/warning-about-multi-node-parallelism-on-slurm/7882
