### ISSUE TITLE
Min cost flow

### ISSUE THREAD

**Issue by mbesancon** [JuliaGraphs/LightGraphs.jl#807]
One commonly used flow algorithm is to find a feasible flow or with a minimum value from source to sink, which minimizes a total cost, given that each edge has a linear cost function with the flow through it cost(e) = flow(e) * c_e

Some variations can be found can be found in NetworkX:  
* [min_cost_flow_cost](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.algorithms.flow.min_cost_flow_cost.html#networkx.algorithms.flow.min_cost_flow_cost)
* [min_cost_flow](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.algorithms.flow.min_cost_flow.html#networkx.algorithms.flow.min_cost_flow)
* [max_flow_min_cost](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.algorithms.flow.max_flow_min_cost.html)

**Comment by juliohm** [comment]
Hi @mbesancon, thank you for sharing the links. Did you have the chance to look into the flow algorithms implemented in LG already? Any of them satisfies your constraints?

https://github.com/JuliaGraphs/LightGraphs.jl/tree/master/src/flow

In particular, it seems that the last link you shared (i.e. max_flow_min_cost) is already in LG? There are so many nuances on these algorithm descriptions that I am not quite sure if they are equivalent. Please let us know what is missing. Pull requests are very welcome. :)

**Comment by mbesancon** [comment]
What I found in LG is maxflow min cut (two versions of one problem). Min cost implies adding meta-information (edge costs), similar to the matching algorithms. I don't think that's what the different algorithms of LG are solving

**Comment by mbesancon** [comment]
So I have an implementation of a min-cost flow algorithm. Before creating a PR for it I had several points:
* Just as the weighted matching algorithms, it solves a Linear Programming problem and requires a LP solver.
* As the guideline was to split parts of the package which require heavy dependencies (I guess JuMP is one of them), should it be put in a separate package? 
* If yes, should a LightGraphsFlows.jl package be created?
* As the dependencies are similar (and some algorithms could be re-used), a possibility would be to merge the flow algorithms with the matching algorithms. For example, a bi-partite matching could use a simple flow model (same thing for the weighted bi-partite matching)
Waiting for your feedback before moving on

**Comment by sbromberger** [comment]
> As the guideline was to split parts of the package which require heavy dependencies (I guess JuMP is one of them), should it be put in a separate package?

Yes, that's the preferred approach.

> As the dependencies are similar (and some algorithms could be re-used), a possibility would be to merge the flow algorithms with the matching algorithms. For example, a bi-partite matching could use a simple flow model (same thing for the weighted bi-partite matching)

This makes a lot of sense. Is there some package name that encompasses both flows and matching?

Also: does it make sense to migrate the flow algorithms we have in LightGraphs now to this new package?

**Comment by mbesancon** [comment]
No idea for a name that would explicitly mention the two sides. Since they both use JuMP, LightGraphsLP / LightGraphsOptim? Which would regroup all graphs problems requiring mathematical programming solvers.

If it seems confusing, we can still keep them in two different packages, one for matching, one for flows.

> Also: does it make sense to migrate the flow algorithms we have in LightGraphs now to this new package?
Good question. If we keep matching and flows separated, I guess it makes sense to regroup all flow algorithms from the ecosystem user's point of view (one package represents variations of some families of algorithms).  

If we regroup matching and flow, one danger would be to simply re-created a too big LightGraphsExtras.jl

**Comment by sbromberger** [comment]
> Which would regroup all graphs problems requiring mathematical programming solvers.

I don't like this because they're not related other than on a common dependent package. That's not intuitive to me.

> If we regroup matching and flow, one danger would be to simply re-created a too big LightGraphsExtras.jl

That's my fear as well.

Are the LP-solver flows fundamentally different from the flows we have in LG right now? If they answer the same questions, then perhaps we move the current LG-based flows into a `LightGraphsFlows` package, even if they don't require JuMP.

**Comment by mbesancon** [comment]
> Are the LP-solver flows fundamentally different from the flows we have in LG right now? 
Well the LP-solver is mostly the reformulation of a flow problem as a LP. The maxflow algorithms as implemented in LightGraphs answer close questions (find maxflow, find feasible flow), since this could be considered as "find the best flow" and also solves a LP problem in a different manner.

> If they answer the same questions, then perhaps we move the current LG-based flows into a LightGraphsFlows package, even if they don't require JuMP.

I guess this would result in the simplest package organization within the ecosystem. If that's validated, I can create the LightGraphsFlows.jl package with the existing flow algorithms, and then PR it with the mincost flow

**Comment by jpfairbanks** [comment]
Does it make sense to organize things like DiffEq where there is a Base package that defines all the types and interfaces and then each solver lives in its own package, with another package which gives you the whole ecosystem?

**Comment by mbesancon** [comment]
you mean for the flow algorithms or the whole JuliaGraphs ecosystem? In our case it would be more a package to define the key types and interfaces, and then different packages for different families of algorithms

**Comment by mbesancon** [comment]
As discussed, I split the flow algorithms in https://github.com/JuliaGraphs/LightGraphs.jl, I'll add the mincost algorithm once this one is stabilized.

**Comment by juliohm** [comment]
I like the idea @jpfairbanks , something like a core package with types and interfaces and multiple topic packages with algorithms. This re-organization would make LightGraphs.jl the lightest of all lights. :) What is your opinion @sbromberger?

**Comment by sbromberger** [comment]
I'm ambivalent, actually. On the one hand, I love organization. :) On the other, I don't want to get into the practice of creating "micropackages". I think so far we've struck a healthy balance (LightGraphsExtras notwithstanding, but we knew that was temporary). As long as we don't have the equivalent of npm's left-pad [1] [2] [3], I'll be reasonably happy.

[1] https://www.npmjs.com/package/left-pad
[2] https://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/
[3] https://arstechnica.com/information-technology/2016/03/rage-quit-coder-unpublished-17-lines-of-javascript-and-broke-the-internet/

**Comment by sbromberger** [comment]
and @juliohm - It is my expectation that pretty soon, LightGraphs will be "Light" in practice only (that is, we may be renamed in the not-to-far-off future).

**Comment by mbesancon** [comment]
I also see the risk of micro-packaging, it is more likely to yield less overwatched and less maintained packages. But as the whole Julia ecosystem is still in rapid evolution while people will begin to expect stability in some of the core features of some environments. That's why splitting families of algorithms with heavy dependencies (as JuMP for matching and flows) seems like a stability (and lightness) bonus for the core LightGraphs

**Comment by juliohm** [comment]
Fully agree with all remarks :+1: Also curious to learn about the new name :)

**Comment by sbromberger** [comment]
Let's give it a try and see how it looks. Sound ok?

**Comment by mbesancon** [comment]
If everyone is ok, we can move on to release https://github.com/JuliaGraphs/LightGraphsFlows.jl, I'll PR the mincost feature after the first release I suppose

**Comment by sbromberger** [comment]
Yes, I'm ok with this. What I'd dearly like to see is a PR that removes the duplicate functionality from LightGraphs.jl once the package has been accepted into METADATA.

**Comment by mbesancon** [comment]
As discussed, PR submitted to remove duplicate from LightGraphs.jl

**Comment by sbromberger** [comment]
Ref #815
