### ISSUE TITLE
simplecycles() does not detect self loops

### ISSUE THREAD

**Issue by myuuuuun** [JuliaGraphs/LightGraphs.jl#816]
Hi. I'm using `simplecycles()` for DiGraphs. I found it does not detect self loops when all cycles are self loops, while it does detect self loops when there exist more than 1 length cycles in a graph. Is this done intentionally? (julia: v0.6.2)

Example:

```jl
m = zeros(Int, (5, 5))
m[1, 1] = 1
m[2, 2] = 1
m[1, 2] = 1
g = DiGraph(m)
simplecycles(g)
```

returns `0-element Array{Array{Int64,1},1}`

while

```jl
m = zeros(Int, (5, 5))
m[1, 1] = 1
m[2, 2] = 1
m[1, 2] = 1
m[2, 3] = 1
m[3, 1] = 1
g = DiGraph(m)
simplecycles(g)
```

returns 
```
3-element Array{Array{Int64,1},1}:
 [1]      
 [1, 2, 3]
 [2]      
```

**Comment by sbromberger** [comment]
Our self-loop capability is really only supported superficially and aren't guaranteed to work with all functions (sorry about that; the history is that they were added for a specific use case and they haven't undergone all function testing yet.)

So it's probably a bug. If you'd like to help, we'd be happy to accept a PR to make the function work with self-loops, or even a PR to update the documentation to specify that it doesn't work w/ self loops.
