### ISSUE TITLE
Chung-Lu, geometric random graph models

### ISSUE THREAD

**Issue by adamglos92** [JuliaGraphs/LightGraphs.jl#829]
Is there a chance, that Chung-Lu random graph model and geometric random graph model will be implemented in the module?

**Comment by sbromberger** [comment]
Not unless someone implements it.

For reference: https://arxiv.org/pdf/1406.1215.pdf page 2 appears to have an implementable (serial) algorithm for Chung-Lu. If you want to give it a try, we'd be happy to review a PR.

**Comment by sbromberger** [comment]
Also: I noticed you had https://github.com/adamglos92/GlosRandomGraphs.jl - do these work? We could look at incorporating them directly into LightGraphs if you're interested.

**Comment by adamglos92** [comment]
It is. I can make a PR when I have more time to check its correctness and efficiency. Still geometric graphs are very slow, as I naively check all pairs of vertices independently. Still the generator is at least general.
In my module I used the algorithm @sbromberger found.

**Comment by sbromberger** [comment]
We can help find optimizations during PR review.

**Comment by adamglos92** [comment]
Ok, so I will try to find some spare time this or next week

**Comment by sbromberger** [comment]
Sounds great! Thanks.

Feel free to file the PR whenever you're ready. I'll close this out in anticipation.
