### ISSUE TITLE
Possible excess pre-allocation of memory

### ISSUE THREAD

**Issue by SohamTamba** [JuliaGraphs/LightGraphs.jl#838]
https://github.com/JuliaGraphs/LightGraphs.jl/blob/9f6ce46dba133cde8330caeb90d4170d77cce268/src/spanningtrees/prim.jl#L25

Any connected tree contains | V | - 1  vertices, but this line of code pre-allocates a vector of length | E | to the mst vector. While it won't affect correctness or significantly slow speed, it seems to be unnecessary overhead to me.

**Comment by sbromberger** [comment]
This seems ripe for optimization. Mind filing a PR?

**Comment by SohamTamba** [comment]
Sure, I'll get on it right away.
