### ISSUE TITLE
Parallel implementation of the Bellman Ford algorithm

### ISSUE THREAD

**Issue by SohamTamba** [JuliaGraphs/LightGraphs.jl#840]
Presently there is no parallel implementation of the Bellman Ford algorithm. I'd like to work on this and try to find my way around parallelization in Julia.

To compare the runtimes, the serial algorithm takes **O(T * E)** while the parallel implementation will have a runtime of **O(T * log(V))**  if sufficient processors **(|E|)** are available or a runtime of **O(T * max_degree)** if sufficient processors **(|V|)** are available.

Here T is the number of iterations of edge relaxations. T <= V

I've started working on a pull request and I have a few doubts :-
I noticed that for multisource Dijkstra, _SharedMatrix_ is used to copy the results of each processor individually running Dijkstra. In the Julia manual, it suggests using _pmap_ when you need to copy the results of a processor and no other memory write operation is used. What would be the best practice in this case?
Is it advisable to use Inf or typemax to mark a node as not visited or should I use a bit array?

**Comment by sbromberger** [comment]
> What would be the best practice in this case?

Up to you. I've found that `@parallel` is more intuitive to use and faster, in many cases, than `pmap` unless you tweak `WorkerPool` settings which then gets it almost (but not quite) as fast. If you use `@parallel` then you're pretty much stuck with `SharedMatrix`.

> Is it advisable to use Inf or typemax to mark a node as not visited or should I use a bit array?
Use either a bitarray or a `Vector{Bool}`. The former will give you better memory / cache utilization; the latter will be faster in most cases at the cost of 8:1 overhead.

**Comment by mbesancon** [comment]
maybe transfer this issue to https://github.com/JuliaGraphs/LightGraphsFlows.jl ?
