### ISSUE TITLE
Optimizing Kruskal's MST

### ISSUE THREAD

**Issue by SohamTamba** [JuliaGraphs/LightGraphs.jl#841]
The current implementation takes **O(E*V+E*logE)** time.

I suggest the following changes:-

- Optimize Union Find to reduce time per operation from **O(V)** to **O(1)** amortized.
- Replace the Min Heap with a sorted array to improve speed and memory.
- Reduce the memory used by mst vector from **E** to **V-1**

This will improve the runtime complexity to **O(E*logE)** and reduce memory by a good factor

**Comment by sbromberger** [comment]
PR with before/after benchmarks (using BenchmarkTools) would be appreciated.

**Comment by SohamTamba** [comment]
@sbromberger  : While benchmarking the code I found that sort does improve performance but blows up memory usage as input size increases. I ended up benchmarking three different algorithms for 3 different graph sizes :-

1 : Trivial Disjoint Set and Heap (Original)
2 : Optimised Disjoint Set and Sort (Intended optimization)
3 : Optimised Disjoint Set and Heap (Best Performance)

|V| = 1,000, |E| = 5,000

|Algorithm|      Runtime           | Allocations  |  Memory |
| ------------- |:-------------:| ---------| ------|
| 1     | 2.793 ms |  23237| 885.61 KiB |
| 2     |   5.811 ms| 144210 | 2.70 MiB | 
| 3          |    1.891 ms|23784 | 863.06 KiB |


|V| = 10,000, |E| = 50,000

|Algorithm|      Runtime           | Allocations  |  Memory |
| ------------- |:-------------:| ---------| ------|
| 1     | 143.058 ms |  293814| 9.59 MiB |
| 2     |   89.008 ms| 1928065 | 34.23 MiB | 
| 3          |    26.486 ms|304363 | 9.45 MiB |



|V| = 100,000, |E| = 500,000

|Algorithm|      Runtime           | Allocations  |  Memory |
| ------------- |:-------------:| ---------| ------|
| 1     | 8.528 s |  2991445| 92.95 MiB |
| 2     |   1.409 s| 23908784 | 409.07 MiB | 
| 3          |    598.489 ms |3090846| 91.41 MiB |

It appears that heap is outperforming sort (Quick Sort) which is quite surprising because repeatedly popping a heap (without insertions in between) is equivalent to call Heap Sort.

Some speed up is possible in the case where the MST is formed before the entire heap is popped but the improvement in memory and speed by using heap instead of sort seems unwarranted in my opinion.

It is possible that sorting in Julia has not been [optimized](https://github.com/JuliaLang/julia/issues/939) yet .

How should I proceed from here?

**Comment by sbromberger** [comment]
@SohamTamba this is great info. I'd recommend creating a PR for option 3 (Optimised Disjoint Set and Heap) and then cutting and pasting raw @benchmark results into a comment in the PR for others to look at. If the numbers hold up and correctness is not impacted this is a no-brainer.
