### ISSUE TITLE
Finding all paths?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaGraphs/LightGraphs.jl#845]
I have a directed graph with no circuits, and I want a list/enumeration of all paths between two nodes. Is this functionality implemented?

**Comment by sbromberger** [comment]
I don't believe we have anything like this.

**Comment by jpfairbanks** [comment]
I would check in the Floyd Warshall code you could probably modify that to calculate the paths in addition to the distances.

**Comment by SohamTamba** [comment]
A graph with no circuits has no cycles.
You can enumerate the paths of a DAG by modifying DFS.

**Comment by sbromberger** [comment]
Closing this out since there doesn't seem to be any additional discussion happening.
