### ISSUE TITLE
Adding Johnson's all pairs shortest path

### ISSUE THREAD

**Issue by SohamTamba** [JuliaGraphs/LightGraphs.jl#849]
I'm almost done writing Johnson's all pairs shortest path algorithm.

Instead of creating JohnsonState struct which will be the same as FloydWarshallState struct and defining another enumerate function, how about creating a AllPairsShortestPathState struct that both of them use?

**Comment by sbromberger** [comment]
I don't know how I feel about this. On the one hand, it's a nice abstraction. On the other, all the other  `<:AbstractPathState`s are algorithm-based. For consistency, we should prefer the latter, but there's something to be said for merging.

@jpfairbanks, @juliohm, @somil55  - thoughts?

**Comment by sbromberger** [comment]
cc also @mbesancon

**Comment by sbromberger** [comment]
@SohamTamba - If it's ok with you, could you hold off on submitting this against 0.6? We are close to feature-freezing and tagging a last version compatible with Julia 0.6, and we're trying to move everything over to 0.7. Sorry for the inconvenience.

**Comment by SohamTamba** [comment]
@sbromberger 
That's fine with me :)

**Comment by mbesancon** [comment]
still coming to 0.7?

**Comment by SohamTamba** [comment]
@mbesancon 
Yes it is in my GSoC proposal :)
