### ISSUE TITLE
GSOC: 2018

### ISSUE THREAD

**Issue by SohamTamba** [JuliaGraphs/LightGraphs.jl#864]
Hi, I am interested in applying for GSoC 2018 at LightGraphs. I've submitted a few PRs (#844 #843 #839) and I'm waiting for migration to 0.7 to complete to submit a few more patches that I've completed.

I'm still trying to draft a concrete project proposal and was wondering if there is any project or direction of interest to the library. My interests would have me pursue a project in optimization with a bit of algorithmic analysis.

Cheers,
Soham

**Comment by severinson** [comment]
Hey everyone,

I'm a PhD student in coding theory for distributed computing in Norway. I'm interested in contributing to LightGraphs within GSOC2018. I'm generally interested in the intersection between algorithms and their implementation. Hopefully I can offer something of value. I'd be happy to discuss it with someone on your side. Is that possible?

Regardless, I appreciate the work you do on this project.
Cheers,
Albin Severinson

**Comment by jpfairbanks** [comment]
Hi @severinson what aspects would you be interested in? Distributed graph algorithms? How does coding theory relate?

**Comment by severinson** [comment]
Thanks for the reply @jpfairbanks. I've looked into it further. It's not possible for me to participate as I have other projects for most of the period May 14, 2018 - August 6, 2018. I wish you the best of luck with GSOC 2018 and with the LightGraphs project in general.
Cheers,

**Comment by SohamTamba** [comment]
Hey @severinson , if you can't participate as a student, maybe you could apply as a Mentor for LightGraphs if you have some time to spare this summer. (I am unaware of anyone volunteering to be a potential mentor)

Distributed graph algorithms are a major part of my proposal but I was a bit unsure about how to go about implementing it in LightGraphs. I'd really appreciate it if you could review my first attempt at a distributed Floyd Warshall code linked in #866 since you have experience in the field.

**Comment by severinson** [comment]
I appreciate the confidence you have in me @SohamTamba. I'll have a look if I can. However, I don't think I'm experienced enough with Julia or LightGraphs to mentor someone else.

**Comment by SohamTamba** [comment]
Closing this as the GSoC application deadline has passed.
