### ISSUE TITLE
Review for Distributed Floyd Warshall

### ISSUE THREAD

**Issue by SohamTamba** [JuliaGraphs/LightGraphs.jl#866]
I have been working on implementing distributed Floyd Warshall.
Since this is my first time implementing a distributed program, can someone offer some tips and reviews?

The code can be found [here](https://github.com/SohamTamba/LightGraphs.jl/blob/distributed_fw/src/shortestpaths/distributed_floyd-warshall.jl).

**Comment by sbromberger** [comment]
Couple of notes:

Are you sure you need those `@eval @everywhere` statements? Generally, `addprocs` happens before `using LightGraphs` so all LG functions are available on all processors.

What do the benchmarks look like?

**Comment by SohamTamba** [comment]
It would give error saying not defined in process if I didn't type it.

My laptop's hard disk has crashed and I'm in the process of recovering from it so I won't be able to give the bench-marks for some time.

**Comment by SohamTamba** [comment]
Benchmarks performed on Complete Graph

|V| = 10,000

|Algorithm|      Runtime           | Allocations  |  Memory |
| ------------- |:-------------:| ---------| ------|
| Sequential     | 13.770372 s |  20.98 k| 16.390 MiB |
| Distributed    |   9.999702 s| 9.57 M | 382.839 MiB | 

|V| = 20,000

|Algorithm|      Runtime           | Allocations  |  Memory |
| ------------- |:-------------:| ---------| ------|
| Sequential     | 159.334386 s |  20.98 k| 62.166 MiB |
| Distributed    |  26.642749 s| 43.69 M | 1.323 GiB | 

I'll try to reduce the memory operations.
Perhaps by avoiding using a distributed array of structs.

But the speed-ups are pretty good.

**Comment by SohamTamba** [comment]
I was able to obtain the following improvements for the distributed version:
|V| = 2,000
 18.267219 seconds (2.81 M allocations: 742.814 MiB, 1.93% gc time)

**Comment by SohamTamba** [comment]
Cache efficient floyd_warshall_shortest_paths had comparable results.
Closing for now.
