### ISSUE TITLE
Replace "using" with "import"

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#872]
per discussion in https://discourse.julialang.org/t/function-name-conflict/10335, it appears that there's a preference for limited `import` of functions as opposed to blanket `using` bringing all function names into the namespace. Here's a good intro issue: determine which functions from each package are required, and `import` them.

**Comment by IssamT** [comment]
I would even vote for importing packages only. We can declare a short alias for them to use when calling a function like:

```julia
import SharedArrays
import ...

const SA = SharedArrays
const ...

meandists = SA.SharedVector{Float64}(Int(n_v))
```

**Comment by sbromberger** [comment]
@IssamT I'm not in favor of using aliases - I think there's big potential for confusion there. But if we want to just import packages, that might make sense.

One question that we should resolve: would we do this (either `import Foo: bar` or just `import Foo`) across the board, or just for non-standard-library packages?

**Comment by IssamT** [comment]
I've suggested aliases only as a side solution if you think that importing packages only would make the code too verbose.

@sbromberger, what do you mean by "non-standard-library packages" ?

**Comment by sbromberger** [comment]
> @sbromberger, what do you mean by "non-standard-library packages" ?

I think there's a difference between `Random` and `CodecZlib`, in that the former is bundled with Julia and is part of the standard library. Currently, we're doing the following:

```
using SharedArrays
using Random
import CodecZlib
using Base64
using DataStructures
using SimpleTraits

using SparseArrays
using LinearAlgebra
using IterativeEigensolvers
using SharedArrays
using Random
using Markdown
using DelimitedFiles
import Base: write, ==, <, *, ≈, convert, isless, issubset, union, intersect,
            reverse, reverse!, isassigned, getindex, setindex!, show,
            print, copy, in, sum, size, eltype, length, ndims, transpose,
            ctranspose, join, start, next, done, eltype, get, Pair, Tuple, zero
import Random: GLOBAL_RNG
import Distributed: @distributed, @sync
import SparseArrays: sparse, blockdiag
import LinearAlgebra: issymmetric, mul!
```

There's some duplication there that could be cleaned up, but on the whole, I don't know whether we should be treating packages that are part of the Julia standard library differently from packages that are not, and would like to discuss.

**Comment by IssamT** [comment]
`Base` has an implicit `using`. So importing a function from `Base` is only needed for method extension. In this case I think `import Base: bar` is fine. For all the other cases, I personally prefer `import Foo`. But since I am more of a user of LightGraphs than an active contributor, my opinion shouldn't matter much.

**Comment by sbromberger** [comment]
> `Base` has an implicit `using`.

Yes, but note that things that used to be in Base have now been moved out into the standard library, where you have to import or use them. (Random, SparseArrays, LinearAlgebra, IterativeEigensolvers, SharedArrays, Markdown, DelimitedFiles). The question is this: do we treat these standard library components differently (by allowing `using` on them) or do we require that their functions be explicitly imported, as we would for third-party packages?

**Comment by IssamT** [comment]
I would say yes; or at least the import of functions.

**Comment by sbromberger** [comment]
cc @jpfairbanks @somil55 @SohamTamba for more input.

**Comment by sbromberger** [comment]
also cc @stefankarpinski since this was his idea in the first place :)

**Comment by sbromberger** [comment]
Looks like the options are as follows:

1) `using` for everything except for overrides ("what we've been doing")
2) `import Package` and use `Package.pkg_func(...)` in the code ("package import")
3) `import Package: pkg_func` and use `func(...)` in the code ("function import")

**Comment by StefanKarpinski** [comment]
I would say give it a try and see how annoying it is in practice. If it's too annoying, please report the experience on Discourse, Slack or as a GitHub issue on JuliaLang/julia.

**Comment by StefanKarpinski** [comment]
Actually, please report either way—if it's good or bad.

**Comment by sbromberger** [comment]
Just to clarify, Stefan indicated to me that his slight preference is for option 3 ("function import").

**Comment by StefanKarpinski** [comment]
Also, try it out at a small scale and see how it feels.

**Comment by iamed2** [comment]
I like to do overrides with:
```julia
function Package.pkg_func(x::MyType)
    # ...
end
```
That way you're declaring that you're overriding a function from another package. 

As our application becomes larger we've been doing more 2) than 3). I'd like to avoid 1) in our production code but that's hard when you're doing rapid development. Overall I think that 2) is best for large packages like LightGraphs with few dependencies.

**Comment by jpfairbanks** [comment]
I guess for LG we are the library so we should take the more verbose but maintainable approach, which is option 2. I think I would not do that in my scripting codes where I would prefer 3. which has the benefit of being unambiguous but compact.

As for treating Stdlib packages like Random as special. I don't think we should. If option 2 is too burdensome  to extend to Stdlib packages, then it is too burdensome for non-Stdlib packages too.  We don't want to create a second class status for those third party packages

**Comment by sbromberger** [comment]
As usual, I find myself in agreement with @jpfairbanks. Let's give option 2 ("package import") a try for this. Any takers? :)

**Comment by SohamTamba** [comment]
My preferences are indifferent to 2 and 3.

Actually I liked the idea of using option 1 for stdlib and option 2 or 3 for others.
You usually won't have to worry about conflicts from stdlib and we use those more often than others.

If you can reduce the code size by some factor, why not do it?

**Comment by sbromberger** [comment]
Reopening this: it has since been recommended that `using Foo: bar` is preferable to `import Foo: bar` when `bar` is not being extended. This should be a straightforward fix.

**Comment by sbromberger** [comment]
Ref: #898. Review and comment there, please.

**Comment by sbromberger** [comment]
Closing now that #898 has been merged.
