### ISSUE TITLE
Transitive reduction

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGraphs/LightGraphs.jl#874]
Recently I had to write a function that calculates the _transitive reduction_ [1] of a graph.
Now I would like to enhance this method a bit and then add it to LightGraphs. Therefore I would like to know if it is a good idea to add this function to LightGraphs.

There are also two issues where I would like to have some input:
1) Calculating the transitive closure of a graph is rather straightforward when relying on the function `transitiveclosure` . On the other hand, this would need a quadratic amount of space when the initial graph is sparse. Calculating the transitive closure is not necessary though, as the transitive reduction can also be calculated by a BFS. This might be slightly slower but should still be in the order of  O(V^3), same as the transitive closure. On the other hand, calculating the transitive closure in Julia is already quit slow at the moment so avoiding calculating it might actually result in a faster calculation.

2) The transitive reduction is well defined for acyclic graphs, but it is not so well defined if the graph contains cycles. In particular, the transitive closure of a cyclic graph might not be a subgraph of the initial graph. A simple way to calculate the transitive reduction is to simply replace every strongly connected component [2] of the graph with a directed cycle. The resulting graph will not be a subgraph of the initial graph, but it will certainly be sparse.
A related concept to the transitive reduction is the so called _minimum equivalent graph_ [3]. As with the transitive reduction, the minimum equivalent graph has the same transitive closure as the initial graph but has in addition the advantage that it is a subgraph of the initial graph. Calculating the minimum equivalent graph is NP-hard though  because we can reduce the Hamilton-cycle problem to it. 

My proposal is now to to write a function with the signature` transitivereduction(g::SimpleDiGraph)` that 

a) Works on cyclic graph.
b) Does not calculate the transitive closure as an intermediate step.
c) Does not guarantee that it is a s subgraph of the initial graph.

Then later we could add some keyword arguments to the signature, that specifies how to handle the two issues.

[1] https://en.wikipedia.org/wiki/Transitive_reduction
[2] https://en.wikipedia.org/wiki/Strongly_connected_component
[3] http://www.cs.ucr.edu/~neal/Khuller94Approximating.pdf

**Comment by sbromberger** [comment]
> Calculating the transitive closure is not necessary though, as the transitive reduction can also be calculated by a BFS.

Our BFS algorithm is pretty darn good these days (use the `gdistances` implementation as the reference).

I'd be interested in seeing this functionality. I think it's worthwhile. I would suggest a PR with good documentation and a `### Performance` section in the docstring. I would put this in `digraph/transitivity.jl`, and I would make the signature `@traitfn function transitivereduction(g::::IsDirected)`.

**Comment by sbromberger** [comment]
Closed by #877, I think (@simonschoelly - let me know if you need this reopened).
