### ISSUE TITLE
Get codecov to 100%

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#885]
https://codecov.io/gh/JuliaGraphs/LightGraphs.jl/tree/master/src

We're close, but there are a few lines that still need tests. Paging @somil55 :)

PS: these weren't as a result of you recent work, for the record.

<img width="1024" alt="screen shot 2018-05-19 at 07 59 20" src="https://user-images.githubusercontent.com/941359/40269998-af7c5d9c-5b3a-11e8-8390-d735e1e91828.png">

**Comment by somil55** [comment]
@sbromberger I will do that :)

**Comment by sbromberger** [comment]
Closing out since we have #888.
