### ISSUE TITLE
Tests for label_propagation sometimes fail

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGraphs/LightGraphs.jl#886]
The issue here is, that label_propagation is a randomized algorithm that does not produce the same output every time. 
To be more precisely, in the tests up to five complete graphs of size 10 are generated and connected by a single edge. The test assumes that the number of labels generated corresponds to the number of complete graphs, but it is possible that with small probability the labels are propagated from one clique to another one, which results in less labels.

One should be able to reproduce the problem by running the test 10000 times, then it will fail almost every time.

**Comment by sbromberger** [comment]
yup. We occasionally get test failures for all sorts of random functions (the random graph generators are another case). When this happens we just retest.
