### ISSUE TITLE
Can shortest path algs be used with custom visitors?

### ISSUE THREAD

**Issue by Shushman** [JuliaGraphs/LightGraphs.jl#887]
This is more of a question than an issue but I wasn't sure where to put it. Is ther e currently a framework for using the shortest path search algorithms in `LightGraphs` with custom visitors? I see `AbstractGraphVisitor` defined in `src/LightGraphs.jl` but I'm not sure where they are being used, if at all. Also, it seems that `dijkstra` and `astar` etc. don't have any scope currently for custom visitors - wanted to confirm this. Thanks!

**Comment by sbromberger** [comment]
We got rid of the custom visitor code a while back since it was horribly inefficient. You might have a look at altering `gdistances!()` which is our current reference model for anything BFS. (If that's too complex, then you can modify Dijkstra.)

**Comment by Shushman** [comment]
Thanks! Will do.
