### ISSUE TITLE
Broadcasting warning in v0.13.0+

### ISSUE THREAD

**Issue by slyles1001** [JuliaGraphs/LightGraphs.jl#892]
Many instances of broadcast warnings generated in test:

Warning: using `A[I...] = x` to implicitly broadcast `x` across many locations is deprecated. Use `A[I...] .= x` instead.

**Comment by sbromberger** [comment]
Primarily in `graphmatrices.jl`. Paging @jpfairbanks :)

**Comment by sbromberger** [comment]
Ooh, I take that back. It's all over the place.

**Comment by slyles1001** [comment]
There are errors in Randgraphs, but I think they're in StatsBase -- it won't build so I'm not including that here.

**Comment by sbromberger** [comment]
I fixed these by eliminating StatsBase as a dependency - the only thing we were using was `std` and we were comparing to `0`, so it was a straightforward substitution.

**Comment by sbromberger** [comment]
Closed via #895.
