### ISSUE TITLE
Use constructor SimpeGraph(Vector{Edge}) for code that generates SimpleGraphs

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGraphs/LightGraphs.jl#903]
Now that we have the constructors `SimpeGraph(Vector{Edge})` and `SimpleGraphFromIterator(iter)`, I would like to replace some of the code that generates SimpleGraphs with these new constructors.
This mainly concerns the code in
* staticgraph.jl
* smallgraph.jl

I also want to see if I can replace some functions in
* euclideangraphs.jl
* randgraphs.jl
* simplegraph.jl and simpledigraph.jl
* persistence/lg.jl

If I'm allowed to, I would actually replace the code in staticgraph.jl by some code that writes directly to the forward and backwards adjacency list, as this is is the fastest way do this.

**Comment by simonschoelly** [comment]
Sure, I will do that.

**Comment by sbromberger** [comment]
Thanks. OK, so to be clear, we've got #908 which takes care of the generators, and then once that's merged we (you) can work on the constructor / generator changes, right?

**Comment by simonschoelly** [comment]
Right. I want to wait on the outcome of your discussion in order to avoid too many merge conflicts.

**Comment by sbromberger** [comment]
I just merged #908 so we should be good to go with next steps. Thanks for your patience.

**Comment by simonschoelly** [comment]
I guess this can be closed then.
