### ISSUE TITLE
Graph Isomorphism

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGraphs/LightGraphs.jl#921]
I recently had a look at the VF2 algorithm [1] for graph isomorphism and I could implement this one for LightGraphs.

Is that something that is desired? Or should it maybe go to another package? Is this already planned for @SohamTamba 's GSoC?

[1] [An Improved Algorithm for Matching Large Graphs](https://pdfs.semanticscholar.org/f3e1/0bd7521ec6263a58fdaa4369dfe8ad50888c.pdf)

**Comment by SohamTamba** [comment]
It's not in my GSoC proposal.
you can find it [here](https://github.com/SohamTamba/GSoC/blob/gh-pages/Proposal.pdf) btw.

**Comment by sbromberger** [comment]
@simonschoelly It'd be nice to have a set of isomorphism checks and algorithms. I've been thinking about how best to do this: there are some very checks for isomorphism that can be made that start off very inexpensive and move up in complexity. If you wanted to implement this in a separate file, that'd be pretty cool.

**Comment by simonschoelly** [comment]
@SohamTamba  cool stuff, you will be quiet busy then

@sbromberger  With inexpensive checks you mean something like first check if the number of vertices is the same, the degree sequence is the same etc?

The VF2 algorithm basically tries all different combinations and uses some heuristics to prune the search tree. It also can solve the subgraph-isomorphis problem and work with graphs that have edge and vertex properties.
There are also some newer extensions such as VF2-plus, VF2++ and VF3, but have not studied them yet.

**Comment by sbromberger** [comment]
> With inexpensive checks you mean something like first check if the number of vertices is the same, the degree sequence is the same etc?

Yup, precisely.

**Comment by sbromberger** [comment]
@simonschoelly if you don't mind, I'll close this issue out pending a PR :) Let me know if it needs to be reopened. Thanks.
