### ISSUE TITLE
Function to return cycle basis for graph

### ISSUE THREAD

**Issue by fneum** [JuliaGraphs/LightGraphs.jl#927]
I am working on a function that returns a list of cycles which form a basis for cycles of an _undirected_ graph. It would translate an algorithm included in the Python library [networkx.algorithms.cycles.cycle_basis](https://networkx.github.io/documentation/latest/reference/algorithms/generated/networkx.algorithms.cycles.cycle_basis.html). A basis for cycles of a network is a minimal collection of cycles such that any cycle in the network can be written as a sum of cycles in the basis.  Once it's done I would submit a PR.

**Now I'm struggling to find an appropriate location in the LightGraphs.jl package to add the function. Can anyone think of a suitable place?**

**Comment by mbesancon** [comment]
Good point, the circuit function for oriented graphs is placed in `digraph/cycles`, maybe a re-organization of the files? `digraph` folder only contains one subfolder, `cycles`, which could go up one level to include both circuits and cycles

**Comment by sbromberger** [comment]
I'd be ok with moving `cycles` up to the main directory.

**Comment by sbromberger** [comment]
@fneum - what's your timeframe for a PR? We are planning a 1.0 freeze soon, but it'd be nice to have this in there when we do.

**Comment by mbesancon** [comment]
If you put the PR early we can help you get it to merge before the freeze

**Comment by fneum** [comment]
I have the changes/reorganisation ready and the tests are passing. I'll put the PR tomorrow.

**Comment by sbromberger** [comment]
Closed via #929. Thanks!!
