### ISSUE TITLE
Documentation for the graph interface

### ISSUE THREAD

**Issue by matbesancon** [JuliaGraphs/LightGraphs.jl#932]
We need to split the interface to make it easier for people to understand and implement.
https://juliagraphs.github.io/LightGraphs.jl/latest/types.html#AbstractGraph-Type-1

1. Give the signature of methods to implement, `f(g)`, `f(g, edge)`, `f(g,::Int)`
2. What needs to be inherited from

It might be unclear for instance what to do with `AbstractEdgeIter`

**Comment by jpfairbanks** [comment]
Yeah I just looked at this documentation page for the first time in a long time and I think I am supposed to define a function `edges(g)` which returns a subtype of `AbstractEdgeIter`

**Comment by mbesancon** [comment]
yup that's it, if it may be confused to use, it is surely for many users

**Comment by sbromberger** [comment]
@matbesancon if you'd like to work on this soon, we can get it into 1.0.

**Comment by matbesancon** [comment]
yes I'll have time to suggest a change somewhere this week

**Comment by sbromberger** [comment]
@matbesancon - do we need to keep this open, or can it be closed with #965? Is there more work you'd like to do?

**Comment by matbesancon** [comment]
The issue as written can be closed yes. If we or other people find
something unclear we'll re-open.

Cheers from London!

**Comment by sbromberger** [comment]
> Cheers from London!

Rub it in! :)

Seriously, great presentation today.
