### ISSUE TITLE
wrong behavior of tensor_product

### ISSUE THREAD

**Issue by adamglos92** [JuliaGraphs/LightGraphs.jl#933]
The current implementation of  tensor_product is wrong, at least for undirected graphs. The tensor product of bipartite graphs consist of two connected components, and currently
```
julia> using LightGraphs

julia> connected_components(tensor_product(PathGraph(3), PathGraph(3)))
5-element Array{Array{Int64,1},1}:
 [1, 5, 9]
 [2, 6]   
 [3]      
 [4, 8]   
 [7]      
```

The reason is that not all edges are considered, as edges can be oriented in common order, or reversed order. The correct definition should be
```
function tensor_product(g::G, h::G) where G <: AbstractGraph
    z = G(nv(g) * nv(h))
    id(i, j) = (i - 1) * nv(h) + j
    for e1 in edges(g)
        i1, i2 = Tuple(e1)
        for e2 in edges(h)
            j1, j2 = Tuple(e2)
            add_edge!(z, id(i1, j1), id(i2, j2))
            add_edge!(z, id(i1, j2), id(i2, j1))
        end
    end
    return z
end
```
Most probably `DiGraph` will require separate implementation (the original one).

**Comment by jpfairbanks** [comment]
@adamglos92 can you write some more test cases for tensor product? I will add a test case based on your example in OP.
