### ISSUE TITLE
Wrong hyperlink in cartesian_product

### ISSUE THREAD

**Issue by adamglos92** [JuliaGraphs/LightGraphs.jl#934]
Documentation of `cartesian_product` is currently pointing at https://en.wikipedia.org/wiki/Tensor_product_of_graphs, while it should probably point at https://en.wikipedia.org/wiki/Cartesian_product_of_graphs

**Comment by jpfairbanks** [comment]
Thanks. I'll bundle this fix with #933

**Comment by sbromberger** [comment]
Fixed via #933. Thanks.
