### ISSUE TITLE
Problem using LightGraphs with Atom

### ISSUE THREAD

**Issue by charlinetess** [JuliaGraphs/LightGraphs.jl#947]
I am having troubles trying to use LightGraphs with Atom. 

When I try  `using LightGraphs`
I get 

> ERROR: MethodError: no method matching shouldlog(::Atom.Progress.JunoProgressLogger, ::Base.CoreLogging.LogLevel, ::Module, ::Symbol, ::Symbol)
> The applicable method may be too new: running in world age 27557, while current world is 27588.

What happens there?
I use Atom, and I dont get the same problem running the same code from the terminal. 

Thanks

**Comment by sbromberger** [comment]
This doesn't really sound like an issue specific to LightGraphs, especially since you can run at the repl. I would recommend opening up a thread on [discourse](https://discourse.julialang.org). Closing out here.
