### ISSUE TITLE
Please use unsafe=true with parse_dict

### ISSUE THREAD

**Issue by andrewcooke** [JuliaGraphs/LightGraphs.jl#95]
hi,  if you're using ParserCombinator.Parsers.GML.parse_dict to parse GML format data, please can you add "unsafe=true" to the call if you don't care about lists other graph, edge and node?

see the docs at https://github.com/andrewcooke/ParserCombinator.jl#parsers for a brief justification.

thanks + sorry for all the emails you must be getting from me on various issues over the last 24 hours.

**Comment by sbromberger** [comment]
No worries. I'll close this out and we can continue the discussion over on your issues page :)
