### ISSUE TITLE
Move parallel functions into a LightGraphs.Parallel module

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#955]
@jpfairbanks had a great suggestion:

* create a LightGraphs.Parallel module
* move all parallel functions into this module (mirroring the file layout in LightGraphs)
* rename all parallel functions to mirror the original names (`dijkstra_shortest_paths()`, etc.)

This way, users can
```
using LightGraphs
import Parallel
d = Parallel.dijkstra_shortest_paths(...)
```

**Comment by somil55** [comment]
I agree with this. 
While writing parallel functions multiple helper functions have to be written. This clutters present sequential version files. Apart from this `Parallel.` seems to be a better syntax than `parallel_`.

**Comment by jpfairbanks** [comment]
See PR #957
