### ISSUE TITLE
Documentation disambiguation

### ISSUE THREAD

**Issue by matbesancon** [JuliaGraphs/LightGraphs.jl#963]
In *docs/src/developing.md*:

```
- [`is_directed`](@ref): Note that since we use traits to determine directedness, `is_directed` for a `CustomGraph` type should have the following signatures:
  - `is_directed(::Type{CustomGraph})::Bool`
  - `is_directed(g::CustomGraph)::Bool`
```

I find it unclear to know if one needs to implement **both** types or **any** of them

**Comment by sbromberger** [comment]
@matbesancon - thank you for your tireless work on the docs. If you're going to fix them via PR (and please continue to do so!), there's no need to open up an issue to discuss – you've been around here long enough that your judgement as to what needs fixing is not in question. Just make the PR and we can hash it out there :)

**Comment by matbesancon** [comment]
yes I wasn't sure if I was gonna do the PR straight away, so this serves both as a personal reminder and as a signal that we've seen the issue and that we'll take care of it at some point.
In that case, I completed the doc here with **any** of the two is good

**Comment by sbromberger** [comment]
Actually, I think you need *both* :)

**Comment by matbesancon** [comment]
woops, I'll update the PR
