### ISSUE TITLE
Functions that return or change a graph often only work with SimpleGraphs

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGraphs/LightGraphs.jl#968]
This mainly concerns the functions in `operators.jl` but also crops up in some other places. I think this is something that should be fixed before a 1.0 release.
At the moment some functions that return another graph don't really work for general graph types even if their method signature suggests otherwise. Here are some examples:

* `complement` is just implemented for `Graph` and `DiGraph`
* `reverse` is implemented for all directed graphs but internally relies on on the fact that the graph has members `fadjlist` and `badjlist`
* `blockdiag` works for all kinds of graphs but relies on the fact that `eltype` is an Integer and that the graph type has implemented `add_edge!`. Furthermore it gives where funny results when you use two graphs of type `SimpleWeightedGraph` -- then it only copies the weights of the first graph and uses a default weight of 1 for the second graph.
* `transitiveclosure` works only for `SimpleDiGraph` but there is no reason why it should.

#### Possible Solutions:
* Such a function could have a alternative signature that also takes a return type. For example we then have a function
`@traitfn reverse(RT::Type, g::::IsDirected) were {RT <: AbstractGraph}`
then we define 
`@traitfn reverse(g::::IsDirected) = reverse(SimpleDiGraph, g)`
If a user then has their own graph type and don't want to have `SimpleDiGraph` they can define
`reverse(g::MyDiGraph) = reverse(MyDiGraph, g)` and if that doesn't work because `MyDiGraph` does something special they can write their own implementation of `reverse(g::MyDiGraph)`. I think this is what I would prefer.

* Such functions can be restricted to only work for SimpleGraphs and the it is up to the user to extend the functions so they also work with other graph types.  This will be safe but then the user might have to do more work than necessary.

* We could define a lot of different traits such has `HasIntegerEltype`, `IsMutable`, `HasMultiEdges`, `HasEdgeWithProperties` and so on. That would be quiet a lot of work though and make the implementation of the functions quiet complicated if we want to catch all possible cases..

**Comment by sbromberger** [comment]
This definitely won't be fixed by 1.0. I've been thinking about moving the operators into SimpleGraphs, since it'a going to be impossible to deal with all the metadata on changed graphs in a consistent manner.

**Comment by sbromberger** [comment]
> If the operators get moved to go SimpleGraphs, then it might be a good idea if the functions still take AbstractGraphs as arguments and then return a SimpleGraph.

That was my thinking as well.

> Hope you don't mind if I open these kind of issues if I see something that bothers me.

Not at all. Just be aware that we're in a 1.0 sprint right now so responses might be delayed :)

**Comment by jpfairbanks** [comment]
The problem of correctly and efficiently implementing all the operators for arbitrary combinations of types is definitely out of scope for 1.0


So I think we will go with a resolution where these troublesome operators raise a method error. Then if you want to get the current behavior where G op H returns a simplegraph. You would convert G and H to simple graphs. 

Then if you want to combine your graphs and combine the corresponding metadata you write a method in your package that works on your graph types. 

If someone solves the problem in general than we can accept that as a new feature. 

Moving the functions for LightGraphs to LightGraphs.SimpleGraphs there will be nowhere for the other packages to hang their implementations. 

Written on my phone.

**Comment by sbromberger** [comment]
@jpfairbanks describes the current behavior and makes a good case for not moving these out to `LightGraphs.SimpleGraphs`, so I think I'm going to close this out as a "wontfix" for now. Please feel free to keep discussing it here, though.
