### ISSUE TITLE
inconsistent results in greedy_color (serial vs parallel)

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#970]
@SohamTamba -

```
julia> g = Graph(7,12)
{7, 12} undirected simple Int64 graph

julia> greedy_color(g)
LightGraphs.coloring{Int64}(3, [3, 1, 2, 2, 1, 3, 1])

julia> Parallel.greedy_color(g)
LightGraphs.coloring{Int64}(4, [4, 2, 2, 2, 1, 1, 3])

julia> collect(edges(g))
12-element Array{LightGraphs.SimpleGraphs.SimpleEdge{Int64},1}:
 Edge 1 => 2
 Edge 1 => 3
 Edge 1 => 4
 Edge 1 => 5
 Edge 1 => 7
 Edge 2 => 6
 Edge 3 => 5
 Edge 3 => 7
 Edge 4 => 5
 Edge 4 => 6
 Edge 4 => 7
 Edge 6 => 7
```

**Comment by jpfairbanks** [comment]
It makes sense to get different answers because of benign race conditions. We just need to make sure that the output is a valid coloring

**Comment by sbromberger** [comment]
It appears to be - that is, you can reduce the larger coloring to a smaller one without an issue - but I don't like the idea of "benign race conditions", especially where they lead to suboptimal results (4 colors instead of 3, for example).

I'll close this out but I wonder if there's a way to eliminate the discrepancy.

**Comment by SohamTamba** [comment]
There aren't any race conditions here.
`vertices(g) ` are iterated in a random order.

**Comment by sbromberger** [comment]
Gotcha. Thanks for the clarification.
