### ISSUE TITLE
Does LG work on Julia  1.0?

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/LightGraphs.jl#977]

**Comment by jpfairbanks** [comment]
![image](https://user-images.githubusercontent.com/2753998/43899506-0e8b117c-9bda-11e8-8bec-1b3cdb345a6b.png)

**Comment by matbesancon** [comment]
So great, I'm crying

**Comment by simonschoelly** [comment]
I tried 
```
Pkg> add LightGraphs
Julia> using LightGraphs
```
but then there are some errors when precompiling (no function `srand`, `SimpleTraits` is not found). Then I tried
```
Pkg> develop LightGraphs
Julia> using LightGraphs
```
and that works. So I think it somehow does not download the newest version when using `add`.

**Comment by sbromberger** [comment]
Yes. The latest master works on 1.0. Patience! :)
