### ISSUE TITLE
count_*isomorphs counting convention

### ISSUE THREAD

**Issue by bovine3dom** [JuliaGraphs/LightGraphs.jl#983]
The isomorph counting is a bit strange to me:

`count_induced_subgraphisomorph(g,g) == 1 # false, for all sane graphs`

I'm wondering if the default behaviour should be to normalise by this, e.g:

```julia
function count_unique_isomorphs(g1,g2;rest...)
        return count_induced_subgraphisomorph(g1,g2;rest...)÷count_induced_subgraphisomorph(g2,g2;rest...)
end
```

or include the `_unique_` as yet another set of isomorphism functions, or, `uniquify(f,g1,g2) = f(g1,g2)÷f(g2,g2)`.

I don't know what the convention is.

**Comment by sbromberger** [comment]
cc @simonschoelly

**Comment by simonschoelly** [comment]
So right now, `count_induced_subgraphisomorph(g1, g2)` corresponds to `length(all_induces_subgraphisomorphism(g1, g2))`. Furthermore, right now we have `count_induced_subgraphisomorph(g1, g2) == count_isomorphism(g1, g2) ` whenever `g1` and `g2` have the same number of vertices.
It counts how many injective functions are there from `g2` to `g1` that are compatible with the edge relation.
For me this is also what I intuitively would assume

In your proposal, what you would get would be the number of subsets of  `g1` that have the same size as `g2` and are isomorphic to `g2`. It would obviously not correspond to `length(all_induces_subgraphisomorphism(g1,g2))` anymore (or you would have to change that function also). But that is a legitimate use case, as for example some users might only be interested in the number of cliques in a graph.

As you demonstrated, it is possible to go from one quantity to the other by multiplying or dividing by the size of the automorphism group of g2 (which can be  expensive to compute). In some cases, it might be easier to compute `count_unique_isomorphs` than `count_induced_subgraphisomorph` but I don't know how to compute `count_unique_isomorphs` with vf2 directly.

So what I would propose: 
*  We keep the behaviour of `count_induced_subgraphisomorph` as it is.
* If you want, you can implement `count_unique_isomorphs`. (or add flag to `count_induced_subgraphisomorph`)
* I'm not sure about the name `count_unique_isomorphs` yet.
* In any case, we have quite a lot of functions now, so they should be well documented, so a user does not get confused when he has to choose betwen 10 different isomorphism functions.
* What would go together with `count_unique_isomorphs` is a function that mimics `all_induces_subgraphisomorphism` and returns either a representative isomorphism for each subset of `g1` that is isomorphic to `g2` or just returns the set of vertices that induce that subgraph.

**Comment by bovine3dom** [comment]
I've left this for a while in the hope that I'd come up with a better name for `count_unique_isomorphs`. I don't think I have. Perhaps `distinct` is slightly better?

I think I would prefer it as a flag for both operations as there are a very large number of functions already.

**Comment by simonschoelly** [comment]
I we use the proposed interface, then we could have a flag in the constructor of the problem that indicates if we are are interested in grouping the automorphisms of `g2` together, i.e we could have
```
InducedSubgraphIsomorphismProblem(distinct=true)
```
