### ISSUE TITLE
Zenodo out of date

### ISSUE THREAD

**Issue by bovine3dom** [JuliaGraphs/LightGraphs.jl#991]
The [Zenodo page](https://zenodo.org/record/1297490) points to an old release of LightGraphs.

It seems quite straightforward to set up a web-hook so that the process is automatic - https://guides.github.com/activities/citable-code/. If you had already set that up in the past, it is plausible that it broke when the `JuliaGraphs` organisation was created.

**Comment by sbromberger** [comment]
@bovine3dom - yeah. The update process has failed for months, but definitely after the JuliaGraphs migration. If you have any ideas on how to fix this, I'm all ears.

**Comment by bovine3dom** [comment]
I can't find any information about how to deal with a migrated repository. 

Zenodo's FAQ https://help.zenodo.org/ suggests

> GitHub
> My organizational repository does not show up on the GitHub list.
>
> In order to see and archive your organizational repositories on Zenodo you will need to have "Admin" permissions on said repository, either as an Admin of the organization or an Admin of one of your organization's repositories. Additionally, please make sure that the OAuth application on GitHub is granting permissions not only to your personal repositories but also to your organizational ones - to verify that go to your GitHub OAuth settings in your profile, and click on the Zenodo application to see more details. Make sure that Zenodo is given access (green tick) to your organization under "Organization access".
>
> After that, navigate to your Zenodo GitHub settings page and click the "Sync now" button at the top.

If that ends up giving you a second DOI I think my next guess would be to make sure the webhook on GitHub (which lives [here](https://guides.github.com/activities/citable-code/webhook-view.png)) points to the right (i.e old) place.

If that didn't work I'd give up and file a ticket : )

**Comment by sbromberger** [comment]
Zenodo's been down for a while due to database failure, so I can't check it now anyway, but I've opened up multiple tickets and they haven't been able to fix it.

**Comment by sbromberger** [comment]
I sent another ticket and am awaiting a response. It usually takes a couple of weeks.

**Comment by sbromberger** [comment]
Update: received a response:
> We're terribly sorry for the late reply, due to our recent database incident we had to allocate some extra efforts into addressing the issue which has caused some delay in our support line response time.

> It appears that the reason that the releases have failed is due to the invalid license value in your ".zenodo.json" file. The correct value would be ' "license": "BSD-2-Clause" ' (note the dash '-'). 

> Since the releases have already been created and rewriting git history to correct some process-specific file isn't of course the way to go (or any fun), and also we don't want to "punish" somebody using the ".zenodo.json" file feature, I suggest that we proceed with a manual fix on our side in order to create records (and DOIs) for all of the failed releases. This will take some time though and we expect to address it sometime during the next week.

> Let me know if that's ok with you so we can proceed.

I responded that it's ok to proceed, and that we'd be fixing the .json issue for a go-forward solution.

**Comment by sbromberger** [comment]
All fixed! Previous versions will be fixed by Zenodo over the coming week or so. Thanks for bringing this up.
