### ISSUE TITLE
TransposeGraph for Lazy Transpose

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/LightGraphs.jl#996]
We could support lazy transpose of a graph by switching in and out neighbors. This would be useful for users where you want to look at some algorithms that assume the edges are oriented one way and some algorithm which assumes the edges are oriented the other way.

https://docs.julialang.org/en/stable/stdlib/LinearAlgebra/#Base.transpose

If anyone thinks that a `TransposeGraph{G}` type would be useful, then I think it would be a good idea.

**Comment by simonschoelly** [comment]
A while ago, I started creating a Julia package that does graph operators lazily.
If you want to have a look at that: https://github.com/simonschoelly/ImplicitGraphs.jl
What you would call `TransposeGraph` is called `ReverseImpDiGraph` here.
I haven't worked on it for a while but I think it still should be able to run on 1.0

**Comment by sbromberger** [comment]
Wouldn't this just be a `SimpleWeightedGraph` with an extra field that denotes the transpose?

**Comment by sbromberger** [comment]
> why `SimpleWeightedGraph`?

Because it's already using sparse matrix transposes (well, `permutedims`):

```
mutable struct SimpleWeightedDiGraph{T<:Integer, U<:Real} <: AbstractSimpleWeightedGraph{T, U}
    weights::SparseMatrixCSC{U, T} # indexed by [dst, src]
    function SimpleWeightedDiGraph{T, U}(adjmx::SparseMatrixCSC{U,T}; permute=true) where T <: Integer where U <: Real
        dima,dimb = size(adjmx)
        isequal(dima,dimb) || error("Adjacency / distance matrices must be square")
        permute ? new{T, U}(permutedims(adjmx)) : new{T, U}(adjmx)
    end

end
```

**Comment by SohamTamba** [comment]
Just a thought: It would be more efficient to represent `CompleteGraph{T}(n::Integer)` as 
`Complement( SimpleGraph([Edge{T}(v, v) for v in OneTo(n)]) )` rather than the current method.

Also, efficiency of `neighbours(g::complement(type_G))` it would be much better if `neighbours(g::type_G)` returns integers in a sorted order. The implementation would look something like

```
function neighbours(g::Complement{type_G}, v) where type_G <: SortedGraph
     prev=1
     for u in neighbors(g, v)
           for i in prev:(u-1) 
                    yield i
           end
           prev = u+1
     end
     for i in prev:nv(g)
            yield i
     end
end
```

Is it possible to provide a different method for graphs with sorted and unsorted adjacency lists?

**Comment by matbesancon** [comment]
nope, will fix, a matter of finding the good design. I might give it a try during the winter holidays (next week-ish)
